### ISSUE TITLE
Add RBG and Arena wins for Wakening Essence

### ISSUE THREAD

**Issue by SacredDuckwhale** [SavedInstances/SavedInstances#101]
Source: [WowAce](https://www.wowace.com/projects/saved_instances/issues/311)

> It would be great to have the following Quests/Objectives tracked since they reward the new currency, Wakening Essence, for buying legendary tokens.

> Daily:
First Random Battleground Win

> Weekly:
Earn 1500 honor in Rated 2v2 Arena
Earn 1500 honor in Rated 3v3 Arena
Earn 1500 honor in Rated Battlegrounds

**Comment by LiangYuxuan** [comment]
I think we can track conquest quest, but I accidentally found a stack of quests named [Conquest's Reward](https://www.wowhead.com/quests/name:Conquest's+Reward), maybe we should find another way.

**Comment by LiangYuxuan** [comment]
I think leaving #213 open is enough. Wakening Essence daily and weekly is no longer available and conquest weekly quests have a quest line, so it can't just adding the quest id to database.

Closing this.
