### ISSUE TITLE
Add tracking for profession & Treasure Hoard WQ

### ISSUE THREAD

**Issue by Duckwhale** [SavedInstances/SavedInstances#103]
Source: [WowAce](https://www.wowace.com/projects/saved_instances/issues/309)

> Is it possible to track World Quests with SavedInstances?
For example i want to track world quest Treasure Master Iks'reeged or quests for Slice of Bacon.
It's a core feature of SavedInstances to track progress across all characters so it would be very handy to add this option.

---
Not sure if we really want this, but forwarding it anyway.

**Comment by LiangYuxuan** [comment]
Can be done by user with new Progress user tracking feature.
