### ISSUE TITLE
Crazy CPU & Memory usage since last Update!

### ISSUE THREAD

**Issue by DoubleHighC** [SavedInstances/SavedInstances#108]
Hi there

Since the last update SavedInstances produces an totally crazy amount of CPU and Memory usage!
I posted a screenshot of it! It constantly stays at around 50ms/s! This is 10x what tradeskill uses and normally this one is the CPU burner of the addons! ;-)

![addons](https://user-images.githubusercontent.com/36462582/37085798-4049fae2-21f6-11e8-9c18-65c00faaea87.jpg)

Would be nice if you could look at it!

Thank you in advance!

**Comment by jsaneu** [comment]
Check a4311dc

**Comment by DoubleHighC** [comment]
Hi there!

Thank you very much that changed everything!!
Just deleting this line brings Saved Instances to a constan 0,45ms/s!!

Very very nice! Thank you again!
