### ISSUE TITLE
Add custom sorting for characters

### ISSUE THREAD

**Issue by SacredDuckwhale** [SavedInstances/SavedInstances#111]
Source: [CurseForge](https://www.curseforge.com/wow/addons/saved_instances?comment=1125)

> I was wondering if theres an option to sort your characters yourself, so not alphabetically? Wasnt able to find it myself. And if its not an option yet, is there any thought about adding it? Cheers!

Right now, only alphabetical sorting seems to be available.

**Comment by Stanzilla** [comment]
meh.

**Comment by fgmenth** [comment]
There is already custom sorting under Interface->Addons->Saved Instances->Characters. Am I missing something here? I don't believe this should be an open issue.

**Comment by SacredDuckwhale** [comment]
I believe said user didn't recognize the possibility of sorting characters manually by assigning the respective number. If the sorting isn't ideal that would be another issue entirely (and I doubt anyone has time to work on it as it is).

I'm just going to close this, Nothing to see here, move along!
