### ISSUE TITLE
LFR: raid is doubled as non-LFR in panel

### ISSUE THREAD

**Issue by esvarc** [SavedInstances/SavedInstances#112]
I'm not sure if this isn't wanted, but I'm doing only LFR raids, but in status page I see for each raid two lines one with prefix LFR: and second one without. There could be just one for each raid, am I right?

![lfr-doubled](https://user-images.githubusercontent.com/6427670/38164717-d0f3d5f2-3508-11e8-9c36-df4030cecb45.jpg)

**Comment by Stanzilla** [comment]
Fixed in alpha already https://www.wowace.com/projects/saved_instances/files
