### ISSUE TITLE
LFR lockouts don't show up when set to united

### ISSUE THREAD

**Issue by enVader** [SavedInstances/SavedInstances#113]
Installing the latest alpha got the problem of no LFR lockouts showing when option "Union LFR" is checked in preferences.

**Comment by SacredDuckwhale** [comment]
Thanks, will investigate on live servers as soon as I get around to it. Since I don't run LFR normally, maybe someone else could confirm this for me?

**Comment by enVader** [comment]
Just cleared 2 wings of Antorus (1 and 4) in lfr and got the same bug. Latest addon version. And they do show separately 2/2 and 3/3. Should i provide some files?
