### ISSUE TITLE
tooltip dairy quest bug

### ISSUE THREAD

**Issue by edu5ardo** [SavedInstances/SavedInstances#114]
if maouse over diary quest 

Message: Interface\AddOns\SavedInstances\SavedInstances.lua:2123: attempt to index field 'Title' (a nil value)
Time: 04/28/18 08:44:13
Count: 10
Stack: Interface\AddOns\SavedInstances\SavedInstances.lua:2123: attempt to index field 'Title' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
Interface\AddOns\SavedInstances\SavedInstances.lua:2123: in function `_OnEnter_func'
...face\AddOns\NPCScan\Libs\LibQTip-1.0\LibQTip-1.0.lua:1321: in function <...face\AddOns\NPCScan\Libs\LibQTip-1.0\LibQTip-1.0.lua:1315>

Locals: errorMessage = "Interface\AddOns\SavedInstances\SavedInstances.lua:2123: attempt to index field 'Title' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

**Comment by SacredDuckwhale** [comment]
I'm not sure when this error is popping up for you, but I'll see if I can replicate it.
