### ISSUE TITLE
[Request/Suggestion] Honor Tracking Across Characters

### ISSUE THREAD

**Issue by rubyrabble** [SavedInstances/SavedInstances#115]
Since honor will be merged account-wide for BFA, is it possible to have SavedInstances track honor across all characters? Not just the honor xp level, or the prestige level, but the total accumulation of honor on each character and across your account. Max prestige takes about 1,078,000 honor and it would be great to see all characters' contribution to this at a glance.

**Comment by SacredDuckwhale** [comment]
Closing this as no longer relevant. It also wouldn't have fitted the addon's scope IMHO, and with how often Blizzard changed their Prestige systems it would likely have ended up inaccurate as well.
