### ISSUE TITLE
Addon is broken as of 8.0.1 (after Blizzard's API changes for BFA)

### ISSUE THREAD

**Issue by Bpsmooth** [SavedInstances/SavedInstances#119]
8.0.1 pre-patch went live July 17th, since the patch this addon is broken.

**Comment by SacredDuckwhale** [comment]
I doubt anyone could be NOT aware of the sweeping changes Blizzard made. Give it some time, it'll be fixed as soon as humanly possible :)

**Comment by SiegaPlays** [comment]
Downloaded the 41b8275 build. These are my current errors: 

5x SavedInstances\SavedInstances-@project-version@.lua:354: attempt to call global 'GetMapNameByID' (a nil value)
SavedInstances\SavedInstances-@project-version@.lua:354: in function `specialQuests'
SavedInstances\SavedInstances-@project-version@.lua:2819: in function <SavedInstances\SavedInstances.lua:2764>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1189: in function <FrameXML\UIParent.lua:1085>

Locals:
nil

----

2x SavedInstances\SavedInstances-@project-version@.lua:2967: attempt to call field 'RequestMapInfo' (a nil value)
SavedInstances\SavedInstances-@project-version@.lua:2967: in function `?'
...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil

----

11x SavedInstances\SavedInstances-@project-version@.lua:3313: attempt to index field 'dataobject' (a nil value)
SavedInstances\SavedInstances-@project-version@.lua:3313: in function <SavedInstances\SavedInstances.lua:3233>
(tail call): ?
DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
 GetCurrentMapAreaID = <function> defined @SavedInstances\SavedInstances.lua:1975
 GetServerOffset = <function> defined @SavedInstances\SavedInstances.lua:916
 oi_cache = <table> {
 }
 questdebug = <function> defined @SavedInstances\SavedInstances.lua:521
 QuestInfo = <function> defined @SavedInstances\SavedInstances.lua:451
 pvpdesertids = <table> {
 }
 icon = <table> {
 }
 histLiveCount = 0
 FindInstance = <function> defined @SavedInstances\SavedInstances.lua:1092
 UpdateToonData = <function> defined @SavedInstances\SavedInstances.lua:1699
 GetRegion = <function> defined @SavedInstances\SavedInstances.lua:932
 InGroup = <function> defined @SavedInstances\SavedInstances.lua:3114
 chatMsg = <function> defined @SavedInstances\SavedInstances.lua:461
 CategorySize = <function> defined @SavedInstances\SavedInstances.lua:1179
 formatNumber = <function> defined @SavedInstances\SavedInstances.lua:580
 GetNextDailyResetTime = <function> defined @SavedInstances\SavedInstances.lua:957
 OrderedCategories = <function> defined @SavedInstances\SavedInstances.lua:1373
 instanceException = <function> defined @SavedInstances\SavedInstances.lua:1278
 db = <table> {
 }
 diff_strings = <table> {
 }
 LFRInstances = <table> {
 }
 transInstance = <table> {
 }
 IsDetached = <function> defined @SavedInstances\SavedInstances.lua:3649
 config = <table> {
 }
 QuestIsDarkmoonMonthly = <function> defined @SavedInstances\SavedInstances.lua:1961
 SkinFrame = <function> defined @SavedInstances\SavedInstances.lua:830
 Categories = <table> {
 }
 histTextUpdate = <function> defined @SavedInstances\SavedInstances.lua:3318
 HistoryEvent = <function> defined @SavedInstances\SavedInstances.lua:3149
 InstanceCategory = <function> defined @SavedInstances\SavedInstances.lua:1159
 histReapTime = 3600
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @SavedInstances\SavedInstances.lua:3652
 UpdateInstanceData = <function> defined @SavedInstances\SavedInstances.lua:1472
 GetNextWeeklyResetTime = <function> defined @SavedInstances\SavedInstances.lua:983
 WorldBosses = <table> {
 }
 region = "US"
 activeHolidays = <table> {
 }
 core = <table> {
 }
 plantName = <function> defined @SavedInstances\SavedInstances.lua:2209
 LDB = <table> {
 }
 histOldest = "n/a"
 UpdateInstance = <function> defined @SavedInstances\SavedInstances.lua:1602
 PlayedTime = 1531911835
 delayUpdate = 1531911846.4903
 debug = <function> defined @SavedInstances\SavedInstances.lua:466
 LookupInstance = <function> defined @SavedInstances\SavedInstances.lua:1128
 oc_cache = <table> {
 }
 resetDays = <table> {
 }
 Indicators = <table> {
 }
 version = "Dev"
 UpdateCurrency = <function> defined @SavedInstances\SavedInstances.lua:1911
 OrderedInstances = <function> defined @SavedInstances\SavedInstances.lua:1360
 updateSpellTip = <function> defined @SavedInstances\SavedInstances.lua:1680
 currency = <table> {
 }
 idtext = <function> defined @SavedInstances\config.lua:42
 normalizeName = <function> defined @SavedInstances\SavedInstances.lua:1066
 instancesUpdated = true
 L = <table> {
 }
 specialQuests = <function> defined @SavedInstances\SavedInstances.lua:314
 dbmhook = true
 BonusRollShow = <function> defined @SavedInstances\SavedInstances.lua:5144
 scaleCache = <table> {
 }
 ShowDetached = <function> defined @SavedInstances\SavedInstances.lua:3663
 HistoryUpdate = <function> defined @SavedInstances\SavedInstances.lua:3233
 ColoredToon = <funct

-------


75x SavedInstances\SavedInstances-@project-version@.lua:917: attempt to perform arithmetic on a table value
SavedInstances\SavedInstances-@project-version@.lua:917: in function `GetServerOffset'
SavedInstances\SavedInstances-@project-version@.lua:1001: in function `GetNextWeeklyResetTime'
SavedInstances\SavedInstances-@project-version@.lua:2664: in function `toonInit'
SavedInstances\SavedInstances-@project-version@.lua:2689: in function <SavedInstances\SavedInstances.lua:2667>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals:
nil

**Comment by SacredDuckwhale** [comment]
Not to worry, I'm already working on it. There are multiple systems Blizzard has broken:

- [ ] Spell Systems API (work in progress)
- [ ] Maps API
- [ ] Calendars API

There is no point posting any error messages until those issues are fixed and things seem stable once more.
