### ISSUE TITLE
Error, nothing showing

### ISSUE THREAD

**Issue by kingreboot** [SavedInstances/SavedInstances#121]
nothing is really showing besides the icon on the map, here is the error. Might not be the full one but the text after talks about bartender, if that part if relevant please tell me 

6x SavedInstances\SavedInstances-8.0.1-1-gb126032.lua:3873: attempt to compare number with nil
SavedInstances\SavedInstances-8.0.1-1-gb126032.lua:3873: in function `ShowTooltip'
SavedInstances\SavedInstances-8.0.1-1-gb126032.lua:2743: in function `OnEnter'

**Comment by kahlano** [comment]
same, I just have a small empty box

**Comment by swatering** [comment]
the same problem occured to me too, any solution noted?
