### ISSUE TITLE
 attempt to call global 'GetMapNameByID' (a nil value)

### ISSUE THREAD

**Issue by Gholrua** [SavedInstances/SavedInstances#123]
Date: 2018-07-18 10:11:12
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\SavedInstances.lua line 3398:
   attempt to call global 'GetMapNameByID' (a nil value)
Debug:
   (tail call): ?
   SavedInstances\SavedInstances.lua:3398: QuestRefresh()
   SavedInstances\SavedInstances.lua:3503: Refresh()
   SavedInstances\SavedInstances.lua:2767:
      SavedInstances\SavedInstances.lua:2767
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...raenorTreasures\libs\AceBucket-3.0\AceBucket-3.0.lua:118: func()
   ...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:57:
      ...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50

**Comment by Roddd** [comment]
That was fixed in https://github.com/SavedInstances/SavedInstances/commit/30dab31e6b8f3ed34694e14e68989a95c3f85552
