### ISSUE TITLE
Keystones aren't displayed

### ISSUE THREAD

**Issue by XlGogetalX** [SavedInstances/SavedInstances#126]
Im sure its been made aware. But as someone who has a ton of alts it was nice to see which one had what level key and who i had to do a key on yet. I dont seem to see that option in the list anymore. was wondering if someone could confirm or lead me to a fix?

**Comment by crusha015** [comment]
I can confirm I'm having the same issue. Previously the addon would show me which keystone each of my characters had in their bag, this is no longer working.

**Comment by Roddd** [comment]
Looks like t.MythicKey.name doesn't exist anymore. t.MythicKey.link still exists so could use that for the name.

**Comment by Roddd** [comment]
Also, KeyInfo array had contents shifted by 1.

**Comment by Roddd** [comment]
PR: #135
