### ISSUE TITLE
Emissaries broken?

### ISSUE THREAD

**Issue by crusha015** [SavedInstances/SavedInstances#127]
I'm only getting the correct emissary for the (+0 Day) emissary. In addition, it's showing emissaries as completed when they're not completed.

**Comment by crusha015** [comment]
espohlig posted a comment on Curse that seems to have fixed this for me:
"Line 2992: local BountyQuest = GetQuestBountyInfoForMapID(627) -- was 1014 (BFA changed all the mapIDs)"

**Comment by Stanzilla** [comment]
Thanks!
