### ISSUE TITLE
Chieftain Hatuun, Krokuun, error completing quest for more troops

### ISSUE THREAD

**Issue by SiegaPlays** [SavedInstances/SavedInstances#128]
Happens every time I complete the quest: Supplying Krokuun. 

3x SavedInstances\SavedInstances-8.0.1-3-g531a3fd.lua:1978: attempt to call global 'GetCurrentMapAreaID' (a nil value)
SavedInstances\SavedInstances-8.0.1-3-g531a3fd.lua:1978: in function `GetCurrentMapAreaID'
SavedInstances\SavedInstances-8.0.1-3-g531a3fd.lua:2043: in function <SavedInstances\SavedInstances.lua:1989>
[C]: in function `GetQuestReward'
FrameXML\QuestFrame.lua:161: in function <FrameXML\QuestFrame.lua:147>

Locals:
self = <table> {
 GetCurrentMapAreaID = <function> defined @SavedInstances\SavedInstances.lua:1977
 GetServerOffset = <function> defined @SavedInstances\SavedInstances.lua:918
 oi_cache = <table> {
 }
 questdebug = <function> defined @SavedInstances\SavedInstances.lua:523
 QuestInfo = <function> defined @SavedInstances\SavedInstances.lua:453
 pvpdesertids = <table> {
 }
 icon = <table> {
 }
 histLiveCount = 0
 FindInstance = <function> defined @SavedInstances\SavedInstances.lua:1094
 UpdateToonData = <function> defined @SavedInstances\SavedInstances.lua:1701
 GetRegion = <function> defined @SavedInstances\SavedInstances.lua:934
 InGroup = <function> defined @SavedInstances\SavedInstances.lua:3116
 chatMsg = <function> defined @SavedInstances\SavedInstances.lua:463
 CategorySize = <function> defined @SavedInstances\SavedInstances.lua:1181
 formatNumber = <function> defined @SavedInstances\SavedInstances.lua:582
 GetNextDailyResetTime = <function> defined @SavedInstances\SavedInstances.lua:959
 OrderedCategories = <function> defined @SavedInstances\SavedInstances.lua:1375
 instanceException = <function> defined @SavedInstances\SavedInstances.lua:1280
 db = <table> {
 }
 diff_strings = <table> {
 }
 LFRInstances = <table> {
 }
 transInstance = <table> {
 }
 IsDetached = <function> defined @SavedInstances\SavedInstances.lua:3651
 config = <table> {
 }
 QuestIsDarkmoonMonthly = <function> defined @SavedInstances\SavedInstances.lua:1963
 SkinFrame = <function> defined @SavedInstances\SavedInstances.lua:832
 Categories = <table> {
 }
 histTextUpdate = <function> defined @SavedInstances\SavedInstances.lua:3320
 HistoryEvent = <function> defined @SavedInstances\SavedInstances.lua:3151
 InstanceCategory = <function> defined @SavedInstances\SavedInstances.lua:1161
 histReapTime = 3600
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @SavedInstances\SavedInstances.lua:3654
 UpdateInstanceData = <function> defined @SavedInstances\SavedInstances.lua:1474
 GetNextWeeklyResetTime = <function> defined @SavedInstances\SavedInstances.lua:985
 WorldBosses = <table> {
 }
 region = "US"
 histOldest = "n/a"
 core = <table> {
 }
 activeHolidays = <table> {
 }
 LDB = <table> {
 }
 plantName = <function> defined @SavedInstances\SavedInstances.lua:2211
 PlayedTime = 1532034866
 UpdateInstance = <function> defined @SavedInstances\SavedInstances.lua:1604
 resetDays = <table> {
 }
 delayUpdate = 1532034866
 debug = <function> defined @SavedInstances\SavedInstances.lua:468
 LookupInstance = <function> defined @SavedInstances\SavedInstances.lua:1130
 oc_cache = <table> {
 }
 histLimit = 10
 Indicators = <table> {
 }
 version = "8.0.1-3-g531a3fd"
 UpdateCurrency = <function> defined @SavedInstances\SavedInstances.lua:1913
 OrderedInstances = <function> defined @SavedInstances\SavedInstances.lua:1362
 updateSpellTip = <function> defined @SavedInstances\SavedInstances.lua:1682
 currency = <table> {
 }
 idtext = <function> defined @SavedInstances\config.lua:42
 normalizeName = <function> defined @SavedInstances\SavedInstances.lua:1068
 instancesUpdated = true
 L = <table> {
 }
 specialQuests = <function> defined @SavedInstances\SavedInstances.lua:316
 dbmhook = true
 BonusRollShow = <function> defined @SavedInstances\SavedInstances.lua:5146
 scaleCache = <table> {
 }
 ShowDetached = <function> defined @SavedInstances\SavedInstances.lua:3665
 HistoryUpdate = <function> defined @SavedInstances\SavedInstances.lua:32

**Comment by Roddd** [comment]
Ya, GetCurrentMapAreaID was removed for C_Map.GetBestMapForUnit("player").

**Comment by Roddd** [comment]
A fix has been sent for review. This is the same issue reported in #134
