### ISSUE TITLE
Garrison Invasion

### ISSUE THREAD

**Issue by Syreanna** [SavedInstances/SavedInstances#131]
Hey,
first of all, thank you for all your work. I love this addon :-)
Just want to ask, if some future update could show which of my alts already has done a Garrison Invasion - Gold. That would really help with mount farming :-)

Thank you :-)

**Comment by LiangYuxuan** [comment]
Got a macro from [here](https://ptr.wowhead.com/item=116980/invaders-forgotten-treasure#comments:id=2065381), and will be added soon.

**Comment by LiangYuxuan** [comment]
Oops, found this already added.
