### ISSUE TITLE
Lua Error Upon Turning In Some Quests

### ISSUE THREAD

**Issue by Tykwer** [SavedInstances/SavedInstances#134]
I have been coming across this error when turning in my weeklies on the Vindicar.  Thanks for your help!

Date: 2018-07-20 16:43:21
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\SavedInstances.lua line 1978:
   attempt to call global 'GetCurrentMapAreaID' (a nil value)
Debug:
   SavedInstances\SavedInstances.lua:1978: GetCurrentMapAreaID()
   SavedInstances\SavedInstances.lua:2043:
      SavedInstances\SavedInstances.lua:1989
   [C]: GetQuestReward()
   ..\FrameXML\QuestFrame.lua:161:
      ..\FrameXML\QuestFrame.lua:147
Locals:
self = <table> {
 GetCurrentMapAreaID = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1977
 GetServerOffset = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:918
 oi_cache = <table> {
 }
 questdebug = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:523
 QuestInfo = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:453
 pvpdesertids = <table> {
 }
 icon = <table> {
 }
 FindInstance = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1094
 UpdateToonData = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1701
 GetRegion = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:934
 InGroup = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3116
 chatMsg = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:463
 CategorySize = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1181
 formatNumber = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:582
 GetNextDailyResetTime = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:959
 OrderedCategories = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1375
 instanceException = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1280
 db = <table> {
 }
 diff_strings = <table> {
 }
 LFRInstances = <table> {
 }
 transInstance = <table> {
 }
 IsDetached = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3651
 config = <table> {
 }
 QuestIsDarkmoonMonthly = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1963
 SkinFrame = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:832
 Categories = <table> {
 }
 histTextUpdate = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3320
 HistoryEvent = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3151
 InstanceCategory = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1161
 histReapTime = 3600
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3654
 UpdateInstanceData = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1474
 GetNextWeeklyResetTime = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:985
 WorldBosses = <table> {
 }
 region = "US"
 core = <table> {
 }
 activeHolidays = <table> {
 }
 LDB = <table> {
 }
 plantName = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:2211
 PlayedTime = 1532130177
 UpdateInstance = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1604
 resetDays = <table> {
 }
 delayUpdate = 1532130178
 debug = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:468
 LookupInstance = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1130
 oc_cache = <table> {
 }
 histLimit = 10
 Indicators = <table> {
 }
 version = "8.0.1"
 UpdateCurrency = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1913
 OrderedInstances = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1362
 updateSpellTip = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1682
 currency = <table> {
 }
 idtext = <function> defined @Interface\AddOns\SavedInstances\config.lua:42
 normalizeName = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:1068
 instancesUpdated = true
 L = <table> {
 }
 specialQuests = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:316
 dbmhook = true
 BonusRollShow = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:5146
 scaleCache = <table> {
 }
 ShowDetached = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3665
 HistoryUpdate = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3235
 ColoredToon = <function> defined @Interface\Ad
AddOns:
  SavedInstances, v8.0.1
  (Truncated)

**Comment by Roddd** [comment]
@Stanzilla fixed this already in #https://github.com/SavedInstances/SavedInstances/commit/30dab31e6b8f3ed34694e14e68989a95c3f85552. If you are using Twitch/Curse addon client, change to Release Type to alpha for this addon to get this fix if you need it immediately, OR just download the SavedInstances.lua file and replace in your addon.

**Comment by Tykwer** [comment]
Great, thanks, I will install the Alpha.

Matt

**Comment by Roddd** [comment]
My mistake. This was one of the other map functions that broke. I was confusing with a different one. I have added a fix for this. You can wait till others review my changes and merge it. If it's super annoying, you can grab from my fork temporarily: https://github.com/Roddd/SavedInstances/blob/master/SavedInstances/SavedInstances.lua

The pull request for the fix here is: #136
