### ISSUE TITLE
SavedInstances window not showing.

### ISSUE THREAD

**Issue by MegaFreak101** [SavedInstances/SavedInstances#138]
Yo. I'm using ElvUI, all of my addon icons are next to the minimap and show only when mousing over any. When I mouse over the SI one all of the others get 'hidden' as if SI is showing the blank window. Left clicking on it shows this tiny window only with the clickable X to close it, top right corner closeish to the minimap. I've updated the addon, reinstalled it, tried deleting addon variables/settings. Addon's loading out properly, I can still access the settings and right click the icon but it just doesn't do what I need it to do ;p

![image](https://user-images.githubusercontent.com/41528462/43041382-ea86db28-8d5e-11e8-8f68-1a8fd836ac07.png)

Any ideas on how to get the errors to show up so?

**Comment by Roddd** [comment]
You can turn on displaying errors with:
/console script errors 1

To turn off:
/console script errors 0
