### ISSUE TITLE
Abbreviate Keystone does not abbreviate Legion keystones

### ISSUE THREAD

**Issue by MarcusTorrent** [SavedInstances/SavedInstances#139]
Text remains at full regardless of setting is switched on or off. Only work around currently to make UI readable is to not track keystones.

**Comment by Stanzilla** [comment]
Are you testing this on the char that has the key?

**Comment by Roddd** [comment]
Try resetting character and repopulating SavedInstances. The side effect of my fix was that it will list long dungeons until it is reset. :(

**Comment by Stanzilla** [comment]
Yeah that's a bit unfortunate :/
