### ISSUE TITLE
Nothing appears when mouseover map icon

### ISSUE THREAD

**Issue by gravebanes** [SavedInstances/SavedInstances#140]
3x SavedInstances\SavedInstances-8.0.2.lua:3871: attempt to compare number with nil
SavedInstances\SavedInstances-8.0.2.lua:3871: in function `ShowTooltip'
SavedInstances\SavedInstances-8.0.2.lua:2741: in function `OnEnter'
BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0-36.lua:67: in function <BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:58>
[C]: ?
[C]: ?

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 EnableModule = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 CancelTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 RequestLockInfo = <function> defined @SavedInstances\SavedInstances.lua:2845
 TRADE_SKILL_LIST_UPDATE = <function> defined @SavedInstances\SavedInstances.lua:4974
 SetDefaultModulePrototype = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 IsEnabled = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ADDON_LOADED = <function> defined @SavedInstances\SavedInstances.lua:2825
 RegisterMessage = <function> defined @BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterBucketEvent = <function> defined @SavedInstances\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 memcheck = <function> defined @SavedInstances\SavedInstances.lua:3331
 scan_item_cds = <function> defined @SavedInstances\SavedInstances.lua:4867
 SetEnabledState = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 localarr#RefreshTemp = <table> {
 }
 IterateModules = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 TradeSkillRescan = <function> defined @SavedInstances\SavedInstances.lua:4953
 CHAT_MSG_MONSTER_YELL = <function> defined @SavedInstances\SavedInstances.lua:3055
 localarr#wbsave = <table> {
 }
 OnInitialize = <function> defined @SavedInstances\SavedInstances.lua:2667
 NewModule = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ShowTooltip = <function> defined @SavedInstances\SavedInstances.lua:3791
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 ScheduleRepeatingTimer = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 toonInit = <function> defined @SavedInstances\SavedInstances.lua:2652
 RefreshMythicKeyInfo = <function> defined @SavedInstances\SavedInstances.lua:2908
 GetName = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 localarr#lfrbox = <table> {
 }
 localarr#instancesaved = <table> {
 }
 localarr#categoryshown = <table> {
 }
 RefreshDailyWorldQuestInfo = <function> defined @SavedInstances\SavedInstances.lua:2989
 scale = 1
 RegisterBucketMessage = <function> defined @SavedInstances\Libs\AceBucket-3.0\AceBucket-3.0.lua:200
 orderedModules = <table> {
 }
 baseName = "SavedInstances"
 Disable = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 Enable = <function> defined @BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 Options = <table> {
 }
 showall = false
 BonusRollResult = <function> defined @SavedInstances\SavedInstances.lua:5118
 updateRealmMap = <function> defined @SavedInstances\SavedInstances.lua:2880
 Unregister

**Comment by Roddd** [comment]
What version are you using?

**Comment by mjbergeron** [comment]
I'm also seeing this exact issue.  Version 8.0.5
