### ISSUE TITLE
LUA Errors: 

### ISSUE THREAD

**Issue by rionshin** [SavedInstances/SavedInstances#144]
**4x SavedInstances\config.lua:12: attempt to index field 'svnrev' (a nil value)
SavedInstances\config.lua:12: in main chunk**

Locals:
addonName = "SavedInstances"
vars = <table> {
 Categories = <table> {
 }
 GetServerOffset = <function> defined @SavedInstances\SavedInstances.lua:918
 Indicators = <table> {
 }
 oi_cache = <table> {
 }
 InstanceCategory = <function> defined @SavedInstances\SavedInstances.lua:1161
 questdebug = <function> defined @SavedInstances\SavedInstances.lua:523
 histReapTime = 3600
 QuestInfo = <function> defined @SavedInstances\SavedInstances.lua:453
 normalizeName = <function> defined @SavedInstances\SavedInstances.lua:1068
 config = <table> {
 }
 specialQuests = <function> defined @SavedInstances\SavedInstances.lua:316
 icon = <table> {
 }
 GetNextWeeklyResetTime = <function> defined @SavedInstances\SavedInstances.lua:985
 WorldBosses = <table> {
 }
 FindInstance = <function> defined @SavedInstances\SavedInstances.lua:1094
 debug = <function> defined @SavedInstances\SavedInstances.lua:468
 BonusRollShow = <function> defined @SavedInstances\SavedInstances.lua:5146
 GetRegion = <function> defined @SavedInstances\SavedInstances.lua:934
 scaleCache = <table> {
 }
 ShowDetached = <function> defined @SavedInstances\SavedInstances.lua:3665
 instanceBosses = <function> defined @SavedInstances\SavedInstances.lua:1302
 core = <table> {
 }
 HideDetached = <function> defined @SavedInstances\SavedInstances.lua:3654
 LDB = <table> {
 }
 InGroup = <function> defined @SavedInstances\SavedInstances.lua:3116
 chatMsg = <function> defined @SavedInstances\SavedInstances.lua:463
 UpdateInstance = <function> defined @SavedInstances\SavedInstances.lua:1604
 IsDetached = <function> defined @SavedInstances\SavedInstances.lua:3651
 CategorySize = <function> defined @SavedInstances\SavedInstances.lua:1181
 histTextUpdate = <function> defined @SavedInstances\SavedInstances.lua:3320
 defaultDB = <table> {
 }
 GetNextDailyResetTime = <function> defined @SavedInstances\SavedInstances.lua:959
 HistoryUpdate = <function> defined @SavedInstances\SavedInstances.lua:3235
 histZoneKey = <function> defined @SavedInstances\SavedInstances.lua:3196
 OrderedCategories = <function> defined @SavedInstances\SavedInstances.lua:1375
 UpdateCurrency = <function> defined @SavedInstances\SavedInstances.lua:1913
 OrderedInstances = <function> defined @SavedInstances\SavedInstances.lua:1362
 GetNextDailySkillResetTime = <function> defined @SavedInstances\SavedInstances.lua:972
 currency = <table> {
 }
 histLimit = 10
 HistoryEvent = <function> defined @SavedInstances\SavedInstances.lua:3151
 GetSeasonCurrency = <function> defined @SavedInstances\SavedInstances.lua:2529
 ColoredToon = <function> defined @SavedInstances\SavedInstances.lua:877
 plantName = <function> defined @SavedInstances\SavedInstances.lua:2211
 GetCurrentMapAreaID = <function> defined @SavedInstances\SavedInstances.lua:1977
 QuestCount = <function> defined @SavedInstances\SavedInstances.lua:1034
 UpdateToonData = <function> defined @SavedInstances\SavedInstances.lua:1701
 updateSpellTip = <function> defined @SavedInstances\SavedInstances.lua:1682
 LFRInstances = <table> {
 }
 transInstance = <table> {
 }
 GetNextDarkmoonResetTime = <function> defined @SavedInstances\SavedInstances.lua:1016
 UpdateInstanceData = <function> defined @SavedInstances\SavedInstances.lua:1474
 ToggleDetached = <function> defined @SavedInstances\SavedInstances.lua:3657
 instanceException = <function> defined @SavedInstances\SavedInstances.lua:1280
 timedebug = <function> defined @Inter

**Comment by Stanzilla** [comment]
You are on a very old version.
