### ISSUE TITLE
Killed bosses not shown in dropdown

### ISSUE THREAD

**Issue by Painstormx** [SavedInstances/SavedInstances#151]
The addon correctly registers the number of killed raid bosses, but the list with what bosses that are killed is not correct.
Just did a ToT and addon only shows the bosses killed in the first wing, despite having killed them all (see screenshot).

![image](https://user-images.githubusercontent.com/41920633/43687395-c57a4ed8-98d4-11e8-925a-c8483075f1cb.png)

**Comment by LiangYuxuan** [comment]
it's a bug and still there currently
