### ISSUE TITLE
Show island expeditions weekly progress

### ISSUE THREAD

**Issue by cremor** [SavedInstances/SavedInstances#153]
Would be nice if I could check the progress of my island expeditions weekly in SavedInstances.

**Comment by cremor** [comment]
Found a thread that contains a macro to check the progress, so you can take the code from there: https://www.mmo-champion.com/threads/2423255-Island-Weekly-Quest-Progress-Macro

**Comment by cremor** [comment]
Here are the related weekly quests:
https://www.wowhead.com/quest=53436/azerite-for-the-alliance
https://www.wowhead.com/quest=53435/azerite-for-the-horde

**Comment by Beet4** [comment]
This would be awesome! Please fix :D

**Comment by KnightDemons** [comment]
This would make Islands so much better for alts.

**Comment by cremor** [comment]
@LiangYuxuan @Stanzilla How/where do I enable the tracking of that weekly?
It doesn't show up as a "normal" weekly quest (most likely because you can't accept it like you normally accept quests).

**Comment by Stanzilla** [comment]
Does show up when you hover the weekly quests header for me

**Comment by cremor** [comment]
Weird, doesn't for me. I even tried interacting with the table and talking with the NPC where you complete it but it still doesn't show up. Do I need to "start" the quest by doing an island expedition?

But since 8.1 added the progress of that weekly to the world map and minimap it's not really important any more to have it in the addon. Only for alts it would be still nice.

**Comment by LiangYuxuan** [comment]
try Alpha since there are not released yet.

In addition, addon just check if quest is done by api `IsQuestFlaggedCompleted`. You don't have to "start" the quest.

**Comment by cremor** [comment]
I did try the latest alpha.

If the addon just checks `IsQuestFlaggedCompleted`, how can it show its progress (x/36000 azerit)?

**Comment by Stanzilla** [comment]
It does only show if it's completed
