### ISSUE TITLE
Feature Request - Sync Data between Friends

### ISSUE THREAD

**Issue by kientran** [SavedInstances/SavedInstances#157]
I'd like a feature where we can offer to share our saved instance information with defined friends.  With a bunch of mythics to do with many alts, it'd be nice to know who has done what to help coordinate.

**Comment by HgAlexx** [comment]
+1
It would also help to sync multiple accounts. Of course both characters would need to be online at the same time for data to be shared.

**Comment by Stanzilla** [comment]
that's a no from me

**Comment by q8light** [comment]
Would love a similar feature to view my other characters on different sub-accounts but under the same battle net .
