### ISSUE TITLE
Integration with the EncounterJournal (Adventure Guide)

### ISSUE THREAD

**Issue by ja0b** [SavedInstances/SavedInstances#158]
Hi,

I just want to post this idea here and hopefully, someone can implement it, I don't have such advance knowledge to do it myself.

So currently we have a great addon that displays a list showing you where you are saved, but it would be great to see this list integrated with the adventure guide so when you open it you can quickly see what is your current status like this:

![adventureguide2](https://user-images.githubusercontent.com/11311685/44957157-15ae2e00-aecf-11e8-9a8b-a7af6ebd2d65.png)

Update 2
------------

![adventureguide4](https://user-images.githubusercontent.com/11311685/44978007-f1535f80-af69-11e8-94fd-b18bd53d2c1d.png)

![adventureguide6](https://user-images.githubusercontent.com/11311685/44978016-f7e1d700-af69-11e8-95db-83ccbfa14c83.png)

What do you think?
I hope you are open to suggestions, thanks!

**Comment by cremor** [comment]
I've searched for something similar and found a separate addon that does this: https://wow.curseforge.com/projects/encounter-journal-saved-instances

**Comment by ja0b** [comment]
@cremor that’s amazing, I’ll have a look when I can, but this seems to do it all 👍
