### ISSUE TITLE
Wrong Location for Weekly/Daily quests

### ISSUE THREAD

**Issue by svetlocrno** [SavedInstances/SavedInstances#159]
Shows completed quests as if they were all from the same zone, started with 8.0.1
https://imgur.com/a/75uKgEM

**Comment by joevt** [comment]
A solution at https://www.curseforge.com/wow/addons/saved_instances?comment=1222

**Comment by Stanzilla** [comment]
Are you sure you are on the latest version?

**Comment by joevt** [comment]
8.0.6-1-g3950175-alpha September 19, 2018.

**Comment by joevt** [comment]
The code assigns zonename in one loop.
https://github.com/SavedInstances/SavedInstances/blob/3950175d359dbfb5b7e78941af29caf86b2defc5/SavedInstances/SavedInstances.lua#L1967
But the next loop does not assign zonename (or it's set to blank for some quests), so all the names will be the same or blank.
https://github.com/SavedInstances/SavedInstances/blob/3950175d359dbfb5b7e78941af29caf86b2defc5/SavedInstances/SavedInstances.lua#L1988

**Comment by Stanzilla** [comment]
Want to make a PR?
