### ISSUE TITLE
Siege of Boralus Boss lockout.

### ISSUE THREAD

**Issue by Nifelhein** [SavedInstances/SavedInstances#160]
Pretty simple issue, the first boss is different if you are Horde or Alliance, the addon is showing both as being available for both factions, even after you kill the relevant one.

**Comment by Azilroka** [comment]
That is how this lockout works. I have a similar issue with a datatext in ElvUI / Tukui. Blizzard returns all 5 bosses even though you only have access to 4.

**Comment by Nifelhein** [comment]
Yeha if it is a pull up and display it will stay as is, unless code around to display differently if any of the two is killed. it is M0 anyways, so not a deal breaker for the addon.
