### ISSUE TITLE
Uldir Raid Process in Wrong Expansion

### ISSUE THREAD

**Issue by LiangYuxuan** [SavedInstances/SavedInstances#164]
`GetLFGDungeonInfo(1888)` returns wrong expansionLevel 6 (should be 7 for BfA), which makes Uldir is in "Legion: Raid"

**Comment by LiangYuxuan** [comment]
Update:

I find Uldir Dungeon Info returned by `GetLFGDungeonInfo` have right expansionLevel 7 on Normal but wrong on Heroic and Mythic. Also I find some code ignoring Normal Raid in `function addon:UpdateInstance(id)` which I don't have any idea of it.

So I changed it and make a PR, it works good for me.

**Comment by Stanzilla** [comment]
Thanks again!
