### ISSUE TITLE
Old Raids: LFR Boss Lockout not being tracked properly

### ISSUE THREAD

**Issue by Nifelhein** [SavedInstances/SavedInstances#170]
I did some runs for Transmogs and noticed that while the tooltip lists the amount of killed bosses and saved stated in it hovering over the instance doesn't show the bosses as being defeated.

**Comment by valahman** [comment]
Yes, old LFR doesn't show the bosses as being defeated.
![wowscrnshot_110918_182830](https://user-images.githubusercontent.com/44904284/48275563-7701f880-e44e-11e8-92c1-1b6a8b2da7b0.jpg)
 Any know how to fix this?

**Comment by LiangYuxuan** [comment]
Duplicated #151
