### ISSUE TITLE
BfA Keys on characters not being shown in overview pane

### ISSUE THREAD

**Issue by tanknotes** [SavedInstances/SavedInstances#173]
Hello,

The keystones you have on your characters do not appear to be getting tracked as they were in Legion. Was nice to have an overview of what keys you have on your account without using another addon. Can the functionality from Legion be recycled for this purpose?

Thanks

**Comment by Stanzilla** [comment]
can you test if this is still a problem in the alpha version?

**Comment by tanknotes** [comment]
Just checked the alpha. It works on there.
