### ISSUE TITLE
Rework how emissaries are displayed

### ISSUE THREAD

**Issue by Eiltherune** [SavedInstances/SavedInstances#175]
I'm sure this would likely be a large task to complete, but here are my ideas for reworking how we display emissaries:

1) Save the name of the emissaries outside of the character's scope (in db.Emissary maybe). This would allow us to reduce bloat and also display the name of the emissary after it has been completed.
2) Rather than show the 3 emissaries on separate lines, show them similar to multi-difficulty raid lockouts, where a mouse-over on the completion icon (✓/X/?) would show the details of that emissary quest. This would incorporate using the X indicator for an emissary that is in progress, instead of the current "1/4", as the mouse-over tooltip would then show the progress information.
3) Once we have the 3 emissaries combined onto one line, re-implement Legion emissaries on a separate line for those users who want to track all 6 emissary quests on each toon because they're a glutton for punishment.  I mean, who doesn't want to do 6 emissaries on 12 toons every day? Sleep? What's that?

I'm willing to help with these, but I don't really understand how the raid lockout displays work.

**Comment by Eiltherune** [comment]
Also in the db.Emissary section, we could connect Alliance/Horde equivalent emissaries (7th Legion and Honorbound are always up at the same time, Proudmoore/Zandalari, Embers/Voldunai, Storm's Wake/Talanji).

Whether or not we cache the emissary names outside of character scope, combining the emissaries onto one line would clarify which factions each toon has emissaries for. Currently if I have two Alliance and one Horde toon being tracked, logging on to the Horde toon would show that all all 3 have Talanji's Expedition, Champions of Azeroth, and Honorbound as their active emissaries, while logging onto either Alliance toon would show Storm's Wake, Champions of Azeroth, and 7th Legion. Minor OCD detail, but it would be nice to fix it.

**Comment by Stanzilla** [comment]
The whole code is pretty bad and I'd love to rework it, I have been trying a few things but haven't finalized anything. If you want to take a stab, please do :)
