### ISSUE TITLE
Issues about Keystone in the character's bag

### ISSUE THREAD

**Issue by xcheng10** [SavedInstances/SavedInstances#176]
Everytime when i was reloading the page, it will pop up such text in the following. Even if I receive the loot, it does so too. And if i didn't receive any mystic ketstone in my bag, it would disappear

|Hkeystone 
158923 
250 
4 
9 
6 
0 
0[xxxxx：xxxxxx (4)]  #dungeonname
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
|Hkeystone 
158923 
250 
4 
9 
6 
0 
0[xxxxx：xxxxxx (4)]  #dungeonname
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil 
nil

**Comment by LiangYuxuan** [comment]
Seems like you need to disable debug mode

**Comment by eTzmNcbkrng** [comment]
@LiangYuxuan is correct, that is debug text I added when I was first trying to figure out how to get keystone tracking to work.  
You can uncheck the debug option in in the config to remove this.
