### ISSUE TITLE
[Feature Request] Option for "Don't show window while in combat"

### ISSUE THREAD

**Issue by StevenSeegal** [SavedInstances/SavedInstances#179]
As I'm using my mouse to select targets I tend to get my cursor up to my broker bar and then the windows pops up.
Can you please implement an config option to not show the windows while in combat?
This is what I did on my side to make it work on line 2515 in SavedInstances.lua:
 
if not addon:IsDetached() and not db.Tooltip.DisableMouseoverthen
    if [config.option.here] and notUnitAffectingCombat("player") then
        core:ShowTooltip(frame)
    end
end

**Comment by Stanzilla** [comment]
That's something your broker display should do, not the broker itself

**Comment by StevenSeegal** [comment]
You're totally right, never thought i'd be an option in the broker display but I found it and it works. Been getting everything to show for years lol. Thanks for this info, it helped me a lot!
