### ISSUE TITLE
mythic key best

### ISSUE THREAD

**Issue by jbuettel09** [SavedInstances/SavedInstances#189]
only displaying keystone not completed keystone for week

**Comment by ronaldpereira** [comment]
Just saw this too. The "Mythic Best" indicator isn't working on the actual release version. Already reinstalled addon (for possible local unwanted changes) and tested enabling/disabling the "Mythic Best" option. None of them worked.

**Comment by LiangYuxuan** [comment]
Fixed in 5a38419, try Alpha since there are not released yet.
