### ISSUE TITLE
Expeditions Weekly, Darkshore World Boss

### ISSUE THREAD

**Issue by oresika** [SavedInstances/SavedInstances#195]
would like to see weekly progress/completion of expeditions as well as ivus the forest lord world boss

**Comment by LiangYuxuan** [comment]
We added Darkshore's World Bosses in c543464. 

Request of Island Expeditions' weekly quests track was mentioned in #153, but wowhead shows that the quests are weekly, so I think the addon should auto track this two quests.
Anyway, I'm trying to fix this.
