### ISSUE TITLE
Not showing best Mythic completed for 1 character.

### ISSUE THREAD

**Issue by DakuProductions** [SavedInstances/SavedInstances#198]
Mythic Key Best is not showing for my main toon after completing a key for the week.  My other 2 characters have no issues and both highest keys completed are shown.  This started happening last week after 8.1 was released.

https://gyazo.com/8db0feed2ba1b09be7782699d7203734
https://gyazo.com/c38e635f1b415ae3813ba98d3b275381

**Comment by LiangYuxuan** [comment]
fixed in 5a38419 and released in v8.0.8

**Comment by DakuProductions** [comment]
perfect, thank you!  Works now!
