### ISSUE TITLE
Possible to track daily warfront world quests per faction?

### ISSUE THREAD

**Issue by oresika** [SavedInstances/SavedInstances#199]
since there are 5 quests per warfront per day (and each warfront can only be had by 1 faction at a time) is it possible to track the WQs as dailies?

also can we make the "zuldazar/tiragarde" very long title text optional

**Comment by LiangYuxuan** [comment]
Optional emissary name text done, not sure for tracking WQ yet (#103)

**Comment by oresika** [comment]
where is this option located i cant find it

**Comment by LiangYuxuan** [comment]
uncheck General > Show all emissary names
if you use latest alpha, find it in Emissary quests, or Miscellaneous Tracking for older version
