### ISSUE TITLE
island expeditions cap and warfront scenario checkmarks

### ISSUE THREAD

**Issue by oresika** [SavedInstances/SavedInstances#206]
"azerite for the alliance" and "azerite for the horde" as well as "battle for arathi" or darkshore all show up under weekly quests completed. is it possible for these to be granted their own checkmarks similar to world bosses?

**Comment by LiangYuxuan** [comment]
maybe Warfront quests is worth a place since their reset time are not really weekly, but for the island weekly quests, if you only care about if it's completed, it is a weekly quest like others.

**Comment by mr-aleks** [comment]
I personally do not understand, everywhere there is "1" and somewhere 2, where the expeditions are completed, and where not? Why can not enter a separate line specifically for the expedition cap?

**Comment by LiangYuxuan** [comment]
> I personally do not understand, everywhere there is "1" and somewhere 2, where the expeditions are completed, and where not? Why can not enter a separate line specifically for the expedition cap?

Currently Island Expedition Weekly Quest counts as weekly quest, so you can hover on the number and check the list to find if it is done this week. Separate line to show progress is under development.

**Comment by mr-aleks** [comment]
I did not see it and did not know it, thanks :)
