### ISSUE TITLE
Issues, Labels, Projects

### ISSUE THREAD

**Issue by LiangYuxuan** [SavedInstances/SavedInstances#207]
I have been watching on these for few months, but I found labels and "timeline" (#91) not used and issues from BfA pre-patch are not closed since they're solved for month. I think it's too hard for @Stanzilla to deal with this as he's the only active maintainer in past months. Now @jokeyrhyme becomes active and it might be better to deal with this things.

Also I'm willing to help with these.

**Comment by Stanzilla** [comment]
It's probably a good idea to set up labels and roles on the project properly, I can do that. I've only recently been given the ownership rights of the GitHub org by @eTzmNcbkrng so I was not able to do that before. I can add you as a contributor so you can do labels, issues etc.
