### ISSUE TITLE
Warmode Indicator

### ISSUE THREAD

**Issue by Nifelhein** [SavedInstances/SavedInstances#209]
Switching to alts for mount/pet/toy farming rares can be quite  apain and having to guess or remember whether each particular character was left with warmode on or off can be quite a pain. Having this marked on the addon would be immensely helpful.

It could either be done with the first live either above or below the character name showing the warmode status (gold color for ON and grey for OFF) or as a graphical crossed swords after the warmode on characters.

**Comment by LiangYuxuan** [comment]
Enabling warmode marks PvP as well as gives you a buff, and you can be more sure by opening talent frame. So it might be not a problem after login.

Recoloring names or adding new icon may leads to confusing, so I guess we can add a new line in character's tooltip showing `Warmode ON/OFF`, which is painless and helpful.

**Comment by Stanzilla** [comment]
I'm not sure something like that belongs into SI

**Comment by LiangYuxuan** [comment]
I mean, flagged PvP is easy to find at first sight, but we know the different.

Back to the topic, SI tracks item level, gold and even ranked battlegrounds rating currently. And it'll be shown in the character's tooltip when you hover the character's name. So when you are finding a character if it's "Warmode on", it won't take long. Actually, enabling or disabling warmode may not affect farming as it can be easily turned off in the rest zone. So, I don't think showing warmode status in a row like instances is a good idea.

**Comment by Stanzilla** [comment]
Yeah I'm against showing it at all, it's not something that really belongs in SI, SI was made for things that you need to know before you log onto a character, like how much of currency x he has or did he do y that week. Warmode is not such a check-list-y item.

**Comment by Nifelhein** [comment]
My reasoning for having it shown in SI is just that farming for open world pets/toys/mounts right now make a world of difference whether you have warmode on or not, even more if you want to quickly jump to a given warmode to take advantage of a group, reported spawn and so on.

As the game evolved SI has become my most used addon simply to check status before swithcing characters and right now the only thing I want to know before switching that SI can't tell me is whether I ahve warmode on or off in a given character.

Warmode changing is painless if you have it on and a major pain if you have it off, I trust your decision regarding the addon either way, was just giving a suggestion based on the use I make of the addon on a daily basis and farming routines. I barely ever use Altoholic (though the datastore libraries are very very useful for the item amount in tooltips) majorly because SI is so useful.

**Comment by LiangYuxuan** [comment]
I think Warmode is like a "status" rather than "check-list-item", it just like showing the zone where character are, which provides some basic information about a character, but of-cause not on check list. You can imagine if zone is showing like instances in a row, that's bad.

So, I still would like to add it in character tooltip. Yes, it would be quite painful when you want to find out all "Warmode ON/OFF" character, or next "Warmode ON" which makes you hover on names next to next. But ensuring the main tooltip clear is an important thing either.

**Comment by Nifelhein** [comment]
I actually think the tooltip is perfect for it as well, for the very same reasons.
