### ISSUE TITLE
Wrong Weekly Reset Time on CN Realm

### ISSUE THREAD

**Issue by LiangYuxuan** [SavedInstances/SavedInstances#211]
**Describe the bug**
Wrong weekly reset time on CN realm.

**Do you have an error log of what happened?**
No

**To Reproduce**
`/dump SavedInstances.GetNextDailyResetTime()`
`/dump SavedInstances.GetServerOffset()`
And then we find the reset time is one day later than it really is. On CN realm, it returns friday other than thursday.

**Additional context**
It works last week and fails now, since we haven't changed the code around this.
I find `addon:GetServerOffset` have some problem, b3b2081 makes `CalendarGetDate` -> `C_Calendar.GetDate` and b80983d removed `-1` following, and then the function just comparing 0-based days to 1-based days.
Simply adding `+1` on `localDay` will fix this, but I'm wondering why it works in the past and is this problem on other realm either?

@Stanzilla since I don't have account on other realm, can you check this out on your realm?

**Comment by Bottox** [comment]
Same problem here , in EU server (dalaran)

**Comment by LiangYuxuan** [comment]
> Same problem here , in EU server (dalaran)

@Bottox to confirm, did you find this problem this week? or a bit longer?

**Comment by Bottox** [comment]
Yes, it's only appeared since this week. Event, instance, quest...etc reset only Thursday instead of Wednesday.

**Comment by JStevenson65** [comment]
After the NA reset it seems that this is happening as well.  All of my toons are still showing they have capped islands for the week after logging in today
