### ISSUE TITLE
Add Conquest point cap for weekly PvP chest

### ISSUE THREAD

**Issue by domzae** [SavedInstances/SavedInstances#213]
_**Is your feature request related to a problem? Please describe.**_
Would like to see progress on the conquest cap/weekly chest.

_**Describe the solution you'd like**_
```
500/500 (green text) : If the pvp chest has been earned for that character
35/500 (white text) : If the pvp chest has not been earned, show progress
```

Further development would be to show if the character is fully caught up on the gear progression system:
```
Green Tick : If chest achieved and fully caught up
300/500+Green Tick (green text) : If chest achieved but not caught up show progress towards next cap: 
300/500 (white text) : If chest not achieved
```

_**Additional context**_
Reaching the end of the conquest bar will flag the character to be eligible to receive a chest with pvp gear of an item level based on the highest rating a win has been achieved in any competitive bracket (2v2,3v3,RBG). 
At the start of each week, the character will remain on any progress he/she already had. It does not matter if you started the week at 0/500 or 490/500, as long as you reach 500/500 and turn in the associated quest.

**Comment by LiangYuxuan** [comment]
https://github.com/SavedInstances/SavedInstances/issues/101#issuecomment-450544599

willing to do this, but still thinking if tracking progress is necessary
