### ISSUE TITLE
Battle of Dazar'alor does not appear to be tracking correctly

### ISSUE THREAD

**Issue by tanknotes** [SavedInstances/SavedInstances#222]
**Describe the bug**
I have cleared normal mode and 7/9 heroic on one of my characters and it states:
11/9 Normal
9/9 Heroic

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**
![image](https://user-images.githubusercontent.com/42097248/51800532-29fd1980-2228-11e9-864e-547d76f76bfb.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**
8.0.9-5-g3880be3-alpha

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by LiangYuxuan** [comment]
Duplicated #220

**Comment by LiangYuxuan** [comment]
Hi, can you check #233 and see if you can dump your instances link?
