### ISSUE TITLE
Add an option for only showing current character

### ISSUE THREAD

**Issue by pitripan** [SavedInstances/SavedInstances#223]
There is an option to always show your current character first and show all other tracked characters.
I would like to have an extra checkbox to **only** show the data for the current logged in character.

**Comment by LiangYuxuan** [comment]
Mark "NEVER" on all toons and you will get what you want.

**Comment by pitripan** [comment]
This isn't a good solution. :/

**Comment by SacredDuckwhale** [comment]
Wouldn't this hide all characters except the one not marked with "NEVER"? If so, it's only a somewhat reasonable workaround (but not a solution( if you have exactly one character you're interested in tracking.

**Comment by LiangYuxuan** [comment]
Actually enabling always show current character and marking "NEVER" on all characters means showing current character only. So it solves this issue.

Yes it is not a perfect solution, but I think is enough for SI. SI is designed for tracking a lot of characters, so adding a standalone option focusing on tracking current character is quite unnecessary.

**Comment by SacredDuckwhale** [comment]
Agreed after playing around with the options.

What you have to do is set ALL characters to "Never show", even the current one. Then, check the "Show self always" box and it will still show the currently logged-in character, overriding the "Never show" setting for that one only.

This is pretty much exactly what was asked for, even if you'll have to set each new character to "Never show" once. That seems like a reasonable amount of work, comparable to all the things you have to set up on a new character anyway (and it can be similarly automated). Or am I mistaken?
