### ISSUE TITLE
Unrecognized LFR instance parent id=1942

### ISSUE THREAD

**Issue by manly1138** [SavedInstances/SavedInstances#225]
**Describe the bug**

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by manly1138** [comment]
Saved Instances said "Please report this issue at github"

**Comment by starcookies** [comment]
same issue when im in hfc mythic it keeps spamming itself. using the current verison of saved instances
it has spammed me 3 times in the last 5 mins
verison 8.0.9

https://imgur.com/a/Wa5psM6

**Comment by LiangYuxuan** [comment]
Fail to reproduce this

**Comment by Rujugy** [comment]
I got this error right after doing lfr BoD on alliance side; the hover over popup is not showing lfr BoD progress either

disabling all other addons still has the issue, using 8.0.9 version

**Comment by Rujugy** [comment]
Sorry for the double post, but steps to reproduce:
Log into character that didn't do BoD LFR (still ally tho) -> get error
Delete first character from addon history, reload ui -> no error
do first boss of BoD LFR -> get error on boss kill into hover over minimap icon

**Comment by cybernami** [comment]
This is an error occuring when "Combine LFR" is turned on
I wonder if it's because the 2 other comming LFR raids are not open yet?

    for boxname, line in pairs(lfrbox) do
      if type(boxname) == "number" then
        bugReport("Unrecognized LFR instance parent id= "..boxname)
        lfrbox[boxname] = nil
      end
    end

boxname is 1942 and recognized as a number which shows this error... maybe somewhere earlier in the code the purpose was to replace boxname to a string with the name of the raid... but that string does not exist in the lookup table used there and because of that it does not get to be a string?

**Comment by boudreau22** [comment]
**Describe the bug** When I hover over the icon attached to the map I receive the error shown in the screenshot.

**Do you have an error log of what happened?** No.

**To Reproduce** Complete M+ 9 Siege of Boralus, hearth from dungeon to The Great Seal in Zuldazar and mouse over the icon attached to the map.
 
**Screenshots** <img width="409" alt="screen shot 2019-01-31 at 10 26 41 am" src="https://user-images.githubusercontent.com/18519302/52067422-9047ac00-2548-11e9-93d7-37fb3f9d16f1.png">

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?** Not running ElvUI, but other addons are enabled.

**Which version of SavedInstances are you using?** 8.0.9

**Was it working in a previous version? If yes, which was the last good one?** It was working before BoD was released, but I'm unsure what version of SavedInstances was running.

**Additional context** This has also happened at other times when hovering over the icon attached to the map. Possibly once per login.

**Comment by adelpha** [comment]
That'll be LFR Defence of Dazar'alor (first wing of BfD).
