### ISSUE TITLE
Empty window when open

### ISSUE THREAD

**Issue by Bottox** [SavedInstances/SavedInstances#227]
Hi,
Saved instance stop working correctly since last update, i only have an empty windows when i open it.
![wowscrnshot_013019_203045](https://user-images.githubusercontent.com/46353113/52010881-e67c0700-24d6-11e9-9fa9-bc12466fff52.jpg)

**Comment by Stanzilla** [comment]
post your errors, install bugsack etc if you don't have it

**Comment by jasoncgc** [comment]
Got the same problem

**Comment by jasoncgc** [comment]
> post your errors, install bugsack etc if you don't have it

1x SavedInstances\SavedInstances-@project-version@.lua:3908: attempt to concatenate local 'name' (a nil value)
SavedInstances\SavedInstances-@project-version@.lua:3908: in function `ShowTooltip'
SavedInstances\SavedInstances-@project-version@.lua:2427: in function `OnEnter'
...ns\FishingBuddy\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua:77: in function <...ns\FishingBuddy\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 localarr#categoryrow = <table> {
 }
 EnableModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 HeaderFont = <function> defined @SavedInstances\SavedInstances.lua:3325
 CancelTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:145
 RequestLockInfo = <function> defined @SavedInstances\SavedInstances.lua:2522
 localarr#blankrow = <table> {
 }
 TRADE_SKILL_LIST_UPDATE = <function> defined @SavedInstances\SavedInstances.lua:4373
 SetDefaultModulePrototype = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 EncounterEnd = <function> defined @SavedInstances\SavedInstances.lua:2625
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:92
 DisableModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ADDON_LOADED = <function> defined @SavedInstances\SavedInstances.lua:2502
 RegisterMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterBucketEvent = <function> defined @NPCScan\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 memcheck = <function> defined @SavedInstances\SavedInstances.lua:2868
 scan_item_cds = <function> defined @SavedInstances\SavedInstances.lua:4266
 localarr#showcol = <table> {
 }
 SetEnabledState = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 localarr#RefreshTemp = <table> {
 }
 IterateModules = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 TradeSkillRescan = <function> defined @SavedInstances\SavedInstances.lua:4352
 CHAT_MSG_MONSTER_YELL = <function> defined @SavedInstances\SavedInstances.lua:2593
 localarr#wbsave = <table> {
 }
 OnInitialize = <function> defined @SavedInstances\SavedInstances.lua:2351
 NewModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ShowTooltip = <function> defined @SavedInstances\SavedInstances.lua:3337
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:170
 ScheduleRepeatingTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:127
 CancelAllTimers = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:158
 toonInit = <function> defined @SavedInstances\SavedInstances.lua:2335
 SendMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 GetName = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 localarr#instancerow = <table> {
 }
 QuestRefresh = <function> defined @SavedInstances\SavedInstances.lua:2880
 localarr#lfrbox = <table> {
 }
 name = "SavedInstances_Core"
 localarr#instancesaved = <table> {
 }
 RegisterBucketMessage = <function> defined @NPCScan\Libs\AceBucket-3.0\AceBucket-3.0.lua:200
 orderedModules = <table> {
 }
 localarr#categoryshown = <table> {
 }
 Disable = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 scale = 1
 Enab

**Comment by jasoncgc** [comment]
> post your errors, install bugsack etc if you don't have it

1x SavedInstances\SavedInstances-8.0.10.lua:3908: attempt to concatenate local 'name' (a nil value)
SavedInstances\SavedInstances-8.0.10.lua:3908: in function `ShowTooltip'
SavedInstances\SavedInstances-8.0.10.lua:2427: in function `OnEnter'
...ns\FishingBuddy\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua:77: in function <...ns\FishingBuddy\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 localarr#categoryrow = <table> {
 }
 EnableModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 HeaderFont = <function> defined @SavedInstances\SavedInstances.lua:3325
 CancelTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:145
 RequestLockInfo = <function> defined @SavedInstances\SavedInstances.lua:2522
 localarr#blankrow = <table> {
 }
 TRADE_SKILL_LIST_UPDATE = <function> defined @SavedInstances\SavedInstances.lua:4373
 SetDefaultModulePrototype = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 EncounterEnd = <function> defined @SavedInstances\SavedInstances.lua:2625
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:92
 DisableModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ADDON_LOADED = <function> defined @SavedInstances\SavedInstances.lua:2502
 RegisterMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterBucketEvent = <function> defined @NPCScan\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 memcheck = <function> defined @SavedInstances\SavedInstances.lua:2868
 scan_item_cds = <function> defined @SavedInstances\SavedInstances.lua:4266
 localarr#showcol = <table> {
 }
 SetEnabledState = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 localarr#RefreshTemp = <table> {
 }
 IterateModules = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 TradeSkillRescan = <function> defined @SavedInstances\SavedInstances.lua:4352
 CHAT_MSG_MONSTER_YELL = <function> defined @SavedInstances\SavedInstances.lua:2593
 localarr#wbsave = <table> {
 }
 OnInitialize = <function> defined @SavedInstances\SavedInstances.lua:2351
 NewModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ShowTooltip = <function> defined @SavedInstances\SavedInstances.lua:3337
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:170
 ScheduleRepeatingTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:127
 CancelAllTimers = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:158
 toonInit = <function> defined @SavedInstances\SavedInstances.lua:2335
 SendMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 GetName = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 localarr#instancerow = <table> {
 }
 QuestRefresh = <function> defined @SavedInstances\SavedInstances.lua:2880
 localarr#lfrbox = <table> {
 }
 name = "SavedInstances_Core"
 localarr#instancesaved = <table> {
 }
 RegisterBucketMessage = <function> defined @NPCScan\Libs\AceBucket-3.0\AceBucket-3.0.lua:200
 orderedModules = <table> {
 }
 localarr#categoryshown = <table> {
 }
 Disable = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 scale = 1
 Enab

**Comment by jasoncgc** [comment]
> Got the same problem

2x SavedInstances\SavedInstances-@project-version@.lua:3908: attempt to concatenate local 'name' (a nil value)
SavedInstances\SavedInstances-@project-version@.lua:3908: in function `ShowTooltip'
SavedInstances\SavedInstances-@project-version@.lua:2427: in function `OnEnter'
...ns\FishingBuddy\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua:77: in function <...ns\FishingBuddy\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 localarr#categoryrow = <table> {
 }
 EnableModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 HeaderFont = <function> defined @SavedInstances\SavedInstances.lua:3325
 CancelTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:145
 RequestLockInfo = <function> defined @SavedInstances\SavedInstances.lua:2522
 localarr#blankrow = <table> {
 }
 TRADE_SKILL_LIST_UPDATE = <function> defined @SavedInstances\SavedInstances.lua:4373
 SetDefaultModulePrototype = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 EncounterEnd = <function> defined @SavedInstances\SavedInstances.lua:2625
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:92
 DisableModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ADDON_LOADED = <function> defined @SavedInstances\SavedInstances.lua:2502
 RegisterMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterBucketEvent = <function> defined @NPCScan\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 memcheck = <function> defined @SavedInstances\SavedInstances.lua:2868
 scan_item_cds = <function> defined @SavedInstances\SavedInstances.lua:4266
 localarr#showcol = <table> {
 }
 SetEnabledState = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 localarr#RefreshTemp = <table> {
 }
 IterateModules = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 TradeSkillRescan = <function> defined @SavedInstances\SavedInstances.lua:4352
 CHAT_MSG_MONSTER_YELL = <function> defined @SavedInstances\SavedInstances.lua:2593
 localarr#wbsave = <table> {
 }
 OnInitialize = <function> defined @SavedInstances\SavedInstances.lua:2351
 NewModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 ShowTooltip = <function> defined @SavedInstances\SavedInstances.lua:3337
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:170
 ScheduleRepeatingTimer = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:127
 CancelAllTimers = <function> defined @HandyNotes_WarfrontRares\libs\AceTimer-3.0\AceTimer-3.0.lua:158
 toonInit = <function> defined @SavedInstances\SavedInstances.lua:2335
 SendMessage = <function> defined @Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 GetName = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 localarr#instancerow = <table> {
 }
 QuestRefresh = <function> defined @SavedInstances\SavedInstances.lua:2880
 localarr#lfrbox = <table> {
 }
 name = "SavedInstances_Core"
 localarr#instancesaved = <table> {
 }
 RegisterBucketMessage = <function> defined @NPCScan\Libs\AceBucket-3.0\AceBucket-3.0.lua:200
 orderedModules = <table> {
 }
 localarr#categoryshown = <table> {
 }
 Disable = <function> defined @AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 scale = 1
 Enab
