### ISSUE TITLE
unrecognized LFR instance 

### ISSUE THREAD

**Issue by Trixz2018** [SavedInstances/SavedInstances#229]
Parent id= 1942

**Comment by adelpha** [comment]
That'll be Defence of Dazar'alor (first wing of BfD).

**Comment by LiangYuxuan** [comment]
Duplicated #225

**Comment by Av8oR127** [comment]
Same here parent id = 1942

**Comment by LiangYuxuan** [comment]
@Av8oR127 please update SI to 8.0.10
