### ISSUE TITLE
royal chemical company

### ISSUE THREAD

**Issue by Zendelar** [SavedInstances/SavedInstances#234]
Hello, the addon for some reason does not track dungeons passed through the search group in the royal chemical company !!! I'm talking about 10 dungeons per hour!

**Comment by LiangYuxuan** [comment]
https://github.com/SavedInstances/SavedInstances/blob/ccd7ae889b4f20ea1254be01220eb2e3d2b9f23d/SavedInstances/SavedInstances.lua#L2784-L2786

Simply commenting this out will work, but I'm looking into something more stable.
