### ISSUE TITLE
showing 3/9M , while I only did 1 boss, 

### ISSUE THREAD

**Issue by Rafinono** [SavedInstances/SavedInstances#239]
**Describe the bug**

showing 3/9M while only 1 boss is killed, and had 10/9HC kills while 8/9 on another char
**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**
latest at this time -  8.0.10
**Was it working in a previous version? If yes, which was the last good one?**
First time I use the addon.
**Additional context**
http://prntscr.com/mqt7ty Screenshot of the annoying bug/feature whatever

**Comment by LiangYuxuan** [comment]
fixed in 59f0d98, please check out latest alpha.
