### ISSUE TITLE
LUA error at daily reset

### ISSUE THREAD

**Issue by hollo6** [SavedInstances/SavedInstances#242]
**Describe the bug**
Was online when the daily reset happened, got the error that time.

**Do you have an error log of what happened?**
Date: 2019-03-05 08:01:06
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\Emissary.lua line 81:
   attempt to index local 'tbl' (a nil value)
Debug:
   (tail call): ?
   SavedInstances\Emissary.lua:81: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by R-Adrian** [comment]
just got that error too

**Describe the bug**
in Europe, at 8 AM server time when the dailies are supposed to reset (07 AM UTC), if you already don't have any lockouts to be affected by the reset then you get a LUA error.

**Do you have an error log of what happened?**
```
Date: 2019-03-05 08:01:07
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\Emissary.lua line 81:
   attempt to index local 'tbl' (a nil value)
Debug:
   (tail call): ?
   SavedInstances\Emissary.lua:81: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
```

  SavedInstances, v8.0.10-18-gcaa836f
