### ISSUE TITLE
Boss Kill count > #bosses in raid

### ISSUE THREAD

**Issue by mrbuds** [SavedInstances/SavedInstances#246]
**Describe the bug**
![prev](https://i.imgur.com/9iltnvl.png)

**Do you have an error log of what happened?**
no error in bugsack

**To Reproduce**
i don't know

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no but i don't use elvui or any skinning addon

**Which version of SavedInstances are you using?**
8.0.10

**Was it working in a previous version? If yes, which was the last good one?**
It's the first time i see this happening

**Additional context**
[SavedInstances.zip](https://github.com/SavedInstances/SavedInstances/files/2948535/SavedInstances.zip)

**Comment by LiangYuxuan** [comment]
fixed in 59f0d98, please try latest alpha
