### ISSUE TITLE
New Feature: Track the CD for the Order Hall ability to instantly complete world quests

### ISSUE THREAD

**Issue by Nifelhein** [SavedInstances/SavedInstances#25]
Tracking the 18h CD on the ability to instantly complete a world quest would make alt hopping a lot less frequent.

The order hall upgrade is available to Warlocks, Mages, Demon Hunters, Death knights Warriors and Paladins.

**Comment by SiegaPlays** [comment]
I went here to request the same notifier.

If it is any help, the order hall advancement 18H names are:

Death Knight: [Frost Wyrm](http://www.wowhead.com/order-advancement=432/frost-wyrm)
Warlock: [Unleash Infernal](http://www.wowhead.com/order-advancement=367/unleash-infernal)
Warrior: [Val'kyr Call](http://www.wowhead.com/order-advancement=410/valkyr-call)
Demon Hunter: [Fel Hammer's Wrath](http://www.wowhead.com/order-advancement=421/fel-hammers-wrath) 
Mage: [Might of Dalaran](http://www.wowhead.com/order-advancement=388/might-of-dalaran)
Paladin: [Grand Crusade](http://www.wowhead.com/order-advancement=399/grand-crusade) 

This page is related to being creditted the first use, no idea if it can help track down the timer:
[Use the World Quest Nuke spell. Internal Only](http://www.wowhead.com/npc=113309/use-the-world-quest-nuke-spell-internal-only)

**Comment by SiegaPlays** [comment]
Credit for picking up the item to do the 18h ability with:
[WQ Nuke Quest Item Collected.](http://www.wowhead.com/npc=113323/wq-nuke-quest-item-collected-internal-only)

**Comment by greerga** [comment]
Add to "local _specialQuests":

  [44209] = { zid=1014, daily=true, sid=221602 }, -- Mage: Might of Dalaran
  [44227] = { zid=1014, daily=true, sid=219540 }, -- Warlock: Unleash Infernal
  [44224] = { zid=1014, daily=true, sid=221561 }, -- Demon Hunter: Rift Cannon
  [44222] = { zid=1014, daily=true, sid=221597 }, -- Warrior: Call the Val'kyr
  [44234] = { zid=1014, daily=true, sid=221557 }, -- Death Knight: Summon Frost Wyrm
  [44220] = { zid=1014, daily=true, sid=221587 }, -- Paladin: Vanguard of the Silver Hand

The quest ID that I used above is the "tutorial" quest you get after first researching that wants you to use the ability.

I did get lazy and put the zone as Dalaran (1014) for all of them, where you could argue the order hall zones makes more sense.

**Comment by SacredDuckwhale** [comment]
It appears the addon is still not tracking this, or am I mistaken? I can't see anything in the code, nor does it show ingame.

The easiest way is to simply track the spell's cooldown via GetSpellCooldown() API.

**Comment by SacredDuckwhale** [comment]
Well, seeing how Blizzard removed the ability we might as well close this.
