### ISSUE TITLE
Saving shown gold for name changed character

### ISSUE THREAD

**Issue by Glaini** [SavedInstances/SavedInstances#250]
**Describe the bug**
When seeing the total gold I have across my chars, it keeps showing gold and ressources from a namechanged character, so the same char shows twice under 2 different names

**Do you have an error log of what happened?**

 

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Nope

**Which version of SavedInstances are you using?**
8.1.0

**Was it working in a previous version? If yes, which was the last good one?**
Never fixed

**Additional context**

**Comment by LiangYuxuan** [comment]
Hello, you can delete renamed character in config, which solves your issue.
