### ISSUE TITLE
Keybind no longer working

### ISSUE THREAD

**Issue by Kezwo** [SavedInstances/SavedInstances#255]
Opening the SI windows via keybind is not working anymore. Minimap icon and LDB button are still working fine.

1x [string "SAVEDINSTANCES"]:1: attempt to index global 'SavedInstances' (a nil value)
[string "SAVEDINSTANCES"]:1: in function <[string "SAVEDINSTANCES"]:1>

Locals:
keystate = "down"
pressure = 1
angle = -1
precision = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'SavedInstances' (a nil value)"

**Comment by Stanzilla** [comment]
Fixed, thanks!
