### ISSUE TITLE
Set Backdrop LUA error - please help

### ISSUE THREAD

**Issue by unleeshed** [SavedInstances/SavedInstances#256]
Thank you so much for this amazing mod, really appreciate it!! Makes WoW so much better.
Since the 8.1.5 patch it has been broken. 
Hovering over the mini-map icon you get spammed in text with the error.
Happens on all my characters. Below is the text from my bug grabber. 

Interface\AddOns\SavedInstances\SavedInstances-8.1.0.lua:3188: Usage: <unnamed>:SetBackdrop(nil or {bgFile = "bgFile", edgeFile = "edgeFile", tile = false, tileSize = 0, edgeSize = 32, insets = { left = 0, right = 0, top = 0, bottom = 0 }}) 
[C]: in function `SetBackdrop'
Interface\AddOns\SavedInstances\SavedInstances-8.1.0.lua:3188: in function <Interface\AddOns\SavedInstances\SavedInstances.lua:3184> 
(*temporary) = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 OnRelease = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:4336
 headerFont = SavedInstancedTooltipHeaderFont {
 }
 autoHideTimerFrame = <unnamed> {
 }
 scripts = <table> {
 }
 SetBackdropBorderColor = <function> defined =[C]:-1
 scrollFrame = <unnamed> {
 }
 anchorframe = LibDBIcon10_SavedInstances {
 }
 template = "Transparent"
 scrollChild = <unnamed> {
 }
 colspans = <table> {
 }
 width = 485.707386
 columns = <table> {
 }
 labelProvider = <table> {
 }
 regularFont = GameTooltipText {
 }
 height = 295.357286
 SetBackdropColor = <function> defined =[C]:-1
 pixelBorders = <table> {
 }
 key = "SavedInstancesTooltip"
}

I use ELVUI and AddonSkins. 

I am using the latest version of Saved Instances. 

It doesn't seem to happen when I have all addons off and only Saved Instances on. 

Suggestions for the root of the problem so I can ask for help there?

**Comment by LiangYuxuan** [comment]
Duplicated #248
