### ISSUE TITLE
LUA Gui error

### ISSUE THREAD

**Issue by amzeus1976** [SavedInstances/SavedInstances#258]
**Describe the bug**

view my saves expect no error, got view + error 

**Do you have an error log of what happened?**

**Comment by amzeus1976** [comment]
384x SavedInstances\SavedInstances-8.1.0.lua:3188: Usage: <unnamed>:SetBackdrop(nil or {bgFile = "bgFile", edgeFile = "edgeFile", tile = false, tileSize = 0, edgeSize = 32, insets = { left = 0, right = 0, top = 0, bottom = 0 }})
[C]: in function `SetBackdrop'
SavedInstances\SavedInstances-8.1.0.lua:3188: in function <SavedInstances\SavedInstances.lua:3184>

**Comment by LiangYuxuan** [comment]
Duplicated #248
