### ISSUE TITLE
Reset Time Wrong on EU Realm

### ISSUE THREAD

**Issue by behhNa** [SavedInstances/SavedInstances#259]
Hi,
suddenly the reset time is wrong. Today (Wed, 03. April 2019) was reset day here in EU. The addon tells me that the reset is tomorrow on Thu.

FYI: We changed to DST last Sunday. Maybe that aligns somehow.

**Comment by LiangYuxuan** [comment]
I have this issue on CN Realm either, which was first found in #211 and fixed in 0529d01. But I don't know why it is happening again. Maybe we should allow a day and check if it is still there.

**Comment by LiangYuxuan** [comment]
https://github.com/SavedInstances/SavedInstances/blob/b305a1989b040855ae5d288de8153837f5eee64a/SavedInstances/SavedInstances.lua#L599-L614

Still the problem of `GetServerOffset`, it compares `monthDay` to `weekday` which causes the issue.
