### ISSUE TITLE
Option to add character tooltip data to general tooltip

### ISSUE THREAD

**Issue by flatluigi** [SavedInstances/SavedInstances#261]
This was going to be a request to add Heart of Azeroth level to the tooltip until I found out it had already been added this month -- which I had never discovered despite using the addon constantly.

It would be nice to have an option that breaks out the character tooltip data (or at least current ilvl, money, and azerite level) and displays it in the same at-a-glance way the rest of the data is shown.

**Comment by LiangYuxuan** [comment]
We have discussed this in #209, and we think ilvl, money and azerite level are not like the data such as instance lockouts or others. So, I guess we don't want to do this.
