### ISSUE TITLE
Error Progress

### ISSUE THREAD

**Issue by Lesyde** [SavedInstances/SavedInstances#264]
425x SavedInstances\SavedInstances-8.1.1.lua:1550: Usage: GetModule(name, silent): 'name' - Cannot find module 'Progress'.
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:212: in function `GetModule'
SavedInstances\SavedInstances-8.1.1.lua:1550: in function `UpdateToonData'
SavedInstances\SavedInstances-8.1.1.lua:3171: in function `Refresh'
SavedInstances\SavedInstances-8.1.1.lua:2604: in function <SavedInstances\SavedInstances.lua:2604>
[C]: ?
Ace3\AceBucket-3.0\AceBucket-3.0-4.lua:73: in function <Ace3\AceBucket-3.0\AceBucket-3.0.lua:71>
Ace3\AceBucket-3.0\AceBucket-3.0-4.lua:89: in function `func'
Ace3\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by Stanzilla** [comment]
Did you update the addon while the game was running?

**Comment by Lesyde** [comment]
After a new download the addon works. I update it without running the game.
Thanks.
