### ISSUE TITLE
Errors on load/tooltip/table

### ISSUE THREAD

**Issue by harl** [SavedInstances/SavedInstances#265]
https://gist.github.com/harl/46088017624afc4facbbd907475bb7cf
I get these above errors when either the tooltip (from either the minimap button or the LDB display) or the separate SavedInstances table should be shown on clicking the button/LDB display (only SavedInstancesDetachHeader appears).

As well as another set of errors when SavedInstances is loaded (on login or reload):
https://gist.github.com/harl/429ebe2e191b83e222ec936c65890861

with SavedInstances as the only enabled addon and everything else disabled.

Version: 8.1.1-9-g8a76071
X-ReleaseDate: 2019-04-17T1:53:08Z

It was working in a previous version, but I don't know which was the last good one.

**Comment by Stanzilla** [comment]
Looks like the zip you install is incomplete or you updated without restarting the client?

**Comment by Stanzilla** [comment]
otherwise maybe a load order issue @SavedInstances/maintainers

**Comment by harl** [comment]
Restarting the client fixed those issues for me.
Thanks, Stan.
