### ISSUE TITLE
Critters of Draenor

### ISSUE THREAD

**Issue by Suggesti0ns** [SavedInstances/SavedInstances#266]
The account wide daily quest [Critters of Draenor] from Erris the Collector was not appearing in my tracking (Alliance quest ID 38299). - I am unable to test this for Horde, I see it's a different quest id (38300)
Neither is the account wide weekly quest [Battle Pet Tamers: Warlords] (Quest ID 40329).

I added the following lines to the variable QuestExceptions in Quests.lua and it worked:
`[38299] = "AccountDaily", -- Critters of Draenor`
`[40329] = "AccountWeekly", -- Battle Pet Tamers: Warlords`

**Comment by LiangYuxuan** [comment]
Currently it is tracked as daily and weekly quest. I tested and it appeared. But it is accoutwide, so it will be flagged soon. Thank you!
