### ISSUE TITLE
LUA Error 8.1.2

### ISSUE THREAD

**Issue by Evolutious** [SavedInstances/SavedInstances#268]
Updated to 8.1.2 Release and now get LUA Error:
`7x SavedInstances\SavedInstances-8.1.2.lua:775: attempt to concatenate field iconTexture (a nil value)
SavedInstances\SavedInstances-8.1.2.lua:775: in function <SavedInstances\SavedInstances.lua:766>
SavedInstances\SavedInstances-8.1.2.lua:3825: in function ShowTooltip
SavedInstances\SavedInstances-8.1.2.lua:2582: in function OnEnter
ElvUI\Modules\datatexts\DataTexts.lua:62: in function onEnter
ElvUI\Modules\datatexts\DataTexts.lua:228: in function <ElvUI\Modules\datatexts\DataTexts.lua:226>
[C]: ?
Locals:
current = <table> {
 monthDay = 22
 weekday = 2
 month = 4
 minute = 25
 hour = 14
 year = 2019
}
monthInfo = <table> {
 firstWeekday = 2
 numDays = 30
 year = 2019
 month = 4
}
month = 4
day = 22
year = 2019
showMonth = 4
showYear = 2019
monthOffset = 0
numEvents = 3
(for index) = 3
(for limit) = 3
(for step) = 1
i = 3
event = <table> {
 clubID = 0
 numSequenceDays = 8
 eventID = 666
 eventType = 4294967295
 sequenceType = "ONGOING"
 isCustomTitle = true
 startTime = <table> {
 }
 difficultyName = ""
 endTime = <table> {
 }
 invitedBy = ""
 dontDisplayEnd = true
 difficulty = 0
 inviteStatus = 1
 title = "PvP Brawl: Arathi Blizzard"
 calendarType = "HOLIDAY"
 inviteType = 1
 sequenceIndex = 7
 dontDisplayBanner = true
 modStatus = ""
}
(*temporary) = <function> defined @SavedInstances\SavedInstances.lua:109
(*temporary) = "iconTexture: "
(*temporary) = nil
(*temporary) = 3
(*temporary) = "attempt to concatenate field iconTexture (a nil value)"
debug = <function> defined @SavedInstances\SavedInstances.lua:109
eventInfo = <table> {
 235477 = true
 1129679 = true
}`

If i downgrade to 8.1.1-9 Alpha, everything is fine. LUA error is also in the 8.1.1-13 Alpha.

**Comment by Brimmo89** [comment]
Have the same bug

**Comment by Evolutious** [comment]
Hello friend(s). I wanted to let you know that this issue is NOT fixed in release 8.1.3.

**Comment by Stanzilla** [comment]
Hrm I don't get the error here
