### ISSUE TITLE
Tooltip not showing and causing Error with 8.1.2

### ISSUE THREAD

**Issue by Serafno** [SavedInstances/SavedInstances#271]
Date: 2019-04-23 18:07:03
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\SavedInstances.lua line 775:
   attempt to concatenate field 'iconTexture' (a nil value)
Debug:
   SavedInstances\SavedInstances.lua:775:
      SavedInstances\SavedInstances.lua:766
   SavedInstances\SavedInstances.lua:3825: ShowTooltip()
   SavedInstances\SavedInstances.lua:2582: OnEnter()
   ...ddOns\AtlasLoot\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:77:
      ...ddOns\AtlasLoot\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60
Locals:
current = <table> {
 monthDay = 23
 weekday = 3
 month = 4
 minute = 6
 hour = 18
 year = 2019
}
monthInfo = <table> {
 firstWeekday = 2
 numDays = 30
 year = 2019
 month = 4
}
month = 4
day = 23
year = 2019
showMonth = 4
showYear = 2019
monthOffset = 0
numEvents = 3
(for index) = 2
(for limit) = 3
(for step) = 1
i = 2
event = <table> {
 clubID = 0
 numSequenceDays = 8
 eventID = 673
 eventType = 4294967295
 sequenceType = "ONGOING"
 isCustomTitle = true
 startTime = <table> {
 }
 difficultyName = ""
 endTime = <table> {
 }
 invitedBy = ""
 dontDisplayEnd = true
 difficulty = 0
 inviteStatus = 1
 title = "PvP Brawl: Arathi Blizzard"
 calendarType = "HOLIDAY"
 inviteType = 1
 sequenceIndex = 7
 dontDisplayBanner = true
 modStatus = ""
}
(*temporary) = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:109
(*temporary) = "iconTexture: "
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to concatenate field 'iconTexture' (a nil value)"
debug = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:109
eventInfo = <table> {
 235476 = true
}

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AdiBags, vv1.9.15
  Altoholic, vr190
  AngryKeystones, v
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  autorolecheck, v0.0.2
  AutoTurnIn, v7.0.9
  AzerothAutoPilot, v
  BagBrother, v
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Chatter, v1.5.8-5-g05bf565
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.19
  DBMCountPackOverwatch, v1.4.3
  DBMDefaultSkin, v
  DBMInterrupts, v8.1.0
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVPVEM, v8.1.0
  DejaCharacterStats, v800r103
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  ExRT, v4000
  GatherMate2, v1.43.6
  GroupfinderFlags, v0.10
  IceHUD, v1.11.9
  Informant, v8.1.6246 (SwimmingSeadragon)
  kSellGreyNRepair, v1.4
  LockoutChecker, v0.9
  MethodDungeonTools, v2.5.6
  MythicHelper, v2.1.5
  Oilvl, v8.0.2
  OmniCC, v8.1.1
  OmniCCConfig, v
  Pawn, v2.2.40
  PersonalLootHelper, v2.19
  PremadeGroupsFilter, v1.27
  QEDungeonTips, v4.9.0
  RaidAssist, v
  RaiderIO, v8.1.0 (v201904220600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  RCLootCouncil, v2.10.2
  SavedInstances, v8.1.2
  ShadowedUnitFrames, vv4.2.2
  Simulationcraft, v1.11.1
  Skada, v1.7.5
  SkadaAvoidableDamageTaken, v0.1
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  SubSpec, v2.2.0.1
  TalentSetManager, v
  TidyPlatesThreatPlates, v9.1.7
  TinyTooltip, v8.0.8
  TomTom, vv80105-1.0.0
  VuhDo, v3.100
  VuhDoOptions, v3.100
  WarPlan, v3.08
  WeakAuras, v2.11.6
  WorldQuestsList, v87
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=a49)

**Comment by LiangYuxuan** [comment]
Please update to 8.1.3 which fixed the issue.
