### ISSUE TITLE
LUA Error Issue - #268

### ISSUE THREAD

**Issue by Evolutious** [SavedInstances/SavedInstances#272]
Hello. I saw that my previous issue (#268) was closed but wanted to advise that this issue is NOT fixed in the latest 8.1.2-2 alpha nor in the 8.1.3 release. I continue to have to use 8.1.1-9 alpha to use the addon.

**Comment by LordDeimos666** [comment]
Can confirm this, altho the error is kinda different on my side now:

> 3x SavedInstances\SavedInstances-8.1.2.lua:775: attempt to concatenate field 'iconTexture' (a nil value)
SavedInstances\SavedInstances-8.1.2.lua:775: in function <SavedInstances\SavedInstances.lua:766>
SavedInstances\SavedInstances-8.1.2.lua:3825: in function `ShowTooltip'
SavedInstances\SavedInstances-8.1.2.lua:2582: in function `OnEnter'
ElvUI\Modules\datatexts\DataTexts.lua:62: in function `onEnter'
ElvUI\Modules\datatexts\DataTexts.lua:228: in function <ElvUI\Modules\datatexts\DataTexts.lua:226>
[C]: ?

> Locals:
> InCombatSkipped`

**Comment by LordDeimos666** [comment]
Managed too find the problem, it's completely unrelated to the addon, the stupid twitch desktop crAPP, doesn't work and keep downloading the wrong version, download the latest version 8.1.3 and the problem is solved.

**Comment by AckItsMe** [comment]
The issue for me was fixed just restarting the game.  Apparently it downloaded the 8.1.3 update after I'd logged in as I saw 8.1.2 was in game but a restart is now showing 8.1.3.

**Comment by LiangYuxuan** [comment]
Hi, I can confirm it is fixed in 8.1.3. If you keep getting the lua error, please try to restart the game and reinstall the addon.

**Comment by AckItsMe** [comment]
It was definitely fixed in 8.1.3.  I was just saying that even though Twitch showed I had 8.1.3, in game it showed 8.1.2 until I relogged.

**Comment by Evolutious** [comment]
Confirmed. After doing a manual refresh using this site's download, everything is fine. i have been noticing some odd behavior with Twitch the past day or so; guess this is among those issues of it not properly refreshing to 8.1.3 on the downloadeder.

thanks!
