### ISSUE TITLE
Add gold to main display table

### ISSUE THREAD

**Issue by denvamnts** [SavedInstances/SavedInstances#274]
Can gold, ilvl, and AP be added to the main display table in addition to name mouseover?
Under settings currency, toggle/options to display on the main table.

When alt farming it would be nice to have a table view of this info, customized by me.

**Comment by Stanzilla** [comment]
I vote nay

**Comment by LiangYuxuan** [comment]
Hi, we have discussed this in #209, and we think ilvl, money and azerite level are not like the data such as instance lockouts or others. So, I guess we don't want to do this. Also, I don't think it is useful in alt farming, since Island Weekly is more useful than AP itself.

**Comment by Zarggg** [comment]
I would agree with that decision, from a user's perspective. SavedInstances is for tracking weekly/recurring loot or activities. Currencies like gold or azurite power and other stats are already readily available in the interface or through DataBroker addons.
