### ISSUE TITLE
[Feature Request] Change Motherlode dungeon name from MOTHER to ML

### ISSUE THREAD

**Issue by AndyxWood** [SavedInstances/SavedInstances#275]
Better abbreviation will help make a less wide window for those of us with too many alts :)

**Comment by LiangYuxuan** [comment]
Is it the one from Mythic+ Keystone?

**Comment by AndyPSI** [comment]
Yes that’s correct

**Comment by AndyxWood** [comment]
> Is it the one from Mythic+ Keystone?

I believe so.
