### ISSUE TITLE
Bug-saving

### ISSUE THREAD

**Issue by Addonman** [SavedInstances/SavedInstances#276]
Addon is not saving stuff correctly.I have done battle of darkshore on few char but it is not saving it.Its not even telling me that i am saved on char i am curently on and i have just finished battle few moments ago.

**Comment by Stanzilla** [comment]
Please fill out the issue template, otherwise we can't help you

**Comment by Addonman** [comment]
100% template doesnt have anything that could help you find bug since I use latest version and i dont get any error for this addon.Only thing i am notising that i do   certain content and when i check if i am saved for it in addon its like i havent finished that conntent.Mostly its battle for dazalor since i try to do it on all chars and i noticed it few times my progress for week wasnt saved.

**Comment by LiangYuxuan** [comment]
Filling template always helps. Otherwise we must ask you more questions.

So, which one part are you getting into trouble? Is it the Warfront _Battle of Darkshore_ or the Raid _Battle for Dazar'alor_? Could you upload a screenshot of this issue?

**Comment by Addonman** [comment]
warfront
https://imgur.com/bc8Eixo

I have done Warfront this week on 5 char and it shows only 2

**Comment by Addonman** [comment]
Baiscly it shows most of times on char that i am logged on currently but not on other chars.

**Comment by LiangYuxuan** [comment]
Could you log in the character that completed the scenario and marked uncompleted, and check if it is remain marked uncompleted?

**Comment by Addonman** [comment]
I did yesterday emisary quests on those chars and now it shows correctly that i completed them. If i remember correctly I noticed it before i reported this bug that sometimes addon resets those saves and not shows it correctly afterwords.

**Comment by Addonman** [comment]
I did yesterday emisary quests on those chars and now it shows correctly that i completed them-by them i mean warfronts. If i remember correctly I noticed  before i reported this bug that sometimes addon resets those saves and not shows it correctly afterwords.

**Comment by LiangYuxuan** [comment]
I think I know why.

For the latter one, did it happened before or after 8.1.3 update?

**Comment by Addonman** [comment]
I think it could be after 8.1.3 update since i noticed it like last 2-3 weeks

**Comment by LiangYuxuan** [comment]
might be related to #259, didn't get it recent weeks
