### ISSUE TITLE
Timewalking Weekly Quests --Boss Drops

### ISSUE THREAD

**Issue by rubyrabble** [SavedInstances/SavedInstances#28]
I wondered if I might get some help on how to clear old Timewalking weekly quests from showing in Saved Instances. The quests seem to be stored as completed, well, forever now. Do they need a quest id update or something? I still have BC Timewalking showing in the list even though it's been weeks since the event (same for WotLK TW quests).

(Also, much love to the LFR tracking fixes, much appreciated from me and my 11 alts)

Just for clarification: 
-- Timewalking Dungeon final boss drops
  [40168] = "Weekly", -- The Swirling Vial - Burning Crusade Timewalking
  [40173] = "Weekly", -- The Unstable Prism - Wrath of the Lich King Timewalking
  [40786] = "Weekly", -- The Smoldering Ember - Cataclysm Timewalking - Horde
  [40787] = "Weekly", -- The Smoldering Ember - Cataclysm Timewalking - Alliance
  [45563] = "Weekly", -- The Shrouded Coin - Mists of Pandaria Timewalking

These quests are not resetting. Probably because they aren't technically "weekly". I believe we have 8 days to turn these in because the vendor stays up for a day after TW events are finished. So these quests are showing up in the Weekly completed list and never resetting.

**Comment by Trid3nt1** [comment]
I've been looking into this and the only conclusion I've come to.. Is remove these quests from SavedInstances.

I see no reason for them needing to be tracked, they're not listed as Weekly, Daily etc in game - They're literally just a hand in you can do for a few extra Badges during the event. The only thing it's doing is causing an infinite spam in the "Weekly Quests" section of the tables.

What do you think @Stanzilla - You're the only active boss I've seen around here, hope you don't mind the tag.

**Comment by TruthNZ** [comment]
The weekly quest for just doing timewalking should cover these surely? (Assuming they're working correctly).
I don't see we need a separate tracker for covering the item drop quest. It'll avoid the issue that it's not technically weekly (and I personally have missed the hand in on an rarely played alt, and carried it right through to the next time round and handed it in then).

**Comment by Trid3nt1** [comment]
Exactly, the actual weekly is already covered - Just outlining the fact this is only adding clutter to the SavedInstances table.

**Comment by Stanzilla** [comment]
Agree and changed :)
