### ISSUE TITLE
Only show active warfronts

### ISSUE THREAD

**Issue by Hemario** [SavedInstances/SavedInstances#281]
Add an option to enable/disable only showing active warfront for your faction.

**Comment by LiangYuxuan** [comment]
I think it is hard to tell if a warfront is active or not. it has different quests to complete and the indicator is more like a reminder.

**Comment by TruthNZ** [comment]
This addon seems to be detecting it:
https://wow.curseforge.com/projects/warfront-rare-tracker

So it's possible somehow.

**Comment by LiangYuxuan** [comment]
> This addon seems to be detecting it:
> https://wow.curseforge.com/projects/warfront-rare-tracker
> 
> So it's possible somehow.

yes, actually SI uses the same APIs to check the status in Warfront Module. But I think he means to hide the line when corresponding warfront is contributing or other. I'm not quite sure about what "active" means.

**Comment by Hemario** [comment]
By active I mean, the phase were the warfront is in its "launch attack" stage for the character's faction. 
So yes, I'd like the hide the line if the warfront status is in any other status besides attack. It feels wrong to see "0/1" without the ability to change anything about it because the warfront scenario is not up.

**Comment by LiangYuxuan** [comment]
> By active I mean, the phase were the warfront is in its "launch attack" stage for the character's faction.
> So yes, I'd like the hide the line if the warfront status is in any other status besides attack. It feels wrong to see "0/1" without the ability to change anything about it because the warfront scenario is not up.

Actually, it's blank at that stage, and "0/1" when scenario is ready.

**Comment by Hemario** [comment]
I didn't realize that is the case
