### ISSUE TITLE
Error after resetting WTF directory

### ISSUE THREAD

**Issue by zaldor29** [SavedInstances/SavedInstances#282]
**Describe the bug**
I had a UI issue with Tukui and had to wipe my WTF folder.  Each time I connect to a character for the first time, I receive and error message.  After the error is closed and I log out and back on that character, everything is ok.

**Do you have an error log of what happened?**
Message: Interface\AddOns\SavedInstances\Progress.lua:134: Usage: IsQuestFlaggedCompleted(questID)
Time: Fri May 17 00:09:43 2019
Count: 1
Stack: Interface\AddOns\SavedInstances\Progress.lua:134: Usage: IsQuestFlaggedCompleted(questID)
(tail call): ?
[C]: ?
Interface\AddOns\SavedInstances\Progress.lua:134: in function `QUEST_LOG_UPDATE'
Interface\AddOns\SavedInstances\Progress.lua:118: in function <Interface\AddOns\SavedInstances\Progress.lua:117>
[C]: ?

**To Reproduce**
Delete WTF folder and connect to a character for the first time.

**Which version of SavedInstances are you using?**
8.1.3

**Was it working in a previous version? If yes, which was the last good one?**
unknown

**Additional context**

**Comment by LiangYuxuan** [comment]
fixed in ddfc7c6, please try alpha :)
