### ISSUE TITLE
warfront indicator (0/1) does not change on quest complete

### ISSUE THREAD

**Issue by Hemario** [SavedInstances/SavedInstances#283]
**Describe the bug**
Completing the quest for the warfront scenario does not mark it as complete. The text stays 0/1. A /reload does fix it.

**Do you have an error log of what happened?**
 
N/A

**To Reproduce**
 

**Screenshots**
![image](https://user-images.githubusercontent.com/14911473/58432871-e79ff800-80b4-11e9-91f1-c5fff2a4d45e.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**
8.1.3

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by LiangYuxuan** [comment]
fixed in 3e38d55, please try out alpha :)

or maybe it is time for us to release 🤔
