### ISSUE TITLE
Account level quests tracked as Character level

### ISSUE THREAD

**Issue by dragoforce5** [SavedInstances/SavedInstances#284]
**Describe the bug**
Many (24) pet battle dailies and two weeklies are tracked on a per character basis rather than on an account level causing all characters to be flagged as saved to those quests.
Weekly Quests:
The Celestial Tournament (33137)
Shipwrecked Captive (40310)
Daily Quests:
Grand Master Hyuna (31953)
Grand Master Mo'ruk (31954)
Grand Master Nishi (31955)
Grand Master Yon (31956)
Grand Master Shu (31957)
Grand Master Aki (31958)
Grand Master Zusshi (31991)
Burning Pandaren Spirit (32434)
Flowing Pandaren Spirit (32439)
Whispering Pandaren Spirit (32440)
Thundering Pandaren Spirit (32441)
Beasts of Fable Book I (32604)
Beasts of Fable Book II (32868)
Beasts of Fable Book III (32869)
Little Tommy Newcomer (33222)
Battle Pet Roundup (36483) Alliance / Scrappin' (36662) Horde
Cymre Brightblade (37201)
Ashlei (37203)
Gargra (37205)
Tarr the Terrible (37206)
Vesharr (37207)
Taralune (37208)
Crysa's Flyers (45083)
Bert's Bots (47895)
**Do you have an error log of what happened?**
No 

**To Reproduce**
Complete one of the relevant quests on one character, log onto other characters and recover dailies to see immediately or switch characters again to update list.

**Screenshots**
![WoWScrnShot_060119_200652](https://user-images.githubusercontent.com/51269790/58755397-ec93eb80-84a8-11e9-9262-c03f6779426f.jpg)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no
**Which version of SavedInstances are you using?**
8.1.3
**Was it working in a previous version? If yes, which was the last good one?**
no
**Additional context**
There may be more individual pet trainers that are mistracked, I only checked the ones useful for leveling pets.

**Comment by Suggesti0ns** [comment]
The two DMF pet battles also need to be flagged as "AccountDaily":
[32175] = "AccountDaily", -- DMF Pet Battle - Jeremy Feasel
[36471] = "AccountDaily", -- DMF Pet Battle - Christoph VonFeasel

**Comment by LiangYuxuan** [comment]
SI uses `GetQuestTagInfo` to check if one quest is account quest. But it seems fail to fetch the real tag. Could you complete these quests with Debug Mode on and check the prints?

**Comment by dragoforce5** [comment]
Weekly Quests:
The Celestial Tournament (33137) - GetQuestTagInfo(33137) = 102 Account
	 SavedInstances: Quest Complete: [The Celestial Tournament] 33137 : The Celestial Tournament (Weekly)  Tue Jun 18 09:59:59 2019
Shipwrecked Captive (40310) - GetQuestTagInfo(40310) = 102 Account
	 SavedInstances: Quest Complete: [Shipwrecked Captive] 40310 : Shipwrecked Captive (Weekly)  Tue Jun 18 09:59:59 2019
Pet Battle Challenge: Wailing Caverns (45539) - GetQuestTagInfo(45539) = 102 Account
	 SavedInstances: Quest Complete: [Pet Battle Challenge: Wailing Caverns] 45539 : Pet Battle Challenge: Wailing Caverns (Account) (Weekly)  Tue Jun 18 09:59:59 2019
Daily Quests:
Grand Master Hyuna (31953) - GetQuestTagInfo(31953) = 102 Account
	 SavedInstances: Quest Complete: [Grand Master Hyuna] 31953 : Grand Master Hyuna (Daily)
Grand Master Mo'ruk (31954) - GetQuestTagInfo(31954) = 102 Account
	 SavedInstances: Quest Complete: [Grand Master Mo'ruk] 31954 : Grand Master Mo'ruk (Daily)
Grand Master Nishi (31955) - GetQuestTagInfo(31955) = 102 Account
	 SavedInstances: Quest Complete: [Grand Master Nishi] 31955 : Grand Master Nishi (Daily)
Grand Master Yon (31956) - GetQuestTagInfo(31956) = 102 Account
	 SavedInstances: Quest Complete: [Grand Master Yon] 31956 : Grand Master Yon (Daily)
Grand Master Shu (31957) - GetQuestTagInfo(31957) = 102 Account
	 SavedInstances: Quest Complete: [Grand Master Shu] 31957 : Grand Master Shu (Daily)
Grand Master Aki (31958) - GetQuestTagInfo(31958) = 102 Account
	 SavedInstances: Quest Complete: [Grand Master Aki] 31958 : Grand Master Aki (Daily)
Grand Master Zusshi (31991) - GetQuestTagInfo(31991) = 102 Account
	 SavedInstances: Quest Complete: [Grand Master Zusshi] 31991 : Grand Master Zusshi (Daily)
Darkmoon Pet Battle! (32175) - GetQuestTagInfo(32175) = 102 Account
	Data Missing
Burning Pandaren Spirit (32434) - GetQuestTagInfo(32434) = 102 Account
	 SavedInstances: Quest Complete: [Burning Pandaren Spirit] 32434 : Burning Pandaren Spirit (Daily)
Flowing Pandaren Spirit (32439) - GetQuestTagInfo(32439) = 102 Account
	 SavedInstances: Quest Complete: [Flowing Pandaren Spirit] 32439 : Flowing Pandaren Spirit (Daily)
Whispering Pandaren Spirit (32440) - GetQuestTagInfo(32440) = 102 Account
	 SavedInstances: Quest Complete: [Whispering Pandaren Spirit] 32440 : Whispering Pandaren Spirit (Daily)
Thundering Pandaren Spirit (32441) - GetQuestTagInfo(32441) = 102 Account
	 SavedInstances: Quest Complete: [Thundering Pandaren Spirit] 32441 : Thundering Pandaren Spirit (Daily) 
Beasts of Fable Book I (32604) - GetQuestTagInfo(32604) = 102 Account
	 SavedInstances: Quest Complete: [Beasts of Fable Book I] 32604 : Beasts of Fable Book I (Daily)
Beasts of Fable Book II (32868) - GetQuestTagInfo(32868) = 102 Account
	 SavedInstances: Quest Complete: [Beasts of Fable Book II] 32868 : Beasts of Fable Book II (Daily)
Beasts of Fable Book III (32869) - GetQuestTagInfo(32869) = 102 Account
	 SavedInstances: Quest Complete: [Beasts of Fable Book III] 32869 : Beasts of Fable Book III (Daily)
Little Tommy Newcomer (33222) - GetQuestTagInfo(33222) = 102 Account
	 SavedInstances: Quest Complete: [Little Tommy Newcomer] 33222 : Little Tommy Newcomer (Daily)
A New Darkmoon Challenger! (36471) - GetQuestTagInfo(36471) = 102 Account
	Data Missing
Battle Pet Roundup (36483) Alliance - GetQuestTagInfo(36483) = 102 Account / Scrappin' (36662) Horde - GetQuestTagInfo(36662) = 102 Account
	Data Missing
Mastering the Menagerie (37644) Alliance - GetQuestTagInfo(37644) = 102 Account / Mastering the Menagerie (37645) - GetQuestTagInfo(37645) = 102 Account
	 SavedInstances: Quest Complete: [Mastering the Menagerie] 37644 : Mastering the Menagerie (Account) (Daily)
Cymre Brightblade (37201) - GetQuestTagInfo(37201) = 102 Account
	 SavedInstances: Quest Complete: [Cymre Brightblade] 37201 : Cymre Brightblade (Daily)
Ashlei (37203) - GetQuestTagInfo(37203) = 102 Account
	 SavedInstances: Quest Complete: [Ashlei] 37203 : Ashlei (Daily)
Gargra (37205) - GetQuestTagInfo(37205) = 102 Account
	 SavedInstances: Quest Complete: [Gargra] 37205 : Gargra (Daily)
Tarr the Terrible (37206) - GetQuestTagInfo(37206) = 102 Account
	 SavedInstances: Quest Complete: [Tarr the Terrible] 37206 : Tarr the Terrible (Daily)
Vesharr (37207) - GetQuestTagInfo(37207) = 102 Account
	 SavedInstances: Quest Complete: [Vesharr] 37207 : Vesharr (Daily)
Taralune (37208) - GetQuestTagInfo(37208) = 102 Account
	 SavedInstances: Quest Complete: [Taralune] 37208 : Taralune (Daily)
Crysa's Flyers (45083) - GetQuestTagInfo(45083) = 102 Account
	 SavedInstances: Quest Complete: [Crysa's Flyers] 45083 : Crysa's Flyers (Daily)
Bert's Bots (47895) - GetQuestTagInfo(47895) = 102 Account
	 SavedInstances: Quest Complete: [Bert's Bots] 47895 : Bert's Bots (Daily)

Horde only and Darkmoon quests could not be tested as Darkmoon Faire is not active and I don't have a Horde character. Mastering the Menagerie and Wailing Caverns are included as a control as they are tracked correctly.
/print GetQuestTagInfo was used to check what SavedInstances should be receiving.
Account level quests appear to be individually added to QuestExceptions in Quests.lua ln 96. GetQuestTagInfo does not appear to be used.

**Comment by LiangYuxuan** [comment]
`GetQuestTagInfo` is called when completing quest.

https://github.com/SavedInstances/SavedInstances/blob/ddfc7c656e3d54d168ade4e87eb3281d7a8a1bdb/SavedInstances/SavedInstances.lua#L1758

We can't maintain a huge list of account quest in the addon. Could you try `/dump QUEST_TAG_ACCOUNT` to make sure it is `102` correctly.

**Comment by dragoforce5** [comment]
[20:59:02] Dump: QUEST_TAG_ACCOUNT
[20:59:02] QUEST_TAG_ACCOUNT=nil,
[20:59:02] empty result

**Comment by LiangYuxuan** [comment]
Ha, found it. `QUEST_TAG_ACCOUNT` was removed in BfA, we have `Enum.QuestTag.Account` for now.

Thank you very much!
