### ISSUE TITLE
\SavedInstances\Warfront.lua:86: attempt to index local 'curr' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [SavedInstances/SavedInstances#285]
Logged on to the following lua error

Message: Interface\AddOns\SavedInstances\Warfront.lua:86: attempt to index local 'curr' (a nil value)
Time: Tue Jun  4 05:23:03 2019
Count: 1
Stack: Interface\AddOns\SavedInstances\Warfront.lua:86: attempt to index local 'curr' (a nil value)
Interface\AddOns\SavedInstances\Warfront.lua:86: in function `UpdateQuest'
Interface\AddOns\SavedInstances\Warfront.lua:52: in function <Interface\AddOns\SavedInstances\Warfront.lua:50>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:489: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1194: in function <Interface\FrameXML\UIParent.lua:1090>
[C]: ?

Locals: <none>

**Which version of SavedInstances are you using?**
8.1.3-5-gddfc7c6-alpha

**Comment by LiangYuxuan** [comment]
Did you get this when you log into a character first time? And is it still happens?

**Comment by Thrumbar** [comment]
When I first logged in after install and have not seen it again.
