### ISSUE TITLE
mousover line highlight issue

### ISSUE THREAD

**Issue by Alex-Miller** [SavedInstances/SavedInstances#286]
not all lines are properly highlighted when mousover

![ezgif-5-e69bae3fb1fa](https://user-images.githubusercontent.com/2015294/58974601-6b4f9800-87cb-11e9-8aae-7325eb083b58.gif)

**Comment by LiangYuxuan** [comment]
It is intended to indicate there is a second tooltip of this cell. But I noticed that the gaps between two categories are unintended highlighted. It'll be fixed.

**Comment by LiangYuxuan** [comment]
I found the gap highlighting is due to QTip feature and cannot be closed.
