### ISSUE TITLE
Cannot see in-game events when this addon is active

### ISSUE THREAD

**Issue by Sastron** [SavedInstances/SavedInstances#287]
**Describe the bug**
I want to see player made in-game events in the in-game calendar where I can see members or confirm or decline the event. With the addon enabled I do not see any player made events.

**Do you have an error log of what happened?**
Even with error reporting enabled I do not see an error (`/console scriptErrors 1`).

**To Reproduce**
1. Enable the addon
2. Log in
3. Open the calendar
4. Do not see player made in-game events

**Screenshots**
Normal: https://i.imgur.com/uzF4FRL.png
Bug: https://i.imgur.com/9NuprnD.png

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of SavedInstances are you using?**
I tried two versions:
09/05/19	8.1.3-5-gddfc7c6-alpha	Alpha
23/04/19	8.1.3	Release

**Was it working in a previous version? If yes, which was the last good one?**
I have not found one yet.

**Additional context**
With the addon enabled I can create events and see them after I created them but I do not see the events I have been invited to. After I log out and in again though I do not even see my own event.

**Comment by Sastron** [comment]
After resetting the addon completly I now get this error when I log in with a new character:

Message: Interface\AddOns\SavedInstances\Warfront.lua:86: attempt to index local 'curr' (a nil value)
Time: Thu Jun 13 22:16:01 2019
Count: 1
Stack: Interface\AddOns\SavedInstances\Warfront.lua:86: attempt to index local 'curr' (a nil value)
Interface\AddOns\SavedInstances\Warfront.lua:86: in function `UpdateQuest'
Interface\AddOns\SavedInstances\Warfront.lua:52: in function <Interface\AddOns\SavedInstances\Warfront.lua:50>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
...
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ns\BattlePetCount\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

**Comment by LiangYuxuan** [comment]
Could you try comment out line 2612 of SavedInstance.lua?

Replace
https://github.com/SavedInstances/SavedInstances/blob/ddfc7c656e3d54d168ade4e87eb3281d7a8a1bdb/SavedInstances/SavedInstances.lua#L2612
by
```lua
-- C_Calendar.OpenCalendar() -- Request for event info, not actually open the calendar
``` and see if this issue is still there.

**Comment by LiangYuxuan** [comment]
The latter one is known issue, #285

**Comment by Sastron** [comment]
I commented out line 2612 like you told me to and it works now.

**Comment by LiangYuxuan** [comment]
Thank you!
