### ISSUE TITLE
neck level on the tracker

### ISSUE THREAD

**Issue by mu-taka** [SavedInstances/SavedInstances#290]
**Is your feature request related to a problem? Please describe.**
Would love to be able to see all my toons azerite neck level in the SI window. i feel like this is something that should have been there from day 1

**Describe the solution you'd like**
just add it to the tracker list

**Describe alternatives you've considered**
other addons but i feel like this is relevant to SI and am all about minimizing my number of addons.

**Comment by LiangYuxuan** [comment]
Hi, you can find HoA level by hovering on character name, which was tracked since 3edf0b4.

**Comment by mu-taka** [comment]
Learn something everyday. Thanks for making such a great addon.
