### ISSUE TITLE
Ignore class trial characters

### ISSUE THREAD

**Issue by pquerner** [SavedInstances/SavedInstances#292]
Most class trials cannot do much, ie. not enter any dungeon / raid.
So they must not be shown in the list.

**Comment by Stanzilla** [comment]
Just delete them?

**Comment by pquerner** [comment]
Not sure if I can follow you. Do you mean delete the characters off the WoW servers or from the AddOn ?
If the latter, I did not know you could do that. But, the problem still exists on newely created class trial characters then.

**Comment by Stanzilla** [comment]
Well both, you can ignore as many chars as you want

**Comment by pquerner** [comment]
Can this not be automated? (AddOn checks if logged in character is a non class trial character)
