### ISSUE TITLE
"Terrasse des Magistères" not tracked properly

### ISSUE THREAD

**Issue by MartinBayard** [SavedInstances/SavedInstances#293]
**Describe the bug**
Instance "Terrasse des Magistères" in French Client is not tracked proerly, see screenshot.

**Screenshots**

![image](https://user-images.githubusercontent.com/45717753/60395998-1ee24880-9b3c-11e9-8bfa-942d9e7018af.png)

**Which version of SavedInstances are you using?**

8.2.1

**Additional context**

		["Terrasse des Magistères"] = {
			["LFDID"] = 201,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 70,
		},

---

		["La terrasse des Magistères"] = {
			["LFDID"] = 1154,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 70,
			["Raid"] = false,
		},

**Comment by LiangYuxuan** [comment]
Could you post your Instance Link of it? You can follow these step to get it.
> 1. Click your DifficultyString like "6/9" in SI's tooltip, then it will be a link in your chat input
> 2. Add a pair of quotes and `/dump` to the very head, it will be like `/dump "[Battle of Dazar'alor]"`
> 3. Press Enter and post what you get here

**Comment by MartinBayard** [comment]
![image](https://user-images.githubusercontent.com/45717753/60546001-b3a39c80-9d1c-11e9-9f6c-793acd1ee9bc.png)
