### ISSUE TITLE
8.2.1 cannot record BFA alchemy transmute cooldowns

### ISSUE THREAD

**Issue by hshh** [SavedInstances/SavedInstances#294]
8.2.1 cannot record BFA alchemy transmute cooldowns.
It can record tailoring cooldowns, but alchemy.

**Comment by hshh** [comment]
After enabled debug mode. for xmute
First, Clearing Trade skill cd
Second, Trade skill cd

**Comment by hshh** [comment]
Set all BfA Alchemy spells to new type, different from "xmute".

**Comment by LiangYuxuan** [comment]
Sorry for the delayed reply.

I found two things in recent research, the first is BFA alchemy transmute will let LEG alchemy in cooldown as well, which is not in previous expansion. The second is we didn't update the code for `UNIT_SPELLCAST_SUCCEEDED`, so it's not working now and cannot tell the different between the trade skills which are sharing cooldown. I think fixing the latter one can fix this issue either, but adding new type is not helpful. Different types only control the display name of trade skills.

**Comment by hshh** [comment]
UNIT_SPELLCAST_SUCCEEDED is not fired while open tradeskill windows for scanning.

**Comment by LiangYuxuan** [comment]
it is fired when player casts trade skill, so SI can record the correct one than taking a full scan and getting confused by a list of spells sharing cooldown.

**Comment by hshh** [comment]
Yes, you are right, that's one bug.
It can't fix cooldown scan when open tradeskill window, that's another bug.

**Comment by LiangYuxuan** [comment]
https://github.com/SavedInstances/SavedInstances/blob/7fe257f3cd477487dfc1bc0698c719bf2cb43652/SavedInstances/Tradeskills.lua#L228

I think it is being fired by `TRADE_SKILL_LIST_UPDATE` and triggering functions.

**Comment by hshh** [comment]
It won't record the missing BFA alchemy transmute cooldowns actually.

How to repeat:
1. Cast BFA alchemy transmute, SI recorded. you fixed the bug at commit f594e63.
2. Log out, and wipe SavedVariables\SavedInstances.lua.
3. Log in. Now, no BFA alchemy transmute cooldowns list in SI.
4. Open alchemy skill window, the BFA alchemy transmute cooldowns is still missing in SI.
5. Like the post 2 and 3, new type needed.

**Comment by LiangYuxuan** [comment]
It's because BFA alchemy transmute shares cooldown with LEG's, so SI is confused by them and choose LEG to display.

**Comment by hshh** [comment]
Ok, I found the problem.
I havn't learned LEG Transmute except Transmute: Wild Transmutation.
