### ISSUE TITLE
Hide non-saved max level characters

### ISSUE THREAD

**Issue by willov** [SavedInstances/SavedInstances#302]
All of my max level alts are being tracked, even with the "show when saved" toggled, despite not being saved for anything. Some of the alts haven't even been signed in for a couple of weeks. 
Would be greate to actually only be able to only track the characters that are currently being played.

**Comment by LiangYuxuan** [comment]
Seems like tracking emissary will try to display all character that "show when saved" and unlocked world quest.

Currently we have module that will marks character "saved" when them have something to display: Trade Skill, Mythic Key, Emissary, Paragon Chest, Bonus Roll. I think we can reduce the list and remove Emissary and Bonus Roll on the list.
