### ISSUE TITLE
Track Laboratory of Mardivas access / completion

### ISSUE THREAD

**Issue by Sipollo** [SavedInstances/SavedInstances#303]
Could support for the weekly Laboratory of Mardivas be added please?

If quest id 57086 has been completed then a character will have access to the weekly quest.

The weekly quest id is 55121; if that has been completed then the character has done it for the week.

It would be nice to have an icon which shows that a character still needs to get access to the lab or not as well!

**Comment by LiangYuxuan** [comment]
I think showing if character has unlocked is not necessary, but I'd like to track this weekly quest without checking unlocked.
