### ISSUE TITLE
Nazjatar Pvp weekly, daily battle and daily crate tracking.

### ISSUE THREAD

**Issue by DeeRez** [SavedInstances/SavedInstances#306]
Can the Nazjatar PVP weekly, Daily battle win and daily crate (the one with conquest as a reward) be added to the tracked weekly/dailies?

**Comment by LiangYuxuan** [comment]
Hi, I don't play PvP in BfA and I found a quest (https://www.wowhead.com/quest=56648/call-to-arms-nazjatar) in Nazjatar. Is this the PvP Weekly? And are there quests to track daliy battle win and crate?

**Comment by DeeRez** [comment]
That's the call to arms event. The PvP weekly is https://www.wowhead.com/quest=56050/pvp-event-battle-for-nazjatar. I'm still looking for the tracking for the crates and daily wins.

**Comment by LiangYuxuan** [comment]
Thank you! If you find it hard to find the quest id of the crates and daily wins, try [QuestsChanged](https://www.curseforge.com/wow/addons/questschanged) :)

**Comment by DeeRez** [comment]
Thanks for that Addon. I warn you, you may have created a monster.

**Comment by DeeRez** [comment]
Daily Crate Tracking:

Drustvar Supply Drop 55408
Nazmir Supply Drop 55409
Stormsong Valley Supply Drop 55410
Tirisgarde Supply Drop 55411
Vol'Dun Supply Drop 55412
Zuldazar Supply Drop 55413
Nazjatar Supply Drop 56792

**Comment by LiangYuxuan** [comment]
Oh, thank you! Also it that "daliy battle win" is Ranked Battleground daliy first win, which is likely to be tracked by https://www.wowhead.com/quest=45434/first-win-of-the-day-10v10 ?

**Comment by DeeRez** [comment]
Nah. it's the Nazjatar zone specific PVP battle. I also found out that there is a daily Nazjatar PVP loss as well, but have been unable to work out which either is as there's like four quests that trigger at the win.

**Comment by DeeRez** [comment]
OK, so after much experimentation and process of elimination the 50 conquest daily appears to be QuestID 53640. This is shared by normal air drop crates and secret supply crates, so no need to track individual zone chest IDs unless people actually want to.

Nazjatar only has one zone so that can be tracked just by the crate ID.

**Comment by linlinglin** [comment]
thx. i'll searching the questid for the chest in  Nazjatar. 
because it may not be looted by  me!!

**Comment by DeeRez** [comment]
> Nazjatar only has one zone so that can be tracked just by the crate ID.

Just found out that this is the quest for eligibility for item rewards from the chest and resets multiple times daily.

The 75 conquest quest is QuestID: 57111.

**Comment by linlinglin** [comment]
wonderful job! thanks!!

**Comment by LiangYuxuan** [comment]
I think it's no longer gives Conquest :( Sorry for delaying this so much.
