### ISSUE TITLE
pin specific quests

### ISSUE THREAD

**Issue by Beornwulf** [SavedInstances/SavedInstances#310]
**Is your feature request related to a problem? Please describe.**
Keeping track of which characters I've done the weekly quest/brawl/etc is currently annoying. similarly world event quests like the brewfest stuff.

**Describe the solution you'd like**
I'd like to be able to pin specific quests, weekly or otherwise, to show as their own item in the list, presumably which would vanish when no longer available for time-limited ones like brawls.

**Describe alternatives you've considered**
I'm aware you can see weeklies by hovering on the weekly quest row, but that's faffy to compare multiple characters with.

**Comment by LiangYuxuan** [comment]
Progress Module was introduced to do the job like this. What quest or progress you want to track?

**Comment by Beornwulf** [comment]
the "weekend event" quest such as the 5 timewalking dungeons, the first brawl win of the week, that sort of thing. I'm not aware of the progress module, it's possible i'm missing a thing

**Comment by LiangYuxuan** [comment]
We have to manually add quest into the Progress Module. It tracks PvP Conquest Weekly and Island Expedition Weekly for now, and I'm happy to add Weekend Event to it and for the PvP Brawl, maybe allowing user to add single quest is better.
