### ISSUE TITLE
Feature req: Track daily/weekly kills on world rares that drop mounts

### ISSUE THREAD

**Issue by rodalpho** [SavedInstances/SavedInstances#312]
I would like to track which of my characters have killed Soundless, Arachnoid Harvester, and Rustfeather on the current day. These are tracked via hidden quests 55512, 55811, and 56298.

Perhaps a better solution would be the ability to add custom trackers for hidden quests via quest ID, as Blizzard will likely be continuing this mechanic in the future?

**Comment by Stanzilla** [comment]
Use a rare tracker for those instead, please

**Comment by rodalpho** [comment]
I do that, but these lack the cross-character tracking from SavedInstances. 

Anyway thanks for considering it.
