### ISSUE TITLE
Classic support

### ISSUE THREAD

**Issue by Mnuzz** [SavedInstances/SavedInstances#313]
Any word on whether this will be supported for classic? I had a friend ask me if I'd make an addon for classic, that tracks instance lockouts. I found this addon that already does just that, but only for retail.

**Comment by LiangYuxuan** [comment]
I would like a no. There are so many features that don't exists in classic, but if you want to make it work in classic, feel free to try it and pr.

**Comment by Mnuzz** [comment]
I'd be happy to give it a go, but I've been unable to find anyone who can tell me where the official Lua documentation is located at.

**Comment by LiangYuxuan** [comment]
https://www.lua.org/ is official but no infomation from wow. I suggest resources channel in WeakAuras Discord (https://discord.gg/wa2)

And closing this :)
