### ISSUE TITLE
failed to find instance Caverns of Time - Anniversary : enUS : 22235 

### ISSUE THREAD

**Issue by BigFire321** [SavedInstances/SavedInstances#314]
**Describe the bug**

The 15th anniversary event instance isn't found.

**Do you have an error log of what happened?**
 
198x AdventureGuideLockouts\Core.lua:202: table index is nil
AdventureGuideLockouts\Core.lua:202: in function `UpdateSavedInstances'
AdventureGuideLockouts\Core.lua:385: in function <AdventureGuideLockouts\Core.lua:377>

Locals:
self = <table> {
 worldBosses = <table> {
 }
 UpdateStatusFramePosition = <function> defined @AdventureGuideLockouts\Core.lua:285
 UpdateSavedInstances = <function> defined @AdventureGuideLockouts\Core.lua:131
 isDarkshoreAvailable = false
 isStromgardeAvailable = true
 instances = <table> {
 }
 GetSavedWorldBossEncounterInfo = <function> defined @AdventureGuideLockouts\Core.lua:119
 instancesLockouts = <table> {
 }
 UpdateInstanceStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:328
 RequestWarfrontInfo = <function> defined @AdventureGuideLockouts\Core.lua:50
 CreateStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:220
 GetSavedWorldBossInfo = <function> defined @AdventureGuideLockouts\Core.lua:89
 eventFrame = <unnamed> {
 }
 UpdateFrames = <function> defined @AdventureGuideLockouts\Core.lua:360
}
savedInstances = 3
savedWorldBosses = 5
instanceName = "Freehold"
instanceID = nil
instanceReset = 175039
instanceDifficulty = 23
locked = true
extended = false
instanceIDMostSig = 524419072
isRaid = false
maxPlayers = 5
difficultyName = "Mythic"
numEncounters = 0
numCompleted = 0
difficulty = 4
playerFaction = "Alliance"
(for index) = 1
(for limit) = 8
(for step) = 1
instanceIndex = 1
encounters = <table> {
}
encounterIndex = 1
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = true
(*temporary) = false
(*temporary) = false
(*temporary) = true
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
GetNumSavedInstances = <function> defined =[C]:-1
UnitFactionGroup = <function> defined =[C]:-1
GetSavedInstanceInfo = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
GetSavedInstanceChatLink = <function> defined =[C]:-1
GetDifficultyInfo = <function> defined =[C]:-1
GetSavedInstanceEncounterInfo = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
C_TaskQuest_GetQuestTimeLeftMinutes = <function> defined =[C]:-1

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by LiangYuxuan** [comment]
that error is not for us :(
