### ISSUE TITLE
SavedInstances: ERROR: Refresh() failed to find instance: Caverns of Tim - Anniversary : enUS : 2235

### ISSUE THREAD

**Issue by popje** [SavedInstances/SavedInstances#315]
title: SavedInstances: ERROR: Refresh() failed to find instance: Caverns of Tim - Anniversary : enUS : 2235 is the error I got followed by a message to report this here

Thanks for doing that btw, love that addon.

**Comment by LiangYuxuan** [comment]
The `instanceID` 2235 (Caverns of Time - Anniversary) is related to three `dungeonID` including 2004 (Memories of Azeroth: Burning Crusade), 2017 (Memories of Azeroth: Wrath of the Lich King) and 2018 (Memories of Azeroth: Cataclysm). None of them have names matched, leads to the bug.

I've done some workaround to this, but require some time to test before release it. Thank you for reporting this.
