### ISSUE TITLE
Donate link on curseforge doesn't work

### ISSUE THREAD

**Issue by popje** [SavedInstances/SavedInstances#317]
**Describe the bug**
It should redirect to your paypal or something

**Do you have an error log of what happened?**
Error Detected

PayPal cannot process this transaction because of a problem with the seller's website. Please contact the seller directly to resolve this problem.

**To Reproduce**
1. go on https://www.curseforge.com/wow/addons/saved_instances
2. click the donate button

**Comment by Stanzilla** [comment]
That's something for @jokeyrhyme

**Comment by jokeyrhyme** [comment]
Hmmm, I can confirm the error

I'm getting lots of "invalid csrf token" when I try to log in though :S

Oh, okay, CurseForge seems to not like Firefox now...

Okay, so, "Project Donation Type" is "Paypal hosted", and it looks like the Button ID refers to an account owned by @Stanzilla (the email address for the Paypal account is a Gmail account theoretically in your name, and with the same icon/photo as your GitHub account)

This looks fine to me, so maybe there is an issue with your Paypal account in terms of receiving donations? I've never used this feature before, do you know if other donations are working?

**Comment by Stanzilla** [comment]
Hrm weird, it works on my other addons pages, I'll ask around with CurseForge.

**Comment by Stanzilla** [comment]
Fixed, thanks!
