### ISSUE TITLE
Mechanized Chest weekly 

### ISSUE THREAD

**Issue by kylerichey** [SavedInstances/SavedInstances#321]
The first time you loot a Mechanized Chest in Mechagon, you are guaranteed to receive a Azeroth Mini Pack: Mechagon  along with some other loot. This is a weekly quest and is tracked by either quest id 57081 or 57133. I couldn't confirm which one it was specifically because they both complete the first time you loot a mechanized chest each week.  I was wondering if you could add in tracking for this, as it would be very helpful for knowing which characters haven't gotten their Mini pack from the mechanized chest yet this week.

**Comment by Stanzilla** [comment]
Why is this relevant? because of the 100g it gives?

**Comment by kylerichey** [comment]
The 100g is the consolation prize from not getting the rare Azeroth Mini: King Mechagon from the pack. Its less than a one percent drop, so I think getting a pack on every alt each week would be the most straightforward way to farm for the item.

**Comment by LiangYuxuan** [comment]
These quests are weekly? I thought they're daily.
I've tried these and comfirmed on two character, but this is the first time they went to Mechagon. Will try tomorrow and check it.

**Comment by kylerichey** [comment]
Looting the chests is a daily, but the first time you loot a chest each week, it has 100% chance to drop the Azeroth Mini Pack. The first time you loot a chest each week, 3 quests will complete. One of them is the specific quest to the specific chest you just looted. The other two (57081 and 57133) are related to the weekly quest that you only get from the first chest of the week. From what I could tell by testing on several characters, both of these quests always complete on the first chest loot of the week. So I think you can track either of them and that will be enough for confirming if the weekly is complete.
