### ISSUE TITLE
Saved Instances quit working today this is the error

### ISSUE THREAD

**Issue by Kazmyer** [SavedInstances/SavedInstances#325]
Date: 2019-11-26 17:12:55
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\Progress.lua line 246:
   attempt to concatenate field 'numRequired' (a nil value)
Debug:
   SavedInstances\Progress.lua:246: ShowTooltip()
   SavedInstances\SavedInstances.lua:3898: ShowTooltip()
   SavedInstances\SavedInstances.lua:2603: OnEnter()
   ...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:77:
      ...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60
   [C]: ?
   [C]: ?
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ShowTooltip = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:216
 defaultModuleLibraries = <table> {
 }
 BuildOptions = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:204
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "SavedInstances_Core_Progress"
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 OnWeeklyReset = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:183
 SetDefaultModuleState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 SetEnabledState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 OnDailyReset = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:162
 enabledState = true
 baseName = "SavedInstances"
 RegisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 QUEST_LOG_UPDATE = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:130
 OnEnable = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:125
 NewModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 IterateModules = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 defaultModuleState = true
 SendMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 GetName = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 moduleName = "Progress"
 UnregisterEvent = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
tooltip = <unnamed> {
 0 = <userdata>
 regularFont = GameTooltipText {
 }
 columns = <table> {
 }
 scrollChild = <unnamed> {
 }
 colspans = <table> {
 }
 anchorframe = LibDBIcon10_SavedInstances {
 }
 width = 297.007095
 headerFont = SavedInstancedTooltipHeaderFont {
 }
 key = "SavedInstancesTooltip"
 scripts = <table> {
 }
 height = 67.670605
 labelProvider = <table> {
 }
 lines = <table> {
 }
 scrollFrame = <unnamed> {
 }
}
columns = <table> {
 Littleribbon - Proudmoore2 = 15
 Littleoff - Proudmoore2 = 27
 Littlelite - Proudmoore4 = 21
 Littlecross - Proudmoore3 = 32
 Littlecross - Proudmoore4 = 33
 Littlelust - Proudmoore1 = 22
 Littlelite - Proudmoore3 = 20
 Littleribbon - Proudmoore4 = 17
 Littlecruel - Proudmoore4 = 5
 Littlecruel - Proudmoore2 = 3
 Littlemean - Proudmoore4 = 9
 Littlecross - Proudmoore1 = 30
 Littlelust - Proudmoore4 = 25
 Littlelite - Proudmoore2 = 19
 Littleribbon - Proudmoore3 = 16
 Littlemean - Proudmoore1 = 6

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.3
  Altoholic, vr191
  AstralKeys, v3.20
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AzeritePowerWeights, v8.2.16
  AzeriteTooltip, v2.0.6
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BFAInvasionTimer, vv8.2.5
  BrokerGarrison, v2.0.8.1
  CanIMogIt, v8.2.5v1.20
  ComboPointsRedux, v5.0.2
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.29
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  Details, v
  Diminish, vv2.2.4
  DiminishOptions, v
  ElvUI, v11.25
  ElvUIExtraActionBars, v2.37
  ElvUISLE, v3.60
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnergyWatch, v
  ExRT, v4110
  GatherMate2, v1.45.5
  GG, v1.0
  GladiatorlosSA2, v2.1.1
  Gladius, v6.1.0
  GTFO, v4.51
  HandyNotes, vv1.5.9
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.31
  HandyNotesCamelFigurines, v1.3
  HandyNotesDraenorTreasures, v1.21
  HandyNotesHallowsEnd, vv1.5
  HandyNotesLegionInstanceWorldQuests, vv1.18
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLostAndFound, v1
  HandyNotesMoleMachine, v1.1.6
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSuramarShalAranTelemancy, vv1.21
  HandyNotesTimelessIsleChests, v1.21
  HandyNotesTimelessTreasures, v1.1.0
  HandyNotesToolsOfTheTrade, v5.0.0
  HandyNotesTreasureHunter, v1
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWorldMapButton, v80205.01-Release
  HeroCache, v8.2.5.01
  HeroLib, v8.2.5.01
  HeroRotation, v8.2.5.01
  HeroRotationRogue, v
  HHTD, v2.4.9.4
  HiddenSkinTracker, v1.04
  idTip, v8.2.1
  Informant, v8.2.6508 (SwimmingSeadragon)
  LibNameplateRegistry10, v0.19T4
  MasterPlanA, vA
  MethodDungeonTools, v2.9.5
  MogIt, v3.9.0
  MogItArtifact, v3.9.0
  MogItLeather, v3.9.0
  MogItOneHanded, v3.9.0
  MogItOther, v3.9.0
  MogItRanged, v3.9.0
  MogItTwoHanded, v3.9.0
  Omen, v3.2.2
  OmniCC, v8.3.1
  oRA3, vv8.2.5
  Pawn, v2.3.11
  Postal, vv3.6.0
  Prat30Libraries, v
  Quartz, v3.5.2
  RaiderIO, v8.1.0 (v201911260600)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  Rarity, v1.0 (r692-release)
  RarityOptions, v
  SalvageCrates, v2.0
  SavedInstances, v8.2.5
  SellJunk, v3.0.20
  Simulationcraft, v1.12.3
  Skillet, v4.10
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TellMeWhen, v8.7.2
  TomCats, v1.3.6
  TomCatsMechagon, v1.3.10
  TomCatsNazjatar, v1.3.10
  WeakAuras, v2.15.5
  WorldQuestTracker, v
  WoWGatheringNodes, vBFA-8.2.5-update-v1.0
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=c9b)

**Comment by Ghli** [comment]
I've had the same issue. It's directly related to tracking the quest progression for Island Expeditions. As for why it's doing that, I have no idea, but turning off the tracking for it shows the tooltip again.

**Comment by dblanch369** [comment]
Yeah I'm getting this too.  I had to roll back to 8.2.4, and then had to roll back to my backup of the save data (corruption of data happens?).  I did not try disabling the islands tracking, but will test it tomorrow when I have time.

**Comment by LiangYuxuan** [comment]
Hi, could you upload your SavedInstances.lua in WTF? I want to check out what's going wrong with `.numRequired`, since it shouldn't be nil.

**Comment by Ghli** [comment]
This is my savedinstances.lua
[SavedInstances.zip](https://github.com/SavedInstances/SavedInstances/files/3895243/SavedInstances.zip)

**Comment by LiangYuxuan** [comment]
I find every `.numRequired` is not nil, have no idea why.
