### ISSUE TITLE
SavedInstances not working since last reset 19-11-27

### ISSUE THREAD

**Issue by Wolle96** [SavedInstances/SavedInstances#327]
**Describe the bug**
<When hovering over the SavedInstances Plugin in my Titanpanel usually a popup for my instances for the week appears, now, as soon as I hover over it my Swatter! gives me the following error report.

Date: 2019-11-28 13:18:17
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\Progress.lua line 246:
   attempt to concatenate field 'numRequired' (a nil value)
Debug:
   SavedInstances\Progress.lua:246: ShowTooltip()
   SavedInstances\SavedInstances.lua:3898: ShowTooltip()
   SavedInstances\SavedInstances.lua:2603:
      SavedInstances\SavedInstances.lua:2601
   Titan\LDBToTitan.lua:327:
      Titan\LDBToTitan.lua:286
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @Interface\AddOns\Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ShowTooltip = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:216
 defaultModuleLibraries = <table> {
 }
 BuildOptions = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:204
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "SavedInstances_Core_Progress"
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @Interface\AddOns\Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 OnWeeklyReset = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:183
 SetDefaultModuleState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 SetEnabledState = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 OnDailyReset = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:162
 enabledState = true
 baseName = "SavedInstances"
 RegisterEvent = <function> defined @Interface\AddOns\Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 QUEST_LOG_UPDATE = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:130
 OnEnable = <function> defined @Interface\AddOns\SavedInstances\Progress.lua:125
 NewModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 IterateModules = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 defaultModuleState = true
 SendMessage = <function> defined @Interface\AddOns\Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 GetName = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 moduleName = "Progress"
 UnregisterEvent = <function> defined @Interface\AddOns\Ahoy\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
tooltip = <unnamed> {
 0 = <userdata>
 regularFont = GameTooltipText {
 }
 columns = <table> {
 }
 scrollChild = <unnamed> {
 }
 colspans = <table> {
 }
 anchorframe = TitanPanelSavedInstancesButton {
 }
 width = 142.015511
 headerFont = SavedInstancedTooltipHeaderFont {
 }
 key = "SavedInstancesTooltip"
 scripts = <table> {
 }
 height = 151.016471
 labelProvider = <table> {
 }
 lines = <table> {
 }
 scrollFrame = <unnamed> {
 }
}
columns = <table> {
 Beelzul - Argent Dawn3 = 4
 Beelzul - Argent Dawn4 = 5
 Beelzul - Argent Dawn2 = 3
 Beelzul - Argent Dawn1 = 2
}
showall = false
preshow = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3898
cpairs = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:3242
first = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
(for control) = 2
index = 2
tbl = <table> {
 weekly = true
 resetFunc = <fu
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  AAPCore, v8.1058
  Ahoy, v1.10
  AllTheThings, v1.9.9c
  Altoholic, vr191
  Auctionator, v8.2.0
  AzerothAutoPilot, v
  BagBrother, v
  Bartender4, v4.8.8
  BattlePetBreedID, vr203
  CamelSpotter, v1.4.9
  Chatter, v1.6.0
  CrossRP, v2.1.3
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.29
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v820r202
  Details, v
  DetailsChartViewer, v
  DetailsDeathGraphs, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidPowerBars, v
  DetailsStreamer, v
  DetailsTimeLine, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  GarrisonCommanderBroker, v3.2.3 1.1.0
  HandyNotes, vv1.5.9
  HandyNotesDraenorTreasures, v1.21
  HandyNotesHallowsEnd, vv1.5
  HandyNotesToolsOfTheTrade, v5.0.0
  IceHUD, v1.12.5
  Inventorian, v8.2.5.0
  Listener, v2.1.7
  MBB, v4.0
  MogIt, v3.9.0
  MogItArtifact, v3.9.0
  MogItOneHanded, v3.9.0
  MogItOther, v3.9.0
  MogItPlate, v3.9.0
  MogItRanged, v3.9.0
  MogItTwoHanded, v3.9.0
  mOnArsWardrobeHelper, v1.18.3
  Paste, v1.4.10
  Pawn, v2.3.11
  Quartz, v3.5.2
  Rarity, v1.0 (r692-release)
  RarityOptions, v
  SavedInstances, v8.2.5
  SellJunk, v3.0.20
  SexyMap, vv8.2.2
  SilverDragon, vv4.0.17
  SilverDragonBattleForAzeroth, vv4.0.17
  SilverDragonBurningCrusade, vv4.0.17
  SilverDragonCataclysm, vv4.0.17
  SilverDragonLegion, vv4.0.17
  SilverDragonMists, vv4.0.17
  SilverDragonVanilla, vv4.0.17
  SilverDragonWarlords, vv4.0.17
  SilverDragonWrath, vv4.0.17
  SlideBar, v7.3.1 (<%codename%>)
  Titan, v5.18.4.80205
  TitanBag, v5.18.4.80205
  TitanClock, v5.18.4.80205
  TitanGold, v5.18.4.80205
  TitanLocation, v5.18.4.80205
  TitanLootType, v5.18.4.80205
  TitanPerformance, v5.18.4.80205
  TitanRepair, v5.18.4.80205
  TitanVolume, v5.18.4.80205
  TitanXP, v5.18.4.80205
  TomCats, v1.3.6
  TomCatsMechagon, v1.3.10
  TomCatsNazjatar, v1.3.10
  TomTom, vv80205-1.0.8
  totalRP3, v1.6.7.1
  totalRP3Data, v
  totalRP3Extended, v1.3.3
  totalRP3ExtendedImpExport, v1.3.3
  totalRP3ExtendedTools, v1.3.3
  TransmogTokens, v1.4.9
  UnlimitedChatMessage, v1.9.14
  WarfrontRareTracker, v1.0.8-1
  WorldQuestTracker, v
  ZPerl, v5.8.7
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=b28)

The same happens when I try to click the map button of SavedInstances.

Even after disabling all other addons the same problem occurs. 

**Which version of SavedInstances are you using?**
<The latest version available on Curseforged (Twitch addon handler)

**Comment by Stanzilla** [comment]
Just pushed a new version that should fix this
