### ISSUE TITLE
Coalescing Visions & Corrupted Mementos not available

### ISSUE THREAD

**Issue by nimble-123** [SavedInstances/SavedInstances#335]
**Describe the bug**

I exptected to be able to display the new 8.3 currencies, but did not found them in the currencies tab.

**To Reproduce**
1. Go to Addon Settings
2. Click on Currency Tab
3. Search for new 8.3 currencies

**Screenshots**
http://prntscr.com/qohbp2

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of SavedInstances are you using?**
8.2.7

**Comment by LiangYuxuan** [comment]
Hi, new currencies have been added into SI already, but Curse's webhook seems like failed to fetch new version, so even no alpha is out :(. I'm sorry for that. Maybe a release can fix this. @Stanzilla

**Comment by Stanzilla** [comment]
Just pushed a tag, let's pray to the Curse Gods \o/

**Comment by LiangYuxuan** [comment]
New release on Curse \0^0/
