### ISSUE TITLE
DC after portaling / entering instances

### ISSUE THREAD

**Issue by llwynog** [SavedInstances/SavedInstances#336]
**Describe the bug**
Frequent DC after using portal, usually to well populated area (SW, Boralus) or entering dungeons or raids

**To Reproduce**
Go through any portal to well-populated area several times: SW, Boralus, Silithus, Chamber of Heart or enter dungeons or raids.

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, it doesn't cause DC if only SavedInstances is enabled.

**Which version of SavedInstances are you using?**
8.3.0

**Additional context**
Addons I'm using:
- AngryKeystones
- Bagnon
- BigWigs
- DejaCharacterStats
- Details!
- GathetMate2
- Healbot
- KeystoneManager
- Leatrix Plus
- LittleWigs
- MSBT (Mik's Scrolling Battle Text)
- MoveAnything
- Quartz
- Raider.IO
- RSA
- SexyMap
- ThreadPlates
- Titan Panel
- TomCat's Tours
- Weakauras 2
- Z-Perl

**Comment by LiangYuxuan** [comment]
I don't think it is SI or any addons' issue :(
