### ISSUE TITLE
Track Vision of N'Zoth daily quest apart from normal daily tracking

### ISSUE THREAD

**Issue by bryanzak** [SavedInstances/SavedInstances#338]
This quest is important enough that I don't want to forget to do it on any of my alts and since I don't run all the dailies on all my alts, it's easy to lose track of which alt still needs to do the daily vision.

**Comment by LiangYuxuan** [comment]
Currently these quests are tracked in daily quests.

**Comment by speedwaystar** [comment]
they are not tracked in daily quests. in fact, i can't see any daily quests in this display, which shows all data.

![](https://i.imgur.com/lIrX2Hj.png)

**Comment by LiangYuxuan** [comment]
Weird, I have they tracked in Daily Quest on my end, since they're daily quest marked by blizzard. I'll working on it.

**Comment by richardfein** [comment]
👍 would love to have these tracked as their own line item, or at least with a common name such as 
"lesser vision", rather than having to remember the specific quest name.
