### ISSUE TITLE
Mini vision taracker add

### ISSUE THREAD

**Issue by zkekahs2** [SavedInstances/SavedInstances#339]
Mini-Vision tracker  

please ...

**Comment by Stanzilla** [comment]
Care to explain what exactly you want there?

**Comment by zkekahs2** [comment]
> Care to explain what exactly you want there?

Daily Mini-Vision Quest...

https://www.wowhead.com/guides/lesser-mini-visions-of-nzoth-corrupted-uldum-vale

**Comment by LiangYuxuan** [comment]
Currently mini vision's daily quests are tracked in Daily Quest. If you want it apart, see also #338 .
