### ISSUE TITLE
savedinstances covers entire screen

### ISSUE THREAD

**Issue by rosedy20** [SavedInstances/SavedInstances#340]
The addon covers my entire screen, An no way to click on it to change size. I need a way to open the setting manually. I have uninstalled it and re installed it removed it from my folder in game and still does the same thing. just need to resize it a bit. however when you put your cursor over button it will not all you to right or left click to open settings.

![2020-01-21 (2)](https://user-images.githubusercontent.com/60154367/72855049-15046c00-3c6b-11ea-99ee-367ff01ee0bc.png)

**Comment by LiangYuxuan** [comment]
Could you show your config in SavedInstances' General? I think there're something related to scale.
