### ISSUE TITLE
SI covers entire screen ( scale )

### ISSUE THREAD

**Issue by rosedy20** [SavedInstances/SavedInstances#341]
The addon covers my entire screen, An no way to click on it to change size. I need a way to open the settings manually. I have uninstalled it and re installed it removed it from my folder in game and still does the same thing. just need to resize it a bit. however when you put your cursor over button it will not allow you to right or left click to open settings. What is Code to open without clicking button.?
![2020-01-21 (2)](https://user-images.githubusercontent.com/60154367/72864797-3294fe00-3c8a-11ea-88cf-3a8f6721e302.png)

**Comment by LiangYuxuan** [comment]
You can press ESC and then Interface>Addons>SavedInstances>General. Or `/si config` can help you.
