### ISSUE TITLE
Uldum and Vale of Eternal Blossoms weekly assaults

### ISSUE THREAD

**Issue by speedwaystar** [SavedInstances/SavedInstances#342]
Track whether alts have completed the main weekly N'Zoth assault in either the Vale or Uldum. Also, track whether they have completed the twice-weekly minor assaults in the zone which is not currently under main assault.

**Comment by justinkb** [comment]
Some code I quickly made in game. Seems to be impossible to query which threats are the weekly threats on a character that has already completed them. So the addon should probably invert the logic (only show what is 'missing'), i.e. if C_TaskQuest.IsActive() returns true

```
threats = C_TaskQuest.GetThreatQuests()
for index, data in ipairs(threats) do
   print(data)
   print(C_TaskQuest.IsActive(data))
   print(IsQuestFlaggedCompleted(data))
end
```
