### ISSUE TITLE
Show Legendary Cloak upgrade level on alts

### ISSUE THREAD

**Issue by speedwaystar** [SavedInstances/SavedInstances#344]
title

**Comment by Stanzilla** [comment]
out of scope

**Comment by LiangYuxuan** [comment]
I like this since Legendary Cloak Level is like APs which're tracked currently.

**Comment by igorrebolj** [comment]
Hey, any progress on this?

**Comment by LiangYuxuan** [comment]
I want to hold this issue until next reset, to find out if tracking Corruption Resistance is possible.

**Comment by igorrebolj** [comment]
Should be possible, this weak aura is doing it (do not know if this can be of any use to you)

https://wago.io/rRenhVWuP

**Comment by igorrebolj** [comment]
`function()
    local corruptionLevel = GetCorruption() - GetCorruptionResistance()
    if corruptionLevel < 0 then
        corruptionLevel = 0 
    end
    
    
    local output = ""
    if aura_env.eqcorruptionids then
        
        for _,corr in pairs(aura_env.eqcorruptionids) do
            output  = output .. "\n".. corr
        end
        
        
    end
    local header = ""
    if aura_env.config["mini"] == true then
        header = ""
    else 
        header = "Total Corruption: "
    end
    return  header .. corruptionLevel ..  output
end`

**Comment by LiangYuxuan** [comment]
`GetCorruptionResistance` returns Corruption Resistance from Essences either, not only from cloak.

**Comment by igorrebolj** [comment]
Hey, any progress on this?

**Comment by DeeRez** [comment]
The Cloak has bonus_id which relates to the corruption level.

id=169223,bonus_id=6577/1472 is +53 corruption

id=169223,bonus_id=6580/1472 is +53 corruption

it then continues following the same pattern (bonus_id=6XXX) up to 

id=169223,bonus_id=6603/1472 for +125 corruption.

If that helps in any way.

**Comment by endotnick** [comment]
Would tracking the 1 to 2 weekly obtainable Malefic Cores to catch up to the new corruption cap fall under this issue or is that a separate weekly quest?
