### ISSUE TITLE
Mount Rares of Uldum/Vale of Eternal BlossoR

### ISSUE THREAD

**Issue by warcry16** [SavedInstances/SavedInstances#348]
Is it possible to add those to the Addon?
Rares like Houndlord Ren and Rei lun etc..

I tried to add them myself but i couldnt get it to work.

**Comment by LiangYuxuan** [comment]
We don't like the idea like tracking tons of rares, but you can add by yourself. Check out #300 that provided a sample that tracks rares in Mechagon.
