### ISSUE TITLE
New Patch 8.3 Call to Arms quests aren't tracked

### ISSUE THREAD

**Issue by DeeRez** [SavedInstances/SavedInstances#349]
Patch 8.3 added new Call to Arms quests which aren't currently tracked

Call to Arms : Vale of Eternal Blossoms - Horde: https://www.wowhead.com/quest=59017
Call to Arms : Vale of Eternal Blossoms - Alliance: https://www.wowhead.com/quest=59018
Call to Arms: Uldum - Horde: https://www.wowhead.com/quest=59016
Call to Arms: Uldum - Alliance: https://www.wowhead.com/quest=59019

**Comment by LiangYuxuan** [comment]
Thank you!
