### ISSUE TITLE
SavedInstances: Unrecognized LFR instance parent id= 1640

### ISSUE THREAD

**Issue by q8light** [SavedInstances/SavedInstances#35]
I have copied the files from Github to make the addon working again. thank you for that .
now when ever i mouseover the minimap button i get this error:
SavedInstances: Unrecognized LFR instance parent id= 1640

**Comment by Stanzilla** [comment]
Is this still happening with the latest release? The LFR is now open.

**Comment by Tumbleweed64** [comment]
[12:33:45] SavedInstances: Unrecognized LFR instance parent id= 1640
[12:33:45] SavedInstances: Please report this bug at: https://github.com/SavedInstances/SavedInstances/issues

v7.3.2 (25549) german client

**Comment by Stanzilla** [comment]
Yeah I still don't know where to find those IDs. Maybe @AlexAtTheBux knows?

**Comment by q8light** [comment]
For me no, now i do not get this error when hovering on the minimap addon icon .
EU / english client

**Comment by chancedj** [comment]
If i remember correctly you can get the correct ID's (that need to be mapped) using this:
*https://wow.gamepedia.com/API_GetRFDungeonInfo

then you get the id for normal (once saved) using this:
*http://wowwiki.wikia.com/wiki/API_GetSavedInstanceInfo

**Comment by AlexAtTheBux** [comment]
I’m at work right now, but I’ll check it when I get home. I meant to update this last week when Antorus opened but got caught up in real life issues.

**Comment by Stanzilla** [comment]
Nice, and please document it so I and others know how to find them in the future as well.

**Comment by chancedj** [comment]
actually, looking at the code - it's already been completed.

https://github.com/SavedInstances/SavedInstances/blob/master/SavedInstances/SavedInstances.lua#L193

**Comment by Stanzilla** [comment]
Yeah those are my guesses from a few months ago

**Comment by chancedj** [comment]
PR submitted - comments have how to derive the id's.
