### ISSUE TITLE
Weekly Horrific Vision Masks Reward

### ISSUE THREAD

**Issue by oresika** [SavedInstances/SavedInstances#352]
Horrific Visions reward a 470 piece of loot for a clear done with 5 masks. This reward is weekly, as the rewards for successive 5 mask runs are on a diminishing reward. After the first 5 mask run is completed, another run would only reward a 465 piece as if 1 less mask were equipped.

My request is for Saved Instances to be tracking these weekly rewards from horrific visions so it would be easy at a glance to see which toon still needs to do a run, or what the highest run was for the week (similar to how it displays keystones).

**Comment by igorrebolj** [comment]
Hey, any progress on this?

**Comment by LiangYuxuan** [comment]
Hi, I got some questID this week, but not quite sure about them. I want to check them on my alts, or anyone can help by checking them using like `/dump IsQuestFlaggedCompleted(57848)`.

| questID | Caches & Mask |
| ------- | ------------- |
| 57848   | 5 Masks       |
| 57844   | 4 Masks       |
| 57847   | 3 Masks       |
| 57843   | 2 Masks       |
| 57846   | 1 Mask        |

**Comment by igorrebolj** [comment]
It checks out.
On alliance , i did 5 4 3 and it shows completed. 2 1 did not do, and are not complete.
On horde, i did 4 3 2 and it shows completed. 5 1 did not do, and are not complete.

**Comment by Hemario** [comment]
@LiangYuxuan  just out of curiosity, how does one go about finding these hidden questIDs?

**Comment by igorrebolj** [comment]
Did 5 mask on horde also, 57848 completed here too.

**Comment by LiangYuxuan** [comment]
> @LiangYuxuan just out of curiosity, how does one go about finding these hidden questIDs?

@Hemario I use [QuestsChanged](https://www.curseforge.com/wow/addons/questschanged) to find them :)

**Comment by LiangYuxuan** [comment]
Update: Got more questIDs! Need some check here :)

| QuestID | Objective                        | Reward iLvl |
| ------- | -------------------------------- | ----------- |
| 57841   | Vision Boss Only                 | 420         |
| 57845   | Vision Boss + 2 Bonus Objectives | 430         |
| 57842   | Full Clear No Masks              | 445         |
| 57846   | Full Clear + 1 Mask              | 450         |
| 57843   | Full Clear + 2 Masks             | 455         |
| 57847   | Full Clear + 3 Masks             | 460         |
| 57844   | Full Clear + 4 Masks             | 465         |
| 57848   | Full Clear + 5 Masks             | 470         |

**Comment by SacredDuckwhale** [comment]
I can confirm 57841 and 57845, I haven't done anything more than that, but those quests worked for both Horde and Alliance, and IIRC they were the same in Orgrimmar (last week), as well.
