### ISSUE TITLE
Weekly Reliquary/Coffer Tracking

### ISSUE THREAD

**Issue by oresika** [SavedInstances/SavedInstances#354]
in uldum and vale the big keys are lootable and usable once per week. can this be tracked via quest id tag?

**Comment by oresika** [comment]
https://www.wowhead.com/item=174768/cursed-relic
https://www.wowhead.com/item=174761/aqir-relic#comments
https://www.wowhead.com/item=174764/tolvir-relic-fragment
https://www.wowhead.com/item=174767/mogu-relic
https://www.wowhead.com/item=174766/mantid-relic

**Comment by DeeRez** [comment]
Cursed Coffer is QuestID: 57628

**Comment by DeeRez** [comment]
Mantid Coffer is QuestID: 58770

**Comment by DeeRez** [comment]
Tol'vir Coffer is QuestID: 55692

**Comment by DeeRez** [comment]
Aqir Coffer is QuestID: 58137

**Comment by LiangYuxuan** [comment]
Hi, could you confirm if Cursed Relic's quest id is shared between Uldum and Vale of Eternal Blossoms?

**Comment by DeeRez** [comment]
I have no idea where the cursed coffer I did was (I think it was the uldum one), so will check next time it's up and add a location note to my previous comment if it's the same quest, then check the other one next time it's up.

**Comment by DeeRez** [comment]
Can confirm Vale and Uldum Cursed Coffers Share QuestID.

Vale/Uldum Cursed Coffer is QuestID: 57628
Mogu Coffer is QuestID: 57214
Mantid Coffer is QuestID: 58770
Tol'vir Coffer is QuestID: 55692
Aqir Coffer is QuestID: 58137
