### ISSUE TITLE
Track weekly pet battle dungeon challenge quests?

### ISSUE THREAD

**Issue by Dalrint** [SavedInstances/SavedInstances#357]
Would it be possible to add the weekly pet battle dungeon challenge quests to the tracker?

There are five of them at the moment.

https://www.wowhead.com/quest=45539/pet-battle-challenge-wailing-caverns
https://www.wowhead.com/quest=46292/pet-battle-challenge-deadmines
https://www.wowhead.com/quest=54186/pet-battle-challenge-gnomeregan
https://www.wowhead.com/quest=56492/pet-battle-challenge-stratholme
https://www.wowhead.com/quest=58458/pet-battle-challenge-blackrock-depths

Thanks!

**Comment by LiangYuxuan** [comment]
They're tracked currently, hover on Weekly Quest to find them :)

**Comment by Dalrint** [comment]
Oh cool, sorry for missing it. :D
