### ISSUE TITLE
Conquest Points For the first chests.(daily)

### ISSUE THREAD

**Issue by linlinglin** [SavedInstances/SavedInstances#365]
i wanna to get that :
there are 50 or 75 Conquest Points in daily first war supply chests. in two dif ares,
can somebady get the questid for them?
i'm in china  ,i just cannot view the web: wowhead .
thx for ur help

**Comment by DeeRez** [comment]
https://github.com/SavedInstances/SavedInstances/issues/306#issuecomment-626702861

**Comment by LiangYuxuan** [comment]
I think it's no longer gives Conquest :( Sorry for delaying this so much.
