### ISSUE TITLE
Currency Section Bugged

### ISSUE THREAD

**Issue by greasypleb** [SavedInstances/SavedInstances#368]
![WoWScrnShot_051220_231505](https://user-images.githubusercontent.com/65273392/81778405-a6f8e480-94a7-11ea-8e3b-4b5559133dfa.jpg)
![WoWScrnShot_051220_232232](https://user-images.githubusercontent.com/65273392/81778408-a8c2a800-94a7-11ea-90c0-fe9a7e28f0b9.jpg)

**My currency section seems to be bugged. All the currency I have on my characters displays regardless of whether or not it is selected under the "currency" tab of the addon. I have tried selecting and deselecting everything, resetting and deleting character data, deleting setting and reverting back to default, disabling all other addons and running just this one, reinstalling multiple times with character logins in between, running the newest and older versions, and yet nothing seems to work. Is there a way to fix this issue?**

**Comment by LiangYuxuan** [comment]
Seems like you have your <kbd>alt</kbd> key down to force SI to show all lockouts and currencies.
