### ISSUE TITLE
Add tracking for the daily rares from 8.3 and 8.2

### ISSUE THREAD

**Issue by ZyerTCoder** [SavedInstances/SavedInstances#369]
Just want be able to track all the 8.3/2 rares I wanna kill daily for collectibles on all my characters

Most prolly don't want all the rares theyve killed that day showing up when so have it be never show by default and people can turn it to always show if they want to see it. The 8.3 rares are only up during their corresponding assault so it'd be nice if a "Show when up" option could be added along "Show when saved"/"Always Show"/"Never Show"

Alternatively maybe adding someway of adding custom daily quests to track so if I need Anh-De I can add the quest id "57363" to be tracked.

I've implemented a makeshift attempt at it by adding them as world bosses in WorldBosses.lua but unfortunately that means they don't get reset daily unless I log onto the character.

Example of what I have:  https://cdn.discordapp.com/attachments/397975832565514280/710947599305277531/unknown.png
Since they're classed as lv120 world bosses they show up together with Ulmath

**Comment by LiangYuxuan** [comment]
We have discussed this issue in #300, and we still don't like this.
