### ISSUE TITLE
1 character/toon not showing up unless I am on it and have "always show self" checked

### ISSUE THREAD

**Issue by hisako87** [SavedInstances/SavedInstances#373]
So I just downloaded this addon yesterday and logged into each of my alts, and they were showing up/listing just fine. After like 6 toons or so, I noticed my priest stopped showing up. First I thought it was a space problem - name too long? No, my DK's name is more characters. Tried scaling down the tooltip/window, still not there. Then I thought maybe it's because she wasn't saved to anything, so I ran a vision and she still wasn't showing up on other toons. (These toons are all 120 and have bonus loot seals etc. that are tracked by this addon so I would assume they'd all show up?)

Today, after weekly reset- looks like all characters get reset and the SI addon fills them back in as you login- so I logged into a few characters, including priest, but the priest still doesn't show up in the tooltip/window. Not sure what the problem is. All other toons show up with their raidinfo etc. except her. There's no specific addons I have on my priest that aren't on other alts that could be conflicting. 

So I checked if this problem persists with only SI enabled (new WTF folder), and it stops recording characters completely after I logged into my shaman whose name has special characters (ù). This is unexpected because my DK has special characters in her name as well, and both of them were showing up fine with other addons enabled.

This is with the SavedInstances-8.3.2.zip installed from the twitch app.

**Comment by LiangYuxuan** [comment]
Hi, we removed bonus roll tracking from "saved" in 11c362b and released in v8.2.3, please use "always" instand :)
