### ISSUE TITLE
Add custom category with UI for adding a rare ID

### ISSUE THREAD

**Issue by fladnagg** [SavedInstances/SavedInstances#374]
The idea is to :
- have an UI for adding a rare by ID, like NPCScan. For example 157162 for Rei Lun
- Main panel display if rare is done for a toon (with IsQuestFlaggedCompleted(ID))

The name of the rare can be found programmatically, NPCScan do it.

**Comment by Stanzilla** [comment]
We're not going to add rare tracking, thats what other addons are for
