### ISSUE TITLE
Essences overview

### ISSUE THREAD

**Issue by stamicvs** [SavedInstances/SavedInstances#379]
Hi Jokerhyme,

first of all thank you very much for this great addon.
I have a feature request or I maybe just missed something.

As we can now buy our Essences for Echoes and I am currently try to keep up with Essence farming I would like to be able to see what Essences my Alts have and at what level to determine with what character I should continue to farm.
Is there already such an overview existing or would this be possible to implement?

Thank you very much in advance.

**Comment by LiangYuxuan** [comment]
Honestly, I don't like this. :/

**Comment by TruthNZ** [comment]
Feels like something more for Altoholic than us.

**Comment by LiangYuxuan** [comment]
Outdated
