### ISSUE TITLE
Cloak resistance shown wrong

### ISSUE THREAD

**Issue by igorrebolj** [SavedInstances/SavedInstances#382]
https://imgur.com/a/FvzPu1V

Have 2 other chars with 65 resistance, its shown correctly for them.

**Comment by LiangYuxuan** [comment]
What's your SI version?

**Comment by igorrebolj** [comment]
8.3.3

**Comment by LiangYuxuan** [comment]
This issue have been fixed in 851e8cd703d87a77dd256e91a2eed73321638b86, please try alpha version:)
