### ISSUE TITLE
Show Old Expac LFR Progress in NPC Dialog

### ISSUE THREAD

**Issue by justinryder** [SavedInstances/SavedInstances#386]
**Is your feature request related to a problem? Please describe.**
I love how SavedInstances tracks my old expac LFR wing progress in the minimap tooltip, but I often forget to check that and forget which named wing I finished with in a previous farming session.

**Describe the solution you'd like**
Showing the LFR wing progress in the NPC dialog would make it super quick and easy to tell which LFR wings have been completed.

e.g. (Seer Kazal, WoD LFR)
> Grant me a vision of the Imperator's Rise atop Highmaul. [1/1]
> Grant me a vision of the Blackrock Foundry's Slagworks. [2/3]
> Grant me a vision of the Blackrock Foundary's Black Forge. [0/3]

**Describe alternatives you've considered**
Displaying this in a tooltip when hovering the dialog option would also provide an easy way to check this info. This could also be a place to display more info, such as the specific bosses killed/skipped, similar to when you hover the full raid progress in the main SavedInstances window.

**Additional context**
![image](https://user-images.githubusercontent.com/2396658/85192235-6307b500-b287-11ea-91e9-544bc095b300.png)

**Comment by LiangYuxuan** [comment]
Found an addon can solve this issue: https://www.curseforge.com/wow/addons/lfr-of-the-past . Hope it can help you.
