### ISSUE TITLE
Lua Error in Version 8.3.4 (Typo? "Tex" instead of "Text"?)

### ISSUE THREAD

**Issue by Tykwer** [SavedInstances/SavedInstances#389]
**Describe the bug**

A Lua error occurs when logging in for the first time.  The error is not subsequently generated on a /reload, but if you completely exit the game and come back in, the error will be generated.

**Do you have an error log of what happened?**

Date: 2020-07-02 22:07:39
ID: -1
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\config.lua line 878:
   attempt to concatenate local 'tex' (a nil value)
Debug:
   [string "@SavedInstances\config.lua"]:878: BuildOptions()
   [string "@SavedInstances\config.lua"]:918: SetupOptions()
   [string "@SavedInstances\config.lua"]:53:
      SavedInstances\config.lua:52
   [string "=[C]"]: ?
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: InitializeAddon()
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:613:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
   SavedInstances, v8.3.4
  BlizRuntimeLib_enUS v8.3.0.80300

**To Reproduce**

1. Log into WoW after a complete logout.
2. The error will be reproduced. 

**Screenshots**

Nope.

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes.

**Which version of SavedInstances are you using?**

8.3.4.  I want to note that the problem is not present in 8.3.3.  If I roll back, it disappears.

**Was it working in a previous version? If yes, which was the last good one?**

Guess I got ahead of myself.  The problem was not present in 8.3.3.

**Additional context**

None.

**Comment by LiangYuxuan** [comment]
Didn't reproduce on my 8.3.4, and 8.3.4 doesn't change any code related to this. If you have any further info, please reply to this:)

**Comment by Tykwer** [comment]
Thank you for your reply!  I am sorry, I have no further information.  I've updated back to 8.3.4 because the error doesn't seem to cause any problems - I just dismiss it.  But it still occurring for me on every fresh login (if I just switch toons this does not happen.)

I appreciate your time, thanks again.

**Comment by LiangYuxuan** [comment]
> Thank you for your reply! I've updated back to 8.3.4 because the error doesn't seem to cause any problems - I just dismiss it. But it still occurring for me on every fresh login (if I just switch toons this does not happen.)
> 
> I appreciate your time, thanks again.

Did you find any currency missing in SI's option on your fresh login?

**Comment by Tykwer** [comment]
Just wanted to mention, I haven't seen this error since my last posting here.  I am not sure what changed, but it appears to be fixed!  Thanks for your time.
