### ISSUE TITLE
Adding custom daily / weekly quests tracking

### ISSUE THREAD

**Issue by MusTangLee** [SavedInstances/SavedInstances#390]
Hi,

Adding a way to track a custom daily or weekly quests would be awesome.

For example, I'm trying to get the achievement [Most Minis Wins](https://www.wowhead.com/achievement=13708/most-minis-wins).
Best way to do that completing 4 hidden weeklies: 57135 Beastbot kill, 57134 Recycling quest, 57132 Reclamation Rig and Mechanized Chest (which is already tracked by SavedInstances).

This is just one example out of many possible ways that a custom weekly or daily tracking would be useful.

I've added manually some of these quests when I need them but they are obviously deleted when updating the addon.

Have been using this addon for years, thank you for all the hard work!

**Comment by Nercus** [comment]
Would love such a feature. Something like a small text box to add questids with a small dropdown list to edit/remove (i.e. set weekly/daily, show/hide on completion). Regarding my personal usecase: I wanna track which of my alts hasn't completed the weekly timewalking quest for 500 badges.

**Comment by Demonicka** [comment]
I would love this feature added as well. I didn't know that updating the addon would delete my additions, so just won't update until it breaks (or until a self-edit feature is added), thanks for the heads up!

**Comment by MusTangLee** [comment]
> > Hi,
> > Adding a way to track a custom daily or weekly quests would be awesome.
> > For example, I'm trying to get the achievement [Most Minis Wins](https://www.wowhead.com/achievement=13708/most-minis-wins).
> > Best way to do that completing 4 hidden weeklies: 57135 Beastbot kill, 57134 Recycling quest, 57132 Reclamation Rig and Mechanized Chest (which is already tracked by SavedInstances).
> > This is just one example out of many possible ways that a custom weekly or daily tracking would be useful.
> > I've added manually some of these quests when I need them but they are obviously deleted when updating the addon.
> > Have been using this addon for years, thank you for all the hard work!
> 
> How Do I add stuff manually to the addon? :O

sorry for the late replay.

I've added these quests by editing the file Quests.lua inside the SavedInstances addon directory.
Here's an example:
![image](https://user-images.githubusercontent.com/20220182/94926566-a948f300-04c9-11eb-8908-b6a4ba1ceb62.png)


Btw, I've seen exactly this custom adding implemented in another addon ("Rarity") and it's amazing!
I'm not sure what's the copyrights on their addon code on github is but sadly I can't code in lua for the life of me to add this feature as a pull request myself.
![image](https://user-images.githubusercontent.com/20220182/94926487-8f0f1500-04c9-11eb-9579-745f27ce20c1.png)
