### ISSUE TITLE
SavedInstances blank with Addonskins addon

### ISSUE THREAD

**Issue by gibletsz** [SavedInstances/SavedInstances#394]
**Describe the bug**
The SavedInstances interface is blank with the Addonskins addon enabled.

**To Reproduce**
1. Enable Addonskins addon
2. Hover over minimap icon
3. It will be blank
--> 

**Which version of SavedInstances are you using?**
8.3.4

**Was it working in a previous version? If yes, which was the last good one?**
the version prior to 8.3.4

**Comment by Stanzilla** [comment]
That sounds more like an AddonSkins bug

**Comment by LiangYuxuan** [comment]
Yea, didn't reproduce on SavedInstances 8.3.4 + AddOnSkins 4.44, maybe you should update AddOnSkins :)
