### ISSUE TITLE
Dont see nothing on addon windows

### ISSUE THREAD

**Issue by Valanian** [SavedInstances/SavedInstances#395]
**Describe the bug**

After update all my addons 7-10 days ago.....now on addon interface window....dont see nothing....is clear

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by LiangYuxuan** [comment]
sounds like #394 , do you have any lua error?
