### ISSUE TITLE
Feature request: track Death Metal Knight @ Dark Moon Faire

### ISSUE THREAD

**Issue by comiluv** [SavedInstances/SavedInstances#396]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
[Death Metal Knight](https://www.wowhead.com/npc=122899/death-metal-knight#comments) is a monthly event taking place at Dark Moon Island only when Dark Moon Faire is active. A toon can partake every month for transmog items and toys. This event is currently not tracked by savedinstances and I think it would be good idea if it's tracked.

**Describe alternatives you've considered**
/dump IsQuestFlaggedCompleted(47767) also kinda works

**Additional context**

**Comment by LiangYuxuan** [comment]
#390
