### ISSUE TITLE
PTR 9.0.1

### ISSUE THREAD

**Issue by Zetaprime82** [SavedInstances/SavedInstances#398]
1x SavedInstances\Emissary.lua:60: attempt to index field 'db' (a nil value)
[string "@SavedInstances\Emissary.lua"]:60: in function `?'
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Zetaprime82** [comment]
3x SavedInstances\MythicPlus.lua:45: attempt to index field 'db' (a nil value)
[string "@SavedInstances\MythicPlus.lua"]:45: in function ?' [string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119> [string "=[C]"]: ? [string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25> [string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function Fire'
[string "@Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by gaveer** [comment]
@https://github.com/SavedInstances/SavedInstances/issues/397
