### ISSUE TITLE
Daily Mount Bosses

### ISSUE THREAD

**Issue by Alauraaa** [SavedInstances/SavedInstances#399]
Dear SavedInstances, I've searched for an Addon which showed me my saved Daily Open World Mount Bosses, Like; Soundless, Ha'Li and so on. It would be great if this feature could be added to your Addon.

**Comment by Nercus** [comment]
This request is kinda incorporated in [this one](https://github.com/SavedInstances/SavedInstances/issues/390) (issue 390). Rare NPCs have a lockout (daily/weekly) with an according questid.
