### ISSUE TITLE
Ability to track pets battle dailies/weeklies in wod, legion, bfa and SL

### ISSUE THREAD

**Issue by javedbartlett** [SavedInstances/SavedInstances#403]
**Is your feature request related to a problem? Please describe.**
Ability to track pets battle dailies/weeklies in wod, legion, bfa and SL. I cannot track this with savedinstances and sucks that i have to use a 2nd addon

**Describe the solution you'd like**
https://i.imgur.com/FUI3cAq.png
https://i.imgur.com/4EcGc7X.png
https://i.imgur.com/APhZRpW.png

**Describe alternatives you've considered**

**Additional context**

**Comment by LiangYuxuan** [comment]
I think it should be fixed #284. Could you check your weekly quest on SI tooltip?
