### ISSUE TITLE
SI Team Attribution

### ISSUE THREAD

**Issue by Alastair-Scott** [SavedInstances/SavedInstances#404]
Hi! 

I recently decided that I would like an addon that tracks my reputations across all characters so that I could see which are close to getting supply chests; being unable to find one, I thought it'd be a fun challenge to make my own, and have met with some success.

As I've never created my own addon before, I thought I'd look through one that I liked the look of (I love the UX of SI), and have used ideas and parts of it in my work. 

Having spoken to a number of my guildies who are interested in using it, I thought I'd look at putting it onto Curse, but wanted to ask if it was OK for me to do this, and if you were happy for me to attribute SI and the team. 

I know that raising an 'issue' isn't necessarily the right place to raise this type of question, but I couldn't find a better place to do so!

Thanks for all of your hard work on an awesome solution!
Alastair

**Comment by TruthNZ** [comment]
Does Altoholic provide this function?

**Comment by Alastair-Scott** [comment]
Not as far as I could see. I've also added some tracking to see how many supply chests you have opened (ever), and how much gold you have got from them in total (since you've installed the addon)

**Comment by Alastair-Scott** [comment]
Hey guys, I was just wondering if there was anyone I could speak to regarding this query? 

Thanks!

**Comment by Stanzilla** [comment]
Hey there, not sure what you mean exactly. The code for SI is all rights reserved, so not a permissive open source license

**Comment by Alastair-Scott** [comment]
Hi Stan, I noticed that the other day, but it also says unless explicitly stated. 

I used SI more as a learning tool to see how you would manipulate data and display it in an addon, and borrowed a couple of utility functions, but my addon does look similar due to using the same methodology of displaying the data (LibQTip).

I'd like to be able to share it with my friends and anyone else that would like to use it, but was wondering if I needed to restructure it / change it's styling, or if I could get permission to post it as is. If you'd like, I could get it up on GitHub so you guys could check it out to see what you think

**Comment by Stanzilla** [comment]
It would be fine with me, the problem is that we are not the original code owners, so technically even our GitHub fork is against the rules but yeah. Let's see it!

**Comment by LiangYuxuan** [comment]
Fine with me too :)

**Comment by Alastair-Scott** [comment]
@Stanzilla & @LiangYuxuan Thanks for your replies both!

The code can be seen here: https://github.com/Alastair-Scott/AltReps

I've added a thank you to the bottom of the readme that would also be included on Curse.

Please let me know if I need to change anything and I'd be more than happy to oblige!
