### ISSUE TITLE
SetBackDrop Error

### ISSUE THREAD

**Issue by MetalHeadSeven** [SavedInstances/SavedInstances#409]
Not working at all.

1x ...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua:540: attempt to call method 'SetBackdrop' (a nil value)
[string "@SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:540: in function <...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:534>
[string "@SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:127: in function `Acquire'
[string "@SavedInstances\Core\Core.lua"]:3282: in function `ShowTooltip'
[string "@SavedInstances\Core\Core.lua"]:2401: in function <SavedInstances\Core\Core.lua:2399>
[string "@Titan\LDBToTitan.lua"]:327: in function <Titan\LDBToTitan.lua:286>

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "SavedInstancesTooltip"
backdrop = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
(*temporary) = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 SetLFGDungeonReward = <function> defined @AllTheThings\AllTheThings.lua:4666
 SetRecipeReagentItem = <function> defined @Altoholic\Tooltip.lua:702
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.050000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetCurrencyByID = <function> defined @AllTheThings\AllTheThings.lua:4628
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:702
 SetGuildBankItem = <function> defined =[C]:-1
 TopLeftCorner = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 comparing = false
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetTrainerService = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetToyByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 TextLeft1 = GameTooltipTextLeft1 {
 }
 BottomEdge = <unnamed> {
 }
 SetLFGDungeonShortageReward = <function> defined @AllTheThings\AllTheThings.lua:4683
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 SetTradeTargetItem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 textLeft2Font = "GameTooltipText"
 textRight2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetExistingSocketGem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 backdropInfo = <table> {
 }
 SetItemKey = <function

**Comment by LiangYuxuan** [comment]
Since you didn't answer the questions in bug report template and I can't reproduce this. :( I have some question for you to gather information.

* What is your SI version?
* What is your WoW version?
* Did you try to let SI be your only enabled addon?

**Comment by MetalHeadSeven** [comment]
What is your SI version? 9.0.0
What is your WoW version? 9.0.1.36230
Did you try to let SI be your only enabled addon? Yes

The error is being caused by Titan Panel.  It happens with Titan Panel version 5.19.0.90001a and older version 5.18.7.80300.

Thanks for your reply.  I guess I need to wait for a Titan Panel update so feel free to close this report.

**Comment by LiangYuxuan** [comment]
Thanks for your feedback :)

**Comment by Nillx** [comment]
Im getting this error too but in my case its caused by multiple addons.

```
3x ...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua:540: attempt to call method 'SetBackdrop' (a nil value)
[string "@SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:540: in function <...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:534>
[string "@SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:127: in function `Acquire'
[string "@SavedInstances\Core\Core.lua"]:3282: in function `ShowTooltip'
[string "@SavedInstances\Core\Core.lua"]:2401: in function `OnEnter'
[string "@BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua"]:77: in function <BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>
[string "=[C]"]: ?

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "SavedInstancesTooltip"
backdrop = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
(*temporary) = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 comparing = false
 __tamedCounts = false
 BottomRightCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 RightEdge = <unnamed> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 SetTradeTargetItem = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 SetInboxItem = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 BottomEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetQuestLogItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 backdropInfo = <table> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetToyByItemID = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 shoppingTooltips = <table> {
 }
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 0 = <userdata>
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 BottomOverlay = <unnamed> {
 }
 Center = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.140000
 textLeft2Font = "GameTooltipText"
 TopEdge = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
}
AcquireTable = <function> defined @SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:514
labelProvider = <table> {
 cells = <table> {
 }
 cellMetatable = <table> {
 }
 cellPrototype = <table> {
 }
 heap = <table> {
 }
}
CELL_MARGIN_H = 6
CELL_MARGIN
```

```
6x ...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua:540: attempt to call method 'SetBackdrop' (a nil value)
[string "@SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:540: in function <...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:534>
[string "@SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:127: in function `Acquire'
[string "@SavedInstances\Core\Core.lua"]:3282: in function `ShowTooltip'
[string "@SavedInstances\Core\Core.lua"]:2401: in function `OnEnter'
[string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua"]:77: in function <BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>
[string "=[C]"]: ?

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "SavedInstancesTooltip"
backdrop = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
(*temporary) = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 comparing = false
 __tamedCounts = false
 BottomRightCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 RightEdge = <unnamed> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 SetTradeTargetItem = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 SetInboxItem = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 BottomEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetQuestLogItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 backdropInfo = <table> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetToyByItemID = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 shoppingTooltips = <table> {
 }
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 0 = <userdata>
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 BottomOverlay = <unnamed> {
 }
 Center = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.118000
 textLeft2Font = "GameTooltipText"
 TopEdge = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
}
AcquireTable = <function> defined @SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:514
labelProvider = <table> {
 cells = <table> {
 }
 cellMetatable = <table> {
 }
 cellPrototype = <table> {
 }
 heap = <table> {
 }
}
CELL_MARGIN_H = 6
CELL_MARGIN
```
