### ISSUE TITLE
Unrecognized trade skill cd Shadestone (307143)

### ISSUE THREAD

**Issue by jscharnitzke** [SavedInstances/SavedInstances#410]
**Describe the bug**

This doesn't appear to be a critical issue since it's just a warning in my chat box that a new CD for Shadowlands isn't recognized.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

1. Log in on a character with Alchemy

**Screenshots**

![image](https://user-images.githubusercontent.com/2000659/96022106-39aa0080-0e05-11eb-8b69-a9e192857a2d.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**

9.0.0

**Was it working in a previous version? If yes, which was the last good one?**

I haven't seen the message before, but I'd assume that it's something that it's related to new Shadowlands recipes that are in the system now from the pre-patch.

**Additional context**

**Comment by LiangYuxuan** [comment]
Thank you!
