### ISSUE TITLE
Error with Prepatch attempt to index field 'Title' (a nil value)

### ISSUE THREAD

**Issue by taoriux** [SavedInstances/SavedInstances#417]
**Describe the bug**
When moving the cursor over dailies breakdown a LUA error pops up.

**Do you have an error log of what happened?**
Yes.
https://pastebin.pl/view/11276432

**To Reproduce**
1. Move cursor to minimap icon of Savedinstances.
2. Scroll to Daily Quests of the toon.
3. Error pops up. Unable to see what daily quests have been done.

**Screenshots**
https://i.imgur.com/4EIpkfI.jpg

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.
Also tested on a freshly installed WoW client.

**Which version of SavedInstances are you using?**
Latest 9.0.1, release date 10/16/20.

**Was it working in a previous version? If yes, which was the last good one?**
It worked before Shadowlands prepatch.

**Additional context**
So far the error triggers when attempting to view Daily Quests, everything else works fine so far.

**Comment by LiangYuxuan** [comment]
Hi, can you try /reload the game and check out if the issue gone? This quest is added in 6.2 to track Terrorfist and not touched. It might be SI fails to fetch the quest title.

**Comment by taoriux** [comment]
Hello, /reload doesn't seem to resolve the issue. Assuming I am doing it right, the quest does return a nil value when running the in-game script:
`/script print (C_QuestLog.GetTitleForQuestID(39288))`

**Comment by LiangYuxuan** [comment]
SI uses hidden tooltip to get quest title. I'll look into it. Thanks for feedback.
