### ISSUE TITLE
Data are not being collected

### ISSUE THREAD

**Issue by Zhoglik** [SavedInstances/SavedInstances#421]
There's a problem with addon - it doesn't collect data.

I've never disabled this addon and before 9.0.1 on live servers I had never faced such issue.
It collects data randomly (possibly it show them randomly, I don't know) but... I've completed Island Expeditions for my 9 chars, but I see data only for 4 of them. I logged on each char many times during this WOW-week and no results.

With many thanks for the addon and hope this will be fixed.

**Comment by LiangYuxuan** [comment]
Like I said in #373 , completing Island Expeditions Weekly is no longer considered as "saved". In this case, you need to change all character to "Always Show" in option, or simply hold alt.
