### ISSUE TITLE
please add legion classhall weakly  quests.

### ISSUE THREAD

**Issue by formigao** [SavedInstances/SavedInstances#423]
https://www.wowhead.com/object=252570/skyhold-chest-of-riches

is one example that can only be farmed weakly

**Comment by LiangYuxuan** [comment]
Er, isn't this chest could be looted every time it spawn?

**Comment by formigao** [comment]
wowhead says its weekly: https://www.wowhead.com/item=141069/skyhold-chest-of-riches#comments:id=2377028

**Comment by SacredDuckwhale** [comment]
This chest used to have no lockout whatsoever; I remember looting it repeatedly on my warrior alt in Legion. Recent wowhead comments suggest they did add a weekly lockout, presumably to stop people monopolizing the chest or something along those lines?

If there is a weekly quest, it should be easy enough to determine the quest ID using this addon: https://www.curseforge.com/wow/addons/questschanged

All someone would have to do is get lucky once and loot the chest :) If you can get a screenshot of the completed quests before/after looting, that should confirm it.

**Comment by wizjany** [comment]
![](https://i.imgur.com/7Ssd5hp.png)
