### ISSUE TITLE
"Scary Ghosts and Nice Sprites" Daily Error

### ISSUE THREAD

**Issue by Kanegasi** [SavedInstances/SavedInstances#428]
When completing this daily on Timeless Isle, listed in Quests.lua with the ID of 32961, then mousing over SavedInstances, an error occurs. I do not have an error log for it since I first came across this last year, but I know the cause, just getting around to reporting it. (I've been fixing it myself each update since I modify SI anyways)

WoW API does not return a name for this quest ID, so SI errors due to trying to concatenate a nil (IIRC). I fix this in Quests.lua like so:

      [32961] = { zid=554, daily=true, name="Timeless Sprites" },  -- Scary Ghosts and Nice Sprites

**Comment by LiangYuxuan** [comment]
Related to #417 and 88090b8 as workaround. Don't like the hard-coded name or locale way. I would like to make it remain as-is for now.
