### ISSUE TITLE
Data not showing and no access to settings

### ISSUE THREAD

**Issue by JediAmerican** [SavedInstances/SavedInstances#429]
**Describe the bug**
Data is not showing at all when I tab over the minimap icon. I also cannot access the settings. SavedInstances shows up in my Addon list and does not have any errors listed next to it. I do not have access to it via the Interface --> Addons tab. 

I use Tomtom and have tried the pastebin method several times with no success. I have also fully deleted and redownloaded the addon several times as well. I use WowUp.io to do the later. 

**Do you have an error log of what happened?** 5 Error Logs listed when I scroll over the minimap icon. 
-------------------------------------------------
Message: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
Time: Tue Nov 10 13:04:41 2020
Count: 1
Stack: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:644: in function `InstanceCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:652: in function `InstancesInCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:854: in function `OrderedInstances'
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:585: in function <Interface\AddOns\SavedInstances\Core\Config.lua:583>
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:622: in function <Interface\AddOns\SavedInstances\Core\Config.lua:575>
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:626: in function `BuildOptions'
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:928: in function `SetupOptions'
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:52: in function <Interface\AddOns\SavedInstances\Core\Config.lua:51>
[string "=[C]"]: ?
[string "@Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

--------------------------------------------------------

Message: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
Time: Tue Nov 10 13:04:48 2020
Count: 1
Stack: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:644: in function `InstanceCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:652: in function `InstancesInCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:854: in function `OrderedInstances'
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:585: in function <Interface\AddOns\SavedInstances\Core\Config.lua:583>
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:622: in function <Interface\AddOns\SavedInstances\Core\Config.lua:575>
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:626: in function `BuildOptions'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:1081: in function `UpdateInstanceData'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:2424: in function <Interface\AddOns\SavedInstances\Core\Core.lua:2424>
[string "=[C]"]: ?
[string "@Interface\AddOns\Rarity\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:73: in function <...e\AddOns\Rarity\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
[string "@Interface\AddOns\Rarity\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:89: in function `func'
[string "@Interface\AddOns\AuctionFaster\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...Ons\AuctionFaster\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: <none>

---------------------------------------------------

Message: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
Time: Tue Nov 10 13:19:15 2020
Count: 8
Stack: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:644: in function `InstanceCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:652: in function `InstancesInCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:854: in function `OrderedInstances'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3322: in function `ShowTooltip'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:2399: in function `OnEnter'
[string "@Interface\AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:77: in function <...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>

Locals: self = <table> {
 GetServerOffset = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:23
 lastrefreshlock = 361522.566000
 QuestExceptions = <table> {
 }
 modules = <table> {
 }
 QuestInfo = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:62
 QuestIgnored = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:491
 histLiveCount = 4
 GetRegion = <function> defined @Interface\AddOns\SavedInstances\Core\Functions.lua:61
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 GetTimeToTime = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:14
 InGroup = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2586
 IsEnabled = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 Emissaries = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2472
 RegisterMessage = <function> defined @Interface\AddOns\AuctionFaster\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 OrderedCategories = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:863
 instanceException = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:759
 maxLevel = 50
 lastrefreshlockshed = 361522.703000
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 BossRecord = <function> defined @Interface\AddOns\SavedInstances\Modules\BonusRoll.lua:163
 LFRInstances = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2421
 SkinFrame = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:408
 localarr#wbsave = <table> {
 }
 Indicators = <table> {
 }
 InstanceCategory = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:639
 UnregisterAllEvents = <function> defined @Interface\AddOns\AuctionFaster\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 thisToon = "Grozfu - Emerald Dream"
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:3123
 GetUnitAura = <function> defined @Interface\AddOns\SavedInstances\Core\Functions.lua:16
 specialQuests = <function> defined @Interface\AddOns\SavedInstances\Modules\Quest.lua:60
 ScanTooltip = SavedInstancesScanTooltip {
 }
 BonusRollCount = <function> defined @Interface\AddOns\SavedInstances\Modules\BonusRoll.lua:140
 WorldBosses = <table> {
 }
 cpairs = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:3037
 currencySorted = <table> {
 }
 GetName = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "SavedInstances"
 playedreg = <table> {
 }
 Disable = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 LookupInstance = <function> defined @Interface\AddOns\Sa

----------------------------------------

Message: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
Time: Tue Nov 10 13:08:26 2020
Count: 3
Stack: Interface\AddOns\SavedInstances\Core\Core.lua:644: attempt to concatenate field 'Expansion' (a nil value)
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:644: in function `InstanceCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:652: in function `InstancesInCategory'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:854: in function `OrderedInstances'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3322: in function `ShowTooltip'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3180: in function `ShowDetached'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3130: in function `ToggleDetached'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:2409: in function `OnClick'
[string "@Interface\AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144: in function <...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals: self = <table> {
 GetServerOffset = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:23
 QuestExceptions = <table> {
 }
 modules = <table> {
 }
 QuestInfo = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:62
 QuestIgnored = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:491
 histLiveCount = 5
 GetRegion = <function> defined @Interface\AddOns\SavedInstances\Core\Functions.lua:61
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 GetTimeToTime = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:14
 InGroup = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2586
 IsEnabled = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 Emissaries = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2472
 RegisterMessage = <function> defined @Interface\AddOns\AuctionFaster\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 OrderedCategories = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:863
 instanceException = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:759
 maxLevel = 50
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 BossRecord = <function> defined @Interface\AddOns\SavedInstances\Modules\BonusRoll.lua:163
 LFRInstances = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2421
 SkinFrame = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:408
 localarr#wbsave = <table> {
 }
 Indicators = <table> {
 }
 InstanceCategory = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:639
 UnregisterAllEvents = <function> defined @Interface\AddOns\AuctionFaster\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 thisToon = "Grozfu - Emerald Dream"
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 histLastZone = "Grozfu - Emerald Dream:Firelands:raid:15:1820"
 HideDetached = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:3123
 GetUnitAura = <function> defined @Interface\AddOns\SavedInstances\Core\Functions.lua:16
 specialQuests = <function> defined @Interface\AddOns\SavedInstances\Modules\Quest.lua:60
 ScanTooltip = SavedInstancesScanTooltip {
 }
 BonusRollCount = <function> defined @Interface\AddOns\SavedInstances\Modules\BonusRoll.lua:140
 WorldBosses = <table> {
 }
 cpairs = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:3037
 currencySorted = <table> {
 }
 GetName = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "SavedInstances"
 pla

-------------------------------------------------

Message: Interface\FrameXML\InterfaceOptionsFrame.lua:426: Usage: InterfaceOptionsFrame_OpenToCategory("categoryName" or panel)
Time: Tue Nov 10 13:04:53 2020
Count: 1
Stack: Interface\FrameXML\InterfaceOptionsFrame.lua:426: Usage: InterfaceOptionsFrame_OpenToCategory("categoryName" or panel)
[string "=[C]"]: in function `assert'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:426: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:419>
[string "@Interface\AddOns\SavedInstances\Core\Config.lua"]:970: in function `ShowConfig'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:2411: in function `OnClick'
[string "@Interface\AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:144: in function <...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals: (*temporary) = nil
(*temporary) = "Usage: InterfaceOptionsFrame_OpenToCategory("categoryName" or panel)"

-------------------------

Locals: <none>

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, this did not correct the errors. 

**Which version of SavedInstances are you using?**
9.0.2

**Was it working in a previous version? If yes, which was the last good one?**

Yes, was working in 9.0.2

**Additional context**

**Comment by LiangYuxuan** [comment]
9.0.1 and later should work without modifying files. And this error log looks you have Emissary.lua missing in your SI. Please try reinstall.
