### ISSUE TITLE
Request for "show only current faction" toggle

### ISSUE THREAD

**Issue by tyrexis26** [SavedInstances/SavedInstances#430]
**Is your feature request related to a problem? Please describe.**
I have a number of characters on both factions on a single server.  The end result is that I see characters I don't need to see while playing either faction.

**Describe the solution you'd like**
Could you please add a toggle to only show characters on your current faction?

**Describe alternatives you've considered**
This could also be resolved with profiles (ie, I could have a profile for Horde and a profile for Alliance)

**Comment by LiangYuxuan** [comment]
Duplicated #422
