### ISSUE TITLE
Not working on one of my characters works fine on 4 others

### ISSUE THREAD

**Issue by stellarflame** [SavedInstances/SavedInstances#432]
Message: Interface\AddOns\SavedInstances\Init.lua:10: Cannot find a library instance of "LibQTip-1.0".
Time: Sun Nov 15 21:27:02 2020
Count: 1
Stack: Interface\AddOns\SavedInstances\Init.lua:10: Cannot find a library instance of "LibQTip-1.0".
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\ArkInventory\Libs\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@Interface\AddOns\SavedInstances\Init.lua"]:10: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibQTip-1.0"."

**Comment by LiangYuxuan** [comment]
Please check if is any addon that is only enabled or disabled on that character. Also try to reinstall SavedInstances.

**Comment by stellarflame** [comment]
Yeah no go, it's weird

**Comment by LiangYuxuan** [comment]
Could you try to let SI be the only enabled addon?

**Comment by stellarflame** [comment]
Message: Interface\AddOns\SavedInstances\Init.lua:2: attempt to call global
'LibStub' (a nil value)
Time: Tue Nov 17 05:42:07 2020
Count: 1
Stack: Interface\AddOns\SavedInstances\Init.lua:2: attempt to call global
'LibStub' (a nil value)
[string "@Interface\AddOns\SavedInstances\Init.lua"]:2: in main chunk

Locals: addon = "SavedInstances"
Engine = <table> {
}
(*temporary) = nil
(*temporary) = "AceAddon-3.0"
(*temporary) = "attempt to call global 'LibStub' (a nil value)"

**Comment by LiangYuxuan** [comment]
Please try reinstall SI.

**Comment by stellarflame** [comment]
Message: Interface\AddOns\SavedInstances\Core\Core.lua:2784: attempt to index field 'dataobject' (a nil value)
Time: Wed Nov 18 11:01:59 2020
Count: 3
Stack: Interface\AddOns\SavedInstances\Core\Core.lua:2784: attempt to index field 'dataobject' (a nil value)
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:2784: in function `?'
[string "@Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:55: in function <Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 GetServerOffset = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:23
 QuestExceptions = <table> {
 }
 modules = <table> {
 }
 QuestInfo = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:62
 QuestIgnored = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:491
 histLiveCount = 0
 GetRegion = <function> defined @Interface\AddOns\SavedInstances\Core\Functions.lua:61
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 GetTimeToTime = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:14
 InGroup = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2586
 IsEnabled = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 Emissaries = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2472
 RegisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 OrderedCategories = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:863
 instanceException = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:759
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 BossRecord = <function> defined @Interface\AddOns\SavedInstances\Modules\BonusRoll.lua:163
 LFRInstances = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2421
 SkinFrame = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:408
 Indicators = <table> {
 }
 InstanceCategory = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:639
 UnregisterAllEvents = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 histReapTime = 3600
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:3123
 GetUnitAura = <function> defined @Interface\AddOns\SavedInstances\Core\Functions.lua:16
 specialQuests = <function> defined @Interface\AddOns\SavedInstances\Modules\Quest.lua:60
 GetNextWeeklyResetTime = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:55
 WorldBosses = <table> {
 }
 cpairs = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:3037
 currencySorted = <table> {
 }
 GetName = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "SavedInstances"
 playedreg = <table> {
 }
 Disable = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 LookupInstance = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:608
 GetNextDailySkillResetTime = <function> defined @Interface\AddOns\SavedInstances\Core\Time.lua:40
 currency = <table> {
 }
 GetUnitDebuff = <function> defined @Interface\AddOns\SavedInstances\Core\Functions.lua:34
 Debug = <function> defined @Interface\AddOns\SavedInstances\Core\Debug.lua:18
 KeystoneAbbrev = <table> {
 }
 BossModEncounterEnd = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2563
 ToggleDetached = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:3126
 BOSS_KILL = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2576
 RefreshLockInfo = <function> defined @Interface\AddOns\SavedInstances\Core\Core.lua:2497
 ChatMsg = <func

**Comment by LiangYuxuan** [comment]
It shows that LibDataBroker-1.1 is still missing. Could you try to download it from Curse directly other than installing it by any updater?

**Comment by stellarflame** [comment]
My bad. I was downloading it from github

**Comment by stellarflame** [comment]
Working great now

**Comment by LiangYuxuan** [comment]
Well, closing this then :)
