### ISSUE TITLE
Spacing Of Categories Setting Non-Operational

### ISSUE THREAD

**Issue by OdessaGrimaldus** [SavedInstances/SavedInstances#433]
**Describe the bug**
The bug is simple, the toggle for the spacing of all the shown categories is nolonger working.

**Do you have an error log of what happened?**
I do not.

**To Reproduce**
Toggling the setting on changes nothing and is as if the option is disabled at all times.

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I have tried it without any other addons enabled and this issue still persists.

**Which version of SavedInstances are you using?**
9.0.2 and just updated to 9.0.2-3-g38cf603 with no change to this issue

**Was it working in a previous version? If yes, which was the last good one?**
It was working just fine, previous to the 9.0.2 update version.

Last working version: 9.0.1-3-gdcb8b92

**Comment by LiangYuxuan** [comment]
Cannot reproduce.

**Comment by Finwickle** [comment]
I have the same / a similar issue. The spacing between categories only works for me if at least one dungeon or raid is showing. If none are saved, the spaces disappears no matter the setting. This has been the case on previous versions as well. 
Workaround for me is to set one dungeon to 'always show'.
