### ISSUE TITLE
Gold shown on realms when mouseover account summary

### ISSUE THREAD

**Issue by igorrebolj** [SavedInstances/SavedInstances#434]
I know this is probably not an issue for 99% of users, but how addon decides what realms it will show there and how many it should show? I have gold on multiple realms and many of them are not show when mouse overing.

**Comment by LiangYuxuan** [comment]
show multi-toon servers with over 10k wealth

https://github.com/SavedInstances/SavedInstances/blob/38cf603ebfdf43527517071047ab2950ffbcb311/SavedInstances/Core/Core.lua#L1881

and closing this

**Comment by igorrebolj** [comment]
Ahh multi toons on server, that makes sense. I only have bankers there so its not shown. 
I edited to if ri.money > 10000*10000 and ri.cnt > 0 then -- show multi-toon servers with over 10k wealth 
and it works fine. But i guess on every addon update this setting will be replaced with default settings and i will need to re-edit it again.
