### ISSUE TITLE
Various Shadowland Activities

### ISSUE THREAD

**Issue by yajinni** [SavedInstances/SavedInstances#438]
Hello, hoping we can add these various weekly/daily things to check.
Daily:
-Covenant Callings

Weekly Quests:
-Renow for covenant
    https://shadowlands.wowhead.com/quest=61324/replenish-the-reservoir
    https://shadowlands.wowhead.com/quest=61334/return-lost-souls
-Torghast layers completed
-Wraith of the Jailor Weekly
     https://www.wowhead.com/news=319498/wrath-of-the-jailer-weekly-event-in-maw-drops-item-level-183-gear-in-shadowlands
-Weekly PvP (1)/ Dungeon Quests(2)
    Listed here : https://www.wowhead.com/news=319393/what-to-do-week-1-of-shadowlands-weekly-and-daily-activities-list

**Comment by LiangYuxuan** [comment]
Warth of the Jailor: 63414

Could you check if `/dump C_QuestLog.IsQuestFlaggedCompleted(63414)` returns true?

**Comment by yajinni** [comment]
US region. Reset today already. Will do it later today and check.

**Comment by LiangYuxuan** [comment]
That's great. Also could you try this before killing Warth of the Jailor and check if it returns false? It would be very helpful :)

**Comment by yajinni** [comment]
of course

**Comment by cetraben** [comment]
Returns true on chars that have completed.
Returns false on chars that have not.

**Comment by yajinni** [comment]
yup it worked fine. false before, true after.

**Comment by cremor** [comment]
There seems to be another weekly event in the Maw. Although we might not know until next reset if it is really weekly: https://www.wowhead.com/news=319623/shadehound-hunt-available-at-venari-ambivalent-rep-chance-at-shadowlands-maw-mou

**Comment by LiangYuxuan** [comment]
I'm not able to access the Beastwarrens yet, so not possible to get the quest ids of Beastwarrens Hunts.

**Comment by cremor** [comment]
I'll get access today. What can I do to find the quest ids?

**Comment by LiangYuxuan** [comment]
I use [questschanged](https://www.curseforge.com/wow/addons/questschanged) to find the quest ids

**Comment by cremor** [comment]
I completed 3 unknown quests while doing the "Death Elemental" hunt today: 63446, 63196, 63198
This is the order in which they were completed. I had 5 minutes between each completion. Since the hunt had 3 steps (2 preparations and the actual kill) that all popped up like a world quest I assume that the actual hunt quest ID was the last quest I completed. So that would be 63198.

**Comment by cremor** [comment]
The quest id for the "Winged Soul Eaters" seems to be 63199.
I completed two other unknown quests before that, although it was only one preparation step: 63197, 62722

**Comment by cremor** [comment]
The "Shadehounds" hunt is quest id 63180 or 63433. Both quests were completed at the same time, so I don't know which it is.
I also didn't get any ids for preparation steps (if there are any) because I joined the hunt when the boss was nearly dead.

**Comment by LiangYuxuan** [comment]
I got this two quest completed at the exact same time too. I guess one of thiese is the quest id for the end rare boss tracking quest.

**Comment by cremor** [comment]
The quest id for the "Soul Eaters" hunt is 63194. The preparation step is 62722. Maybe also 63195, I completed that one 2 minutes before but I was not near the event area yet.

So the full list seems to be:
Death Elemental: 63198
Winged Soul Eaters: 63199
Shadehounds: 63180 or 63433 (most likely 63180 because that's near the quest ids of the other hunts)
Soul Eaters: 63194

**Comment by Haxxen** [comment]
Would really love to see the various weekly quests added/shown in a nice Summary.

2 Trading Favor Quests, Dungeon PVE Quests below the innkeeper. 
2 PVP Quests at PvP Vendor. I think its always one for rated and one for nonrated PvP
1 Weekly Eventquest at the great vault, different content every week
2 Renown Quests (souls&anima)

**Comment by LiangYuxuan** [comment]
> Would really love to see the various weekly quests added/shown in a nice Summary.
> 
> 2 Trading Favor Quests, Dungeon PVE Quests below the innkeeper.
> 2 PVP Quests at PvP Vendor. I think its always one for rated and one for nonrated PvP
> 1 Weekly Eventquest at the great vault, different content every week
> 2 Renown Quests (souls&anima)

They're all tracked under Weekly Quests.

**Comment by Haxxen** [comment]
> > Would really love to see the various weekly quests added/shown in a nice Summary.
> > 2 Trading Favor Quests, Dungeon PVE Quests below the innkeeper.
> > 2 PVP Quests at PvP Vendor. I think its always one for rated and one for nonrated PvP
> > 1 Weekly Eventquest at the great vault, different content every week
> > 2 Renown Quests (souls&anima)
> 
> They're all tracked under Weekly Quests.

With nice summary i meant they are also shown if not done, so that you can quickly see whats left to do, like emmisarys and such. 

Also, the 2 pvp weeklys are not tracked on my end.
