### ISSUE TITLE
SL dailies/weeklies not updating

### ISSUE THREAD

**Issue by zalidthebur** [SavedInstances/SavedInstances#441]
Hi,
The Daily and Weekly Shadowlands quests are not updating to being complete. Just done the dailies in the maw and still showing in SI. My covenant weeklies are still showing in SI too.
Also just noticed my renown is showing 5/5, when I have renown level 6.
Any ideas about these ?
TIA,
ZTB

**Comment by LiangYuxuan** [comment]
Currently the daily and weekly quest are tracked. Special quests list is not yet completed. If you encounter some quests should be daily or weekly but not tracked by SI, please report to us.

Renown is now plus one as BLZ didn't do this in their hidden currency.

Closing this as it's no more issue unsolved currently.
