### ISSUE TITLE
few SL currencies not showing

### ISSUE THREAD

**Issue by stevietv** [SavedInstances/SavedInstances#442]
**Describe the bug**
In the config menu its not possible to enable a few of the SL currencies:
* grateful offering
* infused ruby
* reservoir anima

**Do you have an error log of what happened?**
no bug

**To Reproduce**
1. open config
2. navigate to SI > Currency

**Screenshots**
![image](https://user-images.githubusercontent.com/1117625/101398764-df8e5e80-38ce-11eb-86bb-ff834a3e2d00.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
many addons, though I don't believe it san addon conflict

**Which version of SavedInstances are you using?**
9.0.2

**Was it working in a previous version? If yes, which was the last good one?**
not since SL

**Additional context**

**Comment by LiangYuxuan** [comment]
more SL currencies are added in e9f2c08 and a884c15, please try alpha version
