### ISSUE TITLE
Is savedinstance tracking untimed keys?

### ISSUE THREAD

**Issue by gigecogary** [SavedInstances/SavedInstances#448]
I believe the great vault rewards you even for untimed keys? I just completed a +9 key, not timed but it still shows 5/5 for my character. Is this normal?

<img width="305" alt="Screen Shot 2020-12-14 at 11 45 06 PM" src="https://user-images.githubusercontent.com/56096213/102172269-77a7bd00-3e66-11eb-8cb5-7f7f79f7321c.png">

**Comment by LiangYuxuan** [comment]
#446 
no currently and will be corrected later today.
