### ISSUE TITLE
All characters shown

### ISSUE THREAD

**Issue by Hauchka** [SavedInstances/SavedInstances#451]
All my characters arw shown in the preview, without any advance this week. I only did something with 1 character, but all of them are shown...

**Screenshots**
https://i.imgur.com/MhVkWNk.png

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**
9.0.4

**Was it working in a previous version? If yes, which was the last good one?**
It worked fine 2 versions ago.

**Comment by Stanzilla** [comment]
maybe https://github.com/SavedInstances/SavedInstances/commit/5e6e7530a2043c765bf0c7631d89159700739ea3?

**Comment by Hauchka** [comment]
I'll try this afternoon afterwork thanks 👍

**Comment by LiangYuxuan** [comment]
It's a bug related to Mythic Plus Best weekly reset feature and won't try to fetch new status. Will fix this later today.

**Comment by LiangYuxuan** [comment]
After commit merged and update to new version, you might need to login all character affected to refresh corrupted reward waiting info to stop them showing. Sorry for the inconveniece.

**Comment by Hauchka** [comment]
I've just tested this [changeset ](https://github.com/SavedInstances/SavedInstances/pull/452/commits/99f3e8ed896a1f2662ba204ab7f0beb92c232a16)and it works fine, al least for me :)

**Comment by Hauchka** [comment]
As the new version go live, this issue can be closed.
