### ISSUE TITLE
Legion LFR's

### ISSUE THREAD

**Issue by KrakowPally** [SavedInstances/SavedInstances#455]
I believe I have the latest version and just did a Legion LFR on a toon it does not show up.  I tried setting it to always show and the progress still does not show....I have not used it for tracking lfr's since before shadowlands started so I don't know when this issue first started to occur.  but its happening now.

**Comment by LiangYuxuan** [comment]
#426 known issue but still have no time to work on this, sry

**Comment by KrakowPally** [comment]
No worries. Thanks for the great addon and getting back with me so quickly.

**Comment by Mahotsu** [comment]
is there a new possible fix date for this issue? it's still occuring. May 10 2021

**Comment by LiangYuxuan** [comment]
Caused by same reason in #547, check out #578 for more info.
