### ISSUE TITLE
How do I show Torghast runs that have been completed?

### ISSUE THREAD

**Issue by evacfk** [SavedInstances/SavedInstances#456]
I see nothing in the settings that indicate where to display which characters have completed/not completed each wing of torghast.

**Comment by Finwickle** [comment]
In the addons General Settings under Quest Progresses you can enable/disable Torghast.  (next to the BfA visions and island expeditions)

**Comment by evacfk** [comment]
![image](https://user-images.githubusercontent.com/29907491/103432700-a4fba700-4b98-11eb-9d0d-7c109b2d7a09.png)

I'm assuming you're referring to here? I don't see the option for Torghast. I spent about 15 minutes going through every page on the addon and wasn't able to locate it.

![image](https://user-images.githubusercontent.com/29907491/103432704-c9f01a00-4b98-11eb-80b1-15f94e21e6c4.png)

Here's the version i'm running.

**Comment by Finwickle** [comment]
For me it looks like this:
![savedinstances setting](https://user-images.githubusercontent.com/14930335/103440634-87394b00-4c47-11eb-8872-44764980017a.png)

On top of the General Settings it shows the version number. Does it say 9.0.4 there as well?

**Comment by evacfk** [comment]
That was it, it was showing 9.0.0. Looks like the issue was with my addon manager, reinstalling resolved the issue.

Thank you!
