### ISSUE TITLE
Options for "on click"

### ISSUE THREAD

**Issue by griddark** [SavedInstances/SavedInstances#458]
**Is your feature request related to a problem? Please describe.**
No problems, I'd just love to see the option to change the effect of clicking on the minimap icon, I don't really see a point of having it open the LDB window as the tooltip is enough for me.

**Describe the solution you'd like**
On click, open great vault rewards window "/run LoadAddOn("Blizzard_WeeklyRewards"); WeeklyRewardsFrame:Show()"
or
On click, "do nothing"

**Describe alternatives you've considered**
For those who do still want the LDB window, it would be also awesome to have "left click ldb window" and "right click great vault" we don't always need quick access to the options, normally it's a set and forget sort of thing :)

**Additional context**
Nope, just a thank-you for this awesome addition to wow, couldn't imagine playing without it. 👍

**Comment by LiangYuxuan** [comment]
I'd like to put this click stuff to tooltip title "SavedInstances" rather than an option and LDB. Also an hint text to summary tooltip. Hope this might fulfil your request.
