### ISSUE TITLE
Timer anima conductor

### ISSUE THREAD

**Issue by haegensnico** [SavedInstances/SavedInstances#460]
Right now, I have to either memorize when I activated the anima conductor beam or keep a spreadsheet for it. This gets complicated when you got a bunch of alts, I got 8 characters at max level with anima conductor active.
So a timer for when the current anima conductor beam expires and/or if it's active or not, would be greatly appreciated.

**Comment by LiangYuxuan** [comment]
I havn't find a stable way to track anima conductor beam activated. The API is only available when you're interacting with anima conductor. I would like to use a quest or some but didn't find one.
