### ISSUE TITLE
View Arena Ratings (2s, 3s, RBGs)

### ISSUE THREAD

**Issue by TDillman** [SavedInstances/SavedInstances#461]
I'd like to be able to see the arena ratings for all my characters at a glance (2s, 3s, and RBGs).

A slash-delimited list would probably work just fine. Something like `1550 / 1260 / 1650` or with their labels like `2s: 1550 / 3s: 1260 / RBGs: 1650` would be sufficient.

I've looked for other addons that can do this, but there don't seem to be any that will show me arena ratings of all my characters.

Could probably use GetPersonalRatedInfo API call, but having never written a WoW addon myself I'll have to defer to the experts.

**Comment by LiangYuxuan** [comment]
Currently RBG ranking is tracked. You can find it by hovering on character names. 2v2 and 3v3 will be added in next alpha version.
