### ISSUE TITLE
Tracking The Hunt

### ISSUE THREAD

**Issue by shmehway** [SavedInstances/SavedInstances#462]
It would be excellent to have a tracker for the bi-weekly Hunt event in The Maw, similar to how N'zoth Invasions worked in 8.3

Additionally, sometimes after looting The Great Vault, my Mythic Key Best will still show a (?).

**Comment by LiangYuxuan** [comment]
Beastwarrens Hunts will be tracked in next alpha version. Mythic Key Best is fixed in v9.0.5.
