### ISSUE TITLE
Callings row not shown if all callings completed for all characters

### ISSUE THREAD

**Issue by FlyingDiver** [SavedInstances/SavedInstances#464]
First screenshot from this morning before reset.  Second from after reset.  All four characters had completed all callings, but the callings aren't shown at all.  I would have expected three green checkmarks for each character.

<img width="439" alt="Screen Shot 2021-01-27 at 9 51 08 AM" src="https://user-images.githubusercontent.com/72976/106013068-1ccecb80-608a-11eb-8290-663893a90587.png">
<img width="432" alt="Screen Shot 2021-01-27 at 10 02 11 AM" src="https://user-images.githubusercontent.com/72976/106013090-20625280-608a-11eb-9145-bbf0b14c69ad.png">

**Comment by LiangYuxuan** [comment]
Duplicated #444
