### ISSUE TITLE
The Maw Weeklies

### ISSUE THREAD

**Issue by xhunt3rGhost** [SavedInstances/SavedInstances#465]
**Hello Team,**

Stating SL, I remember to see The Maw weeklies in the Weekly tab of your addon, however, I don't see it anymore, i tried to change the configurations (in case that's the issue) but i did not find any configuration regard this and i tried to find some solution in the web, but no results.
So, is there any reason to eliminate it to the weekly activities done? or if am wrong, is something you can add in the future? 

In addition, is possible to add on the tooltip, if the toon already complete the Jailer Hunt and the Beastwarrens Hunt?

Thanks in advance, and nice job :)

**Comment by LiangYuxuan** [comment]
Weeklies are marked daily by blz at the beginning of season, and now without any mark. It'll be added in next alpha version, so do Beastwarrens Hunt.

Warth of the Jailer is now tracked in World Boss.
