### ISSUE TITLE
Add Npc's

### ISSUE THREAD

**Issue by Imiona** [SavedInstances/SavedInstances#466]
**Is your feature request related to a problem? Please describe.**
Tracking Darkmoon Kills (Rabbit/Moonfang)

**Describe the solution you'd like**
Add these 2 Npc's to SI

**Describe alternatives you've considered**
A Guide on how to add NPC' s yourself, so i could add them myself, but i dont know how

**Comment by LiangYuxuan** [comment]
Moonfang and Darkmoon Rabbit have no lockout to track since they can be looted every time you see them. Base on wowhead comments.

https://www.wowhead.com/npc=71992/moonfang
https://www.wowhead.com/npc=58336/darkmoon-rabbit
