### ISSUE TITLE
Core script error on login with 9.0.5-12-g37abe07

### ISSUE THREAD

**Issue by TheCheat54** [SavedInstances/SavedInstances#470]
After updating to this alpha version, I get the following error when logging in and cannot open the addon interface after:

Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\Core\Core.lua line 1315:
   bad argument #2 to 'tonumber' (base out of range)

**Comment by LiangYuxuan** [comment]
Fixed in latest alpha, sorry for inconvenience
