### ISSUE TITLE
Weekly Quest Tracking of Shadowlands-activities

### ISSUE THREAD

**Issue by Haxxen** [SavedInstances/SavedInstances#471]
I'm Having the problem that the weekly Oribos PvP-Quests are not tracked consistently.

For Example https://wowhead.com/quest=62637 is not tracked. (That's the one from the bonus weekly event, near the m+vault)

https://wowhead.com/quest=62285 This one is tracked. (Weekly non rated PvP from near the PvP Vendor)

https://wowhead.com/quest=62288 This one is not tracked (Weekly rated PvP Quest[RBG])

So only from this week i would assume, tracking of the rated PVP quest, and the bonus event quest doesn't work. [Edit: Im EU, so  weekly reset is tomorrow for me to stop confusion]

I also find it a bit hard to see on a glance whats left to do this week, because there are 7 weekly and only the ones done are shown. So you need to know all Quests and all names of the quests, that are sometimes hard to differentiate.

I would really love to have a summary of all SL-Weeklys, where you can instantly see whats missing on your toon, like withe Thorgast and the callings. Maybe only like a section with Shadowlands weeklys "x/y" quests done and when you hover it all weeklys are shown greyed out, and the one already done are green, and the ones on which you already have progress are yellow. Maybe differentiate pvp/pve/and weekly event quests.

These are the 7 weeklys im talking about:

2 Trading Favor Quests, Dungeon PVE Quests below the innkeeper.
2 PVP Quests at PvP Vendor. I think its always one for rated and one for nonrated PvP
1 Weekly Eventquest at the great vault, different content every week
2 Renown Quests (souls&anima)  (will go away later in the addon)

I commented on [this issue](https://github.com/SavedInstances/SavedInstances/issues/438) but it was closed directly after, and i think my suggestion on the topic wasnt properly adressed nor read. If its not okay to open another issue for this, then sry.

**Comment by LiangYuxuan** [comment]
SL Weekend Quest list are not updated, still BfA. I've been waiting for entire round and now is time.
RGB quest is an issue as its series are added pre-season so might miss this.
These two will be fixed later today.

But I'm not a big fan of "summary of all SL-Weekly". You see, there are lots of weekly lockouts in the game currently. Not just the quest on your list, but *Against Overwhelming Odds*, Ve'nari Weekly, even The Ember Court.
I think it might be great if the addon allows users to decide which quest should be on the list, but still have some issues on here, like Ve'nari Weekly, addon might have to check if the character is able to access Perdition Hold, which makes weekly quest from 2 to 3.
So, I would like to remain the method the addon tracks weekly quest as is, until one or two weekly quests are so important, like Assaults from Patch 8.3 that forces player to do everytime. Then I'll mark it by Module Progress to make a line for them. But I don't think any quest is so important as these.

**Comment by Haxxen** [comment]
Ok, i see your point, but i think a pvpquests/trading favor/weekly event section would be handy. But when alle the other quests are tracked correctly, it still does the job. 

Personal weekly tracking would also be nice. Even nicer that a predetermined overview.

Thanks anyways for considering it!
