### ISSUE TITLE
Mythic Key Best

### ISSUE THREAD

**Issue by niketa-wow** [SavedInstances/SavedInstances#473]
**Describe the bug**
The broker tooltip doesn't display Mythic Key Best for any of my toons, despite having run multiple m+ on each of them each week. I'm not sure if I'm misunderstanding what this is or if a setting of mine got messed up, but in BFA it showed the highest level keystone completed for the week.

**Do you have an error log of what happened?**
No errors, just nothing shows up, as if no key was completed.

**To Reproduce**
1. Hover over the broker icon
2. No keys display next to Mythic Key Best, even if I've completed keys that week

**Screenshots**
![image](https://user-images.githubusercontent.com/58258335/107356310-3f9fad80-6a96-11eb-9a23-dfdbd64f10e6.png)
This week on the monk I've done a 10 and 11. The priest has done 10, 12, 14, 15 and druid has done 2, 4, 7, 8, 9, 10. Yet as you see in the screenshot, it looks like I haven't done any keys.

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of SavedInstances are you using?**
9.0.5

**Was it working in a previous version? If yes, which was the last good one?**
I don't think I've seen it work in Shadowlands at all.

**Additional context**
At some point at the end of BFA a bad kick to power strip messed up my entire UI and all of my addon settings got wiped. So it's possible that something I used to have enabled to track this got disabled, but I've looked over the settings and nothing is popping out at me right away.

**Comment by LiangYuxuan** [comment]
Please try latest alpha.

**Comment by niketa-wow** [comment]
I tried with v 9.0.5-18-g64e7b2c and still nothing shows up. Not sure if this is the latest or not, but it's the last one I found on Curse.

**Comment by LiangYuxuan** [comment]
Would you try this macro on your character and replay what it prints?

```
/dump SavedInstances[1].db.Toons[SavedInstances[1].thisToon].MythicKeyBest
```

**Comment by niketa-wow** [comment]
empty result

**Comment by niketa-wow** [comment]
From what I can see since then, it seems to be working.
