### ISSUE TITLE
character from realm transfer still appearing

### ISSUE THREAD

**Issue by DurkMC** [SavedInstances/SavedInstances#475]
**Describe the bug**

the character from realm a to be deleted and realm b to be there instead but now their both there
**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no
**Which version of SavedInstances are you using?**
9.0.5
**Was it working in a previous version? If yes, which was the last good one?**
i dont know
**Additional context**
i realm transferred and now the character from previous realm still shows with the current realm one

**Comment by LiangYuxuan** [comment]
You can delete your old character in SI settings. It's not possible for addons to tell if a character is deleted or transfered.
