### ISSUE TITLE
In game is showing out-of-date but CurseForge says it is the latest version.

### ISSUE THREAD

**Issue by Meltun** [SavedInstances/SavedInstances#481]
**Describe the bug**

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by FlyingDiver** [comment]
You haven't updated the SavedInstances.toc.  Should be:

`## Interface: 90002`

**Comment by Meltun** [comment]
Will do, thanks for reply.
