### ISSUE TITLE
Highest average item level display

### ISSUE THREAD

**Issue by TheSoulRender** [SavedInstances/SavedInstances#487]
I'm an altoholic, hence why I use this amazing addon. But I never have in mind the item level of my alts, which makes planning for raids/mythic+ quite difficult.

Would it be possible to have a simple button in the menu adding a line similar to currencies, displaying the maximum average item level of your character?

Thanks a lot for the hard work !

**Comment by LiangYuxuan** [comment]
You can hover on your character name to check your iLvl.

**Comment by TheSoulRender** [comment]
Oh my god ! Sorry for the waste of time ! I never realized you could hover over the names >< I'm an idiot. Keep up the great work !!
