### ISSUE TITLE
New Error - 03/31/21

### ISSUE THREAD

**Issue by OldWorldRaiders** [SavedInstances/SavedInstances#495]
**Describe the bug**
Hello, I used Jaina's Locket inside of the Molten Core (At Golemagg) and received this error.

**Do you have an error log of what happened?**
Message: Interface\AddOns\SavedInstances\Modules\Calling.lua:60: attempt to index field '?' (a nil value)
Time: Wed Mar 31 10:01:36 2021
Count: 6
Stack: Interface\AddOns\SavedInstances\Modules\Calling.lua:60: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\SavedInstances\Modules\Calling.lua"]:60: in function `?'
[string "@Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of SavedInstances are you using?**
9.0.7

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by LiangYuxuan** [comment]
Fixed in e8c786961b537e97ae2396ff4f2faade082cd071, please try out latest alpha.
