### ISSUE TITLE
Delete characters 

### ISSUE THREAD

**Issue by Burayanu** [SavedInstances/SavedInstances#498]
**Describe the bug**
I have deleted characters still showing in the addon 

**Do you have an error log of what happened?**
Nop since it does not make the addon crash or anything

**Screenshots**

![Screenshot_657](https://user-images.githubusercontent.com/44420263/114682328-44d7dd80-9d0f-11eb-96b5-897f322a052a.png)

**Which version of SavedInstances are you using?**
9.0.7

**Was it working in a previous version? If yes, which was the last good one?**
Some were getting deleted but the ones shown on the screenshot are around 5 month old

**Additional context**
Just wanted to add that i love your addon !

**Comment by LiangYuxuan** [comment]
You can delete them in `Character` in SI's setting.
