### ISSUE TITLE
Currencies with seasonal limit show wrong value for "max value" in tooltip

### ISSUE THREAD

**Issue by cremor** [SavedInstances/SavedInstances#499]
**Describe the bug**
If you hover over a currency with a seasonal limit (e.g. Valor) in the LDB tooltip, the currency tooltip shows the current value instead of the total value for the "max value" line that is added by SavedInstances.

**Do you have an error log of what happened?**
No error

**To Reproduce**
Hover over "Valor" in the LDB tooltip.

**Screenshots**
![WoWScrnShot_041821_102136](https://user-images.githubusercontent.com/116314/115139031-f76db000-a02f-11eb-99dd-622a6002c49f.jpg)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of SavedInstances are you using?**
9.0.7

**Was it working in a previous version? If yes, which was the last good one?**
No.

**Additional context**
I've debugged this a bit and it seems like you aren't handling all the data returned from `C_CurrencyInfo.GetCurrencyInfo()`. There is a flag `useTotalEarnedForMaxQty` and a `totalEarned` value which seem to be used by the Blizzard tooltip. But both is not used by SavedInstances.

Why does SavedInstances even add an additional line here? That information is already given by the Blizzard default tooltip.
Maybe related: `CURRENCY_SEASON_TOTAL` is not correct to find the season total line in the tooltip. At least not in the German WoW client. The value of that constant is "Insgesamt in dieser Saison erhalten: %s%s" but as you can see in the screenshot above the line added by Blizzard has a different text ("Saisonmaximum").

Not related to the currency tooltip, but for the LDB tooltip in general:
I'd argue that showing the seasonal maximum there at all is wrong. I'd just show the current value there and leave both total earned and seasonal maximum only in the currency tooltip.

**Comment by LiangYuxuan** [comment]
`totalEarned` is handled in latest alpha which is committed in 6b7ecf5. However, SI scans the currency tooltip and put the content into the hover tooltip, which includes current login character's info. This should be fixed.
