### ISSUE TITLE
attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Kvasi** [SavedInstances/SavedInstances#500]
Message: Interface\AddOns\SavedInstances\Modules\Calling.lua:60: attempt to index field '?' (a nil value)
Time: Sat Apr 24 09:01:40 2021
Count: 5
Stack: Interface\AddOns\SavedInstances\Modules\Calling.lua:60: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\SavedInstances\Modules\Calling.lua"]:60: in function `?'
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by LiangYuxuan** [comment]
Fixed in e8c786961b537e97ae2396ff4f2faade082cd071, please try out latest alpha.
