### ISSUE TITLE
on a new character Torghast was not recorded

### ISSUE THREAD

**Issue by Vjordian** [SavedInstances/SavedInstances#504]
I ran 2xL8 on my priest Torghast today. Both runs are not listed.
Are there any requirements to record Torgahst (fame or story section?)

I have reinstalled the addon and then also reinstalled it once including deleting the WTF files from SavedInstances. Unfortunately it is still not displayed.
But as you can see in the screenshot I already have Soul Ash.. :(

![image](https://user-images.githubusercontent.com/83249866/116153740-16cba380-a6e8-11eb-8ffc-2a1c64db4156.png)

Version 9.0.7 in use.

**Comment by LiangYuxuan** [comment]
Torghast is tracked after quest [Into Torghast](https://www.wowhead.com/quest=60136/into-torghast) is completed, which rewards *Access to Torghast*. Would you try `/dump C_QuestLog.IsQuestFlaggedCompleted(60136)` and check if it's completed?

**Comment by Vjordian** [comment]
Hey LiangYuxuan,

3hours before you wrote this I Starter to do some Story Quest including Info Torghast ans yea, my "Bug" was Just the Missing Quest Part.

Nö everything ist shown fine.

Thanks for the fast answer.

Greetings Vjordian
Am 27. Apr. 2021, 04:28 +0200 schrieb LiangYuxuan ***@***.***>:

Torghast is tracked after quest Into Torghast<https://www.wowhead.com/quest=60136/into-torghast> is completed, which rewards Access to Torghast. Would you try /dump C_QuestLog.IsQuestFlaggedCompleted(60136) and check if it's completed?
