### ISSUE TITLE
Progress.lua:431: attempt to index local 'prev' (a nil value)

### ISSUE THREAD

**Issue by Tiiara** [SavedInstances/SavedInstances#507]
**Describe the bug**
Whenever I log in or use a teleport / portal / hearthstone or somesuch I get the following error msg:

**Do you have an error log of what happened?**

22x SavedInstances\Modules\Progress.lua:431: attempt to index local 'prev' (a nil value)
[string "@SavedInstances\Modules\Progress.lua"]:431: in function 'OnWeeklyReset'
[string "@SavedInstances\Core\Core.lua"]:1408: in function 'UpdateToonData'
[string "@SavedInstances\Core\Core.lua"]:2570: in function <SavedInstances\Core\Core.lua:2566>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function 'Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

1x SavedInstances\Modules\Progress.lua:431: attempt to index local 'prev' (a nil value)
[string "@SavedInstances\Modules\Progress.lua"]:431: in function 'OnWeeklyReset'
[string "@SavedInstances\Core\Core.lua"]:1408: in function 'UpdateToonData'
[string "@SavedInstances\Core\Core.lua"]:3450: in function 'ShowTooltip'
[string "@SavedInstances\Core\Core.lua"]:2531: in function <SavedInstances\Core\Core.lua:2529>
[string "@Titan\LDBToTitan.lua"]:327: in function <Titan\LDBToTitan.lua:286>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ShowTooltip = <function> defined @SavedInstances\Modules\Progress.lua:478
 defaultModuleLibraries = <table> {
 }
 UpdateAll = <function> defined @SavedInstances\Modules\Progress.lua:368
 BuildOptions = <function> defined @SavedInstances\Modules\Progress.lua:442
 GetName = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "SavedInstances_Progress"
 TrackedQuest = <table> {
 }
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 OnWeeklyReset = <function> defined @SavedInstances\Modules\Progress.lua:421
 SetDefaultModuleState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 questMap = <table> {
 }
 SetEnabledState = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 OnDailyReset = <function> defined @SavedInstances\Modules\Progress.lua:400
 enabledState = true
 baseName = "SavedInstances"
 RegisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Disable = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 OnEnable = <function> defined @SavedInstances\Modules\Progress.lua:361
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 IterateModules = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 NewModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 defaultModuleState = true
 SendMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 moduleName = "Progress"
 UnregisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 QuestEnabled = <function> defined @SavedInstances\Modules\Progress.lua:454
}
toon = "Anastasìia - Antonidas"
t = <table> {
 Paragon = <table> {
 }
 IL = 177.437500
 LastSeen = 1593548630
 Emissary = <table> {
 }
 Class = "MAGE"
 WeeklyResetTime = 1619593199
 Progress = <table> {
 }
 DailyResetTime = 1619679599
 Race = "Human"
 oRace = "Human"
 Warmode = false
 LClass = "Mage"
 Level = 110
 XP = 10452
 RBGrating = 0
 MythicKeyBest = <table> {
 }
 RestXP = 806332
 MythicKey = <table> {
 }
 Zone = "Nagrand"
 Money = 4596409748
 Order = 50
 currency = <table> {
 }
 PlayedTotal = 353254
 Show = "saved"
 MaxXP = 537730
 PlayedLevel = 188524
 Faction = "Alliance"
 ILe = 151.750000
 Skills = <table> {
 }
 Quests = <table> {
 }
 isResting = false
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 =  <ta

----------------------------------------------------------------

**To Reproduce**
1. Log In
2. Error shows up
3. Use hearthsone
4. Error shows up
5. Hover over the SavedInstances options in Titan Panel
6. Error shows up
5. etc.

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of SavedInstances are you using?**
SavedInstances-9.0.7-10-g2446c91.zip

**Was it working in a previous version? If yes, which was the last good one?**
Yes. First time I got this error. Monday was still fine.

**Comment by LiangYuxuan** [comment]
I find your error line is in old version of SI. You might need to reload after update.

**Comment by prg** [comment]
Phew, for a minute there I thought my changes were causing this. Anyhow, can confirm your changes in 2446c91 fix this.

**Comment by Tiiara** [comment]
Can confirm, seems. It needed a complete restart . Error msg is gone now.
