### ISSUE TITLE
Feature requests (Covenant Campaign & Calling Renown)

### ISSUE THREAD

**Issue by Epi1278** [SavedInstances/SavedInstances#508]
Hello!

If there is a way to implement covenant campaign tracking ( x / 9 ), this would be an excellent feature to help manage where alts are at for their campaign.
With callings, it'd also be great if it's possible to be able to tell if the calling you have picked up on an alt will award renown or not.

Thanks in advance!

**Comment by LiangYuxuan** [comment]
Calling always gives renown if catch-up is active now. Campaign, or questline progress tracking is not what SI is for.
