### ISSUE TITLE
should we publish to Wago Addons?

### ISSUE THREAD

**Issue by jokeyrhyme** [SavedInstances/SavedInstances#511]
> Hey! I wanted to reach out to chat with you about a new project we have rolled out at wago. I'm sure you have seen our public announcements. Feel free to ping me on discord or shoot me an email. REDACTED We would love to get your addon uploaded https://addons.wago.io/ - We support the bigwigs packager as well. https://docs.wago.io/#bigwigs-packager

- https://addons.wago.io/

**Comment by LiangYuxuan** [comment]
Sounds good to me 👍

**Comment by Stanzilla** [comment]
Yeah sounds good to me as well

**Comment by Stanzilla** [comment]
@jokeyrhyme looks like I don't have enough permissions on Github to create it over there

**Comment by jokeyrhyme** [comment]
![image](https://user-images.githubusercontent.com/479816/119891568-7a155380-bf7c-11eb-96c7-0f7d319b36c0.png)

That's weird, I don't have the Settings button for this repository

Anyone know who does? Is it definitely GitHub permissions or is it CurseForge or something else?

**Comment by Stanzilla** [comment]
I think @eTzmNcbkrng is the owner

**Comment by Stanzilla** [comment]
Nevermind, figured it out, here we go https://addons.wago.io/addons/savedinstances

**Comment by Stanzilla** [comment]
Let me know where I can send you guys an invite link to the wago group

**Comment by jokeyrhyme** [comment]
Thanks: jokeyrhyme@jokeyrhy.me (same email as on my GitHub profile) 

Good to double-check though :)

**Comment by LiangYuxuan** [comment]
lyx@lyx.es, also it would be great if I would be invited on curseforge as well ;)

**Comment by Stanzilla** [comment]
Sent to you both!

@LiangYuxuan For CF you have to ask @jokeyrhyme for an invite, I'm only "Author" there.

**Comment by jokeyrhyme** [comment]
Happy to add you @LiangYuxuan , just let me know what your CurseForge username is (I don't think it takes email addresses)

It'll probably end up being your twitch.tv username :shrug:

**Comment by LiangYuxuan** [comment]
`rhyster0`, and its display name `Rhyster0` for double check.

**Comment by jokeyrhyme** [comment]
Should be done now :)

**Comment by jokeyrhyme** [comment]
Kinda' wish there was a way to keep the membership synchronised between GitHub project/org, CurseForge project, and now Wago project
