### ISSUE TITLE
Callings not being tracked properly

### ISSUE THREAD

**Issue by Azerate2021** [SavedInstances/SavedInstances#512]
**Describe the bug**
Callings are not tracked properly. They remain shown as ? or ! or 0% (whichever one applies) for characters that I have completed the calling on after relogging to an alt. The only way to 'fix this' is to specifically mouseover the SavedInstances icon after turning in the calling.

As a result, whenever I forget to mouseover the icon before logging out, the addon gives me the impression that my callings are either unfinished, or that I forgot to turn them in. This gets fixed once I log the character in question and mouseover the icon.

**To Reproduce**
1. Do not mouseover the SavedInstances icon
2. Complete a calling and turn it in
3. Relog to another character
4. Mouseover the icon and the calling is still listed as incomplete. If you haven't moused over since starting the calling, it will show 0% as well. It seems as it only checks for callings once you mouseover it.

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I do not use ElvUI, nor any kind of full-UI addon. I have lots of utility addons that I haven't tried turning off yet because it would be too much hassle.

**Which version of SavedInstances are you using?**
Newest one from WoW Up app.

**Was it working in a previous version? If yes, which was the last good one?**
Not sure tbh. I didn't have that many alts until a while ago at 60, so I didn't really need the tracking for this that much. I do believe it used to work previously, but I can't say for sure.

**Comment by LiangYuxuan** [comment]
It's limited by Blizzard's API, as it reports wrong Calling quest info after turning in quest, or just loging in. Mouseover the SavedInstances icon will force SI to refresh and get the correct info.
