### ISSUE TITLE
Adventure table campaign progress going beyond max (20) after swapping covenant

### ISSUE THREAD

**Issue by nullValueReturned** [SavedInstances/SavedInstances#514]
![image](https://user-images.githubusercontent.com/47422133/122716796-04df2a80-d26b-11eb-8f8c-0e92c1524f83.png)
After having been a NF i swapped my main over to venthyr and started leveling followers etc there. Progress is now counted from where i ended my progress as a NF (which was 20).

Thanks for this addon. Legit one of the best addons i use.

**Comment by LiangYuxuan** [comment]
Adventure Campaign Progress is a hidden currency, and SI just get the quantity and show it, no magic inside. I'm sorry but there is not possible to tell the progress get in current covenant as Blizzard won't give us one.
