### ISSUE TITLE
Add Profiles option

### ISSUE THREAD

**Issue by SiderealDay** [SavedInstances/SavedInstances#515]
The issue is not a bug, but an inconvenience.

At the moment, it seems that every change I make to the addon settings -including the keybind- will have to be remade manually on every one of my alts.
So, it would be really helpful to add a "Profiles" option to store changes globally, or per character if one prefers.

**Comment by SiderealDay** [comment]
hmm It seems I had to do that only on 2 alts, but the settings are saved for the other alts?

**Comment by LiangYuxuan** [comment]
SI saves settings globally. If you encounter different settting on alt, you might want to fill the bug report form.
