### ISSUE TITLE
Wild hunt paragon tracking has wrong faction ID

### ISSUE THREAD

**Issue by DeeRez** [SavedInstances/SavedInstances#517]
Wild hunt paragon chests aren't being tracked because it has the incorrect ID. The Wild hunt is faction ID 2465, but the addon is tracking faction ID 2432, which is the ID for Ve'nari in the maw.

**Comment by LiangYuxuan** [comment]
Yea, it will be fixed in #513 a44839f41410cc21a9fe57e98ff1b5ccd1e3b92f
