### ISSUE TITLE
covenant assault tracking

### ISSUE THREAD

**Issue by haegensnico** [SavedInstances/SavedInstances#519]
I would like you to add tracking on which alt I did my covenant assault on.  It's not being tracked in the weekly or daily quests tracker. I think the following page contains links to the individual assault quests:
https://www.wowhead.com/achievement=15000
I currently got 8 chars doing the assaults on twice every week and leveling some more chars.

**Comment by fzarr** [comment]
Tracking Tormenters of Torghast event would be great too :)

**Comment by AshleyRawls** [comment]
This is also what I came to request (Assault + Tormenters)
Thank you!

**Comment by agentschmitt** [comment]
for tornments there is an open pr already https://github.com/SavedInstances/SavedInstances/pull/522
i patched my savedinstances with this changes and it woks :)

**Comment by srenauld** [comment]
The PR I sent in was merged, so I guess it will show up soon in addons. It's only for tormentors - I'm collecting quest IDs for the assaults.

**Comment by prg** [comment]
According to wowhead, the first three should be `63824`, `63543` and `63823`.
([Kyrian](https://ptr.wowhead.com/quest=63824/kyrian-assault), [Necrolord](https://ptr.wowhead.com/quest=63543/necrolord-assault) and [Night Fae](https://ptr.wowhead.com/quest=63823/night-fae-assault))

For the Venthyr assault, wowhead has [two entries](https://ptr.wowhead.com/item=185990/harvesters-war-chest), `63822` and `64554`. The assault should be up for EU until Tuesday, I guess I can verify this tomorrow.
