### ISSUE TITLE
Saved instances not showing ingame

### ISSUE THREAD

**Issue by Castamage** [SavedInstances/SavedInstances#520]
Hey greetings 

not entirely sure if it is a bug or not 

but when i instal the addon Saved instances and yes i installed it properly

it shows in my curseforge
it shows in my addon folder 
and it shows in my addon folder ingame on the character screen

but here comes the best bit 

when im actually ingame 
it is like the addon is not there at all like it never existed
it doesnt show up at all it doesnt even show with the command /SI 

its litterly like it doesnt wanna work 

im speaking for TBC classic ofcourse but it should be working right? or am i really that wrong here?

**Comment by Castamage** [comment]
if it is because its completely updated for retail purpose

then please can someone link me the TBC version of it so i can use it for that version of the game

thanks

**Comment by haegensnico** [comment]
The framework Blizzard built for TBC is most probably different than the one for the live version, so there would have to be a seperate version for TBC and afaik, there isn't one. You should check addons that are written specificially for TBC.

**Comment by LiangYuxuan** [comment]
Discussed in #313
