### ISSUE TITLE
Track Shadowlands Maw Assault Quests

### ISSUE THREAD

**Issue by tfmonk** [SavedInstances/SavedInstances#524]
**Is your feature request related to a problem? Please describe.**
Keeping track of which assaults have been completed on alts can be annoying and requires logging into multiple character to check map

**Describe the solution you'd like**
option for showing if the current maw assault has been completed along with name of assualt

**Additional context**
Quest progress can be tracked using below. 
/run print(C_QuestLog.IsQuestFlaggedCompleted(XXXXX)) 
63824 - Kyrian
63823 - Night Fae
63822 - Venth
63543 - Necro

**Comment by LiangYuxuan** [comment]
Added in 1aaa0d3717c58cae35ab6b928c1d1b72ef6cc7f3. Please try latest alpha.
