### ISSUE TITLE
Sanctum of Domination lockout info

### ISSUE THREAD

**Issue by TreizeEU** [SavedInstances/SavedInstances#538]
When I mouse-over the raid lockout display in SavedInstances for the new raid, it say "Boss kill information is missing for this lockout. This is a Blizzard bug affecting certain old raids.".

Reloading UI seems to temporarily fix it, until I kill a new boss?

**Which version of SavedInstances are you using?**

9.1.2-3-g629ce65

**Was it working in a previous version? If yes, which was the last good one?**

Appears to work with version 9.1.2-2-ga9bcb7e.
Or I can't tell now since I've reloaded my UI since downgrading and upgrading a few times.

![WoWScrnShot_072321_223728](https://user-images.githubusercontent.com/57756419/126841441-b5e3a453-eb48-4523-aa1a-fdb886d0109d.jpg)

**Comment by TreizeEU** [comment]
Is this not fixable, or why has nobody replied to this ticket yet?

**Comment by Yarvillian** [comment]
Having the same problem.

**Comment by LiangYuxuan** [comment]
Might need more investigation on this. If your lockout is missing boss info on tooltip, please try following steps:

1. Click your DifficultyString like "6/10" in SI's tooltip, then it will be a link in your chat input
2. Add a pair of quotes and /dump to the very head, it will be like /dump "[Sanctum of Domination]"
3. Press Enter and post what you get here

And sorry for late reply, quite busy in recent months.

**Comment by TreizeEU** [comment]
Thank you for finally responding.

It seemed to me to be quite random, and I don't regularly raid anymore this patch. We'll see if I can pug a normal on my hunter tonight or something.

**Comment by Yarvillian** [comment]
Dump: value="[Sanctum of Domination]"
[1]="|cffff8000|Hinstancelock:Player-60-06570EC1:2450:16:359|h[Sanctum of Domination]|h|r"

Its ok! Real life comes first! Theres my /dump

**Comment by LiangYuxuan** [comment]
I tried to reproduce but failed. Might need more data to found the source of the issue.

**Comment by TreizeEU** [comment]
I tried to pug the raid on normal on my hunter but never got into any groups that I signed up for, so I gave up. And now there's new things to do, not much time to try and pug normal Sanctum on even my main. :(

**Comment by LiangYuxuan** [comment]
Let's wait 'til next week and see if this can be reproduced in Sepulcher of the First Ones, then we can get more data to fix this.

**Comment by TreizeEU** [comment]
Aye, I will do a /dump of the lockout in the new raid, should it happen for that raid as well.

**Comment by Yarvillian** [comment]
Error occured in the new raid as well. Unsure if you want a new issue but leaving it here as was asked.
This is normal dump:
Dump: value=[Sepulcher of the First Ones]
Dump: ERROR: [string "return |Hinstancelock:Player-60-06570EC1:2481:14:1467..."]:1: unexpected symbol near '|'

Heroic Dump:
Dump: value=[Sepulcher of the First Ones]
Dump: ERROR: [string "return ..."]:1: unexpected symbol near '|'
