### ISSUE TITLE
Show ilvl of alts

### ISSUE THREAD

**Issue by Erelyes** [SavedInstances/SavedInstances#544]
**Is your feature request related to a problem? Please describe.**
It'd be nice to have a reminder of what the ilvl of the various alts are when showing the tooltip.

**Describe the solution you'd like**
It would be handy to have a toggle option to show ilvl of alts. 
Perhaps have the option of either showing next to charactername, or as a separate row.
Perhaps also have the option of either showing just the equipped ilvl, or the equipped / bags ilvl (like Blizz does)

**Comment by LiangYuxuan** [comment]
You can hover on character name and find ilvl :)
