### ISSUE TITLE
Timewalking quest check during timewalking events

### ISSUE THREAD

**Issue by m33shoq** [SavedInstances/SavedInstances#546]
Would be cool to see a feature that tracks if quest for 500 Timewarped Badges completed.
These quests can only be completed during event specific for expansion, they are rewarded with items that drops in the end of timewalking run.
There is a list for these quests
For TBC timewalking https://www.wowhead.com/quest=40168/the-swirling-vial
For WoTLK  timewalking https://www.wowhead.com/quest=40173/the-unstable-prism
For Cata (Alliance) https://www.wowhead.com/quest=40787/the-smoldering-ember
For Cata (Horde) https://www.wowhead.com/quest=40786/the-smoldering-ember
For MoP https://www.wowhead.com/quest=45563/the-shrouded-coin
For WoD (Alliance) https://www.wowhead.com/quest=55498/the-shimmering-crystal
For Wod (Horde) https://www.wowhead.com/quest=40786/the-smoldering-ember
Sometimes after passing a timewalking run I can forget to complete quest, so would be cool if addon could track an item in bags and show that you can complete quest that you missed.

**Comment by LiangYuxuan** [comment]
They're currently tracked in Weekly Quests. About item tracking, I'm not a big fan of it.
