### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by vKryptic** [SavedInstances/SavedInstances#550]
I don't get any errors or any reaction from mouse over or left-click. right-click will open the options panel but other than that it doesn't work since 9.1.5 drop

Never reported a bug before so I don't know if this is helpful or not

Keep up the good work!

**Comment by archxlock** [comment]
It doesn't work for me either, even trying the lua changes mentioned in the previous thread. Nothing happens when left clicking on the mini map button, and even the slash command does not open the UI.

**Comment by Seguaro** [comment]
Same issue. Seems to be related to the 9.1.5 patch release.

**Comment by archxlock** [comment]
@vKryptic - downloading https://www.curseforge.com/wow/addons/libqtip-1-0 resolved the issue for me.

**Comment by JoAnnNoted** [comment]
Same issue. Worked just fine BEFORE 9.1.5 patch release. Have tried all recommended ways to open. Hope you can fix it. Would prefer to have your solution to the problem over the libqtip-1-0 solution mentioned by archxlock.

**Comment by Seguaro** [comment]
Just installed the updated LibQtip-1-0 and it now works for me as well. It also fixed other Chocolate Bar data broker plugins that I was have issues with since the patch drop. Thanks for the fix.
