### ISSUE TITLE
/si show does nothing (same with keybind)

### ISSUE THREAD

**Issue by igorrebolj** [SavedInstances/SavedInstances#551]
/si show does nothing (same with keybind)
Addon version 9.1.4

This is what i get when tracking lua errors in case it helps solving:

Message: ...dOns\MountCollector\libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Wed Nov  3 21:50:10 2021
Count: 1
Stack: ...dOns\MountCollector\libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function `origErrorHandler'
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `GetBackdrop'
[string "@Interface\AddOns\MountCollector\libs\LibQTip-1.0\LibQTip-1.0.lua"]:543: in function <...dOns\MountCollector\libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@Interface\AddOns\MountCollector\libs\LibQTip-1.0\LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3454: in function `ShowTooltip'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3341: in function `ShowDetached'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3291: in function `ToggleDetached'
[string "SAVEDINSTANCES"]:1: in function <[string "SAVEDINSTANCES"]:1>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Comment by Stanzilla** [comment]
Are you sure you are on 9.1.4 because that fixed the issue?

**Comment by igorrebolj** [comment]
## Interface: 90105
## Title: SavedInstances
## Notes: Tracks Raid, Instance, World Boss lockouts for all your characters, daily/weekly quests, currencies, trade cooldowns, and more!
## Author: oscarucb and the Saved Instances Community
## Version: 9.1.4
## X-ReleaseDate: 2021-11-03T19:19:52Z

**Comment by igorrebolj** [comment]
After further investigation it seems to work when disabling mount collector, heads up if other people use same combo and have issues.
