### ISSUE TITLE
Renown & Anima datatext for every Covenant

### ISSUE THREAD

**Issue by Nokramx** [SavedInstances/SavedInstances#552]
Currently you are only able to see the Renown level and the Anima amount from your currently active Covenant. 

With the 9.1.5 changes it would be nice to see this data also for the 3 other covenants, i imagined a tooltip if you mouseover the appropriate datatexts.

**Comment by Galthariel** [comment]
It will be awesome if instead of seeing only the current Covenant Renown we can see how much Renown we have with all other Covenants
