### ISSUE TITLE
Characters Ilevels

### ISSUE THREAD

**Issue by G1ak1** [SavedInstances/SavedInstances#553]
Hey there. Amazing addon but if i am not blind it misses one thing. Show characters ilevel for every character :)

if that is possible it will be amazing if u can add it.,

thanks in advance

**Comment by Nokramx** [comment]
you need to mouseover your characters name at the top, then you will see each characters item level.

**Comment by G1ak1** [comment]
i see ok.thank u. but can u add an option to make ilevel visible below every character maybe? easier to see all alts ilevel rather than mousovering every one seperately.
