### ISSUE TITLE
Torghast not tracked

### ISSUE THREAD

**Issue by keypulse** [SavedInstances/SavedInstances#554]
**Describe the bug**
Ran torghast layer 12, one of the wings (can't remember which, I actually rely on SI to tell me!).  I expected to see either the usual 12 / 0 or 0 / 12, but it persists to say 0/0.  A reload of the UI, leaving the zone, WeeklyRewardsFrame:Show() attempt to trigger some sort of refresh, logging out and back in cannot fix this.  It may have something to do with 9.1.5 having repeatable torghasts for unlimited cinders/ash.

**Do you have an error log of what happened?**
There is no error reported, it is just simply not tracking it.

**To Reproduce**
1. Run a torghast, either wing
2. Note that SI will still say 0/0 when completed, logged out/in, reload, etc.
--> 

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, issue not related to other addons.

**Which version of SavedInstances are you using?**
9.1.4

**Was it working in a previous version? If yes, which was the last good one?**
Yes, but that was also prior to WoW 9.1.5

**Additional context**
I appreciate you and your work, and this addon! <3

**Comment by LiangYuxuan** [comment]
Could you hover on Torghast icon on map The Maw and screenshot that tooltip?

**Comment by keypulse** [comment]
Ah yes it simply says "available" on both places, likely why it's not tracking nor giving an error:
![tg_available](https://user-images.githubusercontent.com/10053091/140529757-ea7288ee-17fa-4d74-b1e6-9d7ab27ec1d0.jpg)

**Comment by Nokramx** [comment]
It's because you can do torghast on repeat now and still get currency etc. so it's always "available"

**Comment by keypulse** [comment]
Yeah, makes sense - I suppose this should be turned into a feature request, to tell me how many I've completed in what wing, now that it works differently

**Comment by LiangYuxuan** [comment]
Count of wings' completion is more like a stat but not a lockout. I'm interested in if there are still a lockout of AV that we can track if you get your conduit upgraded this week.

**Comment by LiangYuxuan** [comment]
No longer needed.
