### ISSUE TITLE
make ilevels visible below characters names

### ISSUE THREAD

**Issue by G1ak1** [SavedInstances/SavedInstances#555]
Hey. Since u closed the previous request before i got time to reply (and i am not sure if the reply i wrote even comes to you guys after its closed). About the ilevels. If possible make it so we can have the ilevels visible below characters or something. When u have a lot of alts its more handy to instantly see them rather than needing to mousover each char individually.

thank u and sorry for posting again.,

**Comment by Duckwhale** [comment]
Isn't there already an option to display this? Pretty sure I've seen it before, though I can't currently check to make sure it's still there.

Also, don't worry about an issue being closed; that doesn't prevent anyone from commenting and is mostly to help with organizing the development process, by "tagging" issues that aren't currently actionable.

**Comment by G1ak1** [comment]
yeah again i am sorry for posting this. i dont know if there is i checked everywhere so either i am blind or there is no option/it was removed :P

**Comment by LiangYuxuan** [comment]
We have discussed this in #209, and we think ilvl, money are not like the data such as instance lockouts or others. So it'll be a no.
