### ISSUE TITLE
Tracking for Shaping Fate weekly quest...

### ISSUE THREAD

**Issue by Laconia1** [SavedInstances/SavedInstances#573]
**Is your feature request related to a problem? Please describe.**

I can't find anyplace to track the Shaping Fate weekly Korthia renown quest. (questID 63949)

**Describe the solution you'd like**

Add a way to track this that displays the percent quest progress.

**Describe alternatives you've considered**

I was able to tweak my download by adding a few lines in the progress module.  I basically copied the code for The World Awaits and substituted the correct quest ID for Shaping Fate.  This allows me to display a 0/1 output for the quest to see which alts have completed it, but can't figure out a way to show percent progress.

**Additional context**

**Comment by Undeathmetal1717** [comment]
SavedInstances is not showing any way for me to track "Shaping Fate" at all, as of 6/5/22. Please fix?

**Comment by LiangYuxuan** [comment]
> SavedInstances is not showing any way for me to track "Shaping Fate" at all, as of 6/5/22. Please fix?

It's not offically supported but allow users to modify lua files to track, before #541 is done.
