### ISSUE TITLE
Getting LUA Error on hovering over SavedInstanced minimap icon

### ISSUE THREAD

**Issue by MisterT87** [SavedInstances/SavedInstances#574]
Hey Guys first of all: Thanks to all Guys for good work on SavedInstances... :)

I am using SavedInstances 9.2.0 
When hovering over minimap Icon -> I dont get any information but a LUA Error:  [Pastebin](https://pastebin.com/iE66fVr9)

I also get the same LUA Error when clicking on minimap button and I only get a (small) empty window :(

Have a nice start into Patch 9.2 / a nice day :D 
Greetings

**Comment by LiangYuxuan** [comment]
Please try reinstall SI with game closed :)

**Comment by MisterT87** [comment]
Tried but dont fixed the problem :(

But got some more SI errors directly after wow login:
[Pastebin](https://pastebin.com/7kE6TN9u) (4 Lua errors in one pastebin)

**Comment by LiangYuxuan** [comment]
Would you try comment out line 83 in Currency.lua? Like

```lua
  --   2000, -- Motes of Fate
```

**Comment by MisterT87** [comment]
@LiangYuxuan also didnt changed anything :(
same 4 lua errors like in Post 2

**Comment by LiangYuxuan** [comment]
Try this Currency.lua and replace the one at `SavedInstances/Modules/Currency.lua`

[Currency.lua.zip](https://github.com/SavedInstances/SavedInstances/files/8121791/Currency.lua.zip)

**Comment by MisterT87** [comment]
@LiangYuxuan  This changed something but same behavior like in Post 1

But now I get only 2 (other) Lua errors after wow login:
[Pastebin](https://pastebin.com/vYbqEenm)

And thx for your help :)

btw: I hope this doesnt matter ->
Its a new (fresh) installed WoW
I am on (fresh) on Windows 11 :)

**Comment by LiangYuxuan** [comment]
Do you play WoW at EU region?

**Comment by MisterT87** [comment]
@LiangYuxuan yes -> maintenance for patch 9.2 coming in an hour

**Comment by LiangYuxuan** [comment]
Version 9.2.0 is for Patch 9.2 and we have some new currencies added, where the issue is caused. You need to use version 9.1.5 before the patch arrived.
