### ISSUE TITLE
Patterns Within Patterns finished, the markings are unchanged.

### ISSUE THREAD

**Issue by Humwq** [SavedInstances/SavedInstances#584]
法则中的法则，完成后，还是标示的叹号。改成绿色勾号更好。
The law in the law, when finished, is still marked with an exclamation point. change it to a green check mark is better.

**Comment by Humwq** [comment]
![图片](https://user-images.githubusercontent.com/9313456/158558906-774faafe-916c-4db8-bb96-8518cd678408.png)

**Comment by LiangYuxuan** [comment]
Which version of SI you're using?

**Comment by Humwq** [comment]
## Interface: 90200
## Title: SavedInstances
## Notes: Tracks Raid, Instance, World Boss lockouts for all your characters, daily/weekly quests, currencies, trade cooldowns, and more!
## Author: oscarucb and the Saved Instances Community
## Version: 9.2.1
## X-ReleaseDate: 2022-02-28T09:00:52Z
## X-License: All Rights Reserved
## X-Category: Raid
## X-LoadOn-Always: delayed
## X-Curse-Project-ID: 13998
## X-Wago-ID: RaN0W3Gj
## OptionalDeps: Ace3, CallbackHandler-1.0, LibDataBroker-1.1, LibDBIcon-1.0, LibQTip-1.0
## SavedVariables: SavedInstancesDB
## LoadManagers: AddonLoader

for curseforge.

**Comment by Humwq** [comment]
![图片](https://user-images.githubusercontent.com/9313456/158559927-65e78e73-f2d1-4f35-b233-9b48357cbdad.png)

**Comment by LiangYuxuan** [comment]
The quest id changed when it became weekly. We updated it in e47985c, please try out latest alpha. (Right click and choose alpha in WoWUp can do)
