### ISSUE TITLE
Please add "Sandworn Relic"

### ISSUE THREAD

**Issue by barnosch** [SavedInstances/SavedInstances#587]
**Describe the solution you'd like**
Please add "Sandworn Relic" currency
https://www.wowhead.com/item=190189/sandworn-relic

NPC Rafiq
https://www.wowhead.com/npc=185587/rafiq
in Zereth Mortis sells some 246 items for this currency
(the items can be converted to legendaries or transmog gear in the „Creation Catalyst“)

**Comment by LiangYuxuan** [comment]
Duplicate #95, I'm not a big fan of this as BagSync works super great for this.
