### ISSUE TITLE
Fated World boss not displayed

### ISSUE THREAD

**Issue by larryeltee** [SavedInstances/SavedInstances#602]
**Describe the bug**
The world boss revamped with fated affix, as part of the new season 4, are not displayed in the addons, when killed.

**Do you have an error log of what happened?**
No

**To Reproduce**
 

**Screenshots**
N/A

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
The addons works properly and display other world boss kill in Shadowlands (i.e Antros)

**Which version of SavedInstances are you using?**
9.2.3

**Was it working in a previous version? If yes, which was the last good one?**
N/A this is a new patch

**Additional context**
As the world boss kills use Id of the entity, I suppose these new World Boss have new ID, compared to their previous versions

**Comment by 1701NCC** [comment]
Having the same issue. It appears that the Fated version of the world boss doesn't use the same quest ID, the 

/run print(C_QuestLog.IsQuestFlaggedCompleted(61814))

returns false on alts who have completed the world boss so it must have changed from 61814. Not sure how to find the fated quest IDs.

**Comment by LiangYuxuan** [comment]
Any world quest active for the fated world bosses? If so, you can dump the quest id by opening chat input with `/dump ""` and shift+click to world quest icon to insert quest link into quotes.

**Comment by warshal77** [comment]
can confirm bugged on all characters.

the /dump you asked LiangYuxuan
[1]="|cffffff00|Hquest:66615:2426|h[Nurgash Muckformed]|h|r"

**Comment by LiangYuxuan** [comment]
Thanks! And we have to wait for weeks to get Fated version of quest ids.
