### ISSUE TITLE
Fated World Bosses not being tracked

### ISSUE THREAD

**Issue by Alauraaa** [SavedInstances/SavedInstances#605]
**Is your feature request related to a problem? Please describe.**
Fated World Bosses not being tracked, the old ones from 9.0

**Describe the solution you'd like**
I would like be able to track them to see which alt already has killed the Fated World Boss

**Describe alternatives you've considered**
I'm already keeping an excel pad but sometimes forget to write down.

**Comment by ntowle** [comment]
This is a duplicate of #602 and will be fixed in the next release.
