### ISSUE TITLE
Option to track the weekly pvp quest "A New Deal"

### ISSUE THREAD

**Issue by zeenk** [SavedInstances/SavedInstances#608]
Could we get an option to track this weekly pvp quest please? :)
After 5 weeks when you have collected all the trinkets it gives you 3k honor instead of 500 honor + a trinket so it's a pretty nice quest to do on all your alts if you don't like pvping that much but still want to get the honor level mounts.

https://www.wowhead.com/quest=65649/a-new-deal

Core.lua
Progress11 = false, -- A New Deal

Progress.lua
  {
    name = L["A New Deal"],
    weekly = true,
    quest = 65649,
    relatedQuest = {65649},
  },

**Comment by LiangYuxuan** [comment]
It should be tracked under quest module in Weekly Quest line. Not a fan to track it by Progress.

**Comment by zeenk** [comment]
Nah I searched for "65649" in the Quest.lua and no results but I added it myself now so should be tracking it now I hope :P

**Comment by LiangYuxuan** [comment]
If a quest is tagged daily or weekly, it will be tracked by SI when SI found it completed. Quest.lua only contains quests which are daily or weekly but BLZ didn't tag.
