### ISSUE TITLE
new Owner for Curse project?

### ISSUE THREAD

**Issue by jokeyrhyme** [SavedInstances/SavedInstances#61]
As mentioned over in https://github.com/eTzmNcbkrng/SavedInstances/issues/54 we're open to transferring ownership of the Curse project

Nominate yourself here and we'll figure it out :)

**Comment by jokeyrhyme** [comment]
Also, if you want some level of non-Owner access as per https://github.com/eTzmNcbkrng/SavedInstances/issues/54#issuecomment-334975120 please let me know your Curse / WowAce username :)

**Comment by vforge** [comment]
@jokeyrhyme I had my own repo with SI where I was fixing bugs then I found this fork. I'd appreciate invite to wowace project (I'd prefer GitHub, but I have curse account). You can find me under VForge on wowace.

**Comment by jokeyrhyme** [comment]
@vforge I've added you as a Maintainer, let's see how we go :)

**Comment by TruthNZ** [comment]
What is the state of the curse project?
Have we lost something in their move to www.curseforge.com as the main addons page?

https://www.curseforge.com/wow/addons/search?search=SavedInstances
Shows last update being Dec 2016.

https://www.curseforge.com/wow/addons/saved_instances/files
Shows the last update at the top of the page being an hour ago (Which would match the Wakened Essence Changes).
But the latest file is listed as Dec 2016, which is also the latest one you seem to be able to download - and the one you get from the default download link.

**Comment by speedwaystar** [comment]
the latest file is the alpha release.

**Comment by TruthNZ** [comment]
How do you view and access those?
In the Files List: https://www.curseforge.com/wow/addons/saved_instances/files
I can only see Beta and Release Type files.

**Comment by TruthNZ** [comment]
Found them on the Project site files: https://www.wowace.com/projects/saved_instances/files

Is there a way we can list the alpha files on the curseforge site? That's where most of my guildies go - and I'm assuming most other people.

**Comment by jokeyrhyme** [comment]
@TruthNZ you can also set the Release Type in the Twitch app: 
![screenshot 2](https://user-images.githubusercontent.com/479816/33490724-318381c0-d70c-11e7-80fe-241dc2091366.png)

**Comment by speedwaystar** [comment]
to be honest, i don't see any reason not to bump the alpha up to release. it's solid, and most people are missing out.

**Comment by Stanzilla** [comment]
Went ahead and tagged a v7.0.11 release

**Comment by TruthNZ** [comment]
@jokeyrhyme That's what I ended up doing myself.
But I have a bunch of guild mates who don't run the twitch app, and update manually - who couldn't see the files.
@Stanzilla (and everyone else too) Thank you!

**Comment by SacredDuckwhale** [comment]
Seems like this is now sorted out, so I'm closing up here :)
