### ISSUE TITLE
Renown-specific currency for all renowns

### ISSUE THREAD

**Issue by AlexL1118** [SavedInstances/SavedInstances#613]
Hello.
We can see various currencies, including those which are specific for the current Renown (examples: Renown level, Reservoir Anima, Redeemed Souls, etc.).
It would be nice to see the same currencies for each Renown which has been learned by the character.
For example: 20000 Anima as Kyrian, 10000 Anima as Necrolord, 5000 Anima as Night Fae, etc.
Of course, values for the current Renown and for the non-current Renown(s) do not have to have the same font, colour, etc. We can do something like this (not sure how to set colours in the post, so writing it by words):
- Today: 20000(in green)/200000(in white).
- I suggest: 20000(in cyan)/10000(in green)/5000(in blue)/200000(in white).
  Or: 20000(K)(in green)/10000(N)(in green)/5000(F)(in green)/200000(in white). "K", "N" "F", "V" are the letters which refer to Renowns (Kyrian, Necrolord, Night Fae and Venthyr accordingly). In addition, can also do these letters (only the letters, not the numbers) according to the colour of their respective Renowns.

**Comment by LiangYuxuan** [comment]
Currently, you can hover on currency of a character to show detail info of all convenants. I think showing all values in the main tooltip might be too long. If any further is wanted, feel free to reopen.
