### ISSUE TITLE
Track Shaping Fate

### ISSUE THREAD

**Issue by corveroth** [SavedInstances/SavedInstances#615]
**Describe the solution you'd like**
I would appreciate if SI would track Shaping Fate, the Korthia/Maw weekly. It awards a noteworthy amount of gold via vendor grays, and 500 Anima.

**Additional context**
https://www.wowhead.com/quest=63949/shaping-fate

**Comment by LiangYuxuan** [comment]
> It's not offically supported but allow users to modify lua files to track, before #541 is done.
