### ISSUE TITLE
Adventure Campaign Progress currency incorrect after changing Covenants

### ISSUE THREAD

**Issue by corveroth** [SavedInstances/SavedInstances#616]
**Describe the bug**
My priest's Campaign Progress is reported as being higher than he has reached with any Covenant.

**To Reproduce**
1. My priest moved from Venthyr to Night Fae prior to installing the addon. 
2. He was at ACP 15.
3. I believe he is currently at ACP 1.
4. SI and Venture Plan both report ACP 16, and he has only very low-level missions available.

**Which version of SavedInstances are you using?**
9.2.4

**Additional context**
This may not be a fixable bug since it is present in multiple addons.

**Comment by LiangYuxuan** [comment]
Adventure Campaign Progress is tracked by inner currency 1889 without any modify. Since BLZ didn't expose any "current covenant ACP" info, I don't think it's fixable.
