### ISSUE TITLE
Daily reset time in EU/RU realms is off by 3 hours.

### ISSUE THREAD

**Issue by Snufkin2153** [SavedInstances/SavedInstances#620]
Daily reset happens at 8:00 am server time, or 7:00 am UTC.
SI for some reason thinks it is 3h earlier.

Result of **/si time** command:

SavedInstances: Version: 10.0.0
SavedInstances: Realm: Разувий (EU)
SavedInstances: Zone: Даларан (125)
SavedInstances: time() = 1667892274, GetTime() = 3290.593
SavedInstances: Local time: 2022/11/08 09:24:34 local
SavedInstances: GetGameTime: 8:24 server
SavedInstances: C_DateAndTime.GetCurrentCalendarTime: 2022/11/8 server
SavedInstances: GetQuestResetTime: 20 ч. 35 мин.
SavedInstances: Daily reset: 2022/11/09 05:59:59 local (based on GetQuestResetTime)
SavedInstances: Local to server offset: -1 hours
SavedInstances: Next daily reset: 2022/11/09 05:59:59 local, 2022/11/09 04:59:59 server
SavedInstances: Next weekly reset: 2022/11/09 05:59:59 local, 2022/11/09 04:59:59 server
SavedInstances: Next skill reset: 2022/11/09 05:59:59 local, 2022/11/09 04:59:59 server
SavedInstances: Next Darkmoon reset: 2022/11/14 00:59:00 local, 2022/11/13 23:59:00 server

**Comment by LiangYuxuan** [comment]
SI get these time from in-game APIs. Would you try another /si time and /dump C_DateAndTime.GetSecondsUntilWeeklyReset()

**Comment by Snufkin2153** [comment]
Weekly reset on EU would be moved 3h earlier, Blizzard mentioned this here:
https://eu.forums.blizzard.com/en/wow/en/wow/t/weekly-reset-time-changing-to-0500-cet-on-16-november/398498

But daily reset time should remain same, 8:00 am CET (also 8:00 am server time)

`/si time`:
SavedInstances: Version: 10.0.0
SavedInstances: Realm: Разувий (EU)
SavedInstances: Zone: Даларан (125)
SavedInstances: time() = 1668156323, GetTime() = 23583.892
SavedInstances: Local time: 2022/11/11 10:45:23 local
SavedInstances: GetGameTime: 9:44 server
SavedInstances: C_DateAndTime.GetCurrentCalendarTime: 2022/11/11 server
SavedInstances: GetQuestResetTime: 19 ч. 14 мин.
SavedInstances: Daily reset: 2022/11/12 05:59:59 local (based on GetQuestResetTime)
SavedInstances: Local to server offset: -1 hours
SavedInstances: Next daily reset: 2022/11/12 05:59:59 local, 2022/11/12 04:59:59 server
SavedInstances: Next weekly reset: 2022/11/16 05:59:59 local, 2022/11/16 04:59:59 server
SavedInstances: Next skill reset: 2022/11/12 05:59:59 local, 2022/11/12 04:59:59 server
SavedInstances: Next Darkmoon reset: 2022/11/14 00:59:00 local, 2022/11/13 23:59:00 server

`/dump C_DateAndTime.GetSecondsUntilWeeklyReset()`:
Dump: value=C_DateAndTime.GetSecondsUntilWeeklyReset()
[1]=414875

**Comment by LiangYuxuan** [comment]
Might be the side effect of changing weekly reset time next reset to make GetQuestResetTime returning wrong time. I'll keep this open until next reset and checkout if daily reset time changes too or it fixes itself.

**Comment by Snufkin2153** [comment]
Apparently daily reset time was moved 3h earlier and now happens at 5am server time.
`/si time` and `/dump GetQuestResetTime()` now both return correct info, this bug should be closed.
