### ISSUE TITLE
Addon has a white 'SI' label even when label is disabled

### ISSUE THREAD

**Issue by raysmith59** [SavedInstances/SavedInstances#621]
I'm not sure when this started but the icon for SI has a white 'SI' that shows on the right side when label is disabled... enabling label just adds a yellow label to the existing white one.  I don't particularly care about the label but it isn't factored into the spacing so in my case the letters interfere with the clock.  Happens both in normal and right side positioning.

![image](https://user-images.githubusercontent.com/2917594/201244336-81389d2d-a35d-45ad-ab6f-22c60ee14a0b.png)

**Comment by Stanzilla** [comment]
That sounds more like an issue with your LDB display addon

**Comment by raysmith59** [comment]
So you're thinking it's a Titan Panel issue?  It's only affecting this addon but I'll report it over there as well, thanks.

**Comment by raysmith59** [comment]
Looks like line 2987 in core.lua is what's causing my problem; commenting it out removes the white label. Unsure if that's useful info or not but it's working for me.

SI.dataobject.text = "SI"

**Comment by LiangYuxuan** [comment]
It's LDB display addons to choose icon or text or both to show in their panel. SI must provide both info for them. Sorry but nothing we can do.

**Comment by raysmith59** [comment]
Quick note that Titan Panel just put out a patch to fix this issue; unsure why SI was the only affected addon for me but it's sorted now.

"Revert a change that forced LDB text to always show."
