### ISSUE TITLE
Request: Track the world bosses for the anniversary event

### ISSUE THREAD

**Issue by willov** [SavedInstances/SavedInstances#622]
**Is your feature request related to a problem? Please describe.**
The world bosses for the anniversary event are not tracked

**Describe the solution you'd like**
Tracking the bosses in the same way as other world bosses

**Describe alternatives you've considered**
Using a macro to track if they have been killed or not: 
```
/run for k, v in pairs({ Kazzak = 47461, Azuregos = 47462, Dragons = 47463}) do print(format("%s: %s", k, C_QuestLog.IsQuestFlaggedCompleted(v) and "\124cff00ff00Yes\124r" or "\124cffff0000No\124r")) end
```

**Comment by LiangYuxuan** [comment]
They're tracked in daily quest due to world bosses are always weekly but they're not.
