### ISSUE TITLE
Support The Maw Hunts

### ISSUE THREAD

**Issue by andybergon** [SavedInstances/SavedInstances#626]
**Is your feature request related to a problem? Please describe.**
Just like other World Bosses it would be nice to track The Hunt WB, especially [Hunt: Shadehounds](https://wowpedia.fandom.com/wiki/Hunt:_Shadehounds) as it drops a mount from [Gorged Shadehound](https://www.wowhead.com/npc=174861/gorged-shadehound).

Either tracking the quest or the boss would work!

**Comment by LiangYuxuan** [comment]
Maw Hunts is tracked under Weekly Quest.

**Comment by andybergon** [comment]
Maw Hunts quest often bugs out (it doesn't show as complete in the game)  but you can still drop the mount from the Shadehound kill.
Not a huge deal, just wanted to make sure people are aware.
