### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by blecaplol** [SavedInstances/SavedInstances#627]
10x Interface/AddOns/SavedInstances/Core/Core.lua:3154: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Interface/AddOns/SavedInstances/Core/Core.lua"]:3154: in function `Refresh'
[string "@Interface/AddOns/SavedInstances/Core/Core.lua"]:2613: in function <Interface/AddOns/SavedInstances/Core/Core.lua:2613>
[string "=[C]"]: ?
[string "@Interface/AddOns/Quartz/libs/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <...e/AddOns/Quartz/libs/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Interface/AddOns/Quartz/libs/AceBucket-3.0-4/AceBucket-3.0.lua"]:85: in function `func'
[string "@Interface/AddOns/BagSync/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <...ce/AddOns/BagSync/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

**Comment by LiangYuxuan** [comment]
`SI.WorldBosses` is defined in other file and shouldn't be nil, so your install might be broken. Reinstall can solve this.
