### ISSUE TITLE
keep it as WowAce subversion? Or switch to WowAce git or GitHub?

### ISSUE THREAD

**Issue by jokeyrhyme** [SavedInstances/SavedInstances#63]
From: https://github.com/SavedInstances/SavedInstances/issues/54#issuecomment-334975538

> deciding on a home for the code: keep it in WowAce Subversion? switch to WowAce git? move it to GitHub?

I'm greatly prefer git to subversion, but that's just me
Also, whilst normally I would prefer to keep it on GitHub, do note that WowAce has the benefit of making translations slightly easier to submit

Of course, I'm happy either way, just want to see what others think

**Comment by Stanzilla** [comment]
I created a repo on Wowace now and left the license as is https://www.wowace.com/projects/saved_instances/source

**Comment by jokeyrhyme** [comment]
Awesome, I'll close this for now then, but others can still chime in, etc

**Comment by SacredDuckwhale** [comment]
As is evident from the amount of feedback here (and personal forks/patches being created in your absence), git seems to be the better choice.

The translations can still be handled by CurseForge (= WowAce), the GitHub project doesn't need to contain all the localized phrases. They're handled by the CF packager, anyway.

**Comment by jokeyrhyme** [comment]
Hmmm, that's pretty cool if it's part of the packaging step!

**Comment by Stanzilla** [comment]
That is true, indeed. The translation system works with external (GitHub) and internal repos since the site rework.

**Comment by SacredDuckwhale** [comment]
Okay, so regarding the issues and all, I think the project would benefit from some streamlining. Right now it is all over the place with the various forks, dozens of issues everywhere, and while I'd like to help manage the issues more easily that won't work until "we" (=everybody who wants to chime in) have decided on how to proceed. Thusly, I am suggesting this:

### Repository:
* Use GitHub to host both the code and manage the project's issues (implying continued use of git, obviously)
* Designate one (!) repository that will be the "official" home and keep that up to date with all the changes. While this one seems the most lively, I suppose having @jokeyrhyme fork it and then using that would be the most logical solution, him being the original author and all
* Permissisions for that repository would allow the current "Authors" (Stanzilla etc.) to review pull requests and do the actual management of the code, while "Maintainers" (including myself) would at least need to organize the issues, create tags etc. to help triage them and move stuff over from CurseForge where necessary
 
 ### Localization:
 * As mentioned, this will simply be handled by Curse/WowAce - the code will contain only the original phrases and the localization substitutions for the packager (as is already the case, I believe)
 * The English phrases will be added to the code as usual, but they then need to be copy/pasted or uploaded via script to keep them current on CurseForge. I don't have a script to upload and manage them automatically at this time, but maybe someone else already wrote one? (I do have a script to extract them similar to the one used by the WeakAuras team, but that still requires copy/pasting when phrases have changed)
 * New translations will usually origin from CurseForge users and be added automatically with no effort on the developers' part
 
 ### Issues
 * Keep CurseForge issues open to users, but focus on GitHub for the actual management. It's a bit more work but there are many people who would rather just post with their Curse account and not bother with GitHub
 * Same for the regular comments. I know it's annoying if people post issues there and not where they should, but realistically it won't happen that everybody magically creates properly tagged issues on GitHub anyway, so they might as well have the convenience of posting where they want to (as they do if given the chance)
 * Basically, I'd just comment on/close/tag as viewed the issues on CF and then handle everything on GitHub. No need to organize CF issues much, just keep them open (and not replace them with a link to GitHub, which instead could be part of the project description)
 * I'd want to create some useful tags for the GH Issue Tracker to help manage and prioritize stuff that developers or maintainers may focus working on. I don't know what the best format for this is, but I have been using something like [this](https://github.com/SacredDuckwhale/TotalAP/labels) for my own project(s). Those don't have anybody else contributing so it might not be ideal? Though I did some research on bigger projects' handling of them to come up with it in the first place
 * Similarly, I found it useful to create a project board to prioritize tasks and have an overview of what needs to be done, like [this](https://github.com/SacredDuckwhale/TotalAP/projects/1) - This idea I stole from some large-ish projects so I do believe it will work with many people contributing. You can always split it into several boards for features, bugs, architecture/engineering etc. if it gets too much to handle in just one
 
 ### Project Description
 * I usually have the project description as a markdown file and use it as README.MD on GitHub. I don't know if this is the best solution, but you can copy/paste it to Curse/WowAce and they will read it properly, which allows managing it via git without having to focus on their terrible editor interface :)
 * With the nature of the project changing to a somewhat more open philosophy, I'd want to add some parts to the project description, indicating that people are free to contribute, post issues or follow the development process actively (e.g., via the Timeline mentioned above) to hopefully get some more participation aside from "addon broken pls update"
 
 Uh... I think that is all... for now. Thoughts?

**Comment by Stanzilla** [comment]
I'd say a GitHub organisation (https://github.com/organizations/new) would be the better idea, then @eTzmNcbkrng can move the repo to it and we don't have to fork again and we can add people to the organization that want to do things.

**Comment by jokeyrhyme** [comment]
Thanks @SacredDuckwhale for typing all that down! I agree with all of that, although I'd personally prefer a GitHub Organisation as @Stanzilla suggests

I also don't my status as "original author" to have special weight or be used to pull rank, I mean, I did stop work on the add-on myself years ago
I'm happy to facilitate / steer things, of course, I just want to reiterate that I'm keen for this to be collaborative and fun, and I don't want the add-on to die whilst people still care about it

**Comment by SacredDuckwhale** [comment]
Ah, yes - that is a much better idea. I've only started using GitHub more somewhat recently, so I wasn't aware of the organizations feature. 

I understand what you mean, but I figured if you technically have the "authority" you could at least make sure the project won't be abandoned again. Though, to be fair, if there are several people involved it seems unlikely. Usually it's just one author who loses interest/hasn't time/gets abducted by aliens and then the addon either dies, is maintained by someone else, or has some fixes posted by knowledgeable users if there are enough who care about it.

In any event, if someone (@jokeyrhyme ?) creates one and invites me, I'd see if I can get the issues sorted out - as outlined above.

**Comment by Nifelhein** [comment]
Not able to help in any capacity but I would just like to say that your timely save of this addon @jokeyrhyme  is exactly why you should keep some power over the addon and protect it from another near death experience.

Now back to your important discussion.

**Comment by jokeyrhyme** [comment]
I'd suggest that this repo itself become our central GitHub presence
If we're keen on making a GitHub Organisation, then it might be easiest if @eTzmNcbkrng migrates this repo, although sufficient powers should be able to be granted without the Org

**Comment by SacredDuckwhale** [comment]
It's all the same to me, but without proper permissions on GitHub **and** WowAce, nobody will be able to do anything. That's why I thought it best if you were the owner, so that you can make sure everything is managed properly without relying on someone else to be present.

**Comment by eTzmNcbkrng** [comment]
Glad you all decided to stay on Github. From an AddOn-User perspective I think it gives a better insight into development work, even if one doesn't understand the code.  
I have created the SavedInstances organisation and migrated the repo there.

**Comment by SacredDuckwhale** [comment]
Very good. If someone can add me and grant the appropriate permissions I will be happy to move over the issues here, tag them etc., as soon as I have some time. I'm too busy to do much development work right now, but that seems easy enough :)

**Comment by jokeyrhyme** [comment]
I just tried to update the links so that users would submit issues here on GitHub

https://www.wowace.com/projects/saved_instances seems to have updated
https://mods.curse.com/addons/wow/saved_instances has not yet, but maybe it's something that takes a while to be copied over? /shrug

**Comment by Stanzilla** [comment]
Yeah that always takes a while to sync

**Comment by jokeyrhyme** [comment]
@SacredDuckwhale currently only @eTzmNcbkrng has permissions to invite to the GitHub

**Comment by TruthNZ** [comment]
If we could get invites to the Org out? I would think most on this list would be interested, and a good starting point (And they can decline if they're not).
