### ISSUE TITLE
Support Dragonflight weekly events

### ISSUE THREAD

**Issue by brikr** [SavedInstances/SavedInstances#635]
**Is your feature request related to a problem? Please describe.**
I see that "Community Feast" is tracked under weekly quests, but Siege on Dragonbane Keep and the Maruuk hunts don't show up anywhere that I can find.

**Describe the solution you'd like**
It would be great if Siege on Dragonbane Keep, hunts, and other renown weekly events could show so that I can easily track which will still give me loot.

**Describe alternatives you've considered**
Looking at the event on the map shows the rewards. If they are purple, I know I haven't done it on that character

**Additional context**
If you've already done an event, it can sometimes list no available loot, and sometimes list a blue cache as loot. I think this varies per event. Personally all I care about is whether I've collected the purple loot that week

**Comment by LiangYuxuan** [comment]
Just completed some weekly events, and found some quest ids.

* Siege on Dragonbane Keep: 70866
* Grand Hunts (Mythic Reward): 70906 or 70007 (Need help here)
* Wrathion or Sabellian: 66805 then 66133 (Wrathion) 66805 (Sabellian)

**Comment by wizjany** [comment]
Purple hunt bag is 70906.
Blue hunt bag is 71136, green is 71137.

Ran QuestsChanged on an alt and compared IDs to what was flagged completed on my main. The rest seem to be hunt(area)-specific or other tracking quests. https://i.imgur.com/eNI7ZHi.png https://i.imgur.com/Q5vfsQ6.png
