### ISSUE TITLE
Add dragonflight renown

### ISSUE THREAD

**Issue by marulovinia** [SavedInstances/SavedInstances#638]
Since it's "important" to track certain milestone renown levels on dragonflight reps, could this be added as an option for those who want to track this across alts?

**Comment by skjetne** [comment]
Yes, SI would be perfect for this. It's such a hassle logging back and forth

**Comment by aproctor** [comment]
Yeah I've been looking for an addon that tracks this as well, and was hoping SavedInstaces would add it.

There appear to be new CVars that might make this pretty easy
```
lastRenownForMajorFaction2503
lastRenownForMajorFaction2507
lastRenownForMajorFaction2510
lastRenownForMajorFaction2511
```

I was thinking it'd be nice to view it in a compact format like the Mythic+ vault string.

eg:
`10 / 12 / 8 / 7` might be a string representing 10 Centar, 12 Dragonscale, 8 Valdrakken and 7 Tuskar rep.

**Comment by Stanzilla** [comment]
I did this recently https://wago.io/zCAWWcTfN/3 

relevant function

```lua
local function getRenownInfo()
    wipe(renownInfo)
    local majorFactionIDs = C_MajorFactions.GetMajorFactionIDs(LE_EXPANSION_DRAGONFLIGHT)
    
    for _, v in pairs(majorFactionIDs) do
        local level = C_MajorFactions.GetCurrentRenownLevel(v)
        local data = C_MajorFactions.GetMajorFactionData(v)
        local factionName = data.name
        table.insert(renownInfo, { factionName, level })
    end
end
```

**Comment by skjetne** [comment]
I think just having them as separate lines would also be fine no? Having them in one line can make it confusing to new players. Also you might not be too interested in tracking all of the renowns.
