### ISSUE TITLE
Track which toons have used their profession knowledge treatise

### ISSUE THREAD

**Issue by matthewmerendo** [SavedInstances/SavedInstances#639]
**Is your feature request related to a problem? Please describe.**
I have a lot of toons with a lot of professions, and I don't always remember which toons have read their weekly treatises.

**Describe the solution you'd like**
A simple row in the plugin that says what treatises have been read, if any.

**Describe alternatives you've considered**
You could also consider the treatises weekly quests and just plop them in there.

**Comment by StevesExperiments** [comment]
I submitted a PR for this here: https://github.com/SavedInstances/SavedInstances/pull/653

Yes, it's been driving me nuts, too.
