### ISSUE TITLE
Mythic Keystone missing from SavedInstances

### ISSUE THREAD

**Issue by geeet1** [SavedInstances/SavedInstances#645]
**Describe the bug**

Mythic Keystone not showing up in SavedInstances

**Do you have an error log of what happened?**

No.

**To Reproduce**
 
1. Just have Mythic Keystone enabled in settings
2. Look at the addon table
3. Keystone is missing there despite it being enabled

**Screenshots**
![SI](https://user-images.githubusercontent.com/120192641/207799478-57a58a39-0cf6-4729-b80f-204649ddb1f5.jpg)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of SavedInstances are you using?**
10.0.3

**Was it working in a previous version? If yes, which was the last good one?**
Yes, not sure which one.

**Additional context**

**Comment by LiangYuxuan** [comment]
fixed in #644
