### ISSUE TITLE
Feast/Siege/Aiding the accord tracker

### ISSUE THREAD

**Issue by KYESAR** [SavedInstances/SavedInstances#647]
**Is your feature request related to a problem? Please describe.**
Ability to easily see what alts have done Feast/Siege/Aiding the accord

**Describe the solution you'd like**
Trackable like everything else 

**Describe alternatives you've considered**
Currently there are weakauras but have to log onto to each char cant see all at once.

**Additional context**

**Comment by LiangYuxuan** [comment]
Currently tracked in Weekly Quest
