### ISSUE TITLE
Primal Storm Rare Weekly Kill Tracker

### ISSUE THREAD

**Issue by leiffure** [SavedInstances/SavedInstances#654]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
A weekly kill tracker for the 16 rare spawns from the Primal Storm to see at a glance which you haven't killed yet

**Comment by Sritam28** [comment]
I want to contribute to the code please assign me this.

**Comment by LiangYuxuan** [comment]
> I want to contribute to the code please assign me this.

Feel free to pr :)
