### ISSUE TITLE
Unable to see dungeons

### ISSUE THREAD

**Issue by ssmithstone** [SavedInstances/SavedInstances#66]
Hi, I checked out the master branch also i downloaded from WowAce so i have version 7.0.8 and got the plugin configured to show the Classic and TBC dungeons that I have been running , and its not showing any data , is there something else I need to do ?

**Comment by jasoncgc** [comment]
Hi, I have download the latest version of SI but the minimap icon has been disappeared.  I can see any option to appear back.  Kind of annoying.  Please help.  Great thanks.

**Comment by ssmithstone** [comment]
My mistake this works with heroic dungeons,
