### ISSUE TITLE
PvP Item Level indicatortip

### ISSUE THREAD

**Issue by aoc742** [SavedInstances/SavedInstances#661]
I would like to add PvP Item Level directly beneath the Item Level indicatortip.

I've already written code to do this and would be happy to contribute if given permission!

Example screenshot:
![image](https://user-images.githubusercontent.com/13649476/210110795-9959aa52-011b-4cec-997d-059fec2c468c.png)

**Comment by LiangYuxuan** [comment]
Hey, feel free to open pr if you want to contribute!

**Comment by aoc742** [comment]
Created PR  https://github.com/SavedInstances/SavedInstances/pull/662 for this issue
