### ISSUE TITLE
Datatext/Broker Text broken with latest ElvUI update

### ISSUE THREAD

**Issue by Hranor** [SavedInstances/SavedInstances#682]
**Describe the bug**
A change was made with ElvUI that seems to have broken the SavedInstances datatext. It no longer shows up as a datatext option in ElvUI

**Do you have an error log of what happened?**
No known error, just compatabilty broken. 

**To Reproduce**
1. Install only ElvUI and SavedInstances
2. Go to Datatexts > Panels in ElvUI settings.
3. SavedInstances no longer shows as an option in the dropdown lists. 

**Screenshots**
This seems to be the change made to ElvUI
![image](https://user-images.githubusercontent.com/47311699/213292554-f55a8039-ba49-481b-a9fd-b8ddfe02d2ac.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Tried only using ElvUI and SI as they're the only ones pertinent to this issue.

**Which version of SavedInstances are you using?**
SI Version: 10.0.6
ElvUI Version 13.20

**Was it working in a previous version? If yes, which was the last good one?**
Worked with previous ElvUI versions until latest update.

**Comment by Stanzilla** [comment]
I was told the ElvUI change did not break anything, are you getting any Lua errors?

**Comment by Stanzilla** [comment]
The SavedInstances option is called LDB: SavedInstances after their changes

**Comment by Hranor** [comment]
Ah I completely missed that! Sorry, my mistake. Thanks!
