### ISSUE TITLE
Issue Tracking a Cooldown for JC

### ISSUE THREAD

**Issue by Dirtimoney** [SavedInstances/SavedInstances#685]
**Describe the bug**
This error appeared when I utilized the ability "Timewatcher's Patience" https://www.wowhead.com/spell=374550/timewatchers-patience

**Do you have an error log of what happened?**
N/A

**To Reproduce**
Be a Jewelcrafted and make a Timewatchers Patience

**Screenshots**
![image](https://user-images.githubusercontent.com/31905666/214137129-75dd9c40-aeda-4e37-add8-70be0259e48a.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
This is not a conflict with another addon based on the error message

**Which version of SavedInstances are you using?**
9.0.4
**Was it working in a previous version? If yes, which was the last good one?**
N/A

**Additional context**

**Comment by LiangYuxuan** [comment]
Version 9.0.4 is way too old that I'm surprised on it's still working. Update to latest release can fix this.
