### ISSUE TITLE
DMF error

### ISSUE THREAD

**Issue by amey1956** [SavedInstances/SavedInstances#69]
SavedInstances\SavedInstances-7.0.8.lua:1811: attempt to index local 'texture' (a number value)
SavedInstances\SavedInstances-7.0.8.lua:1811: in function `QuestIsDarkmoonMonthly'
SavedInstances\SavedInstances-7.0.8.lua:1836: in function <SavedInstances\SavedInstances.lua:1830>
[C]: ?
[C]: in function `GetQuestReward'
Leatrix_Plus\Leatrix_Plus-7.3.25.lua:1753: in function <Leatrix_Plus\Leatrix_Plus.lua:1686>

Locals:
self = <table> {
 GetCurrentMapAreaID = <function> defined @SavedInstances\SavedInstances.lua:1818
 GetServerOffset = <function> defined @SavedInstances\SavedInstances.lua:768
 oi_cache = <table> {
 }
 questdebug = <function> defined @SavedInstances\SavedInstances.lua:396
 QuestInfo = <function> defined @SavedInstances\SavedInstances.lua:328
 pvpdesertids = <table> {
 }
 icon = <table> {
 }
 histLiveCount = 0
 FindInstance = <function> defined @SavedInstances\SavedInstances.lua:976
 UpdateToonData = <function> defined @SavedInstances\SavedInstances.lua:1568
 GetRegion = <function> defined @SavedInstances\SavedInstances.lua:784
 InGroup = <function> defined @SavedInstances\SavedInstances.lua:2825
 chatMsg = <function> defined @SavedInstances\SavedInstances.lua:338
 CategorySize = <function> defined @SavedInstances\SavedInstances.lua:1063
 formatNumber = <function> defined @SavedInstances\SavedInstances.lua:454
 GetNextDailyResetTime = <function> defined @SavedInstances\SavedInstances.lua:809
 OrderedCategories = <function> defined @SavedInstances\SavedInstances.lua:1256
 instanceException = <function> defined @SavedInstances\SavedInstances.lua:1161
 db = <table> {
 }
 diff_strings = <table> {
 }
 LFRInstances = <table> {
 }
 transInstance = <table> {
 }
 IsDetached = <function> defined @SavedInstances\SavedInstances.lua:3358
 config = <table> {
 }
 QuestIsDarkmoonMonthly = <function> defined @SavedInstances\SavedInstances.lua:1804
 SkinFrame = <function> defined @SavedInstances\SavedInstances.lua:682
 Categories = <table> {
 }
 histTextUpdate = <function> defined @SavedInstances\SavedInstances.lua:3029
 HistoryEvent = <function> defined @SavedInstances\SavedInstances.lua:2860
 SetupVersion = <function> defined @SavedInstances\SavedInstances.lua:2601
 InstanceCategory = <function> defined @SavedInstances\SavedInstances.lua:1043
 histReapTime = 3600
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @SavedInstances\SavedInstances.lua:3361
 playedpending = false
 UpdateInstanceData = <function> defined @SavedInstances\SavedInstances.lua:1355
 delayedReset = false
 GetNextWeeklyResetTime = <function> defined @SavedInstances\SavedInstances.lua:868
 WorldBosses = <table> {
 }
 revision = 550
 region = "US"
 histOldest = "n/a"
 PlayedTime = 1510184928
 resetDays = <table> {
 }
 core = <table> {
 }
 activeHolidays = <table> {
 }
 LDB = <table> {
 }
 playedreg = <table> {
 }
 scaleCache = <table> {
 }
 UpdateInstance = <function> defined @SavedInstances\SavedInstances.lua:1471
 delayUpdate = 1510184929
 debug = <function> defined @SavedInstances\SavedInstances.lua:342
 oc_cache = <table> {
 }
 LookupInstance = <function> defined @SavedInstances\SavedInstances.lua:1012
 GetSeasonCurrency = <function> defined @SavedInstances\SavedInstances.lua:2370
 version = "7.0.8"
 idtext = <function> defined @SavedInstances\config.lua:45
 Indicators = <table> {
 }
 UpdateCurrency = <function> defined @SavedInstances\SavedInstances.lua:1754
 OrderedInstances = <function> defined @SavedInstances\SavedInstances.lua:1243
 updateSpellTip = <function> defined @SavedInstances\SavedInstances.lua:1549
 currency = <table> {
 }
 normalizeName = <function> defined @SavedInstances\SavedInstances.lua:950
 BonusRollShow = <function> defined @SavedInstances\SavedInstances.lua:4749
 instancesUpdated = true
 L = <table> {
 }
 specialQuests = <function> defined @SavedInstances\SavedInstances.lua:231
 dbmhook = true
 ShowDetached = <functio

**Comment by ceylina** [comment]
Looks like you are using an old version of saved instances. This was fixed months ago. Switch to an alpha release in the twitch client and download the latest.
