### ISSUE TITLE
Window not displaying certain options

### ISSUE THREAD

**Issue by ryanceleslie** [SavedInstances/SavedInstances#690]
The flyout window does not show specific options I've set, for example Community Feast, Siege on Dragonbane Keep 

**Do you have an error log of what happened?**
 

**To Reproduce**
Set the options for viewing quests, view window

**Screenshots**
![image](https://user-images.githubusercontent.com/20121443/215886065-504bb760-7468-4342-bf8a-112625b908c8.png)

Even when exapnded, they're not displayed

![image](https://user-images.githubusercontent.com/20121443/215886234-8779ad5a-488f-455d-81ea-cf067c9045b3.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, screenshots show only SavedInstances enabled

**Which version of SavedInstances are you using?**
10.0.9

**Was it working in a previous version? If yes, which was the last good one?**
Unknown, just installed it

**Additional context**

**Comment by LiangYuxuan** [comment]
They're not going to show when none of characters have completed, no matter expanded (or we call showall) or not. The first behavior is intended but the latter one is not.

**Comment by ryanceleslie** [comment]
Can we get an option to show it?

This tool is as close to complete alt management as I can get, so having items shown even when none have done it is really help to clue me into doing it.
