### ISSUE TITLE
Trial of Elements

### ISSUE THREAD

**Issue by subj99** [SavedInstances/SavedInstances#691]
SavedInstances was showing when I completed "Trial of Elements" fine on all my characters.  However now it's not showing it at all.  

This changed after I downloaded your latest version yesterday.

**Comment by LiangYuxuan** [comment]
Is it gone after weekly reset on your region? Or could you try to complete it once more?

**Comment by subj99** [comment]
I actually noticed it was gone before weekly reset, it was gone on Monday after I installed the new update.  It was displaying on my characters before the update.  Now I am not seeing it at all.

**Comment by LiangYuxuan** [comment]
Is it enabled in settings? Could you check out your weekly quest list and find out if its in there?

**Comment by subj99** [comment]
It's definitely enabled in settings, that's the first thing I checked.  Not sure what you mean by "weekly quest list"?

I have quite a few toons by the way, I definitely depend on this addon it's great!

**Comment by subj99** [comment]
I didn't change anything on my side, I just updated the addon yesterday and noticed it no longer showed Trial of Elements but I thought maybe that had happened before and I never noticed.  However today I did it Trial of Elements on a few characters after weekly reset  and I noticed it didn't show up.

**Comment by LiangYuxuan** [comment]
Try to run `/dump C_QuestLog.IsQuestFlaggedCompleted(71995)` and reply what it prints.

Also could you share your SavedInstances data file in your WTF folder? The path to it is `WTF/Account/(YOUR ACCOUNT ID)/SavedVariables/SavedInstances.lua`.

**Comment by LiangYuxuan** [comment]
I can see two characters are marked completed on Trial of Elements using your data file. For make sure, what version of SI you're using?

**Comment by subj99** [comment]
Yes I have 2 characters that have completed Trial of Elements when I gave you that file, I have 3 now I believe.  None of them show Trial of Elements on the minimap icon list where they used to before I downloaded the update on Monday.  The addon file I used was SavedInstances-10.0.9.zip

**Comment by subj99** [comment]
I'm not sure why this has marked can't reproduce as it would seem like an easy problem.  I've attached a snapshot of the toon and you can see that Trial of Elements is no longer being showed.  I tried rolling back to the older version of Savedinstances and still can't see it, so no idea what has changed?  This is a toon that had completed Trial of Elements.

![new-version](https://user-images.githubusercontent.com/124111960/216167177-0ee6b46b-7461-433b-9c57-d374c1829a24.jpg)

**Comment by subj99** [comment]
Trial of the Flood is also not showing anymore.

**Comment by subj99** [comment]
Actually I can see that it doesn't show in the list anymore (as I've showed in my snapshot) but it's showing on its own line now (maybe it always was and I never noticed).  That's obviously good enough (likely better), thanks and sorry about the confusion!
