### ISSUE TITLE
Request: Show up to top 8 Mythic+ dungeon levels completed across characters

### ISSUE THREAD

**Issue by mikemaring** [SavedInstances/SavedInstances#693]
I'm not sure if the API gives this data, but...

It would be very helpful to not just track highest dungeon across characters, but also how close I am go completing 2, 4 or 8 and what the highest and lowest levels are for each character.

Example: Invited to go on a Mythic+17. It would be nice to see, at a glance, exactly which character needs that one the most, not just what the highest for each is.

Thanks!

**Comment by LiangYuxuan** [comment]
Currently Mythic+ records shows best levels for three caps of Great Vault and show full 8 best levels when you hover on it.
