### ISSUE TITLE
[QoL] Can we hide Revival Catalyst completion on alts?

### ISSUE THREAD

**Issue by TreizeEU** [SavedInstances/SavedInstances#694]
Hello.

Are there any way to hide the Revival Catalyst quest completion on alts, other than hiding weekly quests altogether? Every time I complete it and relog alts, it'll show as completed on every single one (I have most alts set to "only show when saved").

**Comment by formigao** [comment]
same issue, really anoying and useless to flag an account quest.  all my chars start showing because this quest
