### ISSUE TITLE
M+ weekly reward resetting

### ISSUE THREAD

**Issue by johnsolver** [SavedInstances/SavedInstances#7]
For whatever reason blizzard's C_ChallengeMode.IsWeeklyRewardAvailable() only returns true for the very first time you login after a weekly reset on that character.

Afterwards it returns false even if the chest wasn't opened. Perhaps some workaround with saving that state until you open the chest.

**Comment by eTzmNcbkrng** [comment]
Firstly, thanks for reporting.
I've been giving this problem some thought over the past few days and I agree with your solution, the problem with it is that this will only be picked up if the addon is enabled the first time you log in each week.  
I'd prefer a solution that works in all circumstances.  
I'll try to find some time to spend on this over the weekend and see if I can figure something out.

**Comment by SacredDuckwhale** [comment]
Is this still an issue? I haven't seen the reward reset even after relogging.

C_ChallengeMode.IsWeeklyRewardAvailable() always returns valid results, but only if C_ChallengeMode.RequestRewards() has been called before. I don't see this anywhere in the addon, but it seems to work regardless?

**Comment by jokeyrhyme** [comment]
It could be that another add-on is calling RequestRewards() ?

**Comment by SacredDuckwhale** [comment]
Good point, I forgot that the result was most likely permanently stored.

This is an easy fix, then. Self-assigning this while I test the (minor) changes required.
