### ISSUE TITLE
Suggested additional tracking: Argus and Broken Shore Rares. (or user addable)

### ISSUE THREAD

**Issue by NuclearToasted** [SavedInstances/SavedInstances#70]
I have been trying to farm all my toons through Argus to get the various mounts/pets.... ive found it difficult to track which toons have which one done... I would love to have additional options to add argus rares... or a user addable quest section... .let us manually put in a quest completion we can manually add.

**Comment by speedwaystar** [comment]
there's an achievement called Argus Commander which tracks rares killed for each of your toons.
