### ISSUE TITLE
Incorrect font for russian language when using english client

### ISSUE THREAD

**Issue by artazika** [SavedInstances/SavedInstances#703]
**Describe the bug**
with character names everything is fine when using a russian client, but when using an english client - squares instead of nicknames

**Do you have an error log of what happened?**
nope

**To Reproduce**
1. Have russian characters
2. login into english client
3. check SI spreadsheet
4. See squares
--> 

**Screenshots**
![image](https://user-images.githubusercontent.com/39316666/220226155-2ca9779c-de8e-4353-a797-647c070fad5f.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yep

**Which version of SavedInstances are you using?**
v10.0.10

**Was it working in a previous version? If yes, which was the last good one?**
no

**Comment by LiangYuxuan** [comment]
SavedInstances uses the default font of QTip, the same one Blizzard uses, GameTooltipHeaderText, and it uses `Fonts/FRIZQT___CYR.TTF ` in Russian client, `Fonts/FRIZQT__.TTF ` in English client.

https://github.com/Gethe/wow-ui-source/blob/532edb9c5c2930dcc60a2f59c48f8fb414652be1/Interface/SharedXML/SharedFonts.xml#L1677-L1693

Without font with Russian character, the game will fail to display it correctly. I think forcing font file would break the ability to let other addon to adjust GameTooltipHeaderText and SI tooltip, and don't like to do it.

You can download `FRIZQT___CYR.TTF`, and then rename and put it to `_retail_/Fonts/FRIZQT__.TTF` to fix this.

https://wow.tools/files/#search=%5E615971&page=1&sort=0&desc=asc
