### ISSUE TITLE
Feature Request: Track Renascent Lifeblood (Revival Catalyst charges)

### ISSUE THREAD

**Issue by Dathwada** [SavedInstances/SavedInstances#705]
**Describe the solution you'd like**

Hello, I would like to see the [Renascent Lifeblood](https://www.wowhead.com/currency=2166/renascent-lifeblood) (Revival Catalyst charges) to be tracked, so I can see how many of them I have on all of my alts.

**Comment by LiangYuxuan** [comment]
You can track Catalyst Charges. The quantity of Renascent Lifeblood isn't the left charges according to wowhead comment.
