### ISSUE TITLE
Missing Weekly Profession Quest

### ISSUE THREAD

**Issue by Ricodyn** [SavedInstances/SavedInstances#707]
The following weekly profession quests are missing:
 - When You Give Bakar a Bone (Leatherworking)  _70567_
 - The Case of the Missing Herbs (Herbalism) _70615_ 
 - Blingtron 8000...? (Engineering) _70545_
 - Spread the Enchantment (Enchanting) _72155_

**Comment by LiangYuxuan** [comment]
fixed in #711
