### ISSUE TITLE
Itemlevel in Table view.

### ISSUE THREAD

**Issue by Harlekintv** [SavedInstances/SavedInstances#712]
**Is your feature request related to a problem? Please describe.**
in the whole charakter window to show the ilvl for all chars not only in tooltip
**Describe the solution you'd like**
to show under charakter name the itemlevel like 394/397 for example. left should be the weared ilvl and the right the max. 

**Describe alternatives you've considered**
not good to track all itemlevels of all chars only in tooltip. with more than 13 chars u loosing quickly the overview.

**Additional context**

![Unbenannt](https://user-images.githubusercontent.com/128061999/225651243-100ec2f6-aaca-44ff-84d5-3c6193df6277.png)

**Comment by LiangYuxuan** [comment]
Duplicated #704
