### ISSUE TITLE
A suggestion to show current covenant icon next to renown & an issue with Shadehound tracking

### ISSUE THREAD

**Issue by Alfakennyone** [SavedInstances/SavedInstances#715]
I know it's an old expansion but it would be helpful for a lot of old farming.

I lose which one of my alts current covenant, so to fix that; could you add the covenant icon next to the renown level? 

example: 80 (venthyr icon), 75 (night fae icon), 69 (necrolord icon), 65 (kyrian icon) etc etc

The issue with Gorged Shadehound tracking is it seems it can only be tracked on toons that have the Event unlocked by completing Rule 6 quest (unlocked with Ambivolent rep with ve'nari). Alts can complete the event - even though it doesn't show up - regardless if they have completed the Rule 6 quest. 

I noticed in the quests.lua it has shadehounds quest ID as 63180, that only seems to track if you completed the event, which obviously alts that don't have it unlocked won't get tracked. So for that, changing it from 63180 to 63433 (loot lockout id from Gorged Shadehound that can drop the mount) would make more sense.

I'm sure it's the same for other hunts, but this is the more important one to track correctly.

**Comment by LiangYuxuan** [comment]
To renown tracking: you can find your current covenant by hovering on your character name and all renown level by tracking currency Renown. Loot lockout will be tracked.

**Comment by Alfakennyone** [comment]
> To renown tracking: you can find your current covenant by hovering on your character name and all renown level by tracking currency Renown. Loot lockout will be tracked.

Ooh I never noticed that, I was always trying to look for it down by the Renown section, whether it was hovering over the level or the Renown on the left but it never showed which is the current covenant. So this works BUT if it's not too much of a hassle, integrate the covenant icon next to the renown level anyways

thanks and thanks for upgrading the Shardhound tracker :)

**Comment by Kaaena** [comment]
if i may, i totally second that. adding a small icon + renown lvl so you can see at first glance would be super, super helpful.

that aside, tysm for this addon that i've been using for years now!!

**Comment by Alfakennyone** [comment]
> if i may, i totally second that. adding a small icon + renown lvl so you can see at first glance would be super, super helpful.
> 
> that aside, tysm for this addon that i've been using for years now!!

If you read the conversation you would've seem that you can view this from hovering over your characters in the SI window :)

**Comment by Kaaena** [comment]
> > if i may, i totally second that. adding a small icon + renown lvl so you can see at first glance would be super, super helpful.
> > that aside, tysm for this addon that i've been using for years now!!
> 
> If you read the conversation you would've seem that you can view this from hovering over your characters in the SI window :)

and if you read my comment i said i second the idea to have an icon to see it at first glance :) not by hovering ^^ but thanks !
