### ISSUE TITLE
Zskera Vault keys and doors

### ISSUE THREAD

**Issue by keflatbn** [SavedInstances/SavedInstances#716]
**Is your feature request related to a problem? Please describe.**
Currently SavedInstances do not offer to show the number of Zskera Vault keys in character.
It also does now show how many Vault doors has been opened.

**Describe the solution you'd like**
Ability to show the number of keys the char has and how many Vault doors has been opened of the total amount. For better structure it would make sense so show Vault doors and keys separatly.
Example: CharX has 5 keys in inventory and has opened 12 of the 29 vault doors.
SavedInstances show:

"Zskera Vault keys: 5"
"Zskera Vault doors unlocked: 12/29"

**Describe alternatives you've considered**
Just manually keeping track of this info, have not found any addon supporting it.

**Additional context**
Tracking keys should be fairly easy, but unlocked doors might be harder to track if info is not available.

Thanks for a great addon!

**Comment by LiangYuxuan** [comment]
Tracking door is nearly a mess as no hidden quest is related to unlocking the door, and the spell id of unlocking door is different nearly every door. There is no reliable way to track this.

Tracking items is not the proposal of SI. Try BagSync which do super great to this.
