### ISSUE TITLE
Aiding the accord Zkera Vaults is not tracking correctly

### ISSUE THREAD

**Issue by 1701NCC** [SavedInstances/SavedInstances#718]
**Describe the bug**

The Aiding the Accord Zskera Vaults is not tracking the progress but is showing the checkmark once complete.

**Do you have an error log of what happened?**
No errors popping up in Bugsack. 

**To Reproduce**

1. Log into game. Pick up this weeks aiding the accord
2. check saved instances
3. see a blank space where there is normally the 0/1 0/3000 progress tracker
4. feel sadness
--> 

**Screenshots**
![image](https://user-images.githubusercontent.com/73872724/231314928-7b9dca22-4a08-4ed8-b4bf-9cbbbf9ddebd.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yup, not showing still. 

**Which version of SavedInstances are you using?**

SavedInstances-10.0.11

**Was it working in a previous version? If yes, which was the last good one?**
Worked fine for last weeks aiding the accord. 

**Additional context**

**Comment by neftha** [comment]
Seems to fix it:

Progress.lua, add after line 688:
`	  75259, -- Aiding the Accord: Zskera Vault`
Quest.lua, add after line 355:
`  [75259] = "Weekly", -- Aiding the Accord: Zskera Vault`

**Comment by 1701NCC** [comment]
This does indeed correct the issue. It is showing the progress now correctly. Thanks neftha. 

![image](https://user-images.githubusercontent.com/73872724/231834264-4b6327f5-39db-46c0-9e6a-fcc5771b007c.png)


Do i mark this as closed or does someone else mark it as closed once its been added to an update?
