### ISSUE TITLE
Catalyst Charges not showing correct maximum

### ISSUE THREAD

**Issue by crusha015** [SavedInstances/SavedInstances#723]
The Catalyst Charges are showing a maximum of 12, instead of 6. This doesn't affect much, but it does make it harder to see at a glance when you are nearing the cap, or at the cap due to the color coding not working.

I've added 1 row to the Currency.lua module to resolve this:

Add the following at row 230:
`ci.totalMax = 6`

This will all be moot come 10.1 in a few weeks, but it's possible the new catalyst charge system has the same bug, so I figured I should share.

**Comment by LiangYuxuan** [comment]
No longer used and will be unlimited when Catalyst reopen in S2. Will see if the new currency have the same issue.
