### ISSUE TITLE
Wrong "Le Coeur-de-Pierre" translation

### ISSUE THREAD

**Issue by PrFalkenGH** [SavedInstances/SavedInstances#726]
**Describe the bug**
Wrong Instance Name in FR Client

**Do you have an error log of what happened?**

**To Reproduce**
Tag a character in the instance

**Screenshots**

![image](https://user-images.githubusercontent.com/70543980/235092390-609b467c-06be-4bb9-9020-3b681193ebed.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of SavedInstances are you using?**

10.0.12

**Was it working in a previous version? If yes, which was the last good one?**

Never noticed

**Additional context**

**Comment by LiangYuxuan** [comment]
Could you share your SavedInstances data file in WTF if the issue still exists?

**Comment by PrFalkenGH** [comment]
Hello,

I attached the file and here is the corresponding screenshot of the UI :

[image.png]

The problem is with the uppercase "P" in "Pierre"

Martin aka "PrFalken"
***@***.***) - [Web](https://prfalken.org/) - [Twitter](https://twitter.com/martinbayard)

------- Original Message -------

**Comment by LiangYuxuan** [comment]
Hey, your "attached" file and screenshot image is not available in the issue page. Maybe you need to attach them though the webside.

**Comment by LiangYuxuan** [comment]
Hey, your "attached" file and screenshot image is not available in the issue page. Maybe you need to attach them though the webside.

**Comment by PrFalkenGH** [comment]
![Screenshot 2023-05-09 134909](https://github.com/SavedInstances/SavedInstances/assets/70543980/6e6f89e7-9e3f-45a3-8631-bbb0f4cf8ae1)

[SavedInstances.zip](https://github.com/SavedInstances/SavedInstances/files/11431693/SavedInstances.zip)

Here are the files :)

**Comment by LiangYuxuan** [comment]
Did some research and found that the instance with lower "p" (id: 1148) is actually used by timewakling and should not have lockouts on it. All you need is change it's config from Always to Show on Saved or Never and it'll be fine. And set the config of the correct one (id: 320) to Always if you want.

Since it's a little display issue fetched from API, and won't be displayed unless enforce it to show, we don't like to fix this lower "p".
