### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by Mithras2801** [SavedInstances/SavedInstances#728]
1st error:

392x SavedInstances/Core/Core.lua:1487: attempt to call method 'UpdateCurrency' (a nil value)
[string "@SavedInstances/Core/Core.lua"]:1487: in function `UpdateToonData'
[string "@SavedInstances/Core/Core.lua"]:2874: in function <SavedInstances/Core/Core.lua:2868>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 GetServerOffset = <function> defined @SavedInstances/Core/Time.lua:24
 QuestExceptions = <table> {
 }
 modules = <table> {
 }
 QuestInfo = <function> defined @SavedInstances/Core/Core.lua:60
 QuestIgnored = <function> defined @SavedInstances/Core/Core.lua:552
 GetRegion = <function> defined @SavedInstances/Core/Functions.lua:41
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 GetTimeToTime = <function> defined @SavedInstances/Core/Time.lua:15
 InGroup = <function> defined @SavedInstances/Core/Core.lua:3039
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 ScheduleTimer = <function> defined @Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 Emissaries = <table> {
 }
 ADDON_LOADED = <function> defined @SavedInstances/Core/Core.lua:2925
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 OrderedCategories = <function> defined @SavedInstances/Core/Core.lua:928
 instanceException = <function> defined @SavedInstances/Core/Core.lua:822
 maxLevel = 70
 db = <table> {
 }
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 BossRecord = <function> defined @SavedInstances/Modules/BonusRoll.lua:163
 LFRInstances = <table> {
 }
 OnEnable = <function> defined @SavedInstances/Core/Core.lua:2854
 SkinFrame = <function> defined @SavedInstances/Core/Core.lua:469
 Indicators = <table> {
 }
 InstanceCategory = <function> defined @SavedInstances/Core/Core.lua:702
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 thisToon = "Nedylene - Burning Legion"
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @SavedInstances/Core/Core.lua:3571
 playedpending = true
 specialQuests = <function> defined @SavedInstances/Modules/Quest.lua:157
 ScanTooltip = SavedInstancesScanTooltip {
 }
 BonusRollCount = <function> defined @SavedInstances/Modules/BonusRoll.lua:140
 WorldBosses = <table> {
 }
 cpairs = <function> defined @SavedInstances/Core/Core.lua:3485
 toonInit = <function> defined @SavedInstances/Core/Core.lua:2738
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "SavedInstances"
 playedreg = <table> {
 }
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 LookupInstance = <function> defined @SavedInstances/Core/Core.lua:671
 GetNextDailySkillResetTime = <function> defined @SavedInstances/Core/Time.lua:41
 currency = <table> {
 }
 Debug = <function> defined @SavedInstances/Core/Debug.lua:18
 KeystoneAbbrev = <table> {
 }
 BossModEncounterEnd = <function> defined @SavedInstances/Core/Core.lua:3016
 ToggleDetached = <function> defined @SavedInstances/Core/Core.lua:3574
 BOSS_KILL = <function> defined @SavedInstances/Core/Core.lua:3029
 RefreshLockInfo = <function> defined @SavedInstances/Core/Core.lua:2950
 ChatMsg = <function> defined @SavedInstances/Core/Functions.lua:20
 getRealmGroup = <function> defined @SavedInstances/Core/Core.lua:3008
 UnregisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 GetCurrentMapAreaID = <function> defined @SavedInstances/Core/Functions.lua:65
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 oi_cache = <table> {
 }
 hoverTooltip = <table> {
 }
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 baseName = "SavedInstances"
 Requ...
 
 2nd error:
 
42x SavedInstances/Core/Config.lua:915: attempt to index local 'data' (a nil value)
[string "@SavedInstances/Core/Config.lua"]:915: in function `BuildOptions'
[string "@SavedInstances/Core/Config.lua"]:946: in function `SetupOptions'
[string "@SavedInstances/Core/Config.lua"]:56: in function <SavedInstances/Core/Config.lua:55>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

3rd error:

21x SavedInstances/Modules/Currency.lua:1 (null)

4th error:

21x SavedInstances/Modules/Currency.lua:104: attempt to index a nil value
[string "@SavedInstances/Modules/Currency.lua"]:104: in function <SavedInstances/Modules/Currency.lua:103>
[string "=[C]"]: in function `sort'
[string "@SavedInstances/Modules/Currency.lua"]:103: in main chunk

Locals:
c1 = 2533
c2 = 81
(*temporary) = nil
(*temporary) = 2533
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
C_CurrencyInfo_GetCurrencyInfo = <function> defined =[C]:-1

**Comment by Stanzilla** [comment]
Don't update addons today if you are in the EU
