### ISSUE TITLE
Unrecognized trade skill cd Transmute: Dracothyst (405847)

### ISSUE THREAD

**Issue by Healcapone** [SavedInstances/SavedInstances#731]
**Describe the bug**
Opened the Alchemy profession book

**Do you have an error log of what happened?**
No

**Screenshots**

![World of Warcraft 2023-05-04 10 54 58](https://user-images.githubusercontent.com/132558012/236157347-d74071a3-3850-46c8-a46a-09833543faeb.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of SavedInstances are you using?**
10.1.1

**Was it working in a previous version? If yes, which was the last good one?**
Not sure

**Additional context**

**Comment by LiangYuxuan** [comment]
Fixed in fecf75023b0581e01105c82284c2a2c2f3230037
