### ISSUE TITLE
New aiding the accord quest tracking

### ISSUE THREAD

**Issue by 1701NCC** [SavedInstances/SavedInstances#734]
Aiding the Accord: Sniffenseeking https://www.wowhead.com/quest=75859/aiding-the-accord-sniffenseeking
Aiding the Accord: Researchers Under Fire https://www.wowhead.com/quest=75860/aiding-the-accord-researchers-under-fire

The two most recent aiding the accord aren't being tracked. 

Adding into Quest.Lua after line 357
`  [75859] = "Weekly", -- Aiding the Accord: Sniffenseeking `
`  [75860] = "Weekly", -- Aiding the Accord: Researchers Under Fire`
`  [75861] = "Weekly", -- Aiding the Accord: Suffusion Camp`

and 
  `      75859, -- Aiding the Accord: Sniffenseeking`
  `      75860, -- Aiding the Accord: Researchers Under Fire`
  `      75861, -- Aiding the Accord: Suffusion Camp`
      After line 691 in Progress.lua

 Is what i entered into those files to get it to track currently. 

![image](https://github.com/SavedInstances/SavedInstances/assets/73872724/63be7516-d624-49fe-a446-9ab13bb64ebe)

**Comment by crusha015** [comment]
Also:
[75861] = "Weekly", -- Aiding the Accord: Suffusion Camp

75861, -- Aiding the Accord: Suffusion Camp

**Comment by 1701NCC** [comment]
Yeah, was just about to add that one. Seems to depend on how far you are in the campaign as some alts got the researchers under fire and alts that just started the zone got suffusion camp.

**Comment by LiangYuxuan** [comment]
Thank you! Will be included in PR later.
