### ISSUE TITLE
Cannot open Saved Instances window 

### ISSUE THREAD

**Issue by rionshin** [SavedInstances/SavedInstances#735]
**Describe the bug**

When i try to open saved instance window it return error, if i remove saved instance it is working. 

**Do you have an error log of what happened?**
2x SavedInstances/Core/Core.lua:3799: attempt to compare number with nil
[string "@SavedInstances/Core/Core.lua"]:3799: in function `ShowTooltip'
[string "@SavedInstances/Core/Core.lua"]:2832: in function `OnEnter'
[string "@BugSack/Libs/LibDBIcon-1.0-50/LibDBIcon-1.0.lua"]:76: in function <BugSack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:59>

Locals:
self = <table> {
 GetServerOffset = <function> defined @SavedInstances/Core/Time.lua:24
 QuestExceptions = <table> {
 }
 modules = <table> {
 }
 QuestInfo = <function> defined @SavedInstances/Core/Core.lua:60
 QuestIgnored = <function> defined @SavedInstances/Core/Core.lua:552
 histLiveCount = 1
 GetRegion = <function> defined @SavedInstances/Core/Functions.lua:41
 SetDefaultModulePrototype = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetTimeToTime = <function> defined @SavedInstances/Core/Time.lua:15
 InGroup = <function> defined @SavedInstances/Core/Core.lua:3039
 IsEnabled = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 localarr#columns = <table> {
 }
 ScheduleTimer = <function> defined @AutoCombatLogger/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 Emissaries = <table> {
 }
 ADDON_LOADED = <function> defined @SavedInstances/Core/Core.lua:2925
 RegisterMessage = <function> defined @AutoCombatLogger/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 OrderedCategories = <function> defined @SavedInstances/Core/Core.lua:928
 instanceException = <function> defined @SavedInstances/Core/Core.lua:822
 GetPlayerAuraExpirationTime = <function> defined @SavedInstances/Core/Functions.lua:14
 db = <table> {
 }
 SetEnabledState = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 BossRecord = <function> defined @SavedInstances/Modules/BonusRoll.lua:163
 LFRInstances = <table> {
 }
 OnEnable = <function> defined @SavedInstances/Core/Core.lua:2854
 SkinFrame = <function> defined @SavedInstances/Core/Core.lua:469
 localarr#wbsave = <table> {
 }
 Indicators = <table> {
 }
 OnInitialize = <function> defined @SavedInstances/Core/Core.lua:2756
 NewModule = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 thisToon = "Rionpally - Twisting Nether"
 resetDetect = SavedInstancesResetDetectHiddenFrame {
 }
 HideDetached = <function> defined @SavedInstances/Core/Core.lua:3571
 playedpending = false
 specialQuests = <function> defined @SavedInstances/Modules/Quest.lua:157
 ScanTooltip = SavedInstancesScanTooltip {
 }
 BonusRollCount = <function> defined @SavedInstances/Modules/BonusRoll.lua:140
 WorldBosses = <table> {
 }
 cpairs = <function> defined @SavedInstances/Core/Core.lua:3485
 currencySorted = <table> {
 }
 GetName = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "SavedInstances"
 playedreg = <table> {
 }
 Disable = <function> defined @Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 LookupInstance = <function> defined @SavedInstances/Core/Core.lua:671
 showall = false
 GetNextDailySkillResetTime = <function> defined @SavedInstances/Core/Time.lua:41
 currency = <table> {
 }
 localarr#categoryshown = <table> {
 }
 detachframe = SavedInstancesDetachHeader {
 }
 Debug = <function> defined @SavedInstances/Core/Debug.lua:18
 KeystoneAbbrev = <table> {
 }
 BossModEncounterEnd = <function> defined @SavedInstances/Core/Core.lua:3016
 ToggleDetached = <function> defined @SavedInstances/Core/Core.lua:3574
 BOSS_KILL = <function> defined @SavedInstances/Core/Core.lua:3029
 RefreshLockInfo = <function> defined @SavedInstances/Core/Core.lua:2950
 ChatMsg = <function> defined @SavedInstances/Core/Functions.lua:20
 getRealmGroup = <function> defined @SavedInstances/Core/Core.lua:3008
 UnregisterEvent = <function> defined @AutoCombatLogger/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 GetCurrentMapAreaID = <function> define
**To Reproduce**

Just clicking on Saved instance icon 

**Screenshots**
<img width="374" alt="Screenshot 2023-05-10 at 20 15 06" src="https://github.com/SavedInstances/SavedInstances/assets/41396180/5ad61ec4-781c-48f5-8d38-ad2c6ba6020c">

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Don't use ELVUI, didn't try it yet.  

**Which version of SavedInstances are you using?**
SavedInstances-10.1.1.zip

**Was it working in a previous version? If yes, which was the last good one?**
It was working yesterday, not working today - it was working with same version of Savedinstance.  

**Additional context**
if i select Show instance NEVER - it start working.

**Comment by Stanzilla** [comment]
That's an upgrading issue in LibDBIcon-1.0, so other addons that use the newer version cause it for us. should solve itself once they update again to the fixed version.
