### ISSUE TITLE
Alchemy Dracothyste

### ISSUE THREAD

**Issue by Charlys2112** [SavedInstances/SavedInstances#738]
**Describe the bug**

When i launch the game, i have an error message in the chat
**Do you have an error log of what happened?**

Savedinstances : Unrecognized trade skill cd Transmutation : dracothyste (405847)

**To Reproduce**

1. launch the game
2. open alchemy tradeskill
3. error available in the chat

**Screenshots**
![image](https://github.com/SavedInstances/SavedInstances/assets/133338465/7cc072b4-99b0-4b0d-a699-eae42779c2ee)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?** 10.1.1

**Was it working in a previous version? If yes, which was the last good one?** No since patch 10.1

**Additional context**

**Comment by FlareStarrr** [comment]
Same issue.
Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?
YES.

Which version of SavedInstances are you using? 10.1.1
10.1.1

**Comment by LiangYuxuan** [comment]
Fixed in https://github.com/SavedInstances/SavedInstances/commit/fecf75023b0581e01105c82284c2a2c2f3230037 .
