### ISSUE TITLE
10.1 New things to track

### ISSUE THREAD

**Issue by TeiranDragon** [SavedInstances/SavedInstances#739]
Can we get options to track some of the big new weekly quests and events as separate lines?

The chest from Fyrakk Assaults 
Killing the Fyrakk Assaults spawned world boss (There's a turn in quest for them, track that maybe?)
Reward level gained from the Researchers event

(Edit: My original request included the Niffen rep quest being added, because Curseforge's install was not actually installing the SavedInstances-10.1.1.zip version)

**Comment by GitMestra** [comment]
Kretchenwrath should have a killed ID without the hand in since you are saved to the kill, but it is not listed in Raid Info, so a good thing for SI to track. The other disciple is https://www.wowhead.com/npc=203411/shadeisethal.

The chest being tracked is something I would love too. Maybe a combined Fyrakk Assault line with both of these shown "0/0" with the details on tooltip.

**Comment by Tlazolteotl** [comment]
https://www.wowhead.com/quests/dragonflight/suffusion-camps

Here are the Quest IDs for kretchenwrath and shadeisethal:
https://www.wowhead.com/quest=74775/disciple-of-fyrakk-kretchenwrath
https://www.wowhead.com/quest=75239/disciple-of-fyrakk-shadeisethal

**Comment by crusha015** [comment]
I believe the Researcher Bag quest IDs are as follows. Only one I have not confirmed myself is the T2 bag.

T1 = 75627
T2 = 75628
T3 = 75629
T4 = 75630

**Comment by emynii** [comment]
I would also like to add to this list the Chest you can loot from the assault points once a week

**Comment by Ahfau77** [comment]
> https://www.wowhead.com/quests/dragonflight/suffusion-camps
> 
> Here are the Quest IDs for kretchenwrath and shadeisethal: https://www.wowhead.com/quest=74775/disciple-of-fyrakk-kretchenwrath https://www.wowhead.com/quest=75239/disciple-of-fyrakk-shadeisethal

------

Tracking the quests might not work...
On a fresh week/id i have tested it via 
`/run print(C_QuestLog.IsQuestFlaggedCompleted(75239))`
which shows that the char has completed the quest but the npc wasn't killed in this week/id by that char.

Maybe it is possible to track the kill of the npc by the npc-id ?
https://www.wowhead.com/npc=201673/kretchenwrath
https://www.wowhead.com/npc=203411/shadeisethal

**Comment by LiangYuxuan** [comment]
Sorry for delayed reply. I haven't spent much time on outdoor content and get some questIDs finally.

#### Researchers Under Fire
```
75630, -- Epic
75629, -- Rare
75628, -- Uncommon
75627, -- Common
```

#### Disciple of Fyrakk
```
75467,
```

#### Secured Shipment (Any of following)
```
75525,
74526,
```

Please try out previous questIDs by using macro `/run print(C_QuestLog.IsQuestFlaggedCompleted(XXXXX))` and replace `XXXXX` with actual questID.
