### ISSUE TITLE
[Bug] Weekly Conquest Tracking Not Working

### ISSUE THREAD

**Issue by tusharsaxena** [SavedInstances/SavedInstances#740]
**Describe the bug**
The weekly conquest tracker (e.g. get 1350 conquest for the week) is not working correctly. Shows 0/1250(0/3) - seems to be for an older expansion or patch.

**Do you have an error log of what happened?**
No error logs

**To Reproduce**
1. Earn conquest
2. Check SavedInstances

**Screenshots**
[Link](https://i.imgur.com/FDOTAGF.jpeg)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of SavedInstances are you using?**
10.1.2

**Was it working in a previous version? If yes, which was the last good one?**
Not sure

**Additional context**
N/A

**Comment by LiangYuxuan** [comment]
Could you run `/dump C_WeeklyRewards.GetConquestWeeklyProgress()` and reply what it prints.

**Comment by LiangYuxuan** [comment]
It looks like the progress on the PvP UI is showing the currency Conquest's info. And this line is tracking the honor loot in The Great Vault. Could you confirm the currency Conquest in SI showing the correct info?
