### ISSUE TITLE
Add the ability to dynamically add quest tracking from within the addon

### ISSUE THREAD

**Issue by lholbert** [SavedInstances/SavedInstances#741]
**Is your feature request related to a problem? Please describe.**
There are quests that come out that I would like to keep track of across all my toons, for instance, in the latest patch (10.1), there is "A Worthy Ally" and "Fighting is Its Own Reward"

**Describe the solution you'd like**
Through the UI, I would like to be able to manually enter a quest into the "monitor" list.  It could be as sophisticated as adding a button the quest log, or as simple as providing input fields in the options area to allow one to enter the pertinent information.

**Describe alternatives you've considered**
Currently editing "Progress.lua" to have them show up.  PITA because after every update the file needs to be updated again.

**Additional context**
This could be extended to add "inventory" currencies, such as the crests for example.

**Comment by StefanLE1979** [comment]
Where can I support the request? ;-)

**Comment by GitMestra** [comment]
I do like the idea of adding custom quest IDs. 

The tracking of inventory items is out of scope though. Inventory scanning is a lot harder than keeping a database of the currency tab. There are quite a few trackers for this already: TSM, Altoholic, etc.
