### ISSUE TITLE
Alpha Progress Module Issues

### ISSUE THREAD

**Issue by crusha015** [SavedInstances/SavedInstances#744]
I've updated to the most recent alpha version and testing out the new progress tracking.

It looks like the progress types for "all" and "list" are not working and/or missing features. Here is a list of issues I have encountered:

- Timewalking is showing as complete for some of my characters, despite not being available this week. I have used this command (/run print(C_QuestLog.IsQuestFlaggedCompleted(72724))) and got false for all 6 different Timewalking quests, but I am still seeing the green checkmark in Saved Instances. This seems to only be affecting some of my characters.
- I am seeing a similar issue for Aiding the Accord, for only 1 character. Saved Instances is showing it as completed, when I sitll have the quest in my log in progress.
- On several other characters who HAVE completed Aiding the Accord this week, SavedInstances is showing a blank row for Aiding the Accord (but Aiding the Accord does show up in the weekly quests tracking portion).
- Aiding the Accord is no longer tracking progress (such as 2200/3000 for rep, or 0/1 for the different weekly tasks). I also do not see the yellow question mark when the quest is awaiting turn in. The row is just blank until I turn the quest in, and then I get the green checkmark.
- Researchers Under Fire and Secured Shipment both appear to not be tracking at all. A row is not added to the Saved Instances window, even when these quests are completed, and the checkbox for tracking is turned on.
- Now I've got 1 character showing Secured Shipment completed, yet it's not completed. The same character also shows Sparks of Life completed and I've never done that quest all expansion.
- Tooltips seem inconsistent. For example, a completed Aiding the Accord row shows a green checkmark and if I hover over it, there is a tooltip with a green checkmark. However, for Community Feast and A Worthy Ally, there is no tooltip when I hover over a completed or in progress character.

Not related specifically to Progress, but I am getting the following errors if I try to move the Saved Instances window:

```
Message: Interface/AddOns/SavedInstances/Core/Tooltip.lua:119: attempt to call method 'StartMoving' (a nil value)
Time: Wed Jun 21 12:58:12 2023
Count: 1
Stack: Interface/AddOns/SavedInstances/Core/Tooltip.lua:119: attempt to call method 'StartMoving' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: in function `StartMoving'
[string "@Interface/AddOns/SavedInstances/Core/Tooltip.lua"]:119: in function <Interface/AddOns/SavedInstances/Core/Tooltip.lua:118>

Locals: 
```
___________

```
Message: Interface/AddOns/SavedInstances/Core/Tooltip.lua:122: attempt to call method 'StopMovingOrSizing' (a nil value)
Time: Wed Jun 21 12:58:13 2023
Count: 1
Stack: Interface/AddOns/SavedInstances/Core/Tooltip.lua:122: attempt to call method 'StopMovingOrSizing' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: in function `StopMovingOrSizing'
[string "@Interface/AddOns/SavedInstances/Core/Tooltip.lua"]:122: in function <Interface/AddOns/SavedInstances/Core/Tooltip.lua:121>

Locals: 
```

edit: I also just deleted my Saved Instances saved variables because I thought maybe some old data left in there was messing something up. I loaded into essentially a "fresh install" and it didn't fix any of the issues described above.

**Comment by LiangYuxuan** [comment]
I've created a pr (#745 ) to attempt to fix these. You can download [artifact](https://github.com/SavedInstances/SavedInstances/suites/13778471526/artifacts/763586975) and try.

As having a huge issue on updating and showing `any` and `list`, the issue here related to `any` and `list` might be good after fix. For me it make Aiding the Accord working correctly but didn't try any other yet.

For the tooltip inconsistency, it is working as intended as only Aiding the Accord has more than one objective. Like the old version, only it has tooltip, and manual controlled by `fullObjective`.

**Comment by crusha015** [comment]
Yes, these updates have fixed it for me too! Thank you
