### ISSUE TITLE
v10.1.3 error right after updating from v10.1.2

### ISSUE THREAD

**Issue by R-Adrian** [SavedInstances/SavedInstances#746]
**Describe the bug**

after updating from SavedInstances 10.1.2 to 10.1.3 the first character that i logged on was a level 50 alt that i keep parked at an Auction House... thus it has no recent instance history logged... 
and the error below happened

logged out... back in... error no longer happens. 

**Do you have an error log of what happened?**

```
6x SavedInstances/Modules/Progress.lua:755: attempt to index local 'store' (a boolean value)
[string "@SavedInstances/Modules/Progress.lua"]:755: in function <SavedInstances/Modules/Progress.lua:754>
[string "@SavedInstances/Modules/Progress.lua"]:1134: in function `ResetEntry'
[string "@SavedInstances/Modules/Progress.lua"]:1148: in function `OnDailyReset'
[string "@SavedInstances/Core/Core.lua"]:1349: in function `UpdateToonData'
[string "@SavedInstances/Core/Core.lua"]:2530: in function <SavedInstances/Core/Core.lua:2524>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
store = true
persists = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'store' (a boolean value)"

```

**To Reproduce**  (probably)
1. have a previous version (10.1.2) installed with instance data logged from other characters
2. close warcraft
3. update SavedInsances to v10.1.3
4. Start warcraft, log on a character that is not among those with already-saved instance data
5. error happens

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
i first tried restarting the game - error no longer happens even if nothing changed in the list of addons loaded.
I think it was caused probably by something in the SavedVariables of the previous version and that data was overwritten with new SavedVariables now.

**Which version of SavedInstances are you using?**
SavedInstances 10.1.3 - freshly updated a few minutes ago
Ace3 **r1306-alpha | nevcairiel | 2023-06-23**

**Was it working in a previous version? If yes, which was the last good one?**
10.1.2

**Comment by Masumia** [comment]
Same issue here.
