### ISSUE TITLE
Layout improvement to use the horizontal space more efficiently

### ISSUE THREAD

**Issue by tflo** [SavedInstances/SavedInstances#749]
See the highlighted Renown line of the screenshot (click the thumbnail to get a bigger view):

![image](https://github.com/SavedInstances/SavedInstances/assets/1410282/e7449b35-f717-4fb4-b410-4140a1ce09db)

It is very difficult to visually separate each character's Renown, unless you highlight with the mouse. They flow into each other, and the space between the columns is tiny.

A fairly simple solution would be to remove the space characters between the numbers and the slashes. This would significantly reduce the amount of space used on the x-axis. This would allow for more space between the columns.

Personally, and ignoring all semantics, I would also replace the slashes with pipe characters (aka "VERTICAL LINE", Unicode U+007C). Not that they save space, but I get the impression that they would help readability in this context (if the spaces after the numbers are removed).

Another thing that comes to mind is adding tiny (2px) column separator lines.

**Comment by denzildk** [comment]
if you open Modules/Progress.lua and ctrl+f for "renown" you can find the " / " strings (there are 2) and just replace them with "|", i did it and it's such an improvement, specially with the dream wardens.

**Comment by tflo** [comment]
> replace them with "|", i did it and it's such an improvement

Thanks for the confirmation.
