### ISSUE TITLE
Completed Checkmarks Missing?

### ISSUE THREAD

**Issue by crusha015** [SavedInstances/SavedInstances#755]
I'm no longer seeing the completed check mark in the main window. Maybe the texture name changed or something?

**Comment by snackiesmores** [comment]
Agreed, I'm seeing this as well. Was able to temporarily fix the Aiding the Accord: Time Rift tracker (https://github.com/SavedInstances/SavedInstances/issues/756) but once it's complete, there's no checkmark.

**Comment by LiangYuxuan** [comment]
`READY_CHECK_WAITING_TEXTURE` and `READY_CHECK_READY_TEXTURE` are changed to atlas.

**Comment by crusha015** [comment]
I messed around with trying to figure out how to use the atlas, but wasn't getting anywhere. For the meantime I made a simple mod to get the completed marks back.

Within Modules folder, modify Progress.lua and Core.lua.

Replace all instances of: `"\124T" .. READY_CHECK_READY_TEXTURE .. ":0|t"`

with: `(GREEN_FONT_COLOR_CODE .. "X" .. FONT_COLOR_CODE_CLOSE)`

This will give you a green "X" where we used to see the checkmarks.

**Comment by zkekahs2** [comment]
> I messed around with trying to figure out how to use the atlas, but wasn't getting anywhere. For the meantime I made a simple mod to get the completed marks back.
> 
> Within Modules folder, modify Progress.lua and Core.lua.
> 
> Replace all instances of: `"\124T" .. READY_CHECK_READY_TEXTURE .. ":0|t"`
> 
> with: `(GREEN_FONT_COLOR_CODE .. "X" .. FONT_COLOR_CODE_CLOSE)`
> 
> This will give you a green "X" where we used to see the checkmarks.



Can you tell me in detail how you fixed it?

**Comment by snackiesmores** [comment]
Great fix, thanks @crusha015!

I took your idea and also did this for the ? textures:

Replace:
"(\124T" .. READY_CHECK_WAITING_TEXTURE .. ":0|t)"
and:
"\124T" .. READY_CHECK_WAITING_TEXTURE .. ":0|t"

with:
(RED_FONT_COLOR_CODE .. "?" .. FONT_COLOR_CODE_CLOSE)

**Comment by crusha015** [comment]
Sorry, the Core.lua file is not within the Modules folder, but rather the SavedInstances/Core folder.

I created a pull request with my modifications. I think you can download the modified .lua files from the pull request:
https://github.com/SavedInstances/SavedInstances/pull/759

**Comment by lholbert** [comment]
Two alternatives to the "X":

Unicode checkmark (must be supported by your font)
(GREEN_FONT_COLOR_CODE .. "✓" .. FONT_COLOR_CODE_CLOSE)

Codepage 437 square root (old IBM PC charset, seems to be supported)
(GREEN_FONT_COLOR_CODE .. "√" .. FONT_COLOR_CODE_CLOSE)

**Comment by hollo6** [comment]
Original textures:

"\124T" .. READY_CHECK_READY_TEXTURE .. ":0|t"
"\124T"..READY_CHECK_READY_TEXTURE..":0|t"
->
"|TInterface\\RaidFrame\\ReadyCheck-Ready:0|t"


"\124T"..READY_CHECK_WAITING_TEXTURE..":0|t"
"\124T" .. READY_CHECK_WAITING_TEXTURE .. ":0|t"
"(\124T" .. READY_CHECK_WAITING_TEXTURE .. ":0|t)"
->
"|TInterface\\RaidFrame\\ReadyCheck-Waiting:0|t"

**Comment by LiangYuxuan** [comment]
Sorry for delayed patch. Been a tough week and get fixes pushed at weekend.

**Comment by LordofHounds** [comment]
Thank you LiangYuxuan for all your hard work, I didn't see them was posted when I posted mine so I will just wait!
