### ISSUE TITLE
Quest Progresses not work

### ISSUE THREAD

**Issue by Enkaf** [SavedInstances/SavedInstances#757]
Hello.

I have issue with Quest Progresses. I already done Community Feast, but it not showing for me as done.
![image](https://github.com/SavedInstances/SavedInstances/assets/28902145/198cfa49-d355-412c-9243-990ea6ef0f1e)
When I disabled Quest Progresses, it show me Weekly quests.
![image](https://github.com/SavedInstances/SavedInstances/assets/28902145/1e9842cd-a65b-4ad9-b380-596a5830b6f0)

Also it dont work with other Quest Progresses, like a Disciple of Fyrakk etc.

Thanks.

**Comment by LiangYuxuan** [comment]
Related to #755
