### ISSUE TITLE
10.1.5 duplicate row for Aberrus

### ISSUE THREAD

**Issue by hollo6** [SavedInstances/SavedInstances#758]
**Describe the bug**
Since 10.1.5, there are two separate rows for Aberrus LFR:
![image](https://github.com/SavedInstances/SavedInstances/assets/365584/991adce8-5a3b-4ce1-9a51-f5f7172fea73)

Before the patch, there was only one row for Aberrus (the top one in my picture) and it was absolutely fine.
Now there is a separate row for LFR which is empty and unnecessary.

**Do you have an error log of what happened?**
There are no errors.

**To Reproduce**
1. Kill a boss in LFR (1 is enough as seen in my picture above)
2. Observe 2 rows appearing

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of SavedInstances are you using?**
10.1.4

**Was it working in a previous version? If yes, which was the last good one?**
It was fine with this version before 10.1.5 patch.

**Additional context**

**Comment by LiangYuxuan** [comment]
Duplicated #599 , #755
