### ISSUE TITLE
Suggestion:  Weekly Greater Invasion Points and Draenor Garrison Gathering

### ISSUE THREAD

**Issue by Beleynn** [SavedInstances/SavedInstances#76]
It would be great to have both the weekly Argus Greater Invasion Point and the Draenor Garrison mining/harbalism tracked, if possible.

**Comment by speedwaystar** [comment]
the Greater Invasion point boss is tracked.
![](https://i.imgur.com/otiYAq1.png)

**Comment by TruthNZ** [comment]
Is it possible to add "Greater Invasion:" in front of the current boss?
Or would that take up too much space?

**Comment by Beleynn** [comment]
It's entirely possible that I missed the option to enable it, but I've cleared Alluradel on all 5 characters and do NOT see it in my list.

![screenshot 2017-11-30 19 33 22](https://user-images.githubusercontent.com/34138536/33462429-8683d39e-d605-11e7-9b73-34764a8e25b3.png)

**Comment by TruthNZ** [comment]
I believe 7.0.8 is an old version.

**Comment by speedwaystar** [comment]
the updated version is the alpha. the release version is ancient.
