### ISSUE TITLE
Check marks no longer showing

### ISSUE THREAD

**Issue by LordofHounds** [SavedInstances/SavedInstances#762]
I logged in to do my raids/world boss runs for this week, and I noticed since Nalak is the only world boss I have left that there isn't a check mark next to any of my chars, even though I know I've already done some of them. It was working last week I'm pretty sure before the update. I have a few screenshots I took because I also switched it to combine the world bosses so I could track them that way. This is my first time even putting in a bug report so I'll try my best but that's just what I noticed, thank you!
![Screenshot 2023-07-15 025606](https://github.com/SavedInstances/SavedInstances/assets/139614891/6efcbe18-ace9-4cc3-af02-40b788c88b86)
![Screenshot 2023-07-15 025701](https://github.com/SavedInstances/SavedInstances/assets/139614891/bbe491c7-6dd9-46e9-bbb6-7b30d7cd9468)

**Comment by LiangYuxuan** [comment]
Duplicated #755
