### ISSUE TITLE
add/fix german translations

### ISSUE THREAD

**Issue by Ahfau77** [SavedInstances/SavedInstances#763]
**Is your feature request related to a problem? Please describe.**
not really, it's a translation-enhancement

**Describe the solution you'd like**
add germen translations

please add the follwoing german translations to Locales/Locale.lua:

```
803: La["Disciple of Fyrakk"] = "Anhänger von Fyrakk"
941: La["Researchers Under Fire"] = "Forscher unter Feuer"
952: La["Secured Shipment"] = "Gesicherte Lieferung"
```
and correct:
`849: La["Grand Hunt"] = "Große Jagd"`

**Comment by LiangYuxuan** [comment]
You can submit translations at https://legacy.curseforge.com/wow/addons/saved_instances/localization
