### ISSUE TITLE
Quest stuck in weekly tab

### ISSUE THREAD

**Issue by zeenk** [SavedInstances/SavedInstances#764]
https://www.wowhead.com/quest=65649/a-new-deal

Noticed that this quest was still in my weekly quest tracker tab even tho it's now removed from the game (old shadowlands pvp weekly quest)
![2023-07-16_02-29-07](https://github.com/SavedInstances/SavedInstances/assets/68170439/e78366ab-cab0-4b02-9d2c-731fd397a8d7)
I remember adding it myself last year #608 so not sure if that's why its still there cause I couldn't find it now when I searched in progress/quests.lua for the quest id, would I have to wipe my savedvariable file if I wanted to get rid of it or is it something that could be fixed within the addon to remove it?

**Comment by LiangYuxuan** [comment]
You can edit `Quest.lua` and add this quest as Regular.

**Comment by zeenk** [comment]
Nice that worked, thx!
