### ISSUE TITLE
## Interface: 100100

### ISSUE THREAD

**Issue by EyeSage** [SavedInstances/SavedInstances#770]
**Describe the bug**

**I think this should be  ## Interface: 100105**

**Comment by EyeSage** [comment]
I just downloaded the addon this evening.  100107 is the new version number, so it is still out of date.   

## Interface: 100100
## Title: SavedInstances
![Saved](https://github.com/SavedInstances/SavedInstances/assets/55958529/a9956036-2296-408b-8e1f-f6e7b1bab280)

**Comment by LiangYuxuan** [comment]
Patch 10.2 soon and will be updated at that time. No more release before that so closing this.
