### ISSUE TITLE
 The reset of the Primal Storms Elementals is weekly, not daily

### ISSUE THREAD

**Issue by qertss** [SavedInstances/SavedInstances#771]
The reset of the Primal Storms Elementals is weekly, not daily

**Comment by greerga** [comment]
I tried changing to `reset = 'weekly'` in their setup in `Modules/Progress.lua` (`df-primal-storms-elementals`) but that didn't fix the issue for me, oddly.

**Comment by LiangYuxuan** [comment]
Primal Storms Elementals is to track the rare within Primal Storms area. The lockout of them are daily. If you're looking for weekly quest including Storm's Fury, Storm Surge, and four elemental cores, you can use Primal Storms Core.
