### ISSUE TITLE
Add tracking for Time Rift completion with Siridormi (npc)

### ISSUE THREAD

**Issue by huastekotester** [SavedInstances/SavedInstances#775]
**Is your feature request related to a problem? Please describe.**
A way to track Time Rift completion. 

**Describe the solution you'd like**
Tracking similar to Researchers under fire or otherwise similar to Disciple of Fyrakk

**Describe alternatives you've considered**
Any other way you consider better for this type of tracking.

**Additional context**
This is for Dragonflight expansion.

**Comment by kilolum** [comment]
sorry im not giga sure how to do proper pull request so i post the progress.lua that i edited and tracks the time rift weekly correctly (also tracks the dreamsurge emissary of war correctly since it wasnt updated):

progress.lua: https://pastecode.io/s/xhqf0w4o
locales.lua: https://pastecode.io/s/q2v8twiz

**Comment by kilolum** [comment]
well tbh i dont know how much u need tracking if you can only do it on 1 character. 

"The "When Time Needs Mending" quest can only be completed once per account per week. It cannot be completed again until after the weekly reset occurs. This is working as intended."

https://us.battle.net/support/en/article/339842

**Comment by Kralizek** [comment]
I'd rather have a check if the character did the first run of the week.

**Comment by LiangYuxuan** [comment]
Tracked under weekly quest. If you want a line for it, add custom entry in progress, quest id is 77836.

**Comment by Kralizek** [comment]
Thanks :) Can I make a PR for both this one and the Dreamsurge weekly and let the user enable/disable it?

**Comment by LiangYuxuan** [comment]
Feel free to make a PR. ;)
