### ISSUE TITLE
Please add Shaping the Dreamsurge weekly per-character quest

### ISSUE THREAD

**Issue by wheatbread** [SavedInstances/SavedInstances#777]
**Is your feature request related to a problem? Please describe.**
Would you consider adding the Shaping the Dreamsurge weekly per-character quest as an option for tracking?

https://www.wowhead.com/quest=77251/shaping-the-dreamsurge

It is a weekly quest that you can do on all your characters at the Dreamsurge zone, as a catch up gearing mechanic.  (It awards a token for an item that is 415 and upgrades to 437.)

**Comment by Kralizek** [comment]
Worked on #781
