### ISSUE TITLE
Addon compartment tooltip doesn't disappear properly

### ISSUE THREAD

**Issue by Sluimerstand** [SavedInstances/SavedInstances#778]
When hovering over the SavedInstances entry for the addon compartment, the tooltip shows up. Great.
But when leaving the SavedInstances entry and hovering over another addon entry, the tooltip does not disappear. It only disappears when leaving the addon compartment entirely with the mouse.

This can cause multiple tooltips to be visible at the same time.

**Comment by LiangYuxuan** [comment]
Didn't reproduced. Could you provide version and screenshot?

**Comment by Sluimerstand** [comment]
![image](https://github.com/SavedInstances/SavedInstances/assets/29845810/f33541af-8008-454e-8cfc-22eb2bf4fb43)
Running SavedInstances 10.1.5 (latest CurseForge release).

On second viewing, this only seems to happen when going from SavedInstances to WeakAuras, not when moving from SavedInstances to WeakAuras, when testing with AllTheThings, Rematch, Profession Shopping List this does not occur. However, it also does not occur when hovering from another addon to WeakAuras, so it seems to be a weird interaction between these two addons in particular.

**Comment by LiangYuxuan** [comment]
I see the problem.

In SavedInstances, tooltip is shown when the compartment entry is entered, but won't hide the tooltip as soon as the entry is leaved but waits a bit. At this time, WeakAuras entry is entered and show the tooltip. And then the tooltip of SavedInstances is entered to prevent it from hiding. WeakAuras entry is "leaved" but they didn't register this.

https://github.com/WeakAuras/WeakAuras2/blob/46ab4204f3c01d3901d358fa66b117f14c405fca/WeakAuras/Init.lua#L449-L476

**Comment by Stanzilla** [comment]
> I see the problem.
> 
> In SavedInstances, tooltip is shown when the compartment entry is entered, but won't hide the tooltip as soon as the entry is leaved but waits a bit. At this time, WeakAuras entry is entered and show the tooltip. And then the tooltip of SavedInstances is entered to prevent it from hiding. WeakAuras entry is "leaved" but they didn't register this.
> 
> [WeakAuras/WeakAuras2@`46ab420`/WeakAuras/Init.lua#L449-L476](https://github.com/WeakAuras/WeakAuras2/blob/46ab4204f3c01d3901d358fa66b117f14c405fca/WeakAuras/Init.lua#L449-L476)

So we need to add the onleave function in WA?

**Comment by LiangYuxuan** [comment]
I think the WeakAuras is more like waiting for others to use GameTooltip, so the old content will be gone and "hide". The "delayed hide" of SI is intended but the "waiting to lost GameTooltip" of WeakAuras is not that like intended.

**Comment by Stanzilla** [comment]
> I think the WeakAuras is more like waiting for others to use GameTooltip, so the old content will be gone and "hide". The "delayed hide" of SI is intended but the "waiting to lost GameTooltip" of WeakAuras is not that like intended.

So do you think I should change it in WA or not?

**Comment by LiangYuxuan** [comment]
> > I think the WeakAuras is more like waiting for others to use GameTooltip, so the old content will be gone and "hide". The "delayed hide" of SI is intended but the "waiting to lost GameTooltip" of WeakAuras is not that like intended.
> 
> So do you think I should change it in WA or not?

I'd recommend doing so too.
