### ISSUE TITLE
Huolon is missing

### ISSUE THREAD

**Issue by Ylaana** [SavedInstances/SavedInstances#783]
Huolon (Timeless Isle) is missing from the world bosses listed in the Pandaria Raid category. As this is one of the bosses that can drop a mount, it'd be nice to be able to track kills like we can with Nalak, Oondasta and others. Please can he be added?

![image](https://github.com/SavedInstances/SavedInstances/assets/398738/bd698548-0146-4c27-8258-2f4cbc5e8b1f)

**Comment by LiangYuxuan** [comment]
Hi, Huolon has no lockout and can be killed as many as you want. So it's not tracked by SI.

**Comment by LiangYuxuan** [comment]
Also, if you want to track some rares with lockouts, which we don't want to maintain a huge database like RareScanner and others do, you can add tracking quest id in Progress and create your own tracking.
