### ISSUE TITLE
For some weird reason addon shows that low-lvl toons has a daily lockout for random timewalking dungeon if they are uneligible to queue there due to low ilvl

### ISSUE THREAD

**Issue by Snufkin2153** [SavedInstances/SavedInstances#784]
**Describe the bug**
When I log in on a low-lvl toon, the addon shows that it has a daily lockout saved for MoP random timewalk (It's currently a MoP timewalking week, maybe this bug would reproduce for other timewalks too). This lockout is then displayed in `/si show` tooltip for all other characters.
After some research it became clear that this was due to low item level. This character is a lvl 36 warlock in with 89 ilvl gear and random MoP timewalking requires 35 lvl and 90 ilvl to queue there.

**Do you have an error log of what happened?**
No errors shown in BugGrabber, or similar addons. Also no errors in chat in debug mode.

**To Reproduce**
1. Have a character with low level gear, or delete/sell some gear to lower the average ilvl.
2. Ensure that this toon is ineligible to queue for random timewalking dungeon due to low ilvl, but has high enough character level (35 is currently required for MoP timewalking).
3. See SI tooltip on this or any other character. Lockout for daily timewalk would be there as shown in the screenshot below.
4. Lockout disappears if I raise ilvl to minimum required for timewalk (by buying from AH or creating heirlooms for example).
5. And appears again if I delete/sell those newly acquired items.

Items 4-5 can be repeated indefinitely, the bug is always reproduced.

**Screenshots**
Too low ilvl to queue to MoP timewalk:
![image](https://github.com/SavedInstances/SavedInstances/assets/43489417/d46e6b1a-ba9c-4d09-b942-fce3ddfb8f06)

Raised ilvl to 90 by creating an 100-lvl heirloom, now eligible to queue. No lockout in toolip on this and all other toons:
![image](https://github.com/SavedInstances/SavedInstances/assets/43489417/9577f182-c74b-4a28-bbb9-556949a18689)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes. Same result.

**Which version of SavedInstances are you using?**
Latest (10.1.6)

**Was it working in a previous version? If yes, which was the last good one?**
I can't really say. Wasn't playing on low-lvl characters for long time.

**Additional context**

**Comment by Snufkin2153** [comment]
Update: same issue with WotLK timewalking week, but requirements are a bit lower (30 character level and 75 item level).

**Comment by LiangYuxuan** [comment]
It seems `GetLFGDungeonRewards` always return daily reward claimed when uneligible to queue.

**Comment by Snufkin2153** [comment]
Yes, unfortunately seems like it.
Result of `/dump GetLFGDungeonRewards(995)` is completely the same for uneligible character, and for character that has a timewalk daily save.
I believe this bug is unfixable for now.
