### ISSUE TITLE
Add tracking of weekly quest "Show your Mettle" to SavedInstances

### ISSUE THREAD

**Issue by Feedy88** [SavedInstances/SavedInstances#785]
**Is your feature request related to a problem? Please describe.**
I always forget if I picked up my weekly mettle from "show your mettle" quest (Quest ID: 70221)

**Describe the solution you'd like**
Add "Show your mettle" tracking to SavedInstances

**Describe alternatives you've considered**
I am tracking per character with a WeakAura but I don't log in on all chars every week so it is easy to miss. Account-Wide tracking would allow em to log in when end of week comes close.

**Additional context**
n/a

**Comment by LiangYuxuan** [comment]
You can create your own progress entry by tracking quest 70221.

**Comment by Feedy88** [comment]
Thanks for the input. Can you give me a hint where to add tihs?

**Comment by LiangYuxuan** [comment]
You can add it in SI's config -> Progress -> Custom.

**Comment by Feedy88** [comment]
Thanks. For reference if someone else is looking for it: SI config > Quest Progress > User.
