### ISSUE TITLE
Make renown line a bit more readable.

### ISSUE THREAD

**Issue by Snufkin2153** [SavedInstances/SavedInstances#790]
**Is your feature request related to a problem? Please describe.**
Renown line is long and quite unreadable. Also it makes the tooltip unnecessary wide.
![image](https://github.com/SavedInstances/SavedInstances/assets/43489417/2f7f00a1-5119-4717-8654-9700a89cda7d)

**Describe the solution you'd like**
Make this line shorter and more readable.
![image](https://github.com/SavedInstances/SavedInstances/assets/43489417/9ca493dc-9c05-4152-b69c-805c0789f103)
Maybe add color coding (here I made red = 200% bonus rep for alts, yellow = 100% bonus rep, white = no bonus rep)

**Describe alternatives you've considered**
Maybe add this to options?

**Additional context**

**Comment by Razertongue** [comment]
This 100%. Would like a 10.0 read out, 10.1 on a seperate line (Niffen) and 10.2 on another (Dream Wardens). This way you can hide hide the bigger ones that we should be finished with, this far in

**Comment by LiangYuxuan** [comment]
Not really like the idea of coloring while red & yellow is quite confusing in this case. The other is duplicated by #749 but using "|" instand of "/" to make it different to the progress like "X/Y".

If you have better idea of coloring, feel free to reopen.

**Comment by Razertongue** [comment]
you have to agree that a line of numbers isnt good formatting. Id honestly like to see all 6 renown broken out into their own entries with x/20 Dream Wardens 

or like I said before. Line 1: 10.0 Renown, Line 2: 10.1 Niffen Line 3: 10.2.
