### ISSUE TITLE
Aurostor kill not recognized correctly

### ISSUE THREAD

**Issue by hollo6** [SavedInstances/SavedInstances#794]
**Describe the bug**
Killing Aurostor is not being recognized, only on /reload or relog. So if I kill the boss and log out, it will not be remembered.

**Do you have an error log of what happened?**
There is no error.

**To Reproduce**
1. Kill Aurostor
2. Note that the box stays empty
3. Log out and in on another character
4. Note that the box is still empty. The checkmark only appears after logging on that character again or doing a /reload.

**Which version of SavedInstances are you using?**
10.2.1

**Was it working in a previous version? If yes, which was the last good one?**
N/A (last version was released before the boss was live)

**Comment by LiangYuxuan** [comment]
Cannot reproduce.

**Comment by hollo6** [comment]
I'm out of unsaved chars but will repro next week, what do I look for or are there any debug printouts / logs I can gather?

**Comment by LiangYuxuan** [comment]
You can enable SavedInstances' debug mode. And you can provide WTF file of SI after your kill and log out.

**Comment by LiangYuxuan** [comment]
Also try `/run print(C_QuestLog.IsQuestFlaggedCompleted(76367))`.

**Comment by hollo6** [comment]
Thanks, will do all that and report back after reset.

**Comment by hollo6** [comment]
Well, this went from 100% reproducible to never happens, so I guess it must have been a bug that they fixed sometime last week.
