### ISSUE TITLE
Timerifts not recognized since last update

### ISSUE THREAD

**Issue by Natheedo** [SavedInstances/SavedInstances#795]
**Describe the bug**
Timerifts doesnt get recognized anymore since last update. Before was everything fine. I did them this week on many chars, but not even on 1 of them was ist listed.

Sidenote: using german client.

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of SavedInstances are you using?**
The latest from Curse Forge 10.2.1

**Was it working in a previous version? If yes, which was the last good one?**
I think it was working fine in the last version before 10.2.1, but have to check it

**Comment by LiangYuxuan** [comment]
It seems like blizzard changed the quest id after patch 10.2.

**Comment by TruthNZ** [comment]
Quest has definitely changed as you now get Dilated Time Pod instead of the older Dilated Time Capsule.

**Comment by LiangYuxuan** [comment]
I did it last lockout and still working. It's account wide weekly and shown when you hover on "Weekly Quests" text.

Cannot reproduce. If it's still a bug, feel free to reopen.
