### ISSUE TITLE
Add yearly Anniversary Bosses

### ISSUE THREAD

**Issue by Tigon3rd** [SavedInstances/SavedInstances#796]
I think it would be great to be able to track which of the Anniversary Bosses you have done, especially since you have a chance of loot each day.
This would really be helpful as the Anniversary event is a great way to gear up alts.

Of course the Bosses being Doomwalker, Lord Kazzak, Azuregos and one of the 4 Nightmare Dragons, as it stands for now.

Thank you for the addon.

**Comment by LiangYuxuan** [comment]
Currently they're tracked in Daily Quests. If you want a line for it, you can add in Quest Progress config.
