### ISSUE TITLE
Unrecognized LFR instance parent id

### ISSUE THREAD

**Issue by repairbills** [SavedInstances/SavedInstances#80]
https://i.imgur.com/LAf3JW3.png

Unrecognized LFR instance parent id=1640

Did all the Pandarian raids on LFR and this error popped up.

**Comment by Trid3nt1** [comment]
I believe this has been fixed 18 hours ago.

#79

**Comment by repairbills** [comment]
Had v7.0.11 and just updated to .v7.0.12 via twitch client.  Update wasn't available to me when I posted this.  Thanks for the update.
