### ISSUE TITLE
Adding Show Your Mettle to traker

### ISSUE THREAD

**Issue by Hermonii** [SavedInstances/SavedInstances#805]
Hi, just a simple request : 
That would be really nice to have the option to add the quest "Show Your Mettle" ( https://www.wowhead.com/quest=70221 ) to see wich character already took it or not.
I know we can see it on weekly quests like if we mouseover it, but a ligne exclusive to this one would be great !

Thanks for reading !

**Comment by LiangYuxuan** [comment]
#785
