### ISSUE TITLE
Great Vault progress tracking

### ISSUE THREAD

**Issue by durandal42** [SavedInstances/SavedInstances#807]
**Is your feature request related to a problem? Please describe.**
I want to be able to see at a glance which of my tracked alts have unlocked vault rewards for the upcoming week. (I'd also like to know when they have a vault reward available for pickup right now, but that's a separate feature.

**Describe the solution you'd like**
In the same manner as "Mythic Key Best" I'd like to see which raid/dungeon/pvp vault reward slots I've unlocked, my progress toward the next unlocked one, etc. Note in particular that as of Dragonflight Season 3, heroic/timewalking dungeons count toward dungeon vault rewards.

**Describe alternatives you've considered**
I can log into each character and check their vault progress individually, but SavedInstances does so much of this work for me, and it'd be awesome if it could do this too.

**Comment by LiangYuxuan** [comment]
We have raid & pvp great vault tracking in Quest Progress, you can enable them.

**Comment by durandal42** [comment]
> Note in particular that as of Dragonflight Season 3, heroic/timewalking dungeons count toward dungeon vault rewards.

SavedInstances does not seem to track heroic/timetalking dungeon progress. Is there a setting for that which I'm missing?

**Comment by LiangYuxuan** [comment]
Yea, PR not merged yet #801
