### ISSUE TITLE
希望使用/si show 顯示的視窗能分割成兩個

### ISSUE THREAD

**Issue by fineend** [SavedInstances/SavedInstances#809]
由於角色越來越多，使用/si show 視窗裡面角色太多，導致文字太小，看不到文字，希望可以新增分成上下兩個視窗?

超過30個角色自動分割另一個視窗在原有視窗下面，或可選擇一個還是兩個視窗，選擇視窗角色數量，希望能新增這功能，謝謝！

![WoWScrnShot_120823_142314](https://github.com/SavedInstances/SavedInstances/assets/153260663/a071210b-0236-484d-8b27-cfc920efb8d7)

**Comment by LiangYuxuan** [comment]
Duplicated #392
