### ISSUE TITLE
Lua error upon logging in

### ISSUE THREAD

**Issue by Windmere98** [SavedInstances/SavedInstances#816]
**Describe the bug**
Lua error immediately upon logging in.  Don't have much more context than that sorry.
I've not seen any lua errors with this addon until now.

**Do you have an error log of what happened?**
1x SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
[string "@SavedInstances/Modules/MythicPlus.lua"]:133: in function <SavedInstances/Modules/MythicPlus.lua:127>
[string "@SavedInstances/Modules/MythicPlus.lua"]:146: in function `ProcessKey'
[string "@SavedInstances/Modules/MythicPlus.lua"]:159: in function `RefreshMythicKeyInfo'
[string "@SavedInstances/Modules/MythicPlus.lua"]:121: in function <SavedInstances/Modules/MythicPlus.lua:109>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
level = 20
color = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"
colorCache = <table> {
}
C_ChallengeMode_GetKeystoneLevelRarityColor = <function> defined =[C]:-1

**To Reproduce**
Just Enter world.

**Comment by jardragon901** [comment]
I'm still getting this error but just slightly different
`
41x SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
[string "@SavedInstances/Modules/MythicPlus.lua"]:133: in function <SavedInstances/Modules/MythicPlus.lua:127>
[string "@SavedInstances/Modules/MythicPlus.lua"]:146: in function `ProcessKey'
[string "@SavedInstances/Modules/MythicPlus.lua"]:159: in function `RefreshMythicKeyInfo'
[string "@SavedInstances/Modules/MythicPlus.lua"]:121: in function <SavedInstances/Modules/MythicPlus.lua:109>
[string "=[C]"]: ?
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:572: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:777: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
level = 20
color = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"
colorCache = <table> {
}
C_ChallengeMode_GetKeystoneLevelRarityColor = <function> defined =[C]:-1

`

**Comment by RavenPrime** [comment]
Getting similar error twice:
Message: ...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
Time: Tue Apr  2 20:40:59 2024
Count: 1
Stack: ...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:133: in function <...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:127>
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:146: in function `ProcessKey'
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:159: in function `RefreshMythicKeyInfo'
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:121: in function <...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:777: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by gizzmo** [comment]
looked through the code and it seems that `C_ChallengeMode.GetKeystoneLevelRarityColor(level)` can return an nil value, and not a color.

Change line 133 to : `colorCache[level] = color and color:GenerateHexColor() or 'ffffffff'`

**Comment by LiangYuxuan** [comment]
Moved to #828
