### ISSUE TITLE
Not tracking heroic dungeons

### ISSUE THREAD

**Issue by galapogosian** [SavedInstances/SavedInstances#824]
**Describe the bug**
Expected to see lockout after running specific Dragonflight 5-man heroic but no indicator

**Do you have an error log of what happened?**
 
No

**To Reproduce**
1. Run specific 5-man heroic
2. Check window
3. See missing lock indicator

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes. No change.

**Which version of SavedInstances are you using?**
10.2.5

**Was it working in a previous version? If yes, which was the last good one?**
Unknown to me

**Additional context**
Addon will show names of instances, but does not checkmark after running.

**Comment by LiangYuxuan** [comment]
No lockouts now.
