### ISSUE TITLE
Community Feast not showing up since WoW 10.2.6

### ISSUE THREAD

**Issue by salvebalve** [SavedInstances/SavedInstances#827]
**Describe the bug**
In the list of things that are tracked the Community Feast is not there. The setting to have it show is enabled. Noticed shortly after WoW 10.2.6 was released. I did not check if other things are also missing. All three Emerald Dream weeklies (Dreamseeds, Superbloom, Worthy Ally) seem to track just fine.

**Do you have an error log of what happened?**
No errors were caught by BugSack/BugGrabber

**To Reproduce**
Just display the SavedInstances window. Feast is not there.

**Screenshots**
No screenshot, the line where Feast should be just doesn't show.

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, disabled all other addons, same error.

**Which version of SavedInstances are you using?**
Current (10.2.5).

**Was it working in a previous version? If yes, which was the last good one?**
It worked with this current version before WoW patch 10.2.6.

**Additional context**
Checked many characters on same account. Same error

(Edited for grammar and readability.)

**Comment by LiangYuxuan** [comment]
Cannot reproduce with progress enabled. Maybe related to #753 ?
