### ISSUE TITLE
New Mythic Plus LUA Error

### ISSUE THREAD

**Issue by OldWorldRaiders** [SavedInstances/SavedInstances#830]
I logged in today and started receiving this error spam:

37x SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
[string "@SavedInstances/Modules/MythicPlus.lua"]:133: in function <SavedInstances/Modules/MythicPlus.lua:127>
[string "@SavedInstances/Modules/MythicPlus.lua"]:146: in function `ProcessKey'
[string "@SavedInstances/Modules/MythicPlus.lua"]:159: in function `RefreshMythicKeyInfo'
[string "@SavedInstances/Modules/MythicPlus.lua"]:121: in function <SavedInstances/Modules/MythicPlus.lua:109>
[string "=[C]"]: ?
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:572: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:777: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
level = 23
color = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"
colorCache = <table> {
}
C_ChallengeMode_GetKeystoneLevelRarityColor = <function> defined =[C]:-1

**Comment by LiangYuxuan** [comment]
Duplicated #828 , temp workaround in 10.2.6
