### ISSUE TITLE
Season 4 quest/currency  are not being tracked

### ISSUE THREAD

**Issue by BigFire321** [SavedInstances/SavedInstances#837]
**None of Season 4 of Dragonflight are being tracked.**

**There is no error log.  Nothing from season 4 is being tracked.**

**To Reproduce**
 

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**  Yes.

**Which version of SavedInstances are you using?**  10.2.6.zip

**Additional context**  Nothing from Season 4 is being tracked.

**Comment by BigFire321** [comment]
Things not tracked:
The Last Hurrah weekly Valdrakken quest.
The new Awaken crests.

**Comment by Stanzilla** [comment]
Try the alpha version

**Comment by srbaby** [comment]
> Try the alpha version

Where the alpha version I can find？

**Comment by LiangYuxuan** [comment]
> > Try the alpha version
> 
> Where the alpha version I can find？

https://www.curseforge.com/wow/addons/saved_instances/files/all?page=1&pageSize=20&showAlphaFiles=show

**Comment by Stanzilla** [comment]
New release is now out as well
