### ISSUE TITLE
Version 10.2.6-5-g8f9ef11 not showing wyrm´s awakened crests

### ISSUE THREAD

**Issue by saikenpwn** [SavedInstances/SavedInstances#838]
**Describe the bug**
After checking the Actions on this Update i´ve deviced to try it.
Every new Currency like Aspects, Drakes, Sparks, Bullion or showing up in the Addon except die Wyrms.
In the Settings i´ve checked that the Wyrms are "enabled".
They are still not showing up in the addon.

**Do you have an error log of what happened?**
 

[**Screenshots**]
![Screenshot_5](https://github.com/SavedInstances/SavedInstances/assets/29467308/30cece16-80f8-4a47-9f23-d69436ea614c)

**Comment by LiangYuxuan** [comment]
Cannot reproduce. It shows when you loot any of wyrm, could you show currency frame in your character frame.

**Comment by saikenpwn** [comment]
I cant show you these. Since i logged in 2 minutes ago it works. (Had Balance for this Currency since two days)

**Comment by LiangYuxuan** [comment]
That's weird. Closing this, feel free to reopen if you encounter it again.
