### ISSUE TITLE
PrePatch:  Emissary.lua:80: attempt to call upvalue 'GetNumQuestLogRewardCurrencies' (a nil value)

### ISSUE THREAD

**Issue by Tovrin** [SavedInstances/SavedInstances#848]
45x SavedInstances/Modules/Emissary.lua:80: attempt to call upvalue 'GetNumQuestLogRewardCurrencies' (a nil value)
[string "@SavedInstances/Modules/Emissary.lua"]:80: in function `?'
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bears_Audio_Switcher/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...rs_Audio_Switcher/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 baseName = "SavedInstances"
 moduleName = "Emissary"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = true
 defaultModuleState = true
 name = "SavedInstances_Emissary"
 orderedModules = <table> {
 }
}
t = <table> {
 Arena3v3rating = 0
 isResting = true
 Emissary = <table> {
 }
 Race = "Dwarf"
 LClass = "Hunter"
 RBGrating = 0
 SoloShuffleRating = <table> {
 }
 lastbosstime = 1721439670
 Covenant = 1
 Show = "always"
 TimewornMythicKey = <table> {
 }
 MythicKeyBest = <table> {
 }
 Calling = <table> {
 }
 ILe = 498.687500
 Quests = <table> {
 }
 Paragon = <table> {
 }
 WeeklyResetTime = 1722351599
 LastSeen = 1721794768
 SpecializationIDs = <table> {
 }

**Comment by LiangYuxuan** [comment]
Not released yet, try latest alpha.

**Comment by Stanzilla** [comment]
I just pushed the tag
