### ISSUE TITLE
TWW Prepatch Errors

### ISSUE THREAD

**Issue by yajinni** [SavedInstances/SavedInstances#849]
3x SavedInstances/Modules/BonusRoll.lua:41: CreateFrame(): Couldn't find inherited node "SpellBookSkillLineTabTemplate"
[string "=[C]"]: ?
[string "@SavedInstances/Modules/BonusRoll.lua"]:41: in function <SavedInstances/Modules/BonusRoll.lua:27>
[string "@SavedInstances/Modules/BonusRoll.lua"]:62: in function <SavedInstances/Modules/BonusRoll.lua:61>
[string "=[C]"]: ?
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Accountant/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Rarity/Core/Collections.lua"]:63: in function `ScanToys'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = "Button"
(*temporary) = "SavedInstancesBonusRollFrame"
(*temporary) = BonusRollFrame {
 PromptFrame = Frame {
 }
 SpecRing = Texture {
 }
 BlackBackgroundHoist = Frame {
 }
 SpecIcon = Texture {
 }
 StartRollAnim = AnimationGroup {
 }
 LootSpinnerBG = Texture {
 }
 FinishRollAnim = AnimationGroup {
 }
 IconBorder = Texture {
 }
 WhiteFade = Texture {
 }
 Background = Texture {
 }
 CurrentCountFrame = Frame {
 }
 RollingFrame = Frame {
 }
}
(*temporary) = "SpellBookSkillLineTabTemplate"

**Comment by LiangYuxuan** [comment]
Affects Bonus Roll counter, sorry for both beta and ptr are down and pre-patch haven't hit Asia yet. Might take time to fix this.

**Comment by Stanzilla** [comment]
I replaced the template with something different to make the error go away, didn't check if it looks right though.
