### ISSUE TITLE
[TWW-pre-event] "token of the remembrancers" weekly 

### ISSUE THREAD

**Issue by Fleymour** [SavedInstances/SavedInstances#859]
(https://imgur.com/12r8yrO)

this would the only thing i would log into each char and do the event

**Comment by Veyska** [comment]
As a user-end solution, SavedInstances > Quest progresses > User, set quest name to whatever you want (or "Memories of Adventures Past" which Wowhead thinks might be the "official" name), quest ID 84083, and quest reset type of weekly.
