### ISSUE TITLE
Uncategorized Trade Skill CD "Invent" (447312) - TWW Engineering

### ISSUE THREAD

**Issue by Feedy88** [SavedInstances/SavedInstances#864]
**Describe the bug**

SavedInstances prompted an Error Message upon opening the Engineering Book which was added with TWW.
`Uncategorized Trade Skill CD "Invent" (447312)`

**Do you have an error log of what happened?**

BugSack and BugGrabber are not showing an error

**To Reproduce**

1. Log into Chrackter with Engineering in TWW
2. Learn "Invent"
3. Use "Invent" -> It goes on 24h CD

**Screenshots**
none

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no

**Which version of SavedInstances are you using?**
11.0.2

**Was it working in a previous version? If yes, which was the last good one?**
n/a

**Additional context**

**Comment by ayoubleborgne** [comment]
Adding " [447312] = true, -- Invent " at the line 197 of SavedInstances\Modules\TradeSkill.lua solves this issue

**Comment by yaddanadda** [comment]
I got the same thing except all I did was to open engineering. My Invent was still on CD for 23 more minutes when I got the error message. I have not modified the file as described above.
