### ISSUE TITLE
[TWW] New Weeklies

### ISSUE THREAD

**Issue by F-Lambda** [SavedInstances/SavedInstances#871]
With new expansion comes new weeklies with new quest IDs. Here's the main ones I've seen so far.

#### PvP
47148		Something Different
80184		Preserving in Battle
80185		Preserving Solo
80186		Preserving in War
80187		Preserving in Skirmishes
80188		Preserving in Arenas
80189		Preserving Teamwork

#### World PvP
81793		Sparks of War: Isle of Dorn
81794		Sparks of War: The Ringing Deeps
81795		Sparks of War: Hallowfall
81796		Sparks of War: Azj-Kahet

#### Dornogal
82449		The Call of the Worldsoul
	This leads to a ton of quests prefixed with "Worldsoul: ", like [Worldsoul: The Dawnbreaker](https://www.wowhead.com/quest=82489/worldsoul-the-dawnbreaker), but I think just tracking this might be enough?

#### Delves
84370		The Key to Success

There's also a bunch of "Delves: " prefixed weeklies, like [Delves: Lost and Found](https://www.wowhead.com/quest=82711/delves-lost-and-found), but I've yet to see how they're picked up.

#### Isle of Dorn (Council of Dornogal)
83240		The Theater Troupe

#### The Ringing Deeps (The Assembly of the Deeps
83333		Gearing Up for Trouble
82946		Rollin' Down in the Deeps

#### Azj-Kahet (The Severed Threads)
80592		Forge a Pact
80670		Eyes of the Weaver
80671		Blade of the General
80672		Hand of the Vizier

#### Special Assignment
"Capstone World Quests", that require completing other world quests first and have a weekly lockout. ~~I'm unsure why some are here multiple times with different IDs, but I've marked the ones that actually show when current.~~ The quests seem to be in pairs, one for unlocking by doing 3 WQs and one for completing.

82146		Special Assignment: Cinderbee Surge (Unlocking)
82355		Special Assignment: Cinderbee Surge (Completing)
82154		Special Assignment: Titanic Resurgence (Unlocking)
83069		Special Assignment: Titanic Resurgence (Unlocking)
83070		Special Assignment: Titanic Resurgence (Unlocking) (Don't know why there's three of these)
81649		Special Assignment: Titanic Resurgence (Completing)
81650		Special Assignment: Titanic Resurgence (Completing) (This one is the same as the previous but only shows in beta database)
82155		Special Assignment: Shadows Below (Unlocking)
81691		Special Assignment: Shadows Below (Completing)
82156		Special Assignment: When the Deeps Stir (Unlocking)
83229		Special Assignment: When the Deeps Stir (Completing)
82158		Special Assignment: Lynx Rescue (Unlocking)
82852		Special Assignment: Lynx Rescue (Completing)
82157		Special Assignment: Rise of the Colossals (Unlocking)
82787		Special Assignment: Rise of the Colossals (Completing)
82159		Special Assignment: A Pound of Cure (Unlocking)
82414		Special Assignment: A Pound of Cure (Completing)
82161		Special Assignment: Bombs from Behind (Unlocking)
82531		Special Assignment: Bombs from Behind (Completing)

**Comment by RavenPrime** [comment]
The weekly profession quests, i.e., Tailoring serves requested, are showing up--Thank you!

The gathering weekly quests however are not.
