### ISSUE TITLE
Keyboard Input Nearly Entirely Disabled Whilst Panel is Open

### ISSUE THREAD

**Issue by RadekRatel** [SavedInstances/SavedInstances#874]
Describe the bug
When the Saved Instances window is open, keyboard input appears entirely disabled with the exception of the Esc key. Cannot move, turn, or type via keyboard, or open any other UI panels via hotkey. Mouse is unaffected. 

Do you have an error log of what happened?
There are no errors generated.  

To Reproduce:
Test keyboard input.
Open the Saved Instances panel via /si show . 
Try to use the keyboard for anything. 
Close SI panel via X button or Esc key.
Test keyboard input.

Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes.

Which version of SavedInstances are you using?
11.0.3

Was it working in a previous version? If yes, which was the last good one?
Yes, 11.0.2

**Comment by GitMestra** [comment]
Confirmed. I thought it was the toggle keybind i am using was failing to toggle off the pane. After testing, I have all other keybinds not work after opening the pane.

**Comment by fwr82** [comment]
I got the same issue though. I have a small window as I like it. When it up, it disables the keyboard functions but the movement on the mouse is working fine. 
Tried to uninstall the addon and delete the lua file in "SavedVariables" and do a fresh install also removed the cache.

**Comment by add1kted2ka0s** [comment]
Confirmed, same is happening for me. Been using this addon for year, first time I'm seeing this.

**Comment by LiangYuxuan** [comment]
Related to recent fix for #862 by simple removing :SetPropagateKeyboardInput , will be a fix for not stopping keyboard input and allow ESC closing.
