### ISSUE TITLE
Adding gold tracking

### ISSUE THREAD

**Issue by pepan92** [SavedInstances/SavedInstances#88]
Hello can you add gold tracking for each character and then summary total gold on account. I think that would be great. Hope its possible to do it for you as there is so many things to track but not gold atm. Thank you

**Comment by greerga** [comment]
That is already tracked by mouseover on the character names at top, or the "SavedInstances" in upper-left corner for the totals.

**Comment by denvamnts** [comment]
Couldn't they be added as toggles to the currency tab settings for display in the table???
