### ISSUE TITLE
Delves completed for the week similar to M+/Raid 

### ISSUE THREAD

**Issue by Shrinkage69** [SavedInstances/SavedInstances#883]
**Is your feature request related to a problem? Please describe.**
I love the vault tracking on alts SI does, with Delves now being a major part of weekly progress it would good to be able to see at a glance how many delves each character had completed and what tier they were.

**Describe the solution you'd like**
Exactly as it is for M+ and Raid now so if one character had done 4 Delves and 3 of them were 8 and one was a 2 it would display 8 | 2 to indicate vault

**Describe alternatives you've considered**
Zero alternative

**Additional context**
Delves vault progress shares with the open world so I assume there would be an impact there

**Comment by Shrinkage69** [comment]
I have introduced a few people to SI recently and one of the first thing commented on is how great it is but it's missing Delves :)

**Comment by Kralizek** [comment]
I didn't check the M+ code, but maybe it can be used as inspiration...

**Comment by backcho** [comment]
I checked the API to add related information, but it is difficult to trace the history.
It seems possible to show World reward information as N|N|N, just like M+ reward information is shown in N|N|N format.

It is currently being tested, and I will contribute when it is completed.

**Comment by LiangYuxuan** [comment]
Added in c964a229f892c1c7bd4058d2fc29a538286b54b0

**Comment by Starlynk1** [comment]
I read the update notes and saw that Great Vaults was added. However I cannot find it anywhere in SI to enable it. Also, this issue shows to be about delves, so that adds a but more confusion. Looking at the code, it is set to reset weekly so that kind of defeats the purpose IMO of having it since we would want to see which characters still show a GV reward. Can we get clarification on what the GV add is handled and how it is intended to be used?

**Comment by hollo6** [comment]
It's called "World" and works almost like dungeons. However, it doesn't show the actual number/list of delves you did, so I'd like to hereby request that to be added, so instead of just seeing the current slots, we would know how many more we have to do to fill the next one.

**Comment by Starlynk1** [comment]
Hmm, yeah don't see a world category or anything saying world. But I haven't done a delve yet this week so there's that. What I am looking for is to see what characters have a GV that needs claimed.

**Comment by hollo6** [comment]
![image](https://github.com/user-attachments/assets/19ba7da4-c89d-4181-bd24-e6d8063a38b1)

Looks like this but only shows up when you actually have something there. If you did 0 world content and don't have unclaimed vault, this row does not appear. If you have unclaimed vault, it shows a question mark there.
You enable showing this row here:
![image](https://github.com/user-attachments/assets/92a65db4-254e-4369-9cc7-847b05547aa1)

**Comment by Starlynk1** [comment]
ok thanks, I do have those checked. I will keep an eye on it this week and next week.
