### ISSUE TITLE
Feature Request: Add Skinning Bait/Lure and TWW Alchemy Thaumaturgy daily quest

### ISSUE THREAD

**Issue by pepedressingroom** [SavedInstances/SavedInstances#897]
**Skinning Bait/Lure**

> ```
> local tradeSpells = {
>  ...
>   -- Bait/Lure
>   [382134] = "item", -- Elusive Creature Bait
>   -- [382134] = "item", -- Decay-Infused Creature Bait
>   -- [382134] = "item", -- Frost-Infused Creature Bait
>   -- [382134] = "item", -- Earth-Infused Creature Bait
>   -- [382134] = "item", -- Titan-Infused Creature Bait
>   [442680] = "item", -- Elusive Creature Lure
>   -- [442680] = "item", -- Crystalline Creature Lure
>   -- [442680] = "item", -- Sporefused Creature Lure
>   -- [442680] = "item", -- Writhing Creature Lure
> }
> ```

> ```
> local itemCDs = {
> ...
>   -- Elusive Creature Bait/Lure
>   [382134] = 193906, -- Elusive Creature Bait
>   -- [382134] = 198806, -- Decay-Infused Creature Bait
>   -- [382134] = 198804, -- Frost-Infused Creature Bait
>   -- [382134] = 198805, -- Earth-Infused Creature Bait
>   -- [382134] = 198807, -- Titan-Infused Creature Bait
>   [442680] = 219007, -- Elusive Creature Lure
>   -- [442680] = 219009, -- Crystalline Creature Lure
>   -- [442680] = 219011, -- Sporefused Creature Lure
>   -- [442680] = 219010, -- Writhing Creature Lure
> }
> ```

-----------------------------------------------------------
**Alchemy Thaumaturgy daily quest**
Specialization: Thaumaturgy (55) 
Your first act of Thaumaturgy each day yields a significant amount of extra transmutagen.
spellID: 430315
questID: 81090
(I don't know how to add this)

Regards

**Comment by hollo6** [comment]
I read in the changelog that this is now supposed to be implemented but I can't see it shown anywhere or find an option to enable it, even after it's completed.

**Comment by LiangYuxuan** [comment]
Implemented in #902
