### ISSUE TITLE
"Mythic Best" and "Show When Saved" do not play well together for level 71+ characters

### ISSUE THREAD

**Issue by cixel** [SavedInstances/SavedInstances#898]
**Describe the bug**
If I log onto a level 71 character, which isn't saved to anything, my tooltip will now show that character as if it's saved when I have "Show When Saved" enabled. There is a "?" for "Dungeon Runs" in the tooltip for these characters, even if they haven't done any M+ dungeons (or dungeons at all). This stops happening if I unset "Mythic Best."

**To Reproduce**

1. Enable "Show When Saved" for a level 71+ character
2. Enable "Mythic Best"
3. Log into the "Show When Saved" character
4. Log onto different character, observe tooltip, and note that the character shows as saved with a "?" for Dungeon Runs even if not saved to anything

**Screenshots**
![image](https://github.com/user-attachments/assets/90b56da2-8960-4aa0-8bf5-1f36312dfbec)

**Which version of SavedInstances are you using?**

11.0.5 (latest on CurseForge).

**Was it working in a previous version? If yes, which was the last good one?**

Unsure.

**Comment by LiangYuxuan** [comment]
Could you dump some info for locating the bug API?

```
/dump C_WeeklyRewards.HasAvailableRewards()
/dump C_WeeklyRewards.CanClaimRewards()
```

**Comment by cixel** [comment]
Sorry for the delay.

```
/dump C_WeeklyRewards.HasAvailableRewards()
    --> true
/dump C_WeeklyRewards.CanClaimRewards()
    --> false
```

However, I realized today that not all of my level 71+ characters have the issue. Both functions return false on characters which don't have `?` (which correctly do not show as saved).
