### ISSUE TITLE
the new "TWW Weekly Cache" tracker stopped working this week

### ISSUE THREAD

**Issue by durandal42** [SavedInstances/SavedInstances#908]
**Describe the bug**
Expected: opening a weekly cache would increment the 0/4 "TWW Weekly Cache" tracker
Actual: it did not

**Do you have an error log of what happened?**
No.

**To Reproduce**
1. Complete any weekly TWW activity that rewards a box. (might be specific to 20th Anniversary weekly events)
2. Open that box.
3. Look at "TWW Weekly Cache" tracker.

**Screenshots**
![Screenshot 2024-10-23 100711](https://github.com/user-attachments/assets/9090fd08-0832-410c-826b-1bc9447bdbbe)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but literally everything else about SavedInstances is working just fine, and there are no LUA errors.

**Which version of SavedInstances are you using?**
11.0.6

**Was it working in a previous version? If yes, which was the last good one?**
This worked last week, but the Anniversary event wasn't live then, so maybe it's related to that!

**Comment by durandal42** [comment]
Looks like non-anniversary weekly chests still increment the counter as expected, so it's just something special about the anniversary weeklies. They do give chests which give coffer keys, and those coffer keys are still limited to 4/week.

**Comment by durandal42** [comment]
I tried using questids [84736 ... 84739] as a workaround, but those aren't being set either. I'm not sure what SavedInstances is using under the hood to determine cache progress.

**Comment by LiangYuxuan** [comment]
The weekly cache counter is more like coffer key counter, so the same quest id is used.

https://github.com/SavedInstances/SavedInstances/blob/5f0cc7ba371274f2d11e87014078de733b07acc4/SavedInstances/Modules/Progress.lua#L811-L814

Most weekly activities exists before 11.0.5 is tracked by SI, but the counter is not provided.

**Comment by LiangYuxuan** [comment]
Is there any new quest/chest that provides a coffer key?

**Comment by durandal42** [comment]
[Bronze Celebration Cache of Treasures] says "Weekly cache containing materials for upgrading gear, gold, and more. The **first** weekly cache you earn each week contains a piece of Champion gear from Blackrock Depths and a Restored Coffer Key. Subsequent caches contain a piece of Veteran gear."

I don't know how to determine the quest id tracking this, but I'm willing to go open a first-weekly-chest on a new character to find out, if you can suggest how to observe the questid being set.

**Comment by durandal42** [comment]
I'm going to try installing https://www.curseforge.com/wow/addons/questschanged and then earning and opening a Bronze chest on an alt, unless you can think of a better thing to try.

**Comment by durandal42** [comment]
![Screenshot 2024-10-23 120123](https://github.com/user-attachments/assets/e356725e-8eaf-46ff-ba24-f5af1aac9411)

"Timely Gate Crashers" was the weekly quest which rewarded a chest.

84665 was set at the same time I turned in Timely Gate crashers.

86202 was set when I opened the box.

I suspect that the "one coffer key from Bronze Celebration Caches" quest is the latter, but I'm not sure how to confirm this.

**Comment by yoshimo** [comment]
you could try and see if https://warcraft.wiki.gg/wiki/API_C_QuestLog.GetTitleForQuestID after a succesfull https://warcraft.wiki.gg/wiki/API_C_QuestLog.RequestLoadQuestByID  gives you a name for them.
Some of these tracking quests have telling names but don't appear in the questlog.

**Comment by durandal42** [comment]
I added both quest ids to SavedInstances as user-defined quests, and they're both set on my main as well.

**Comment by durandal42** [comment]
> you could try and see if https://warcraft.wiki.gg/wiki/API_C_QuestLog.GetTitleForQuestID after a succesfull https://warcraft.wiki.gg/wiki/API_C_QuestLog.RequestLoadQuestByID gives you a name for them.
> Some of these tracking quests have telling names but don't appear in the questlog.

I tried running
```
/script C_QuestLog.RequestLoadQuestByID(86202)
```
(prints nothing, as expected?)

```
/script print(C_QuestLog.GetTitleForQuestID(86202))
nil
```

So, no luck there.

**Comment by yoshimo** [comment]
The Answer to RequestLoadQuestByID is an event
QUEST_DATA_LOAD_RESULT: questID, success
but if there is no additional data, it won't change anything.
Was worth trying 
Sometimes you get names like

```44652 Tracking Quest: 7.0 Class Hall - Rogue - Chapter 2 - Troop B Recruiter Acquisition",```

**Comment by durandal42** [comment]
84878 is likely the tracker for the first daily completion of "The Codex of Chromie" (queueable raid anniversary event) which gives a [Chromie's Premium Goodie Bag] (purple quality, ilvl 571). Subsequent clears give only a [Chromie's Tour Goodie Bag] (blue quality, ilvl 561).

**Comment by durandal42** [comment]
84878 is "Chromie's Codex", the weekly quest to do "The Codex of Chromie".

84604 is a no-name quest that was set at the same time I turned in 84878.

So far, my best guess is that 86202 is the first-weekly-anniversary-chest-per-character-gives-a-coffer-key tracking quest.

**Comment by durandal42** [comment]
57300 is "Solider of Time", the weekly quest to gain honor in Korrak's Revenge

84607 is a non-name quest that was set at the same time I turned in 57300 .

It's seeming like 84600~ is trackers for various weekly quests, and 86202  is tracking the better rewards on the first box.
