### ISSUE TITLE
All timewalking events being tracked at the same time. 

### ISSUE THREAD

**Issue by 1701NCC** [SavedInstances/SavedInstances#915]
**Describe the bug**
When logging into my alts to check my weekly vaults each one seems to be tracking every single timewalking event and codex of chromie and says all of them have a 15 hour cooldown. This appears on log in before any weekly quests are picked up. 

**Do you have an error log of what happened?**
No error messages

**To Reproduce**

1. Log onto an alt
2. Open SavedInstances window. 

**Screenshots**
![image](https://github.com/user-attachments/assets/c554d2ed-87b0-42de-98e7-f7f1c399b05d)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of SavedInstances are you using?**
11.0.7

**Was it working in a previous version? If yes, which was the last good one?**
It seemed to be working fine recently, so i don't know if blizz did something with the ids of their timewalking dungeons or what. something is off though. 

**Additional context**

**Comment by 1Holy-Z** [comment]
getting this as well

**Comment by LiangYuxuan** [comment]
I'm getting this last night before Asia's weekly reset. Seems like BLZ have hotfixed something causing this.

**Comment by gotex007** [comment]
How do I tell it not to track this anyway? I don't even know what the Codex of Chromie is and I haven't done any timewalking in two weeks, but I have these things showing for every character I log into.

**Comment by LiangYuxuan** [comment]
> How do I tell it not to track this anyway? I don't even know what the Codex of Chromie is and I haven't done any timewalking in two weeks, but I have these things showing for every character I log into.

You can disable holiday dungeon entirely.

**Comment by HavocR88** [comment]
The same with the Codex of Chromie, Says saved, While not having done it yet on all characters.

**Comment by hollo6** [comment]
> > How do I tell it not to track this anyway? I don't even know what the Codex of Chromie is and I haven't done any timewalking in two weeks, but I have these things showing for every character I log into.
> 
> You can disable holiday dungeon entirely.

I can only get rid of this if I disable both Show Holiday and Show Random, by itself neither seems to do anything. Is that intentional?

**Comment by Nulgar** [comment]
> I can only get rid of this if I disable both Show Holiday and Show Random, by itself neither seems to do anything. Is that intentional?

as far as I know, other than the seasonal event bosses, there is no special "first of the day" reward for any random dungeon - it technically exists, but the rewards are the same as for repeats on the same day. So, might as well disable Show Random anyway.

**Comment by formigao** [comment]
is that fixed? i still have all those bugged locks and i have updated to last version

**Comment by 1Holy-Z** [comment]
> is that fixed? i still have all those bugged locks and i have updated to last version

same here

**Comment by LiangYuxuan** [comment]
Confirm still an issue, due to error info returned by API at logout.
