### ISSUE TITLE
Hiding Timewalking Weekly

### ISSUE THREAD

**Issue by l3vi4than** [SavedInstances/SavedInstances#916]
I would like to request a configuration setting to hide all the Timewalking Weeklies, they pollute the screen heavily and I personally never do these, as I played all these expacs and I am fed up with legacy content. Would it be possible, please?

**Comment by jokey-smurf** [comment]
Came here to request the exact same thing!

**Comment by Nulgar** [comment]
Do you mean the issue described in #915?

**Comment by l3vi4than** [comment]
> Do you mean the issue described in #915?

Yes, very much, it seems like a similiar issue, I would like these Timewalking Entries hidden by config (if possible). It's bloaty and makes the frame waaaay to big without providing much value (at least from my perspective).

**Comment by l3vi4than** [comment]
Hey folks, thanks for looking into it, but I mentioned it might be related/similiar. Correct me if I'm wrong, or missing a setting or so, but the list keeps repopulating, trashing my ui:

![image](https://github.com/user-attachments/assets/6e38b5cb-7694-4fb9-bff4-e8e0a449a62d)

It's really inconvenient. May you please add a setting to hide that whole Random Timewalking / Codex of Chrome section? Cheers.
