### ISSUE TITLE
Removing the embedded LibDataBroker-1.1 library from the repository (?)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SavedInstances/SavedInstances#92]
It appears there's still this one library remaining: **LibDataBroker-1.1**

In trying to work with the files locally, this proved a minor annoyance. Therefore, I suggest we do as follows:
1. Remove this last embedded library from the repository and add it to the .pkgmeta*
2. Add the libs/ directory to .gitignore so libraries can be added (for testing purposes) without affecting pulls to the local copy

*_There may (still) be an issue with the .pkgmeta and that particular library, in which case we should do as suggested [here](https://www.wowace.com/projects/libdatabroker-1-1) and add a "tools used" entry. I can't speak to the status of the ticket mentioned, as it's been many years and the CF website has been revamped since then._

**Comment by Stanzilla** [comment]
it's custom to include it this way and the actually recommended way. we could submodule it but, eh.

https://github.com/tekkub/libdatabroker-1-1

**Comment by SacredDuckwhale** [comment]
Yup, I read that this is due to a bug mentioned in the link I provided:
> Do not use an embed entry for LDB if you allow no-lib packages, your no-lib versions will not include LDB in them. Instead you should hard-embed LDB in your addon and add a “tools used” entry for “libdatabroker-1-1”. Any files packaged after that will include the relationship. If you don’t want to repack, you can edit the existing files on wowace to add the relationship.
**Vote for this ticket if you’d like Ace to fix the .pkgmeta issue so you don’t have to hard-embed.**

Unfortunately, the link is dead. Since it's been several years, I'm not sure if hard-embedding is still necessary or if the issue mentioned there has already been fixed.

Regardless, updating the .gitignore should be a trivial matter, with no adverse effects. I've added a PR for it: #93
