### ISSUE TITLE
Skinning bait and Thaumaturgy not working

### ISSUE THREAD

**Issue by hollo6** [SavedInstances/SavedInstances#920]
**Describe the bug**
Thaumaturgy does not show up anywhere, not even when already completed and bait CD is still wrong:
![image](https://github.com/user-attachments/assets/cdfd03ef-ca7f-44d9-a157-08fa912ed11f)

(Same as before, https://github.com/SavedInstances/SavedInstances/issues/897)

**Do you have an error log of what happened?**
There is no error.

**To Reproduce**
1. Do daily Thaumaturgy
2. Use Skinning bait
3. See SI info, Thaumaturgy does not show up and bait CD is displayed incorrectly.

**Screenshots**
![390791788-cdfd03ef-ca7f-44d9-a157-08fa912ed11f](https://github.com/user-attachments/assets/2d5db535-6d85-4779-aeea-595303210c3a)
![image](https://github.com/user-attachments/assets/a0dcdfcb-ddbd-4485-adcc-91d18f1b08a4)

(It is not even on CD on this screenshot and the time is always wrong regardless of its actual CD time/state.)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of SavedInstances are you using?**
11.0.7-3-gee6b8f9

**Was it working in a previous version? If yes, which was the last good one?**
No.

**Additional context**

**Comment by LiangYuxuan** [comment]
Cannot reproduce the bait cooldown issue. Used Elusive Creature Lure and it works good.

Could you try `/dump C_Item.GetItemCooldown(219007)` and reply the result.

**Comment by hollo6** [comment]
When I used the base Elusive Creature Lure (screenshot in previous thread), it looked the same.

[15:19:03] Dump: value=C_Item.GetItemCooldown(219007)
[15:19:03] [1]=0,
[15:19:03] [2]=0,
[15:19:03] [3]=false

**Comment by LiangYuxuan** [comment]
The result shows that it didn't has cooldown. Could you give me more info?

```
/dump C_Item.GetItemCooldown(219007)
/dump C_Item.GetItemCooldown(219009)
/dump C_Item.GetItemCooldown(219010)
/dump C_Item.GetItemCooldown(219011)
```

**Comment by hollo6** [comment]
I just accidentally found Thaumaturgy. It is under weekly quests (that is definitely not the right place :) ).
Will send the dumps when next able to log on to that char.

**Comment by hollo6** [comment]
[16:15:00] Dump: value=C_Item.GetItemCooldown(219007)
[16:15:00] [1]=0,
[16:15:00] [2]=0,
[16:15:00] [3]=false
[16:15:04] Dump: value=C_Item.GetItemCooldown(219009)
[16:15:04] [1]=0,
[16:15:04] [2]=0,
[16:15:04] [3]=true
[16:15:07] Dump: value=C_Item.GetItemCooldown(219010)
[16:15:07] [1]=0,
[16:15:07] [2]=0,
[16:15:07] [3]=false
[16:15:10] Dump: value=C_Item.GetItemCooldown(219011)
[16:15:10] [1]=0,
[16:15:10] [2]=0,
[16:15:10] [3]=false

**Comment by LiangYuxuan** [comment]
So it's more like false data remaining. Run this on skinning character `/run SavedInstances[1].db.Toons[SavedInstances[1].thisToon].Skills[442680] = nil`

**Comment by hollo6** [comment]
Okay looks like this did the trick, thanks! :)

Regarding Thaumaturgy, would it be possible to have it in the Tradeskill CDs group? If not, daily quest is fine, just not the weekly. :)

**Comment by hollo6** [comment]
Understood, just move it to daily then, it'll be fine.
