### ISSUE TITLE
[Feature Request] Ability to report all of one's characters' keys to party chat, similar to AstralKeys

### ISSUE THREAD

**Issue by wheatbread** [SavedInstances/SavedInstances#923]
**Is your feature request related to a problem? Please describe.**
As title says.  Currently, the only way to report all the keystones you have on multiple characters is to click them into chat one by one, which isn't really feasible if you have many alts and also have to repeatedly do it when your group is deciding what keys to run.  Please add a functionality where you can just click a little loudspeaker button to report to party chat all your alts' keystones in 1 go.  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LiangYuxuan** [comment]
You can set report channel to Party in General and click "Mythic Key", the title of the row, to report all your keys.
