### ISSUE TITLE
Option to remove the "Random Timewalking Dungeon" lines

### ISSUE THREAD

**Issue by Gaviin1242** [SavedInstances/SavedInstances#926]
Relatively recently, the addon started including multiple lines near the top like:

Random Timewalking Dungeon (BC)
Random Timewalking Dungeon (Legion)
...etc

As well as a line for "The Codex of Chromie".

I can't seem to find any option to disable/remove those lines.  Am I missing something, or can I request that this feature be added?  They are needlessly cluttering up my SI window.  :)

And to confirm, disabling the "Show Holiday" option does *not* remove these lines.

Thanks!

**Comment by LiangYuxuan** [comment]
fixed in 16c1d15e896a43f15c97f07f810219d579d69420 , please update SI to latest alpha
