### ISSUE TITLE
I got frame issue

### ISSUE THREAD

**Issue by rkdlq812** [SavedInstances/SavedInstances#97]
https://drive.google.com/open?id=1199zSSewuoPU9dK2Oo-Rjk0YtZC0HnMh

All graphic options are 1(very low).

Whenever I move into another zone, I feel throttling.

Unlike an issue that already closed few days ago, I couldn't feel fps drop while character is standing.

**Comment by SacredDuckwhale** [comment]
I can't reproduce this, and the only part of SI doing anything at that time is costing negligible amounts of time.

The only thing I can imagine is some memory churn, but unless it can be pinpointed accurately (= we'll need more info about memory usage, actual ingame FPS, and similar/different situations where this might occur) ... I doubt anyone will have the time to optimize it for this specific case :(

**Comment by LiangYuxuan** [comment]
Can't reproduce this currently, is there the problem now?
