### ISSUE TITLE
Wakening Essence in instances.lua not being tracked

### ISSUE THREAD

**Issue by spottsy** [SavedInstances/SavedInstances#98]
I love the addon and very thankful it is being updated on github.

I noticed that on December 1st in Comments that "Added Wakening Essence" was added to currencies but it isn't being traked. I did a word search in the instances.lua and it is listed in the file though. 

If you could fix or add Wakening Essence to currencies being traced I that would be so helpful as I play a lot of alts.

**Comment by Trid3nt1** [comment]
It's in there, you need to go the SavedInstances in your interface options, go to Currencies and its all in there to track/ untrack

**Comment by spottsy** [comment]
Thankyou so much for the reply. I had no ideas options existed. Thanks for keeping this updated as I play 7 alts is has become essential for mythic plus keys etc.
